### ISSUE TITLE
Design of our standard on-disk dataset format?

### ISSUE THREAD

**Issue by JackKelly** [nilmtk/nilmtk#13]
Just some basic questions about our on-disk dataset format.
#### Name?

Name?  REDD+ is nicely descriptive (because our format will be an extension of REDD), but I worry that this name might, um, have political implications?  We should perhaps approach the REDD authors before committing to this name (if indeed we like the name!)
#### Standardise units and names

Should our format standardise the following:
- standardise units (use unix timestamp (UTC) for timestamps, Watts, Volts, etc)
- standardise column names for aggregate data (e.g. 'main0_apparent', 'mains1_active')
- standardise appliance names (perhaps based on the HES appliance naming scheme with apparent/active/reactive appended to the name like kettle_active?)

So, for example, once data is in our format, users will know for sure that the kettle appliance is called 'kettle_active' and not 'Kettle' or 'KETTLE0' or something.

It would be the responsibility of functions like `HES.load_buiding` to convert from HES's units to our standard units.

I think we should standardise.  It feels like The Right Thing To Do; and it should minimise the complexity of our NILM code.
#### Storing power data on disk

We can probably just use the basic REDD structure (a directory per house; a labels.dat file for channel labels etc).

I think we should allow users the option of saving either CSV or HSF5.  CSV files can be slow to load for large datasets (even from an SSD).

It would be good if our format could be loaded by existing tools written to process REDD.  i.e. anything we add (e.g. metadata) should be in separate files.
#### Storing metadata on disk

It sounds like we're thinking of using JSON.  Is that OK?  Maybe call the file 'metadata.json'.  I guess we need a metadata file for the dataset as a whole (storing country of origin, academic references, URL, nominal mains voltage etc) and a metadata file per house (geo location, number of occupants etc).  How does that sound?

The metadata ideas described by @nipunreddevil in the wiki look very sensible.  I wonder if we can also use some ideas from [Xively's metadata spec](https://xively.com/dev/docs/api/quick_reference/api_resource_attributes/) and/or [SensorML](http://en.wikipedia.org/wiki/SensorML).  And this blog has some interesting and up-to-date ideas: [Data models for the Internet of Things](http://iot-datamodels.blogspot.co.uk/)
#### How to cope with BLUED?

As @oliparson pointed out yesterday, BLUED  doesn't record the power consumption of individual appliances.  Instead it records whether appliances are on or off.  Trying to estimate the individual appliance power consumption is bound to be prone to large uncertainties so I think we shouldn't do that.  Instead, it may be simpler to add a new class of file: `channel_X_state.dat` that has two columns: a timestamp and a state (an integer).  We could also use this format for the exporting appliance estimates from NILM algorithms which know about separate appliance states.
#### Allow multiple columns per file?

For mains, my dataset records active, apparent and voltage for aggregate. It's much for efficient to store this in a single csv file with 4 columns rather than 3 csv files (because the timestamp must be duplicated in each file) . Should we allow multiple columns in our on disk  format? 
#### Compact representation?

The standard REDD format is quite space inefficient, especially if we use it for storing appliance state.  e.g.:

```
1303132929 0
1303132930 0
1303132931 0
...
1303170000 0
1303170001 1
...
```

So perhaps we could allow users to export CSV files as either 'complete' or 'compact' (where only change points would be reported).

**Comment by Zouhour03** [comment]
How can i download BLUED Data set ? I need it plz

**Comment by oliparson** [comment]
http://portoalegre.andrew.cmu.edu:88/BLUED/

**Comment by Zouhour03** [comment]
the size of BLUED data set is for 3.5GB is it too much for the PC ??

**Comment by nipunbatra** [comment]
@Zouhour03 NILMTK doesn't support Blued like datasets. Please contact the dataset authors in case you have other clarifications.

**Comment by abrahamdmt** [comment]
@nipunbatra  How can I load REDD(Which I downloaded and saved in my hard drive) to NILMTK?

**Comment by nipunbatra** [comment]
@abrahamdmt : Please see NILMTK documentation https://github.com/nilmtk/nilmtk/tree/master/docs/manual

**Comment by abrahamdmt** [comment]
@nipunbatra  Thank you!!
