### ISSUE TITLE
redd converter producing hdf5 file with all timestamps in the year 1969

### ISSUE THREAD

**Issue by oliparson** [nilmtk/nilmtk#131]
I've successfully converted REDD to HDF5, but whenever I try to do anything with it, e.g.

redd.buildings[1].elec[1].power_series_all_data()

I get the following stack trace:

---

ValueError                                Traceback (most recent call last)
/usr/lib/python2.7/dist-packages/IPython/utils/py3compat.pyc in execfile(fname, *where)
    176             else:
    177                 filename = fname
--> 178             **builtin**.execfile(filename, *where)

/home/oli/nilmtk/nilmtk/dataset_converters/redd/test_dataset_redd.py in <module>()
     13 print('loading HDF5')
     14 redd = DataSet(output_directory)
---> 15 redd.buildings[1].elec[1].power_series_all_data()
     16

/home/oli/nilmtk/nilmtk/electric.pyc in power_series_all_data(self, **kwargs)
     59     def power_series_all_data(self, **kwargs):
     60         chunks = []
---> 61         for series in self.power_series(**kwargs):
     62             chunks.append(series)
     63         return pd.concat(chunks)

/home/oli/nilmtk/nilmtk/elecmeter.pyc in power_series(self, **kwargs)
    309
    310         # Pull data through preprocessing pipeline
--> 311         for chunk in generator:
    312             series = chunk.icol(0).dropna()
    313             series.timeframe = getattr(chunk, 'timeframe', None)

/home/oli/nilmtk/nilmtk/datastore.pyc in load(self, key, cols, sections, n_look_ahead_rows, chunksize)
    120                 # Set timeframe
    121                 if len(data) > 0:
--> 122                     data.timeframe = TimeFrame(data.index[0], data.index[-1])
    123                 else:
    124                     data.timeframe = TimeFrame()

/home/oli/nilmtk/nilmtk/timeframe.pyc in **init**(self, start, end)
     26         self.clear()
     27         self.start = start
---> 28         self.end = end
     29         self.include_end = False
     30

/home/oli/nilmtk/nilmtk/timeframe.pyc in end(self, new_end)
     67         new_end = pd.Timestamp(new_end)
     68         if self.start and new_end <= self.start:
---> 69             raise ValueError("end date must be after start date")
     70         else:
     71             self._end = new_end

ValueError: end date must be after start date

> /home/oli/nilmtk/nilmtk/timeframe.py(69)end()
>      68         if self.start and new_end <= self.start:
> ---> 69             raise ValueError("end date must be after start date")
>      70         else:

Inspecting these variables, they are in fact equal, which is causing this error to be thrown:

ipdb> new_end
Timestamp('1969-12-31 18:59:57.852516352-0500', tz='US/Eastern')
ipdb> self.start
Timestamp('1969-12-31 18:59:57.852516352-0500', tz='US/Eastern')

**Comment by abrahamdmt** [comment]
@oliparson 
In my case, I have been trying to convert REDD to HDF5, but I am getting this error report.
 HDF5ExtError: HDF5 error back trace

  File "C:\ci\hdf5_1510862294786\work\src\H5F.c", line 522, in H5Fcreate
    unable to create file
  File "C:\ci\hdf5_1510862294786\work\src\H5Fint.c", line 1003, in H5F_open
    unable to open file: time = Fri Jul 13 11:04:13 2018
edd_my.h5', tent_flags = 13t\Redd
  File "C:\ci\hdf5_1510862294786\work\src\H5FD.c", line 993, in H5FD_open
    open failed
  File "C:\ci\hdf5_1510862294786\work\src\H5FDsec2.c", line 339, in H5FD_sec2_open
edd_my.h5', errno = 22, error message = 'Invalid argument', flags = 13, o_flags = 302

End of HDF5 error back trace

edd_my.h5'open/create file 'F:\Project\DataSet\Redd

**Comment by PMeira** [comment]
@abrahamdmt Did you forget to escape the backslashes or use raw strings? i.e., try

```
convert_redd(r'F:\Project\DataSet\Redd\low_freq\low_freq', r'F:\Project\DataSet\Redd\redd_my.h5')
```

This is not really related to NILMTK, we don't customize the HDF5 installation at all. If that still doesn't work, try creating a Pandas dataframe and saving it to HDF. Adapting one of examples from the Pandas docs:

```
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]}, index=['a', 'b', 'c'])
df.to_hdf(r'F:\Project\DataSet\Redd\redd_my.h5', key='df', mode='w')
```

If this doesn't work, you might need to adjust you filesystem permissions.

By the way, using the forward slash also works on Windows in most scenarios, e.g. this also works:

```
convert_redd('F:/Project/DataSet/Redd/low_freq/low_freq', r'F:/Project/DataSet/Redd/redd_my.h5')
```

**Comment by abrahamdmt** [comment]
Thank you @PMeira  this has worked for me,
 `convert_redd(r'F:\Project\DataSet\Redd\low_freq\low_freq', r'F:\Project\DataSet\Redd\redd_my.h5')`

**Comment by nipunbatra** [comment]
Excellent work @PMeira. Could we add the escaping or raw string part to the
documentation?

**Comment by PMeira** [comment]
@nipunbatra Done in cba5ad4aa04d67bcb1f00762411125e6a29718b3. I added a note to three of the notebooks, should be enough.
