### ISSUE TITLE
Plotting Disaggregator Predictions in v0.2?

### ISSUE THREAD

**Issue by athenawisdoms** [nilmtk/nilmtk#175]
In v0.1, we could do the following:

```
disaggregator.disaggregate(test)
predicted_power = disaggregator.predictions
```

and get a DataFrame containing all the various appliances in the dataset, which we can easily plot using

```
predicted_power["2011-04-27 20:00":"2011-04-27 23:00:00"].plot()
```

![title](http://i.stack.imgur.com/FhUzx.png)

How can we do the same in v0.2?

Here's where I'm stuck at:

```
mains = elec.mains()
output = HDFDataStore("output.h5", "w")
co.disaggregate(mains, output)

output.store.get('/building1/elec/meter5').plot()
output.store.get('/building1/elec/meter6').plot()
output.store.get('/building1/elec/meter7').plot()
output.store.get('/building1/elec/meter8').plot()
output.store.get('/building1/elec/meter9').plot()
```

Seems like for the above method, we need to manually find out the data structure of the ElecMeters in the HDFDataStore (eg: /building/elec/meterN), and they are all plotting to individual plots rather than all into one plot.

![](http://i.stack.imgur.com/gam0D.png)
![](http://i.stack.imgur.com/jq2YT.png)

Finally, I tried loading the dataset from `output.h5` but it appears that the appliance name was not stored?

```
disag = DataSet("output.h5")
disag_elec = disag.buildings[1].elec
disag_elec.appliances
```

Output

```
[]
```

**Comment by PMeira** [comment]
Closing, nowadays some examples include plotting ground truth vs predictions.

> Approach 1
>
>We assume that it is entirely the responsibility of the user to see how many data they are plotting. They should be the one to see that their hog memory if they plot everything. They should be the one who make the decision to downsample the data if it doesn't fit into the memory. This approach is quicker to get working.

I'd go with this but we'll see later if the new API facilitates a move general approach.
