### ISSUE TITLE
Inquiry for error in REDD conversion process

### ISSUE THREAD

**Issue by bundit786** [nilmtk/nilmtk#185]
Hi,
     I have installed Anaconda (Python 2.7.8) and git client on Windows 7 (Home Premium) following the instructions in its documentation and all the process passed successfully. I would like to get analyzed of REDD data set.
     However, when I started to convert REDD data, after the conversion of the 6th house finished, it turned error as 

```
    Loading house 6... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 

    Traceback (most recent call last):
     File "<pyshell#2>", line 1, in <module>
     convert_redd('C:/Users/bundit/Desktop/REDD/low_freq','C:/Users/bundit/Desktop/redd.h5')
     File "C:\Users\bundit\Anaconda\lib\site-packages\nilmtk-0.2.0.dev-        py2.7.egg\nilmtk\dataset_converters\redd\convert_redd.py", line 57, in convert_redd hdf_filename)
     File "c:\users\bundit\nilm_metadata\nilm_metadata\convert_yaml_to_hdf5.py", line 30, in   convert_yaml_to_hdf5
     assert isdir(yaml_dir)
     AssertionError 
```

After check if the module get_module_directory exists, it turned out error as:

```
   >>> from nilmtk.utils import get_module_directory

  Traceback (most recent call last):
   File "<pyshell#2>", line 1, in <module>
   from nilmtk.utils import get_module_directory
   ImportError: cannot import name get_module_directory

   >>> print get_module_directory()

  Traceback (most recent call last):
   File "<pyshell#3>", line 1, in <module>
   print get_module_directory()
   NameError: name 'get_module_directory' is not defined
```

The nilmtk module already exists in the system (No error when running >>> import nilmtk)

So, can anyone point out for cause of the error that prevent completion of the data conversion process?

Thanks.
Bundit

**Comment by ineswater** [comment]
Hi, 

i got the following problems:

![image](https://cloud.githubusercontent.com/assets/17250328/13048109/99d31154-d3db-11e5-8755-b0e5bca7b586.png)

![image](https://cloud.githubusercontent.com/assets/17250328/13048131/aad7b234-d3db-11e5-9365-42165bd84e7c.png)

So, can anyone help me?

Thanks.
Inês

**Comment by JackKelly** [comment]
please look closely at the IOError near the bottom of the first image :)  `/data/REDD does not exist`.

Also, in future, please copy-and-paste the text from your errors into the issue queue rather than screen shots so that the text is machine-searchable.  Thank you.

**Comment by abhisheknalin** [comment]
This error troubling me since yesterday and I found a solution. I am on windows 10 and using Spyder.
1. Check the working directory. Make sure it is where the nilmtk is installed.

2. Change 
`convert_redd('/data/REDD/low_freq', '/data/REDD/redd.h5')`
to
`convert_redd('data/REDD/low_freq', 'data/REDD/redd.h5')`

3. Inside nilmtk directory there is a data folder. Create a REDD folder and place the REDD data inside it.

Your program should work now.

**Comment by ikrambennasrbennasr** [comment]
Hello i had this issue ! Can someone help me please 
![capture](https://user-images.githubusercontent.com/36957166/38884832-163312fc-4271-11e8-9f49-87f63ec4f240.PNG)

**Comment by nipunbatra** [comment]
@ikrambennasrbennasr I think this suggests that neural NILM isn't properly installed. However, it is out of scope for NILMTK. So, I'll not reopen this issue.
