### ISSUE TITLE
Update JSON import and export functions in CombinatorialOptimisation

### ISSUE THREAD

**Issue by JackKelly** [nilmtk/nilmtk#193]
Perhaps use (and update) the [ApplianceModel](http://nilm-metadata.readthedocs.org/en/latest/central_metadata.html#appliancemodel) schema in NILM Metadata.  Would be nice to have a reusable schema for specifying models.

**Comment by oliparson** [comment]
I've re-implemented model import/export in CO using pickle in a7024fe63ee3f126ca9d361899f9cc611302570f. I know this isn't ideal as the pickled file isn't at all human readable, but at the least it's functional. Sorry Jack!

**Comment by JackKelly** [comment]
That's much better than having no functionality at all!  Good work :)
