### ISSUE TITLE
Reading nilmtk HDF5 in Matlab

### ISSUE THREAD

**Issue by nipunbatra** [nilmtk/nilmtk#200]
This is purely experimental. The aim is to see how efficient Matlab is at reading large HDF5 files.

@RishiBaijal : You can work on this after your current task.

**Comment by PMeira** [comment]
Apparently, if you use the PyTables format it saves as plain HDF5. The file could then be used in external tools more easily:

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.to_hdf.html (`format` parameter)
https://pandas.pydata.org/pandas-docs/stable/io.html#external-compatibility

**Comment by PMeira** [comment]
Cross-reference to a recent nilm_metadata issue: https://github.com/nilmtk/nilm_metadata/issues/36
