### ISSUE TITLE
Simplify writing nilm algorithms by automating metadata creation 

### ISSUE THREAD

**Issue by JackKelly** [nilmtk/nilmtk#210]
Related to #208

**Comment by JackKelly** [comment]
Ok, this is mostly done.  I've modified CO, FHMM and Hart.  I just need to add a doc string to the new method in Disaggregator to make it as easy as possible for folks to write new disaggregation algorithms

**Comment by haderazzini** [comment]
Hi Jack,

I was trying to write a new disaggregation algorithm but I have some problems to save the metadata of a MeterGroup.

And looks like the `_save_metadata_for_disaggregation `is not prepared to MeterGroup, as you can see in:

  ```
        #Appliances and submeters:
        appliances = []
        if supervised:
            for meter in meters:
                meter_instance = meter.instance()
                update_elec_meters(meter_instance)
                for app in meter.appliances:
                    appliance = {
                        'meters': [meter_instance],
                        'type': app.identifier.type,
                        'instance': app.identifier.instance
                        # TODO this `instance` will only be correct when the
                        # model is trained on the same house as it is tested on
                        # https://github.com/nilmtk/nilmtk/issues/194
                    }
                    appliances.append(appliance)
```
For a MeterGroup the `meter_instance` will be a tuple and not a int. When I apply the  DataSet() method the MeterGroup will come like a simple meter. I have tryed to fix it in my code just putting a `if` but didn't work

Could you take a look on this problem?
