### ISSUE TITLE
Parallel processing

### ISSUE THREAD

**Issue by JackKelly** [nilmtk/nilmtk#245]
The chunk-by-chunk architecture introduced in NILMTK v0.2 should make it possible to parellise some functions, e.g. pre-processing and stats functions and possibly metrics and disaggregation.

Perhaps we could achieve this using the [Python multiprocessing module](https://docs.python.org/2/library/multiprocessing.html).

Not a big priority.  And we'd have to be careful to make sure we don't prematurely optimise.  i.e. we need to check that users really want the specific function sped up, and we'd also have to check that the CPU is the bottleneck.

I suspect that some (all?) dataset importers might also benefit from loading the source files in one group of processes, then another group of processes do any conversion, then finally we create a queue of prepared data ready to be written to a `nilmtk.DataStore` (`pd.HDFStore` supports concurrent _reading_ but not concurrent _writing_).  But perhaps it doesn't matter that dataset conversion takes a while because it's only done once.  And wouldn't be done at all if people published their HDF5 files and/or we had a central repository for HDF5 files ;)

**Comment by PMeira** [comment]
Closing in favor of #248 

If someone needs faster converters before that, I implemented an example of multiprocessing in the GREEND converter. It should be straightforward to adapt that for most of the other converters.
