### ISSUE TITLE
Inherit duplicated docstrings in ElecMeter and MeterGroup from Electric

### ISSUE THREAD

**Issue by JackKelly** [nilmtk/nilmtk#276]
@oliparson discovered how to specify common common docstrings using a superclass.  Described in [this comment](https://github.com/nilmtk/nilmtk/issues/268#issuecomment-65666922).

for example, we have copy-and-pasted docstrings for many similar functions in ElecMeter and MeterGroup.

**Comment by PMeira** [comment]
This is the list of common methods in ElecMeter and MeterGroup that are not present in Electric:

```
available_ac_types
available_physical_quantities
building
clear_cache
dataset
dominant_appliance
dropout_rate
get_timeframe
good_sections
instance
is_site_meter
label
load
matches
sample_period
total_energy
upstream_meter
```

**Comment by PMeira** [comment]
There doesn't seem to be much to share anymore, closing. Sharing the same docstring for many of the ones I listed in the previous comment may end up confusing users.
