### ISSUE TITLE
Issue with the iAWE dataset.

### ISSUE THREAD

**Issue by RishiBaijal** [nilmtk/nilmtk#304]
I tried running some of the functions on the iAWE dataset and I encountered some problems. The error messages are too long to be displayed here. Therefore, I have put them on pastebin. The function names  and the links to the errors are given below: 

average_energy_per_period(): http://pastebin.com/CCX2b6Yc
energy_per_meter(): http://pastebin.com/dN32zVXX
entropy_per_meter(): http://pastebin.com/9xB44i8g
fraction_per_meter(): http://pastebin.com/iMgvhpuC

My script: https://github.com/RishiBaijal/nilmtk/blob/master/test_all_functions.py

**Comment by nipunreddevil** [comment]
Work for me. Closing.
