### ISSUE TITLE
Changes to CO

### ISSUE THREAD

**Issue by nipunreddevil** [nilmtk/nilmtk#308]
- [x] train should also take in kwargs?
- [x] allow remove vampire power to be an option
- [x] parameter to fix number of states for each appliance, or, let it be done automatically as we currently do
- [x] breakdown the method to allow disaggregation on a single chunk
- [ ] use partial fit from mini-batch-kmeans
- [x] separate the metadata from the main function (#210)

**Comment by JackKelly** [comment]
Only one TODO is left on this list, so I have split that into a new issue to make it clearer as to what needs to be done: #458
