### ISSUE TITLE
Using `_slots_` for memory optimization

### ISSUE THREAD

**Issue by nipunbatra** [nilmtk/nilmtk#317]
Reference: http://tech.oyster.com/save-ram-with-python-slots/

I am doubtful if we have any class with 1000 or more instances. Still thought of mentioning it here, in case there is a need.

**Comment by PMeira** [comment]
Yeah, I don't think NILMTK structures can gain much from slots. Our main memory difficulties seem to be related to Pandas, and dropping to `float32` where `float64` is used by default should be enough to reduce a lot. 
Dask (and hopefully Pandas2 someday) should help in general if we manage to migrate in the future.
