### ISSUE TITLE
downsample

### ISSUE THREAD

**Issue by MingjunZhong** [nilmtk/nilmtk#343]
There's import error when I am using  `import nilmtk.preprocessing.electricity.building as prepb', see this:

runfile('/home/mzhong/2015-ideal/nilmtk-afhmmsac/demo_nilmtk.py', wdir='/home/mzhong/2015-ideal/nilmtk-afhmmsac')
Traceback (most recent call last):

  File "<ipython-input-1-19d33dc62593>", line 1, in <module>
    runfile('/home/mzhong/2015-ideal/nilmtk-afhmmsac/demo_nilmtk.py', wdir='/home/mzhong/2015-ideal/nilmtk-afhmmsac')

  File "/home/mzhong/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 580, in runfile
    execfile(filename, namespace)

  File "/home/mzhong/2015-ideal/nilmtk-afhmmsac/demo_nilmtk.py", line 9, in <module>
    import nilmtk.preprocessing.electricity.building as prepb

ImportError: No module named electricity.building

=========================================================================
from nilmtk import DataSet, TimeFrame
from nilmtk.disaggregate import CombinatorialOptimisation
from nilmtk.disaggregate import FHMM
from nilmtk import HDFDataStore
from nilmtk.metrics import f1_score
import nilmtk.preprocessing.electricity.building as prepb

target_file = '/home/mzhong/2015-ideal/energy-data/REDD/redd.h5'
redd = DataSet(target_file)

building = redd.buildings[1]
building = prepb.downsample(building, rule='1T')

**Comment by nipunreddevil** [comment]
@MingjunZhong : What sample code are you referring? Could you point to that?
`import nilmtk.preprocessing.electricity.building as prepb` existed long time back and has been deprecated since.

**Comment by MingjunZhong** [comment]
A short question is how to import the function `downsample'?

On 28/01/15 16:28, Nipun Batra wrote:
>
> @MingjunZhong <https://github.com/MingjunZhong> : What sample code are 
> you referring? Could you point to that?
> |import nilmtk.preprocessing.electricity.building as prepb| existed 
> long time back and has been deprecated since.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nilmtk/nilmtk/issues/343#issuecomment-71865459>.
>
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by JackKelly** [comment]
As @nipunreddevil says, the code you refer to uses a very old NILMTK API.  Lots of changes have happened since.  For example, NILMTK now does lazy loading (so you can process arbitrarily large datasets).

If you want to downsample to 1 minute resolution then please use the `sample_period` argument for the `load` or `power_series` methods on the `ElecMeter` or `MeterGroup` classes.  e.g.:

```python
meter = building.elec['washer dryer']
generator = meter.power_series(sample_period=60) # 60 seconds
for chunk in generator:
    # do something with chunk
```

**Comment by nipunreddevil** [comment]
Resampling is an argument to the load function. This function is used throughout the nilmtk pipeline to load data from the Datastore.

Here is a [simple example notebook](http://nbviewer.ipython.org/urls/dl.dropboxusercontent.com/u/75845627/notebooks/wiki/redd_downsample.ipynb) showing how to use resample to load mains data from REDD data set.

Higher order functions in nilmtk (such as disaggregate, train, etc.) allow one to pass parameters the load function. Here' s the method call for FHMM showing how to pass these load arguments: https://github.com/nilmtk/nilmtk/blob/master/nilmtk/disaggregate/fhmm_exact.py#L318

More details about load and the docstring can be found here: https://github.com/nilmtk/nilmtk/blob/master/nilmtk/elecmeter.py#L358

Sorry, we couldn't update our docs explaining this new `load` functionality!

**Comment by MingjunZhong** [comment]
I have this: generator = meter.power_series(sample_period=60), it did not threw errors, but I do not know exactly what generator is? I only know it is an object and it has a few methods. I do not know how to use it. And also generally, I do not know how to use those objects, functions, etc. Do you have manuals?

**Comment by JackKelly** [comment]
generators are a Python concept.  See [here for details](http://www.jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/).

As nipun said, most of our functions have docstrings in the code.  Have a look at the notebook nipun linked to in his last post.  And have a look through the other notebooks in nilmtk/notebooks.  But please note that some of those notebooks are old!

**Comment by MingjunZhong** [comment]
It works. Apologies for those simple questions - I have made a bit progress. Thanks for your help.

**Comment by JackKelly** [comment]
No need to apologise!  I'm sorry our docs are rather out of date.  We plan to update the docs very soon.
