### ISSUE TITLE
HDF and CSV on-disk documentation

### ISSUE THREAD

**Issue by oliparson** [nilmtk/nilmtk#344]
I haven't been able to find any documentation about the structure of the HDF format on disk, and there definitely isn't such docs for the CSV format. Any idea where this documentation should live? I'm happy to add it when I get a chance

**Comment by nipunreddevil** [comment]
Some documentation exists here: http://nilmtk.github.io/nilmtk/master/writing_a_dataset_converter.html

**Comment by oliparson** [comment]
Ah nice, I completely missed that. I guess we should rename this to be a description of an HDF datastore, and write a similar one for the CSV datastore. @JackKelly what are your thoughts?

**Comment by JackKelly** [comment]
Yeah, sounds like a great idea!

**Comment by JackKelly** [comment]
I just had a quick skim read of out existing "Writing a Dataset Converter" docs.  I suspect that about 90% of that text is applicable to CSV as well.  So I wonder if there's a way to have a single page which describes our HDF data format and our CSV data format.  They're pretty similar, right?  Maybe the page would start by describing all the similarities and then go into the few specific details of each format.
