### ISSUE TITLE
Hmmlearn

### ISSUE THREAD

**Issue by lawrencechng92** [nilmtk/nilmtk#346]
Hi, as i was trying out nilmtk on Windows i found out that i do not have a module called hmmlearn. How can i rectify this problem ? Thankss

**Comment by nipunreddevil** [comment]
You can install hmm learn as follows:
`pip install git+https://github.com/hmmlearn/hmmlearn.git`

Or, you may wish to clone hmm learn and run install as per hmmlearn's [documentation](https://github.com/hmmlearn/hmmlearn).

**Comment by nipunreddevil** [comment]
@lawrencechng92 Please let us know if this works. I've also updated the README mentioning how to install hmm learn.

**Comment by lawrencechng92** [comment]
Hi, 
When i tried to run setup.py develop it gave me an error.

Date: Thu, 5 Feb 2015 12:08:45 -0800

**Comment by nipunreddevil** [comment]
`setup.py develop` error on which package?

**Comment by lawrencechng92** [comment]
hmmlearn package on Windows

Date: Thu, 5 Feb 2015 12:46:38 -0800

**Comment by nipunreddevil** [comment]
`hmm learn` documentation states to use `setup.py install` and not `setup.py develop`.

**Comment by lawrencechng92** [comment]
was referring to the readme file that was just posted. However, i change to install and it works fine now. Thank you Mr. Batra. Btw, the python file download_dataport in dataset_converters doesnt have a pyc extension. Therefore, i could not import that module into Python. (I want to download the dataset from pecan street) . Do you know the solution ?

Date: Thu, 5 Feb 2015 12:52:38 -0800

**Comment by nipunreddevil** [comment]
I am closing this issue. If needed, please create a new issue for data port downloader.
