### ISSUE TITLE
Input to metric functions are DataFrame

### ISSUE THREAD

**Issue by MingjunZhong** [nilmtk/nilmtk#349]
I am trying to use metric functions to compute error measures using metric functions, e.g., mean_normalized_error_power. Obviously, it requires nilmtk.MeterGroup as the input. But I have stored the inferred appliances and ground truth ones in DataFrame. Is that possible to transfer a DataFrame to a MeterGroup? Is it possible that these metric functions use DataFrame as input?

I got this:
metrics = {
    'mean normalized error power':
          mean_normalized_error_power,
    'fraction energy assigned correctly': 
          fraction_energy_assigned_correctly,
    'f score': f1_score,
    'RMS Error Power': rms_error_power
}

for metric_name, metric_func in metrics.iteritems():
    result = metric_func(inferredAppliance, groundTruthAppliance)

Traceback (most recent call last):

  File "<ipython-input-42-868f189d9b6c>", line 11, in <module>
    result = metric_func(inferredAppliance, groundTruthAppliance)

  File "/home/mzhong/nilmtk/nilmtk/nilmtk/metrics.py", line 172, in rms_error_power
    predictions, ground_truth)

  File "/home/mzhong/nilmtk/nilmtk/nilmtk/metergroup.py", line 1685, in iterate_through_submeters_of_two_metergroups
    for master_meter in master.submeters().meters:

  File "/home/mzhong/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 1947, in __getattr__
    (type(self).__name__, name))

AttributeError: 'DataFrame' object has no attribute 'submeters'

**Comment by JackKelly** [comment]
> I have stored the inferred appliances and ground truth ones in DataFrame. Is that possible to transfer a DataFrame to a MeterGroup? Is it possible that these metric functions use DataFrame as input?

Great questions!  This is something that we're very much aware of and will implement fairly soon.  i.e. we will soon modify the metrics functions (and the disag classes) so they can work with simple dataframes (as well as MeterGroups).  Right now, I don't think there is a simple way to use dataframes with the metric functions, other than to modify the metrics functions your self, sorry.

**Comment by MingjunZhong** [comment]
Ok I see, then I will be writing myself. Thanks.

**Comment by JackKelly** [comment]
If you do write the code, please consider creating a fork on NILMTK first, then make your modifications, and then submit a pull request so others can benefit from your work ;)

**Comment by nipunreddevil** [comment]
We used to have this in the first release: https://github.com/nilmtk/nilmtk/blob/v0.1.1/nilmtk/metrics.py

Shouldn't be tricky to work with. I had to submit some research a while back and I also resorted to creating functions acting on data frame. The code was pretty ad-hoc though.

**Comment by JackKelly** [comment]
Yeah, I also need to work with DataFrames in my research at the moment.  Definitely need to refactor some of NILMTK to make it easier to work with vanilla DFs.  I'm not sure the best way to expose these functions?  We could have a single function name for each metric which detects if the arguments are DFs or MeterGroups and acts accordingly.  Or should we have a `rms_error_power_single_chunk()` function and a `rms_error_power()` function?  I think I prefer having a single function name.  Although it's slightly less explicit.

**Comment by nipunreddevil** [comment]
I prefer being more explicit. Also, makes functions smaller. Plus, I always would like things to work even outside nilmtk.

**Comment by JackKelly** [comment]
I'm really torn.  On the one hand, Python encourages us to be explicit whenever possible. On the other hand, our API will be simpler if we have a smaller number of function names.  And it's quite normal for libraries like Numpy to have single functions which can take a variety of types (indeed, in statically typed languages like C++, it's positively *encouraged* to make use of function overloading).  For example, `np.sum()` can take a scalar, a Python list, a numpy vector, a numpy matrix etc.  We don't have `np.sum_list()` and `np.sum_vector()` and `np.sum_matrix()`.  The fact that `np.sum()` is overloaded also makes it easier to create general code on top of `np.sum()` (you can write a function which uses `np.sum()` without worrying if you input is a list, vector or matrix).

> Also, makes functions smaller.

Oh, sure, small functions are important.  I'd propose that each public metric function is just a little wrapper function which checks the input types and calls the appropriate private method.  A bit like how `ElecMeter.plot()` works.

>  I always would like things to work even outside nilmtk.

I'm afraid I'm not sure what you mean?

**Comment by nipunreddevil** [comment]
@JackKelly I see your point. It makes sense. Keeping specific methods private as done in `elec.plot()`  is perfect!

**Comment by MingjunZhong** [comment]
Thanks for all, the first release seems working fine! I will need to write up other error measures as well.

**Comment by JackKelly** [comment]
Just a quick update... I'll probably be working on making the v0.2 metrics accept dataframes quite soon, as I need it for my own work.

**Comment by MingjunZhong** [comment]
Good news and thanks!!!
