### ISSUE TITLE
Disaggregation: Missing values / dates

### ISSUE THREAD

**Issue by piskopat** [nilmtk/nilmtk#351]
Hey, I am new in the area of python / nilmtk and want to use nilmtk for an university project.
Maybe a briefly summary of the project:
- My team and me want to develop a prototype website for an utility company, which shows the customer how much each device has consumed. 
- for this purpose, we are using NILMTK with the REDD dataset
- the intention was to export the disaggregated data out of nilmtk and import it into a database

After some issues at the beginning, we started to work with nilmtk on a windows-pc. Our current problem is that the data, which is exported, has missing values (as can be seen in the picture).
![unbenannt](https://cloud.githubusercontent.com/assets/9382099/6349651/08d66b5e-bc2d-11e4-9e04-139a7fd45277.JPG)

Our source code:

```
from nilmtk import DataSet, TimeFrame
from nilmtk.disaggregate import CombinatorialOptimisation
from nilmtk import HDFDataStore
from pandas import HDFStore

redd = DataSet('redd.h5')
redd.set_window(start=None, end='2011-05-01 00:00:00')
for key in redd.buildings:
	elec = redd.buildings[key].elec
	co = CombinatorialOptimisation()
	co.train(elec)


	redd.set_window(start='2011-05-01 00:00:00', end=None)
	
	number=str(key)
	#	mains = elec.meters_directly_downstream_of_mains()
	mains = elec.mains()
	output = HDFDataStore('building_'+number+'.h5', 'w')

	co.disaggregate(mains, output)
	output.close()
	store = HDFStore('building_'+number+'.h5')
	datenarray = store.keys()
	
	for c in datenarray: 
		stringsplit = c.split('/',4)
		building= stringsplit[1]
		meter = stringsplit[3]
		#store[c].to_csv(building+'_'+meter+'.csv',chunksize=100000)
		store[c].to_csv(building+'_'+meter+'.csv')
		print (c+'.csv') 
		del stringsplit
		del building
		
	del elec	
	del output
	del co
	del datenarray
	store.close()
```

Furthermore we noticed, that if we just extract all meters of one building instead of all buildings, the extracted files contain more lines. 
So using elec = redd.buildings[1].elec instead of elec = redd.buildings[key].elec results in files, which have more records.

Unfortuntaley we don´t know why. Can someone help us?
I know this hasn´t to do something with the nilmtk-code itself, but maybe others had the same problem.

**Comment by JackKelly** [comment]
Regarding the gaps in your output data:

REDD has gaps.  Do the gaps in your output correspond to gaps in the REDD mains data?  NILMTK can't disaggregate if there are gaps in the mains data!

**Comment by piskopat** [comment]
Thank you for your answer! It´s as you said because of gaps in the REDD dataset.
Just for my understanding:
If the mains data would be over a longer period than the (sub-)meter data, than NILMTK would still create disaggregated data for each device, right? Lets say I just modify the mains data in REDD and train with the same timeframe. Would this work? (I suppose so, but just to be on the safe side)

**Comment by JackKelly** [comment]
> If the mains data would be over a longer period than the (sub-)meter data, than NILMTK would still create disaggregated data for each device, right

yes, NILMTK will try to disaggregate any mains data that you give to it (once it's trained, of course!)

> Lets say I just modify the mains data in REDD and train with the same timeframe. Would this work?

How exactly do you plan to modify the mains data?

**Comment by piskopat** [comment]
>How exactly do you plan to modify the mains data?

Think your first answer made it clear. I was just thinking about the possibility of adding "fake" consumption data and timestamps (of course starting after the last timestamp in the dataset)  to the REDD dataset.

There is one further question, which arrised during this week:
Can we also use the ECO and GreenD dataset for the disaggregation? Because for the first dataset I can´t disaggregate (receiving an error) and for the second dataset I can´t convert the dataset. Just wanted to ask briefly, before creating new issues.

**Comment by JackKelly** [comment]
> Can we also use the ECO and GreenD dataset for the disaggregation?

I'm afraid I haven't looked at the ECO or GreenD datasets or the converters so I'll let someone else answer...  if you get bugs then by all means submit issues about each separate bug!
