### ISSUE TITLE
Issue on applying CO and FHMM method on AMPDs dataset

### ISSUE THREAD

**Issue by GautierAppert** [nilmtk/nilmtk#352]
Hi everbody :) hope you are fine :)
We have a little issue on applying the nilmtk package on the AMPDs dataset.
We convert the dataset in h5 format and we import the data with the DataSet() function, then we select one day of consumption (using the we.set_window() function). Then we use the fhmm_exact.FHMM() function but we have an error message. We applied this strategy on the redd dataset and it worked but here with the AMPDs dataset it implies a bug that we don't manage to solve.
If anybody has an idea it will be cool for us :+1: 
Have a great day :+1: :+1: 

Gautier and Simon

PS :  the error message : 
![fhmm_faile](https://cloud.githubusercontent.com/assets/10998195/6351451/0f67a0b4-bc3c-11e4-974e-f32328635129.png)

**Comment by JackKelly** [comment]
Hi there,

Thanks for reporting this bug.  Please can you copy and paste the full traceback into the issue queue?

**Comment by GautierAppert** [comment]
Ok no pb, I take all the pictures loool
![first_stage](https://cloud.githubusercontent.com/assets/10998195/6352023/19526772-bc40-11e4-8020-4284571c2875.png)
![second_stage](https://cloud.githubusercontent.com/assets/10998195/6352026/1f875b16-bc40-11e4-80bf-9832b1425270.png)
![third_stage](https://cloud.githubusercontent.com/assets/10998195/6352027/2315fa80-bc40-11e4-841c-9aa960428727.png)
![fourth_stage](https://cloud.githubusercontent.com/assets/10998195/6352028/264f14b6-bc40-11e4-9940-d7cf279d16dc.png)
![five_step](https://cloud.githubusercontent.com/assets/10998195/6352033/2a6123b4-bc40-11e4-95e0-cc0522ab3af5.png)

**Comment by GautierAppert** [comment]
I forgot the CO method : 
![last_step](https://cloud.githubusercontent.com/assets/10998195/6352100/80603ff2-bc40-11e4-8d73-3b720934585d.png)

**Comment by oliparson** [comment]
Hi Gautier,

Can you copy-paste the *text* of the code which will allow us to reproduce the error, as well as the *text* of the error generated? I recently wrote a guide on submitting a report which will allow us to help you as easily possible:
https://github.com/nilmtk/nilmtk#submitting-a-bug-report

**Comment by GautierAppert** [comment]
Thanks you very much for this blog.
Sorry for the delay of the answer, I was quite busy.
I will send you the .py file rigth now 

Sorry again for the delay of the answer

**Comment by GautierAppert** [comment]
# coding: utf-8

# In[2]:

import numpy as np
import pandas as pd
from os.path import join

from pylab import rcParams
import matplotlib.pyplot as plt
get_ipython().magic(u'matplotlib inline')
rcParams['figure.figsize'] = (14, 6)

plt.style.use('ggplot')
import nilmtk
from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore, dataset_converters
from nilmtk.disaggregate import CombinatorialOptimisation
from nilmtk.utils import print_dict
from nilmtk.metrics import f1_score
from nilmtk.metrics import f1_score, rms_error_power, fraction_energy_assigned_correctly, error_in_assigned_energy
from nilmtk.disaggregate import CombinatorialOptimisation, fhmm_exact

import warnings
warnings.filterwarnings("ignore")


# In[3]:

pathIn = "/home/gautier/nilmtk/nilmtk/dataset_converters/ampds/electricity/"
pathOut = "/home/gautier/nilmtk/nilmtk/dataset_converters/ampds/ampds.h5"
dataset_converters.convert_ampds(pathIn ,pathOut)


# In[4]:

data_dir = "/home/gautier/nilmtk/nilmtk/dataset_converters/ampds/ampds.h5"
we = DataSet(join(data_dir))
print('loaded ' + str(len(we.buildings)) + ' buildings')


# In[5]:

print_dict(we.metadata)


# In[9]:

# une seule maison 
building_number = 1
print_dict(we.buildings[1].metadata)


# In[10]:

elec = we.buildings[building_number].elec
elec.appliances


# In[13]:

#on selectionne la plage de données (Vrai data !! attention )
we.set_window(start='2012-04-20 00:00:00', end='2012-04-21 00:00:00')
elec.plot();
plt.xlabel("Time");


# In[20]:

we.set_window(start='2013-03-01 00:00:00', end='2013-03-02 00:00:00')
elec.plot();
plt.xlabel("Time");


# In[25]:

# Train
fhmm = fhmm_exact.FHMM()
fhmm.train(elec)


# In[22]:

co = CombinatorialOptimisation()
co.train(elec)


# In[24]:

for model in co.model:
    print_dict(model)

**Comment by GautierAppert** [comment]
And the Erro Message : 

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-25-c972abce3ee5> in <module>()
      1 # Train
      2 fhmm = fhmm_exact.FHMM()
----> 3 fhmm.train(elec)

/home/gautier/nilmtk/nilmtk/disaggregate/fhmm_exact.pyc in train(self, metergroup)
    240             self.meters.append(meter)
    241 
--> 242         learnt_model_combined = create_combined_hmm(new_learnt_models)
    243         self.individual = new_learnt_models
    244         self.model = learnt_model_combined

/home/gautier/nilmtk/nilmtk/disaggregate/fhmm_exact.pyc in create_combined_hmm(model)
    129                   for appliance in model]
    130 
--> 131     pi_combined = compute_pi_fhmm(list_pi)
    132     A_combined = compute_A_fhmm(list_A)
    133     [mean_combined, cov_combined] = compute_means_fhmm(list_means)

/home/gautier/nilmtk/nilmtk/disaggregate/fhmm_exact.pyc in compute_pi_fhmm(list_pi)
    116     result : Combined Pi for the FHMM
    117     """
--> 118     result = list_pi[0]
    119     for i in range(len(list_pi) - 1):
    120         result = np.kron(result, list_pi[i + 1])

IndexError: list index out of range

**Comment by nipunreddevil** [comment]
`elec. plot()` output looks weird. I think something could be wrong with the data set converter!

Can you print the output of the following?

`elec`

`elec.mains()`

`elec.submeters()`

**Comment by GautierAppert** [comment]
Hey , I give you the output : ( it looks like the elec.submeters() output is weird becausee there is nothing in the attribute submeter() )
![elec](https://cloud.githubusercontent.com/assets/10998195/6417758/1281cea2-beb0-11e4-8904-27d57a36b375.png)
![elec mains](https://cloud.githubusercontent.com/assets/10998195/6417767/20c61cb6-beb0-11e4-9a23-2e36e8c1cb95.png)
![elec submeters](https://cloud.githubusercontent.com/assets/10998195/6417777/277954c4-beb0-11e4-8556-6a28c15596f0.png)

**Comment by nipunreddevil** [comment]
Thanks for this output. So, my hunch is correct that there was something wrong with the metadata itself.
I just had a chance to look at the [AMPds metadata](https://github.com/nilmtk/nilmtk/blob/master/nilmtk/dataset_converters/ampds/metadata/building1.yaml) and I believe I see the tiny bug.

@JackKelly : Meters 2 through 21 should not be an instance of PS18 I imagine, as PS18 is marked as a site meter. 

I am happy to make this small change. However, I won't be to test it soon.

**Comment by GautierAppert** [comment]
Oki but it means that we have to change the .yaml file ? If Meters 2 through 21 is not an instance of PS18 we have to change the metadat files (in the .yaml files) and redo the H5 conversion ?
I have another question, if Meters 2 through 21 is not an instance of PS18, it means that they are an instance of something else but what ?

Thanks again for your help and all the packages

**Comment by nipunreddevil** [comment]
I just made the required change in the above [commit](https://github.com/nilmtk/nilmtk/commit/5ad87bbc94b31dff67dc313b7bfabd80c8cf2662)

You may pull to the latest version.

You don't need to run the full converter again. Just calling the relevant code to copy the metadata should work. However, if time is not an issue, I'd suggest running the whole process again. Please let us know if this works for you.

Caveat: I haven't got the chance to test this change. I think it should address the problem you've raised.

**Comment by GautierAppert** [comment]
Thanks you very much for your correction of the ".yaml " file, it was very quick, thanks again !!  I redo all the code and The CO works but note the FHMM method. I don't really understand why maybe it is due to my computer which is not very powerful, I don't know really. But thanks again for your help and the spirit of code and data science you are sharing :)

**Comment by GautierAppert** [comment]
I give you the code and the errro message : 



# coding: utf-8

# In[2]:

import numpy as np
import pandas as pd
from os.path import join

from pylab import rcParams
import matplotlib.pyplot as plt
get_ipython().magic(u'matplotlib inline')
rcParams['figure.figsize'] = (14, 6)

plt.style.use('ggplot')
import nilmtk
from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore, dataset_converters
from nilmtk.disaggregate import CombinatorialOptimisation
from nilmtk.utils import print_dict
from nilmtk.metrics import f1_score
from nilmtk.metrics import f1_score, rms_error_power, fraction_energy_assigned_correctly, error_in_assigned_energy
from nilmtk.disaggregate import CombinatorialOptimisation, fhmm_exact

import warnings
warnings.filterwarnings("ignore")


# In[3]:

pathIn = "/home/gautier/nilmtk/nilmtk/dataset_converters/ampds/electricity/"
pathOut = "/home/gautier/nilmtk/nilmtk/dataset_converters/ampds/ampds.h5"
dataset_converters.convert_ampds(pathIn ,pathOut)


# In[4]:

data_dir = "/home/gautier/nilmtk/nilmtk/dataset_converters/ampds/ampds.h5"
we = DataSet(join(data_dir))
print('loaded ' + str(len(we.buildings)) + ' buildings')


# In[5]:

print_dict(we.metadata)


# In[6]:

# une seule maison 
building_number = 1
print_dict(we.buildings[1].metadata)


# In[7]:

elec = we.buildings[building_number].elec
elec.appliances


# In[8]:

elec


# In[11]:

elec.draw_wiring_graph();


# In[9]:

elec.mains()


# In[10]:

elec.submeters()


# In[21]:

we.set_window(start='2013-03-01 00:00:00', end='2013-03-02 00:00:00')
elec.plot();
plt.xlabel("Time");


# In[20]:

# Train
fhmm = fhmm_exact.FHMM()
fhmm.train(elec)


# In[15]:

co = CombinatorialOptimisation()
co.train(elec)


# In[16]:

for model in co.model:
    print_dict(model)


# In[17]:

# Disaggregate
data_dir = "/home/gautier/nilmtk/nilmtk/dataset_converters/ampds/"
disag_filename = join(data_dir, "ampds_disag.h5")
output = HDFDataStore(disag_filename, "w")
co.disaggregate(elec.mains(), output)
output.close()


# In[18]:

disag = DataSet(disag_filename)
disag_elec = disag.buildings[building_number].elec
disag_elec.plot()
plt.xlabel("Time")
disag.store.close()

**Comment by GautierAppert** [comment]
the elec.draw_graph function works : 
![elec draw_graph](https://cloud.githubusercontent.com/assets/10998195/6426483/5eb8ce8a-bf5d-11e4-9960-e7560a86ef39.png)

**Comment by GautierAppert** [comment]
the CO works also :+1: 

![co_over_ampds](https://cloud.githubusercontent.com/assets/10998195/6426486/a5f96dae-bf5d-11e4-9ebb-6b17ba751546.png)

**Comment by GautierAppert** [comment]
But the FHMM method seems to have some bug or maybe it is my computer which have not enough memory for doing the job : 
![fhmm_over_ampds](https://cloud.githubusercontent.com/assets/10998195/6426494/14708434-bf5e-11e4-8021-f4c6717480df.png)

**Comment by GautierAppert** [comment]
I give you the all the error message for the FHMM method : 
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-20-c972abce3ee5> in <module>()
      1 # Train
      2 fhmm = fhmm_exact.FHMM()
----> 3 fhmm.train(elec)

/home/gautier/nilmtk/nilmtk/disaggregate/fhmm_exact.pyc in train(self, metergroup)
    240             self.meters.append(meter)
    241 
--> 242         learnt_model_combined = create_combined_hmm(new_learnt_models)
    243         self.individual = new_learnt_models
    244         self.model = learnt_model_combined

/home/gautier/nilmtk/nilmtk/disaggregate/fhmm_exact.pyc in create_combined_hmm(model)
    130 
    131     pi_combined = compute_pi_fhmm(list_pi)
--> 132     A_combined = compute_A_fhmm(list_A)
    133     [mean_combined, cov_combined] = compute_means_fhmm(list_means)
    134     #model_fhmm=create_combined_hmm(len(pi_combined),pi_combined, A_combined, mean_combined, cov_combined)

/home/gautier/nilmtk/nilmtk/disaggregate/fhmm_exact.pyc in compute_A_fhmm(list_A)
     86     result = list_A[0]
     87     for i in range(len(list_A) - 1):
---> 88         result = np.kron(result, list_A[i + 1])
     89     return result
     90 

/home/gautier/anaconda/lib/python2.7/site-packages/numpy/lib/shape_base.pyc in kron(a, b)
    780     axis = nd-1
    781     for _ in range(nd):
--> 782         result = concatenate(result, axis=axis)
    783     wrapper = get_array_prepare(a, b)
    784     if wrapper is not None:

MemoryError:

**Comment by nipunreddevil** [comment]
Thanks for your kind words. FHMM is memory intensive and on 20 appliances the model can't fit into memory. 

Please have a look at this notebook on how to select top-k appliances and learning FHMM on it
http://nbviewer.ipython.org/github/nilmtk/nilmtk/blob/master/notebooks/experimental/co_fhmm.ipynb

More info on FHMM scalability here: https://github.com/nilmtk/nilmtk/issues/67

I'll close this issue now.
