### ISSUE TITLE
ValueError: Length of names must match number of levels in MultiIndex.

### ISSUE THREAD

**Issue by GautierAppert** [nilmtk/nilmtk#363]
Hi everybody, hope you are fine.

Me and a friend  are working on our own dataset now and we managed to convert our dataset in "H5 format" (it works, there is no error message actually) by creating our own dataset converter which is very similar to the one of AMPDs (as we have .csv file as input). 

But we are not sure that our data conversion is really well done because when we try to work on the result H5 file (loading the H5 file works really well with the DataSet() function) and try to plot the data we have the following error message "ValueError: Length of names must match number of levels in MultiIndex." after the command  elec.plot(); plt.xlabel("Time");

If anyone as an idea of what would be the problem that we generate it will be very cool for us.
thanks to all data scientists.
we keep the spirit of the geek attitude

:+1:

**Comment by oliparson** [comment]
This might be a problem with the column names of your dataframes. Did you follow the documentation for writing a data set converter (http://nilmtk.github.io/nilmtk/master/writing_a_dataset_converter.html), specifically the 'Column labels' section?

**Comment by JackKelly** [comment]
@GautierAppert   That's great news that you've written a new dataset converter!

As well as the docs that @oliparson mentioned, it's also worth taking a look at NILMTK's [REDD converter](https://github.com/nilmtk/nilmtk/blob/master/nilmtk/dataset_converters/redd/convert_redd.py) because that code is probably the most well-tested of the converters.

**Comment by GautierAppert** [comment]
Thanks for your answers :+1: 
It was definitely a probleme of how I define the name of the columns. In fact I forgot in the  data converter to organise the columns names with the line code " df.columns.set_names(LEVEL_NAMES, inplace=True) ".  So the header (lables names of colums)  of the data frame was totaly wrong before that line of code.
Thanks again for your help :+1: 

I manage to start some desaggregation with the CO method but I have a probleme with the FHMM method when running the following code " fhmm.disaggregate(elec.mains(), output) " which tells that 
" UnboundLocalError: local variable 'measurement' referenced before assignment ". Maybe I will restart all the process and I will see again.

Thanks for all your Package and data science spirit :+1:
