### ISSUE TITLE
What is "vampire_power" ? We have vampire_power = 0.0 watts

### ISSUE THREAD

**Issue by GautierAppert** [nilmtk/nilmtk#364]
Hi guys :)
We are working again with disagregation with our dataset that we converted in h5 format. But we are wondering why we have a little trouble in disagregation with CO method because we have only the agregate power series in the plot of the result. We are wondering if this is due to the fact that we have the "vampire_power = 0.0 watts".  I give you some picture:
![desag_plot](https://cloud.githubusercontent.com/assets/10998195/6643571/875eba66-c9ad-11e4-9c25-aa3082722581.png)

If you have any ideas it will be very cool 
Thanks to all of us :)
:+1:

**Comment by oliparson** [comment]
`vampire_power` is the amount of power which is 'always on', also known as standby power. Since your power seems to drop to 0, there is no vampire load, so `vampire_power` will be set to 0.
