### ISSUE TITLE
UnboundLocalError: local variable 'measurement' referenced before assignment

### ISSUE THREAD

**Issue by GautierAppert** [nilmtk/nilmtk#365]
Hi guys :)
I am working again with a friend named Simon, with our own data (which are not very well collected but anyway...). We convert all the CSV in h5 formats using yaml files. We tried to launch the FHMM method over this data but it seems that we have a error message when we execute the code : 
"     fhmm.disaggregate(elec.mains(), output) 
      output.close()    "
I give you somes pictures : 
![fhmm_training](https://cloud.githubusercontent.com/assets/10998195/6656239/0bbf903e-cb23-11e4-85d5-3f368ce8d365.png)
![fhmm](https://cloud.githubusercontent.com/assets/10998195/6656240/127bd72a-cb23-11e4-9478-a664d94f8d89.png)
![true_data](https://cloud.githubusercontent.com/assets/10998195/6656241/18acab2e-cb23-11e4-8eba-778f7495b4a1.png)

Thanks you for all your help :+1: 
I know that my level in Python is not very well (since I was more using R in the past)  but with this package I improve my self a lot :+1:

**Comment by JackKelly** [comment]
Sorry for taking a while to get back to you.  I have just pushed some new code which might fix this issue.  Please let me know how you get on!  I suspect the problem was that there was no data to disaggregate and the code couldn't handle that case!

**Comment by nipunreddevil** [comment]
Thanks for the fix @JackKelly 
I guess in the current implementation, this fix would need to go into each disaggregation algorithm. Another reason to have a superclass.

**Comment by JackKelly** [comment]
@nipunreddevil exactly.  I'm really looking forward to us having a Disaggregator superclass.  It should help tidy up the code a lot ;)

**Comment by JackKelly** [comment]
I'll assume this issue is fixed.  Please re-open if necessary.
