### ISSUE TITLE
Contents of each table and frequency of each meters

### ISSUE THREAD

**Issue by GautierAppert** [nilmtk/nilmtk#369]
Hi guys :)
Hope you are fine :)
I am working with Simon on our own data which I converted in h5 format, coding our own dataset converter which is very similar to the one of the AMPDs dataset.
However we have only one measure in our Data which is the Power Active but we don't have the measure  energy reactive and voltage (Maybe the Voltage in France is 230V, we think to put the Voltage variable to the standard measure in France which is 230V). In fact I am wondering if this is a probleme to apply the NILMTK (using the desagregation method like FHMM and CO).
I hope we can do a desagregation with only the Power Active measure since we don't have the
other measures. One last question :  we hope that it does not matter that our frequency measure might be between 5 and  minutes...
Thanks you very much guys :) 
Thanks to share the spirit of data science with your package :)

(I have a last question, in fact I wonder if you think to create a R Shiny application illustrating your package NILMTK ? I ask this because I am more familiar with R but Python is really cool too.)

**Comment by nipunreddevil** [comment]
>However we have only one measure in our Data which is the Power Active but we don't have the measure energy reactive and voltage (Maybe the Voltage in France is 230V, we think to put the Voltage variable to the standard measure in France which is 230V). In fact I am wondering if this is a probleme to apply the NILMTK (using the desagregation method like FHMM and CO).

It should not be a problem. Many data sets provide only active power consumption.

>we hope that it does not matter that our frequency measure might be between 5 and minutes...

You mean 5 seconds and 1 minute? I think 1 minute resolution should be fine.

> if you think to create a R Shiny application illustrating your package NILMTK

We created a Shiny like web application a while ago. Unfortunately, it is not running currently. We'll be more than happy if you would be willing to create such an app :)

**Comment by GautierAppert** [comment]
Thanks you very much for your answer :)
Therefor we will apply the NILMTK on our data this we have only the Power Active variable.
However we have aggregated the data with a 5 minutes frequency, we hope this is not to much large for the Package.
Maybe we will try to build a Shiny application on your Package (we wish to apply this on a R-shiny server but it seems that we have to recode all the algorithm in R which is not very easy loool), but maybe it will be cool to build a R package to publish. 
Thanks you again and we are happy to share the GEEK attitude with you :)

**Comment by nipunreddevil** [comment]
>Maybe we will try to build a Shiny application on your Package
Cool!

I'll close this issue now.

**Comment by JackKelly** [comment]
Hi @Gautier, do you have appliance training data for your dataset? At the
moment, nilmtk's algorithms work best when trained on appliance data from
the same house that will be used for disaggregation (this is a huge
limitation of the algorithms and is something we're working on to change!)

Also, thank you for being so encouraging and positive ;)
