### ISSUE TITLE
Should `Ambient` have a `temperature` attribute or a `weather` attribute?

### ISSUE THREAD

**Issue by JackKelly** [nilmtk/nilmtk#37]
It would be great if we could store different weather variables like sunshine, temperature outside, temperature per room etc.  So I wonder if, instead of a `temperature` attribute, maybe `Ambient` could have a `weather` attribute which is a DataFrame with columns for some combination of temperature, sunshine etc.  What do you think?

**Comment by BaluJr** [comment]
Has the development of an `Ambient` class received further attention? 
I am looking for a way to include weather data. This issue looks like a promising starting point.
But I do not find correponding code anywhere in the repo.

**Comment by nipunbatra** [comment]
Hi.
No. We haven't ever gotten round to support the ambient class. I did some
ad-hoc hack a long time back, but never with nilmtk.
