### ISSUE TITLE
PARAMETER ESTIMATION in THE NILMTK FHMM method

### ISSUE THREAD

**Issue by GautierAppert** [nilmtk/nilmtk#379]
Hi guys :)
Hope you are fine :)
We are working on the NILMTK, but we plan to rewiew the theory in the FHMM method. In fact we are wondering if there is a way to catch the parameters estimation in the FHMM method (and CO maybe).
Is it possible to capture some estimation after the desagregation or it is hidden in the algorithm ?

Thanks your very much for your help :)
:+1:

**Comment by JackKelly** [comment]
NILMTK uses the python library [`hmmlearn`](https://github.com/hmmlearn/hmmlearn) for FHMM parameter estimation, so you should have access to all the parameters estimated by hmmlearn.

Take a look at the `.model` attribute in the disaggregator classes.

One thing to mention is that [we have plans to improve the Disaggregation interface](https://github.com/nilmtk/nilmtk/issues/271) when we get time.

**Comment by nipunreddevil** [comment]
More detail here: https://github.com/nilmtk/nilmtk/issues/367

**Comment by GautierAppert** [comment]
Thanks you very much Guys :)
You are all wonderful :)
Thanks for your help :)
It is very exciting to work on your module NILMTK :+1: 
Thanks again for your share of data science spirit :)
We love data science :)
Gautier and Simon

**Comment by JackKelly** [comment]
Thank you for your kind words ;)
