### ISSUE TITLE
Broken API docs

### ISSUE THREAD

**Issue by oliparson** [nilmtk/nilmtk#380]
Spinx doesn't seem to produce any docs from our docstrings, e.g. http://nilmtk.github.io/nilmtk/master/nilmtk.html#nilmtk-metrics-module

**Comment by nipunreddevil** [comment]
Fixed. Need to call 

`/nilmtk$ sphinx-apidoc -f -o docs/source nilmtk`

More details here: http://nilmtk.github.io/nilmtk/master/contribute.html#contributing-documentation
