### ISSUE TITLE
Parameter estimation in the CO method 

### ISSUE THREAD

**Issue by GautierAppert** [nilmtk/nilmtk#381]
Hi guys :)
Once again we have some questions on the parameter estimation  
We have much more understand how obtain the parameter estimation (transition matrix and initial distribution) in the FHMM method. 
However we are now wondering how obtain the parameter estimation in the CO method. In fact  we are wondering if it exists parameter
in the CO method or just estimation of the "states" (ON, OFF) of the meter.

Thanks again for your package NILMTK and your Help :)
Simon and Gautier

**Comment by JackKelly** [comment]
IIRC all the learnt params are in `CO.model`

**Comment by nipunreddevil** [comment]
Jack is right. Have a look at the train methods in https://github.com/nilmtk/nilmtk/blob/master/nilmtk/disaggregate/combinatorial_optimisation.py for more details on how parameter estimation is done.

**Comment by GautierAppert** [comment]
Hi guys :)
Thanks to all your answers :+1: . We understand much better how to find the mean of consumption of each appliance during each states (ON,OFF) (using something like this loop : for model in co.model:
print_dict(model)). But we have one last question about the CO algorithm : how find the states "ON" or "OFF" in each time slices for each appliance using the command line "co.model" ?
Precisely we did not manage to find the states ("ON","OFF") of each appliances in each time slices.

Thanks you very much again for all your help and code sharing :)
Gautier and Simon

**Comment by nipunreddevil** [comment]
I'll give a minimal example to illustrate how CO works.

Say, we have training data for 2 appliances: air conditioner (AC) and fridge. AC has 2 states consuming 0 Watts and 2000 Watts respectively. Fridge has 2 states consuming 0 Watts and 100 Watts respectively.

Now, we have four possible combinations:

1. AC off, Fridge off (0 + 0 = 0 W)
2. AC off, Fridge on (0 + 100 = 100 W)
3. AC on, Fridge off (2000 + 0 = 2000 W)
4. AC on, Fridge on (2000 + 100 = 2100 W)

Now, say you have aggregate power time series as follows:

[110, 110, 110, 2100, 2100, 2000]

For the first three time slices we'll have the state as fridge on, AC off. For the next two, fridge on, AC on. For the last one, AC on and fridge off.

Hope this is clear.

**Comment by GautierAppert** [comment]
Thanks you ver much :)

**Comment by nipunreddevil** [comment]
It is. Actually, we first estimate the state and then assign power in the CO method. The following snippet borrowed from the [CO disaggregator method](https://github.com/nilmtk/nilmtk/blob/master/nilmtk/disaggregate/combinatorial_optimisation.py) should be useful for you.

```python

indices_of_state_combinations, residual_power = find_nearest(
                summed_power_of_each_combination, chunk.values)

for i, model in enumerate(self.model):
                print("Estimating power demand for '{}'".format(model['training_metadata']))
                data_is_available = True
                predicted_power = state_combinations[
                    indices_of_state_combinations, i].flatten()
```
