### ISSUE TITLE
Convention on the itinial probabilities and transition matrix : What is the order of the states ? (ON,OFF) or (OFF, ON) ?

### ISSUE THREAD

**Issue by GautierAppert** [nilmtk/nilmtk#383]
Hi guys :)
I think we will have forever some questions about all the theory and application of the desagregation.lool
In fact we are wondering what if the order of the state in the transition matrix and the initial probabilities ?
It is (ON,OFF) or (OFF, ON) ?
Thanks you very much guys for your help and motivation :)
Gautier and Simon

**Comment by nipunreddevil** [comment]
It is in increasing order of power. So, can be (off, intermediate, high) as well.

**Comment by GautierAppert** [comment]
Thanks :)

Gautier and Simon
