### ISSUE TITLE
hmmlearn build issue on Windows 7

### ISSUE THREAD

**Issue by gjwo** [nilmtk/nilmtk#386]
An error occurred in the hmmlearn build step  
building 'hmmlearn._hmmc' extension
Microsoft Visual c++ 10.0 required (unable to fined vcvarsall.bat)
I appear to have the 2010 and 2012 redistributables installed for both 32 & 64 bit see below

![image](https://cloud.githubusercontent.com/assets/12109990/7609125/bafae662-f967-11e4-9452-c6b2cb58d027.png)

vcvarsall.bat is not present on my PC

Am I missing another install or is this a build error?

**Comment by JackKelly** [comment]
Hi @gjwo.  Welcome to NILMTK ;)

Please post your issue to the HMMlearn issue queue: https://github.com/hmmlearn/hmmlearn/issues

**Comment by gjwo** [comment]
Thanks Jack, I have done that now issue #30.
you might would to tweak your instructions about were to post issues :)

**Comment by JackKelly** [comment]
Great.  I'll close this issue for now.  I hope they can help you out over on the HMMlearn issue queue.  By the way, HMMLearn isn't associated with NILMTK.  It's a completely separate project.
