### ISSUE TITLE
Problem with local documentation build on windows

### ISSUE THREAD

**Issue by gjwo** [nilmtk/nilmtk#388]
1. Enhancement request -  instructions on producing documentation from the .rst files are not included as part of the build instructions, it would be helpful if they were, particularly for those who are not familiar with the environment being used.
2. Having worked out what a .rst files are, and that sphinx is the tool to build readable documentation from  them, and that sphinx is already included in the build, I found the makefile in nilmtk-metatada. This operated correctly given an html parameter, and generated documentation locally from a command prompt.
3. I then tried to repeat the process for nilmtk documentation, this first failed because it could not find the conf.py file, so tried running from a different place see below
C:\Users\GJWood>cd nilmtk

C:\Users\GJWood\nilmtk>cd docs

C:\Users\GJWood\nilmtk\docs>dir
 Volume in drive C is SSD
 Volume Serial Number is 1E0F-5ECF

 Directory of C:\Users\GJWood\nilmtk\docs

30/04/2015  13:52    <DIR>          .
30/04/2015  13:52    <DIR>          ..
30/04/2015  13:52             6,701 make.bat
30/04/2015  13:52             6,964 Makefile
30/04/2015  13:52    <DIR>          source
               2 File(s)         13,665 bytes
               3 Dir(s)  297,902,440,448 bytes free

C:\Users\GJWood\nilmtk\docs>make html
Error: Source directory doesn't contain a conf.py file.

C:\Users\GJWood\nilmtk\docs>make .\source html
C:\Users\GJWood\nilmtk\docs>make html
Error: Source directory doesn't contain a conf.py file.

C:\Users\GJWood\nilmtk\docs>cd source

C:\Users\GJWood\nilmtk\docs\source>dir *.py
 Volume in drive C is SSD
 Volume Serial Number is 1E0F-5ECF

 Directory of C:\Users\GJWood\nilmtk\docs\source

30/04/2015  13:52            13,351 conf.py
               1 File(s)         13,351 bytes
               0 Dir(s)  297,902,362,624 bytes free

C:\Users\GJWood\nilmtk\docs\source>make html
'make' is not recognized as an internal or external command,
operable program or batch file.

4. Realised there was a difference between the make file in nilmtk-metadata and nilmtk, so replaced the set commands in the nilmtk make.bat file with
set BUILDDIR=build
set ALLSPHINXOPTS=-d %BUILDDIR%/doctrees %SPHINXOPTS% source
set I18NSPHINXOPTS=%SPHINXOPTS% source
This them meant the make file could find the relevant files and run, the then failed - 

C:\Users\GJWood\nilmtk\docs\source>..\make html
Making output directory...
Running Sphinx v1.2.3

Exception occurred:
  File "conf.py", line 17, in <module>
    import sphinx_bootstrap_theme
ImportError: No module named sphinx_bootstrap_theme
The full traceback has been saved in c:\users\gjwood\appdata\local\temp\sphinx-err-v0fxco.log, if you want to report the  issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
Traceback
```
# Sphinx version: 1.2.3
# Python version: 2.7.9
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Loaded extensions:
Traceback (most recent call last):
  File "C:\Users\GJWood\Anaconda\lib\site-packages\sphinx\cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "C:\Users\GJWood\Anaconda\lib\site-packages\sphinx\application.py", line 107, in __init__
    confoverrides or {}, self.tags)
  File "C:\Users\GJWood\Anaconda\lib\site-packages\sphinx\config.py", line 229, in __init__
    execfile_(filename, config)
  File "C:\Users\GJWood\Anaconda\lib\site-packages\sphinx\util\pycompat.py", line 105, in execfile_
    exec code in _globals
  File "conf.py", line 17, in <module>
    import sphinx_bootstrap_theme
ImportError: No module named sphinx_bootstrap_theme
```

**Comment by JackKelly** [comment]
Here are some docs on generating the documentation: http://nilmtk.github.io/nilmtk/master/contribute.html#contributing-documentation

**Comment by nipunreddevil** [comment]
I think we had put up the instructions on how to contribute to nilmtk documentation [up here](http://nilmtk.github.io/nilmtk/master/contribute.html#contributing-documentation). Sorry that we've got stuff here and there!

Regarding sphinx_bootstrap_theme, you can install it by following instructions from [here](http://ryan-roemer.github.io/sphinx-bootstrap-theme/)

Sorry again for all the trouble.

**Comment by gjwo** [comment]
OK, getting closer!
installed sphinx_bootstrap_theme OK
Cloned the documentation - no instruction to install so I haven't done that yet
tried make again - failed can't find numpydoc
C:\Users\GJWood\nilmtk\docs>make html
Running Sphinx v1.2.3

Extension error:
Could not import extension numpydoc (exception: No module named numpydoc)

C:\Users\GJWood\nilmtk\docs>

**Comment by gjwo** [comment]
OK did pip install numpydoc it them seemed to go much better, but with some errors and warnings
C:\Users\GJWood\nilmtk\docs>make html
Running Sphinx v1.2.3
loading pickled environment... not yet created
building [html]: targets for 20 source files that are out of date
updating environment: 20 added, 0 changed, 0 removed
reading sources... [  5%] changelog
reading sources... [ 10%] contribute
reading sources... [ 15%] convert_data_to_NILMTK_format
reading sources... [ 20%] disaggregation_and_metrics
reading sources... [ 25%] elecmeter_and_metergroup
reading sources... [ 30%] index
reading sources... [ 35%] intro_nilmtk_v0_2
reading sources... [ 40%] modules
reading sources... [ 45%] nilmtk
C:\Users\GJWood\Anaconda\lib\site-packages\numpydoc\docscrape.py:120: UserWarning: Unknown section Static Attributes
  warn("Unknown section %s" % key)
C:\Users\GJWood\Anaconda\lib\site-packages\numpydoc\docscrape.py:120: UserWarning: Unknown section Ideas For The Future
(not Implemented Yet!)
  warn("Unknown section %s" % key)
reading sources... [ 50%] nilmtk.dataset_converters
reading sources... [ 55%] nilmtk.dataset_converters.redd
reading sources... [ 60%] nilmtk.disaggregate
reading sources... [ 65%] nilmtk.feature_detectors
reading sources... [ 70%] nilmtk.preprocessing
reading sources... [ 75%] nilmtk.stats
reading sources... [ 80%] nilmtk.stats.tests
reading sources... [ 85%] nilmtk.tests
reading sources... [ 90%] pipeline_preprocessing_more_stats
reading sources... [ 95%] redd_1d_clustering
reading sources... [100%] writing_a_dataset_converter

C:\Users\GJWood\nilmtk\docs\source\convert_data_to_NILMTK_format.rst:5: WARNING: Explicit markup ends without a blank li
ne; unexpected unindent.
C:\Users\GJWood\nilmtk\docs\source\convert_data_to_NILMTK_format.rst:62: WARNING: Explicit markup ends without a blank l
ine; unexpected unindent.
C:\Users\GJWood\nilmtk\docs\source\disaggregation_and_metrics.rst:28: WARNING: Explicit markup ends without a blank line
; unexpected unindent.
C:\Users\GJWood\nilmtk\docs\source\disaggregation_and_metrics.rst:112: WARNING: Explicit markup ends without a blank lin
e; unexpected unindent.
C:\Users\GJWood\nilmtk\docs\source\elecmeter_and_metergroup.rst:441: WARNING: Explicit markup ends without a blank line;
 unexpected unindent.
C:\Users\GJWood\nilmtk\docs\source\elecmeter_and_metergroup.rst:799: WARNING: Explicit markup ends without a blank line;
 unexpected unindent.
C:\Users\GJWood\nilmtk\docs\source\elecmeter_and_metergroup.rst:808: WARNING: Explicit markup ends without a blank line;
 unexpected unindent.
C:\Users\GJWood\nilmtk\docs\source\elecmeter_and_metergroup.rst:816: WARNING: Explicit markup ends without a blank line;
 unexpected unindent.
C:\Users\GJWood\nilmtk\docs\source\elecmeter_and_metergroup.rst:824: WARNING: Explicit markup ends without a blank line;
 unexpected unindent.
C:\Users\GJWood\nilmtk\docs\source\elecmeter_and_metergroup.rst:837: WARNING: Explicit markup ends without a blank line;
 unexpected unindent.
C:\Users\GJWood\nilmtk\docs\source\elecmeter_and_metergroup.rst:850: WARNING: Explicit markup ends without a blank line;
 unexpected unindent.
C:\Users\GJWood\nilmtk\docs\source\elecmeter_and_metergroup.rst:855: WARNING: Explicit markup ends without a blank line;
 unexpected unindent.
C:\Users\GJWood\nilmtk\docs\source\nilmtk.rst:2: SEVERE: Duplicate ID: "module-nilmtk.exceptions".
C:\Users\GJWood\nilmtk\docs\source\nilmtk.dataset_converters.rst:17: WARNING: autodoc: failed to import module u'nilmtk.
dataset_converters.wikienergy'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Users\GJWood\Anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 335, in import_object
    __import__(self.modname)
  File "c:\users\gjwood\nilmtk\nilmtk\dataset_converters\__init__.py", line 6, in <module>
    from .dataport.download_dataport import download_dataport
  File "c:\users\gjwood\nilmtk\nilmtk\dataset_converters\dataport\download_dataport.py", line 9, in <module>
    import psycopg2 as db
  File "C:\Users\GJWood\Anaconda\lib\site-packages\psycopg2\__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: DLL load failed: %1 is not a valid Win32 application.
C:\Users\GJWood\nilmtk\docs\source\nilmtk.dataset_converters.rst:26: WARNING: autodoc: failed to import module u'nilmtk.
dataset_converters'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Users\GJWood\Anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 335, in import_object
    __import__(self.modname)
  File "c:\users\gjwood\nilmtk\nilmtk\dataset_converters\__init__.py", line 6, in <module>
    from .dataport.download_dataport import download_dataport
  File "c:\users\gjwood\nilmtk\nilmtk\dataset_converters\dataport\download_dataport.py", line 9, in <module>
    import psycopg2 as db
  File "C:\Users\GJWood\Anaconda\lib\site-packages\psycopg2\__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: DLL load failed: %1 is not a valid Win32 application.
C:\Users\GJWood\nilmtk\docs\source\nilmtk.dataset_converters.redd.rst:10: WARNING: autodoc: failed to import module u'ni
lmtk.dataset_converters.redd.convert_redd'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Users\GJWood\Anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 335, in import_object
    __import__(self.modname)
  File "c:\users\gjwood\nilmtk\nilmtk\dataset_converters\__init__.py", line 6, in <module>
    from .dataport.download_dataport import download_dataport
  File "c:\users\gjwood\nilmtk\nilmtk\dataset_converters\dataport\download_dataport.py", line 9, in <module>
    import psycopg2 as db
  File "C:\Users\GJWood\Anaconda\lib\site-packages\psycopg2\__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: DLL load failed: %1 is not a valid Win32 application.
C:\Users\GJWood\nilmtk\docs\source\nilmtk.dataset_converters.redd.rst:19: WARNING: autodoc: failed to import module u'ni
lmtk.dataset_converters.redd'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Users\GJWood\Anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 335, in import_object
    __import__(self.modname)
  File "c:\users\gjwood\nilmtk\nilmtk\dataset_converters\__init__.py", line 6, in <module>
    from .dataport.download_dataport import download_dataport
  File "c:\users\gjwood\nilmtk\nilmtk\dataset_converters\dataport\download_dataport.py", line 9, in <module>
    import psycopg2 as db
  File "C:\Users\GJWood\Anaconda\lib\site-packages\psycopg2\__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: DLL load failed: %1 is not a valid Win32 application.
C:\Users\GJWood\nilmtk\docs\source\nilmtk.preprocessing.rst:7: WARNING: toctree contains reference to nonexisting docume
nt u'nilmtk.preprocessing.tests'
C:\Users\GJWood\nilmtk\docs\source\nilmtk.tests.rst:10: WARNING: autodoc: failed to import module u'nilmtk.tests.generat
e_test_data'; the following exception was raised:
Traceback (most recent call last):
  File "C:\Users\GJWood\Anaconda\lib\site-packages\sphinx\ext\autodoc.py", line 335, in import_object
    __import__(self.modname)
ImportError: No module named generate_test_data
C:\Users\GJWood\nilmtk\docs\source\redd_1d_clustering.rst:520: ERROR: Content block expected for the "parsed-literal" di
rective; none found.
looking for now-outdated files... none found
pickling environment... done
checking consistency... C:\Users\GJWood\nilmtk\docs\source\modules.rst:: WARNING: document isn't included in any toctree

C:\Users\GJWood\nilmtk\docs\source\redd_1d_clustering.rst:: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [  5%] changelog
writing output... [ 10%] contribute
writing output... [ 15%] convert_data_to_NILMTK_format
writing output... [ 20%] disaggregation_and_metrics
writing output... [ 25%] elecmeter_and_metergroup
writing output... [ 30%] index
writing output... [ 35%] intro_nilmtk_v0_2
writing output... [ 40%] modules
writing output... [ 45%] nilmtk
writing output... [ 50%] nilmtk.dataset_converters
writing output... [ 55%] nilmtk.dataset_converters.redd
writing output... [ 60%] nilmtk.disaggregate
writing output... [ 65%] nilmtk.feature_detectors
writing output... [ 70%] nilmtk.preprocessing
writing output... [ 75%] nilmtk.stats
writing output... [ 80%] nilmtk.stats.tests
writing output... [ 85%] nilmtk.tests
writing output... [ 90%] pipeline_preprocessing_more_stats
writing output... [ 95%] redd_1d_clustering
writing output... [100%] writing_a_dataset_converter

writing additional files... (36 module code pages) _modules/index genindex py-modindex search
copying images... [  6%] redd_1d_clustering_files/redd_1d_clustering_34_0.png
copying images... [ 13%] elecmeter_and_metergroup_files/elecmeter_and_metergroup_53_0.png
copying images... [ 20%] redd_1d_clustering_files/redd_1d_clustering_31_0.png
copying images... [ 26%] redd_1d_clustering_files/redd_1d_clustering_26_0.png
copying images... [ 33%] redd_1d_clustering_files/redd_1d_clustering_16_0.png
copying images... [ 40%] redd_1d_clustering_files/redd_1d_clustering_28_0.png
copying images... [ 46%] redd_1d_clustering_files/redd_1d_clustering_5_0.png
copying images... [ 53%] elecmeter_and_metergroup_files/elecmeter_and_metergroup_35_0.png
copying images... [ 60%] redd_1d_clustering_files/redd_1d_clustering_8_0.png
copying images... [ 66%] redd_1d_clustering_files/redd_1d_clustering_7_1.png
copying images... [ 73%] convert_data_to_NILMTK_format_files/convert_data_to_NILMTK_format_23_0.png
copying images... [ 80%] redd_1d_clustering_files/redd_1d_clustering_20_0.png
copying images... [ 86%] redd_1d_clustering_files/redd_1d_clustering_13_0.png
copying images... [ 93%] redd_1d_clustering_files/redd_1d_clustering_23_0.png
copying images... [100%] elecmeter_and_metergroup_files/elecmeter_and_metergroup_56_0.png

copying static files... done
copying extra files... done
dumping search index... done
dumping object inventory... done
build succeeded, 22 warnings.

Build finished. The HTML pages are in build/html.

C:\Users\GJWood\nilmtk\docs>

**Comment by JackKelly** [comment]
well done for getting it to work!  What would be super-useful is if you could make a brief note of the steps you took somewhere in the NILMTK docs ;)  No worries if not.

In general, to docs do need a lot of updating & completing.  At the moment, the three main committers to NILMTK (Oli, Nipun and I) are very busy with our own research and so have little time to add to the docs, although we certainly plan to improve the docs whenever we have time...

**Comment by gjwo** [comment]
Jack,
Happy to help if I can, but I am completely new to all of this supporting
infrastructure, git, python, nose, Sphynx etc etc. I have captured all the
issues and any fixed I did on the issues log, so you wouldn't lose anything
required for a fresh windows build etc, so I am coming up a massive
learning curve! It's 35 years since I did my computer science degree at
Imperial, and 25 years since I did any professional programming.

First goal - is to get a fault free tested build, so I am confident that in
anything I do the problems are down to me rather than the set up, *which is
why those two outstanding test failures* are bothering me
.
Second goal - run the toolset all the way through, to understand what it
does

Third goal - import my own data and repeat the run through of the toolset,
this will require (as I understand it)

   1. Write a converter for my format of data
   2. Provide metadata for my Onzo Meter
   3. Provide metadata for the appliances in my house

I will capture as I do this and attempt to produce a guide at the end.

Regards
    Graham

**Comment by JackKelly** [comment]
wonderful, thank you, and of course we'll try to help as much as possible :)

**Comment by gjwo** [comment]
OK in response to the request from @JackKelly here are my notes rengineered into the right sequence to avoid problems, This has not been tested as my actual build was out of sequence and had a lot of repeated steps. The next person to try this needs to follow these instructions and validate whether or not they work.
![image](https://cloud.githubusercontent.com/assets/12109990/7902744/66986f42-07bb-11e5-80af-31e105d96de7.png)

**Comment by JackKelly** [comment]
Thanks loads, @gjwo.  I have linked to your post above from [the docs](http://nilmtk.github.io/nilmtk/master/contribute.html).  

I'll close this issue for now.  Please re-open if necessary.
