### ISSUE TITLE
Environmental problems attempting to run demo on windows

### ISSUE THREAD

**Issue by gjwo** [nilmtk/nilmtk#389]
Having stumbled across the notebook for the BuildSys 2014 demo, this seemed like a good place to start running the toolkit as a way to get up to speed. So tried running fragments of the code under ipython qtconsole  (didn't work before adding the qtconsole parameter) from the nilmtk directory. I wanted to use the data shipped with nilmtk so I have made some changes to the original recorded in the notebook.  
two issues - the print_dict lines are not producing anything except <IPython.core.display.HTML object>, and there seems to be an issue with the use of pygraphviz which doesn't have a windows distribution

I got the following result
IPython QtConsole 3.0.0
Python 2.7.9 |Anaconda 2.2.0 (64-bit)| (default, Dec 18 2014, 16:57:52) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 3.0.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
%guiref   -> A brief reference about the graphical user interface.

In [1]: #demo modified to run with data included in the nilmtk distribution
   ...: import numpy as np
   ...: import pandas as pd
   ...: from os.path import join
   ...: from pylab import rcParams
   ...: import matplotlib.pyplot as plt
   ...: %matplotlib inline
   ...: rcParams['figure.figsize'] = (14, 6)
   ...: plt.style.use('ggplot')
   ...: import nilmtk
   ...: from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
   ...: from nilmtk.disaggregate import CombinatorialOptimisation
   ...: from nilmtk.utils import print_dict
   ...: from nilmtk.metrics import f1_score
   ...: 
   ...: import warnings
   ...: warnings.filterwarnings("ignore")
   ...: # download_wikienergy(database_username, database_password, hdf_filename)
   ...: # Loading data
   ...: data_dir = 'c:/Users/GJWood/nilmtk/data/' #GJW
   ...: we = DataSet(join(data_dir, 'random.h5')) #GJW
   ...: print('loaded ' + str(len(we.buildings)) + ' buildings')
   ...: #Examine dataset metadata
   ...: print_dict(we.metadata)
   ...: #Examine metadata for a single house
   ...: building_number = 1 #GJW was ll
   ...: print_dict(we.buildings[building_number].metadata)
   ...: #Examine sub-metered appliances
   ...: elec = we.buildings[building_number].elec
   ...: elec.appliances
   ...: #Wiring hierarchy of meters
   ...: elec.draw_wiring_graph();
   ...: 
loaded 1 buildings
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c082f213e9c6> in <module>()
     30 elec.appliances
     31 #Wiring hierarchy of meters
---> 32 elec.draw_wiring_graph();
     33 

c:\Users\GJWood\nilmtk\nilmtk\metergroup.pyc in draw_wiring_graph(self, show_meter_labels)
    573         graph = self.wiring_graph()
    574         meter_labels = {meter: meter.instance() for meter in graph.nodes()}
--> 575         pos = nx.graphviz_layout(graph, prog='dot')
    576         nx.draw(graph, pos, labels=meter_labels, arrows=False)
    577         if show_meter_labels:

c:\Users\GJWood\Anaconda\lib\site-packages\networkx\drawing\nx_agraph.pyc in graphviz_layout(G, prog, root, args)
    227 
    228     """
--> 229     return pygraphviz_layout(G,prog=prog,root=root,args=args)
    230 
    231 def pygraphviz_layout(G,prog='neato',root=None, args=''):

c:\Users\GJWood\Anaconda\lib\site-packages\networkx\drawing\nx_agraph.pyc in pygraphviz_layout(G, prog, root, args)
    258         raise ImportError('requires pygraphviz ',
    259                           'http://networkx.lanl.gov/pygraphviz ',
--> 260                           '(not available for Python3)')
    261     if root is not None:
    262         args+="-Groot=%s"%root

ImportError: ('requires pygraphviz ', 'http://networkx.lanl.gov/pygraphviz ', '(not available for Python3)')

In [2]:

**Comment by JackKelly** [comment]
> Having stumbled across the notebook for the BuildSys 2014 demo, this seemed like a good place to start running the toolkit as a way to get up to speed.

Yup, this is a good way to get going!

> So tried running fragments of the code under ipython qtconsole (didn't work before adding the qtconsole parameter) from the nilmtk directory.

Does `ipython notebook` work on your system?  (i.e. using the full IPython web notebook, not qtconsole).  The web notebook is what we (and pretty much everyone, AFAIK), use.

> two issues - the print_dict lines are not producing anything except ,

`print_dict` is specific to the web version of `ipython notebook`.  `print_dict` uses some HTML formatting.  It won't work in non-web enabled versions of the ipython notebook.  If you want to display the contents of a dict and you're not using the webby `ipython notebook` then just do `print(dict)`.

> and there seems to be an issue with the use of pygraphviz which doesn't have a windows distribution

If you don't have `pygraphviz` then remove the call in the notebook to `draw_wiring_graph()`.  I think that's the only function that will use `pygraphviz`.  It's probably not an especially important function!

**Comment by gjwo** [comment]
Thanks Jack, ipython notebook worked and I can now load & display the data in nilmtk\data. 
loaded 1 buildings
meter_devices:
Random Meter:
max_sample_period: 15
model: Random Meter
measurements:
{'type': 'active', 'upper_limit': 6000, 'lower_limit': 0, 'physical_quantity': 'power'}
{'type': 'reactive', 'upper_limit': 6000, 'lower_limit': 0, 'physical_quantity': 'energy'}
{'type': '', 'upper_limit': 6000, 'lower_limit': 0, 'physical_quantity': 'voltage'}
sample_period: 10
manufacturer: Test Manufacturer
instance: 1
dataset: None

I will have a separate look at pygraphviz, I may need to clone & build it.

The data with the code is a bit limited for exploring, is there some 1 second granularity data I can get at (not huge volumes), and I understand there is a way of reading CSV data, is there an example of how to do this?

**Comment by nipunreddevil** [comment]
I have made my [data set](http://iawe.github.io) available as a HDF5. You can access it [here](https://copy.com/C2sIt1UfDx1mfPlC).

**Comment by JackKelly** [comment]
> I understand there is a way of reading CSV data, is there an example of how to do this?

I don't think we have any examples yet for the `CSVDataStore`.  @oliparson do we have any examples for the `CSVDataStore`?

There's also [my UK-DALE dataset](http://www.doc.ic.ac.uk/~dk3810/data/) which is also [available as HDF5](http://data.ukedc.rl.ac.uk/browse/edc/EnergyConsumption/Domestic/UK-DALE-2015/UK-DALE-disaggregated/ukdale.h5.tgz).

**Comment by gjwo** [comment]
Thanks Nipun, I have downloaded your data, and will take a look at it now.
Jack - I had spotted UKDale but it looked a bit on the large size

**Comment by JackKelly** [comment]
> it looked a bit on the large size

NILMTK should handle large datasets fairly well.  It lazy-loads only the data it requires, and loads data in chunks so as not to swamp your system memory.  And you can select a time window of interest for all of your analysis by running  something like `dataset.set_window("2014-01-01", "2014-02-01")`

**Comment by oliparson** [comment]
If you're feeling brave you can try running `Datastore.convert_datastore(input.h5, output.csv)`. Otherwise if you can wait a few days I can share a zip of a CSV data set.

Just to be clear, the aim of the `dataset_converters` is to take a data set in some incompatible format and convert it to a NILMTK `Datastore`, which could be either a `CSVDatastore` or an `HDFDatastore`.

**Comment by gjwo** [comment]
Jack, it's not NILMTK I am worried about, it's that my pc would have problems with 5 terabytes! For now tens to low hundreds of Mb is all I am looking for, I now have 500MB from Nipun
Oli A smallish CSV data set would be nice, no problem with waiting, my goal is to have an example that works so I have a target to aim at when I am working out what to do with my data (which is currently in separate csv files for each measure) that look like this:
2013-10-22 00:00:22,654
2013-10-22 00:00:26,656
2013-10-22 00:00:28,694
2013-10-22 00:00:33,674
2013-10-22 00:00:34,641
2013-10-22 00:00:35,707
2013-10-22 00:00:36,674
2013-10-22 00:00:41,665
2013-10-22 00:00:42,690
2013-10-22 00:00:43,690
2013-10-22 00:00:44,640
2013-10-22 00:00:45,640
2013-10-22 00:00:46,665
2013-10-22 00:01:09,665
2013-10-22 00:01:10,641
So I am expecting to have to combine the different measures into one multicolumn file, add appropriate headers, deal with the intrinsic data compression etc. But I am happy to take an easier route if one is available ;-)

**Comment by gjwo** [comment]
I think I am starting to get somewhere with Nipun's dataset having looked up start and end times 
here http://iawe.github.io/. 
Is there an easy way to recreate the metadata from the .H5 file so I know what's in it and therefore which data queries are likely to work? I have already seen code to see the building and appliance meta data, but not stuff on the rage of Measurements per MeterDevice?

sample graphs from iawe.h5
In [16]:

we.set_window(start='2013-05-16 00:00:00', end='2013-05-30 00:00:00')
elec.plot();
plt.xlabel("Time");
​

In [17]:

we.set_window(start='2013-05-26 00:00:00', end='2013-05-27 00:00:00')
elec.plot();
plt.xlabel("Time");
​

In [ ]:

**Comment by nipunreddevil** [comment]
Hi @gjwo 

I am sorry I didn't fully follow you. Did you mean that you wanted to have a look at the metadata. Here it is: https://github.com/nilmtk/nilmtk/tree/master/nilmtk/dataset_converters/iawe/metadata

**Comment by gjwo** [comment]
Hi @nipunreddevil 
I was a little confused about  what was where, when I asked the question. I subsequently found the metadata in the converters directories of nilmtk, which included the data you have just highlighted (thanks anyway). My question was more about finding out what data was present in the dataset, rather than the shape of the data as described by the metadata. I found the answer on your website http://iawe.github.io/ in one of the notebooks - http://nbviewer.ipython.org/github/nipunreddevil/Home_Deployment/blob/master/notebooks/Data_Time_Range.ipynb
I now understand that sometimes the metadata is embedded in the .h5 file and sometimes it is in a separate metadata directory (please correct me if this is wrong).
It's quite difficult to work some of this stuff out without an understanding of the architecture, and the infrastructure it operates in, but I have got much further in the last 24 hours.
Thanks
   Graham

**Comment by gjwo** [comment]
@JackKelly @nipunreddevil @oliparson 
Thanks for your help

Regarding the elec.draw_wiring_graph() problem, this is a build problem with pygraphviz I found an existing open problem which matches the problem I had when attempting to build pygraphvis
git clone https://github.com/pygraphviz/pygraphviz
cd pygraphviz
python setup.py installl
...
fatal error C1083 cannot open include file 'graphviz/cgraph.h': no such file or dir

issue documented here https://github.com/pygraphviz/pygraphviz/issues/40

Now that I am using ipython notebook I don't think I have any other environmental problems running a demo, just issues with what data to give the toolkit at at various points, so I think it is right to close this issue and open usage issues as they arise.

Oli I will open a request for CSV data for you to repy to with the data when you have it.
