### ISSUE TITLE
Exception in tz_localize when trying to disaggregate

### ISSUE THREAD

**Issue by 7hibault** [nilmtk/nilmtk#390]
Hi all, 
I'm trying to get me head around disaggregation with the NILMtk but have faced a small issue which I don't understand. I have followed the [disaggregation explanations](http://nilmtk.github.io/nilmtk/master/disaggregation_and_metrics.html) but got an exception when running the program. I've tried disaggregating with CO and FHMM and got the same results.

    Traceback (most recent call last):
      File "redd.py", line 21, in <module>
        f.train(elec)
      File "path_to_nilmtk\disaggregate\fhmm_exact.py", line 192, in train
        meter_data = meter.power_series(**load_kwargs).next().dropna()
      File "path_to_nilmtk\electric.py", line 625, in load_series
        for chunk in generator:
      File "path_to_nilmtk\metergroup.py", line 668, in load
        start.tz_localize(None), section.end.tz_localize(None), tz=tz,
      File "tslib.pyx", line 365, in pandas.tslib.Timestamp.tz_localize (pandas\tslib.c:8851)
    Exception: Cannot localize tz-aware Timestamp, use tz_convert for conversions

The exception is raised when calling `tz_localize` in `metergroup.py`.

    start = normalise_timestamp(section.start, freq)
    tz = None if start.tz is None else start.tz.zone
    index = pd.date_range(
        start.tz_localize(None), section.end.tz_localize(None), tz=tz,
        closed='left', freq=freq)

I haven't touched that piece of code and was surprised to get this exception. I checked the code of the pandas library and this exception is defined line 477 of [tslib.pyx](https://github.com/pydata/pandas/blob/master/pandas/tslib.pyx).

    def tz_localize(self, tz, ambiguous='raise'):
        [...]
        if self.tzinfo is None:
            [...]
        else:
            if tz is None:
                [...]
            else:
                raise TypeError('Cannot localize tz-aware Timestamp, use '
                                'tz_convert for conversions')

I don't have enough perspective on the nilmtk code to figure out what's going on here, and I can't see why this exception would be raised. I hope you can help me figure that out!

Thanks.

**Comment by nipunreddevil** [comment]
Can you please do the following:

1. Pull the latest code
2. `ds.clear_cache()` where ds is your nilmtk DataSet object
3. Follow [this notebook](https://github.com/nilmtk/nilmtk/blob/master/notebooks/experimental/co_fhmm.ipynb) for your task. I am afraid the documentation is a bit out of sync. We'll try and fix this as soon as we can.

**Comment by 7hibault** [comment]
Hello Nipun, thank you for your answer. FYI, I am working with the REDD dataset. I've tried following your advice but unfortunately it didn't solve my issue.
1) The code is up to date
2)  I have tried the following but nothing changed

    redd = DataSet(join(data_dir, '/data/REDD/redd.h5'))
    redd.clear_cache()

3) I got the same error (+ another one) in the notebook:

* The line `elec.draw_wiring_graph();` generated a `KeyError: u"Node MeterGroup(meters=\n  ElecMeter(instance=1, building=1, dataset='REDD', site_meter, appliances=[])\n  ElecMeter(instance=2, building=1, dataset='REDD', site_meter, appliances=[])\n) not in graph."`
* The line `we.set_window(start=None, end='2011-05-01 00:00:00-04:00')` generated an `Exception: Cannot localize tz-aware Timestamp, use tz_convert for conversions`. There is no particular reason as to why I chose this time window except that it's the one that was used in the doc.

**Comment by nipunreddevil** [comment]
Hi @7hibault 

At my end, I don't get an error on the draw_wiring_graph. See [here](http://nbviewer.ipython.org/github/nilmtk/nilmtk/blob/49d2188ea05c3092353cd86f7ab78ef6e533d60c/notebooks/issues/390.ipynb).

Regarding, `we.set_window(start=None, end='2011-05-01 00:00:00-04:00') ` error- You need to use the start and end times without the timezone as is done in the [following notebook](http://nbviewer.ipython.org/github/nilmtk/nilmtk/blob/master/notebooks/experimental/co_fhmm.ipynb).

for example the following should be valid.

```python

train.set_window(end="30-4-2011")
test.set_window(start="30-4-2011")

```

**Comment by 7hibault** [comment]
I get the `KeyError` on the draw_wiring_graph with the notebook you provided as well. It is actually not my main point here but I can't figure out while it's not working. 

Regarding  the other error, removing the timezone did allow me to reach step [22] but then fails on `fhmm.disaggregate(test_elec.mains(), output, sample_period=60)` with an`Exception: Cannot localize tz-aware Timestamp, use tz_convert for conversions`. I don't think I could have defined a timezone anywhere else, I have defined the end of the training set and the start of the testing set to 30-4-2011 as you suggested.

Thank you for helping me out, it's a bit tough to get started.

**Comment by 7hibault** [comment]
Is there any more information I could provide?

**Comment by nipunreddevil** [comment]
@7hibault Is it possible for you to regenerate REDD HDF5 file and try on the new one? I am unable to reproduce your error.

**Comment by JackKelly** [comment]
Hi @7hibault, which version of Pandas are you using?

**Comment by 7hibault** [comment]
@nipunreddevil I have tried regenerating REDD HDF5 file but unfortunately nothing changed :(

Hi @JackKelly, I am using pandas 0.14.1

**Comment by nipunreddevil** [comment]
> I am using pandas 0.14.1

Is it possible for you to upgrade to the latest version of Pandas. I think they've fixed a lot of timezone related bugs recently. Also, I am using the latest version and I don't see this bug on my system.
