### ISSUE TITLE
Writing a data converter - multiple files from each meter

### ISSUE THREAD

**Issue by gjwo** [nilmtk/nilmtk#395]
I have a collection of data from a whole house meter in multiple files, with each file containing 2 columns containing, a timestamp string and an integer metric (active or reactive power). Each file contains only one type of metric and are differentiated by standardised names. Each file contains multiple days worth of 1 second granularity data, and there are many files covering a wider span of time. the files come in pairs for example
4-POWER_REAL_FINE 2013-11-20 Dump.csv <-> 5-POWER_REACTIVE_STANDARD 2013-11-20 Dump.csv
4-POWER_REAL_FINE 2013-11-28 Dump.csv <-> 5-POWER_REACTIVE_STANDARD 2013-11-28 Dump.csv
4-POWER_REAL_FINE 2013-12-01 Dump.csv <-> 5-POWER_REACTIVE_STANDARD 2013-12-01 
I have already written the code to walk the directory tree and find the matching pairs.
I have followed the structure that has datasetname/building1/elec
**Question 1** should I add another layer of ../meter1 to allow for the possibility in the future of having more meters so I can keep the files for each meter separate?
**Question 2** is there any scheme for incrementally adding data, that should be included in a converter or would it always read in all the data and construct a new HDF5 file?

**Comment by gjwo** [comment]
@oliparson 
OK some progress with pandas, notwithstanding the questions above, I now have my data all joined up, and in the right shape (I think) see below
                           active  reactive
2013-11-12 09:28:27+00:00    2553      -319
2013-11-12 09:28:30+00:00    2553        22
2013-11-12 09:28:31+00:00    2553       157
2013-11-12 09:28:32+00:00    2637       157
2013-11-12 09:28:59+00:00    2552      -230
2013-11-12 09:29:00+00:00    2487       302
...
2015-05-27 14:08:55+01:00     416       175
2015-05-27 14:15:53+01:00     377       179
2015-05-27 14:41:08+01:00    1048       183

[80297 rows x 2 columns]

Looking at @nipunreddevil convert_iawe I haven't done these steps yet
        df.rename(columns=lambda x: column_mapping[x], inplace=True)
        df.columns.set_names(LEVEL_NAMES, inplace=True)
        df = df.convert_objects(convert_numeric=True)
        df = df.dropna()
        df = df.astype(np.float32)
        df = df.sort_index()
*Question 3* please can you explain what are these steps for?

**Comment by nipunreddevil** [comment]
```python
# Renaming from iAWE header to nilmtk controlled vocabulary
df.rename(columns=lambda x: column_mapping[x], inplace=True)

# Needed for column levelling (all converter need this line)
df.columns.set_names(LEVEL_NAMES, inplace=True)

# Ensuring that all columns are numeric
df = df.convert_objects(convert_numeric=True)

# Dropping NAN entries
df = df.dropna()

# Changing float 64 (default) to float 32 
df = df.astype(np.float32)

# Ensure that time series index is sorted
df = df.sort_index()
```

**Comment by gjwo** [comment]
Thanks Nipun, that confirms what I had worked out, but added some of the reasoning which I didn't know. I know my data does not have a sample every second, the meter outputs when there is a change. **Question 4** should my converter fill in these gaps? There are also larger gaps where the data wasn't recorded, *Question 5** Can the toolset identify the contiguous periods of measurement, so I can fill the gaps in in those periods if required, or run disaggregation for contiguous periods only.

**Comment by gjwo** [comment]
I have put my converter and data on github here https://github.com/gjwo/nilm_gjw_data

**Comment by gjwo** [comment]
@nipunreddevil 
My converter is now running, but it looks like **Question 4** is relevant see output below
![image](https://cloud.githubusercontent.com/assets/12109990/7917110/ca9a532e-087f-11e5-912d-f950590e1f50.png)
Is there anything in the toolkit to put a in a threshold for  real gaps and infill the rest or shall I do this in my converter?

**Comment by nipunreddevil** [comment]
We do have an API for exactly this problem- where we fill short gaps and ignore large ones. @JackKelly : Do we have an example of this somewhere?

**Comment by gjwo** [comment]
Looks like resample will be helpful: samples = samples.resample('S',fill_method='ffill')

**Comment by gjwo** [comment]
After a rewrite with resampling this is what I now get
![image](https://cloud.githubusercontent.com/assets/12109990/7932236/a39d11dc-090e-11e5-9736-3aacbff2a7a6.png)

![image](https://cloud.githubusercontent.com/assets/12109990/7932209/749bed9a-090e-11e5-979c-4c9a9c416931.png)

I think that means I can move on to the next stage!

**Comment by JackKelly** [comment]
> I think that means I can move on to the next stage!

Well done!  In which case, I'll go ahead and close this issue.  Please do re-open if necessary.
