### ISSUE TITLE
File and directory paths on windows when checking directories

### ISSUE THREAD

**Issue by gjwo** [nilmtk/nilmtk#396]
I think check_directory_exists(dirpath) might have a problem with a windows style path i.e. "C:\dir1\dir2" instead of "c:/dir1/dir2" the os module routines seem to cope fine with the appropriate local format (or even a mix of "/" and "\")
I had to enter in unix format then correct later to access files, I think I should have been able to enter in windows format, for example via a copy and paste from the Windows Explorer path display "C:\Users\GJWood\nilm_gjw_data"

```python
home_dir='/Users/GJWood/nilm_gjw_data' # path to input data
def convert_gjw(gjw_path, output_filename, format="HDF"):
     if gjw_path is None: gjwpath = home_dir
    check_directory_exists(gjw_path)
    os.chdir(gjw_path)
    gjw_path = os.getcwd()  # sort out potential issue with slashes or backslashes
    #...
```

**Comment by JackKelly** [comment]
> I think check_directory_exists(dirpath) might have a problem with a windows style path

Hmm.  All `nilmtk.utils.check_directory_exists` does is this:

```python
def check_directory_exists(d):
    if not isdir(d):
        raise IOError("Directory '{}' does not exist.".format(d))
```

Did you get a specific error when you tried passing Windows-style paths to `check_directory_exists`?  (I'm afraid I don't have a Windows install to check on!)

**Comment by gjwo** [comment]
Probably not worth pursuing, I have a work around and your code looks OK
I'll close it

**Comment by JackKelly** [comment]
thanks for closing this, @gjwo
