### ISSUE TITLE
Problems running BuildSys 2014 sequence on my own data

### ISSUE THREAD

**Issue by gjwo** [nilmtk/nilmtk#397]
Now I have some data in the toolkit, I am running tests by following the sequence used for the demo at BuildSys 2014. because I only have one meter and I can't get the wiring diagram tools installed under Windows I have left some steps out.
All my code and data is up to date on github here https://github.com/gjwo/nilm_gjw_data
There are two iPython Notebooks, one to run the converter gjw_converter_test.ipynb and one to run the tests test_gjw.ipynb  <--- see this for the full story.  My data should include active & reactive power, and the dataframe did contain this data immediately before storing in the HDF5 datastore (I dumped 6,115,835 rows into a CSV to prove this).
**Problem 1** the power types available don't look right
Find out what power types are available
![image](https://cloud.githubusercontent.com/assets/12109990/7937474/25009b12-0938-11e5-954f-5eace1f860f9.png)

**Problem 2**
trying to plot a graph of the usage fails (graphs of good sections worked fine so it's not the install)
![image](https://cloud.githubusercontent.com/assets/12109990/7937583/ba4153f6-0938-11e5-962b-c04b0161a2d0.png)

![image](https://cloud.githubusercontent.com/assets/12109990/7937621/0d81c37a-0939-11e5-8b95-ef7c1340e1d7.png)

...

![image](https://cloud.githubusercontent.com/assets/12109990/7937634/26e7119e-0939-11e5-869b-cfb26bc91f78.png)

This leads me to thing I am trying to plot something that is not there
Any guidance would be appreciated

**Comment by gjwo** [comment]
Looks like it's working now!
I changed the column type from active power to apparent power, so the convert gave this output
opening datastore /Users/GJWood/nilm_gjw_data\HDF5\nilm_gjw_data.hdf5
checking c:\Users\GJWood\nilm_gjw_data
checking c:\Users\GJWood\nilm_gjw_data\building1
checking c:\Users\GJWood\nilm_gjw_data\building1\elec
found files for date: 2013-11-20 ['2013-10-17T18:19:07.000000000+0100'] to ['2013-11-20T14:26:53.000000000+0000']
found files for date: 2013-11-28 ['2013-10-21T20:30:26.000000000+0100'] to ['2013-11-28T11:03:40.000000000+0000']
found files for date: 2013-12-01 ['2013-10-24T00:12:05.000000000+0100'] to ['2013-12-01T20:06:23.000000000+0000']
found files for date: 2013-12-04 ['2013-11-08T12:16:21.000000000+0000'] to ['2013-12-04T15:33:05.000000000+0000']
found files for date: 2013-12-13 ['2013-11-16T16:14:40.000000000+0000'] to ['2013-12-13T11:57:52.000000000+0000']
found files for date: 2013-12-27 ['2013-12-02T13:15:47.000000000+0000'] to ['2013-12-27T20:36:46.000000000+0000']
found files for date: 2014-01-09 ['2013-12-15T22:15:33.000000000+0000'] to ['2014-01-09T16:04:49.000000000+0000']
found files for date: 2014-02-09 ['2014-01-12T13:02:22.000000000+0000'] to ['2014-02-09T13:29:49.000000000+0000']
found files for date: 2014-03-27 ['2014-03-13T21:59:56.000000000+0000'] to ['2014-03-26T11:19:40.000000000+0000']
found files for date: 2014-05-26 ['2014-04-27T00:17:57.000000000+0100'] to ['2014-05-26T20:19:31.000000000+0100']
found files for date: 2015-05-12 ['2015-04-17T12:48:40.000000000+0100'] to ['2015-05-12T15:52:28.000000000+0100']
found files for date: 2015-05-27 ['2015-05-03T05:44:28.000000000+0100'] to ['2015-05-27T15:26:35.000000000+0100']
found files for date: 2015-06-03 ['2015-05-10T13:48:52.000000000+0100'] to ['2015-06-03T10:04:05.000000000+0100']
physical_quantity            power         
type                      apparent reactive
2013-10-17 18:19:07+01:00      382        0
2013-10-17 18:19:08+01:00      449        0
2013-10-17 18:19:09+01:00      449        0
2013-10-17 18:19:10+01:00      449        0
... 17387397 rows at Prepared for tool kit
physical_quantity            power         
type                      apparent reactive
2015-06-03 10:04:02+01:00      984        0
2015-06-03 10:04:03+01:00      984        0
2015-06-03 10:04:04+01:00      984        0
2015-06-03 10:04:05+01:00      732        0
Done converting YAML metadata to HDF5!
Done converting gjw to HDF5!
Running the tests I now get
![image](https://cloud.githubusercontent.com/assets/12109990/7986575/3a327552-0ad0-11e5-81ab-5015cac105cd.png)

and
![image](https://cloud.githubusercontent.com/assets/12109990/7986608/61302564-0ad0-11e5-98ae-1c7148febdbb.png)

Which gives me some confidence I have successfully got my data into the toolset

**Comment by gjwo** [comment]
I seem to be missing my meter
In [27]:

mains = elec.mains()
In [28]:

m = mains.meters[1]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-28-93c0486167e7> in <module>()
----> 1 m = mains.meters[1]

AttributeError: 'ElecMeter' object has no attribute 'meters'

This is the relevant section of building1.yaml metadata

elec_meters:
  1:
    site_meter: true
    name: house_total
    room: utility
    submeter_of: 0
    device_model: ED01013  # keys into meter_devices dictionary
    data_location: /building1/elec/meter1

and meter devices.yaml
ED01013:
  model: ED01013
  manufacturer: Onzo Ltd
  manufacturer_url: http://www.onzo.com/
  description: Multifunction whole house meter and home display, 
    #given the different sample rates and cumulative energy mixed, phase one treat the meter
    #as having only 2 measurements power real fine and power reactive, comment out the rest
  sample_period: 1 # the interval between samples. In seconds.
  max_sample_period: 300 # Max allowable interval between samples. Seconds.
  measurements:
  #- physical_quantity: cumulative energy   #energy low res - cumulative energy use every 35 minutes approximately
    #type: active   # active (real power), reactive or apparent?
    #upper_limit: 10000000
    #lower_limit: 0
  #- physical_quantity: cumulative energy   #energy high res - cumulative energy use every 10 minutes approximately
    #type: active   # active (real power), reactive or apparent?
    #upper_limit: 10000000
    #lower_limit: 0
  #- physical_quantity: power   #power real standard - power granularity < 30 Seconds
    #type: apparent   # active (real power), reactive or apparent?
    #upper_limit: 10000
    #lower_limit: 0
  - physical_quantity: power   #power real fine - power granularity  1 Second (no data if no change)
    type: apparent   # active (real power), reactive or apparent?
    upper_limit: 10000
    lower_limit: 0
  - physical_quantity: power   #power reactive standard granularity  1 Second (no data if no change)
    type: reactive   
    upper_limit: 10000
    lower_limit: -10000
**But the meter didn't appear in the building metadata listed**
I also got this which looked OK
In [18]:

elec.meters
​
Out[18]:
[ElecMeter(instance=1, building=1, dataset='gjwdata', site_meter, appliances=[Appliance(type='washing machine', instance=1), Appliance(type='tumble dryer', instance=1), Appliance(type='freezer', instance=1), Appliance(type='boiler', instance=1), Appliance(type='light', instance=1), Appliance(type='light', instance=2), Appliance(type='clothes iron', instance=1), Appliance(type='food steamer', instance=1), Appliance(type='kettle', instance=1), Appliance(type='toaster', instance=1), Appliance(type='coffee maker', instance=1), Appliance(type='microwave', instance=1), Appliance(type='electric oven', instance=1), Appliance(type='fridge', instance=1), Appliance(type='dish washer', instance=1), Appliance(type='waste disposal unit', instance=1), Appliance(type='water filter', instance=1), Appliance(type='fan', instance=1), Appliance(type='light', instance=3), Appliance(type='mobile phone charger', instance=1), Appliance(type='television', instance=1), Appliance(type='server computer', instance=1), Appliance(type='wireless phone charger', instance=1), Appliance(type='light', instance=4), Appliance(type='light', instance=5), Appliance(type='light', instance=6), Appliance(type='vacuum cleaner', instance=1), Appliance(type='vacuum cleaner', instance=2), Appliance(type='television', instance=2), Appliance(type='blu-ray player', instance=1), Appliance(type='light', instance=7), Appliance(type='light', instance=8), Appliance(type='audio system', instance=1), Appliance(type='CD player', instance=1), Appliance(type='light', instance=9), Appliance(type='light', instance=10), Appliance(type='light', instance=11), Appliance(type='plate warmer', instance=1), Appliance(type='light', instance=12), Appliance(type='motor', instance=1), Appliance(type='light', instance=13), Appliance(type='electric space heater', instance=1), Appliance(type='light', instance=14), Appliance(type='light', instance=15), Appliance(type='water pump', instance=1), Appliance(type='CE appliance', instance=1), Appliance(type='CE appliance', instance=2)])]

**Comment by JackKelly** [comment]
> Looks like it's working now!

Well done :).  Sorry it's been a bit of a bumpy ride.  We are (slowly) working to make NILMTK more user friendly :)

Regarding your latest error:

```python
mains = elec.mains()
m = mains.meters[1]
AttributeError: 'ElecMeter' object has no attribute 'meters'
```

This is perhaps a little confusing.  In general (this isn't documented but should be) you should rarely need to directly access the `meters` attribute.  Only `MeterGroup` objects have a `meters` attribute.  `ElecMeter` objects do not.  The basic idea with `MeterGroup` and `ElecMeter` is that `ElecMeter` is for single meters whilst `MeterGroup` is for multiple meters.  They should present a similar public API where it makes sense to (although I accept that this described at all well in the docs yet).

So, given that you have a single aggregate mains meter (and not, say, a three-phase setup), `elec.mains()` will return an **`ElecMeter`** and not a `MeterGroup`.  Hence `mains.meters[1]` fails because `mains` is an `ElecMeter` and has no `meters` attribute.

So, if you want to (for example) plot your mains data you can just do `mains.plot()`.

> But the meter didn't appear in the building metadata listed

Ah, yes, if you do `gjw.buildings[building_number].metadata` then you'll get the metadata specific to the *building* (list of rooms, type of home etc).  All the metadata associated with meters and appliances lives with the relevant ElecMeter and Appliance objects.

I'll make the bold assumption that I've answered your issue and I'll close this issue for now.  Please feel free to re-open if necessary.
