### ISSUE TITLE
Don't use git pull to refresh test HDF5 files

### ISSUE THREAD

**Issue by JackKelly** [nilmtk/nilmtk#403]
instead keep the test HDF5 files in a temporary directory?

related:
- #387 
- #402 
- #462

**Comment by nipunreddevil** [comment]
>instead keep the test HDF5 files in a temporary directory? 

This sounds reasonable. Any reason we didn't opt for this earlier?

**Comment by JackKelly** [comment]
> Any reason we didn't opt for this earlier?

good question :)  I keep asking myself that.  I'm sure there was a reason (and I'm pretty sure my first implementation did copy files from a temporary directory) and there was some reason it didn't work but I can't remember why!  Anyway, using git is definitely a horrible solution here so it needs to go :)
