### ISSUE TITLE
`elec.plot()` not showing labels

### ISSUE THREAD

**Issue by nipunreddevil** [nilmtk/nilmtk#407]
Minimal  example

```python
from nilmtk import *
ds = DataSet("/data/REDD/redd.h5")
elec = ds.buildings[2].elec
%matplotlib qt
elec.plot()
import matplotlib.pyplot as plt
plt.savefig("/Users/nipunbatra/Desktop/407.png")
```

Produced figure

![407](https://cloud.githubusercontent.com/assets/60985/8082364/59c12ab6-0f9a-11e5-92ae-d9103ca209bd.png)

**Comment by JackKelly** [comment]
I've replicated this issue and will work on it now..

**Comment by JackKelly** [comment]
It's a bug in Pandas 0.16.1: https://github.com/pydata/pandas/pull/10131

I'll implement a simple work around.
