### ISSUE TITLE
Dataset Resolution

### ISSUE THREAD

**Issue by athenawisdoms** [nilmtk/nilmtk#408]
What range of the current sensor sampling frequency (ie: readings every 1 sec, or every 5 sec etc) is recommended for a reasonable model?

**Comment by gjwo** [comment]
I have tried both every 6 seconds and every second, the issue with 6 seconds is that the transitions are very variable in value, as the exact value will depend when in the time period it happened. The bigger issue is that over a 6 second period it is much more likely that several events happen, as human activity tends to happen in clusters. My recommendation is go for a 1 second granularity. This is the non-academic view, it is possible to disaggregate at six seconds, but not without a lot more algorithm training and more advanced techniques to extract a pattern. 

Personally I understand why the academics use lots of sub metering, but I take the purist view that it ought to be unnecessary (tantamount to cheating :smiley:), given some confirmation about which device a pattern relates to.

**Comment by JackKelly** [comment]
> Personally I understand why the academics use lots of sub metering

oh, submetering is usually just to generate the ground-truth for what each appliance is *really* using.  This is used to train and validate our algorithms.  (although there is also some work which looks at strategies for doing 'minimal submetering')

> What range of the current sensor sampling frequency (ie: readings every 1 sec, or every 5 sec etc) is recommended for a reasonable model?

Unfortunately I'm not aware of a study which directly addresses this question.  You could try asking in the [Energy Disaggregation mailing list](https://groups.google.com/forum/#!forum/energy-disaggregation).  The answer will probably depend on exactly which type of model you're using.  For example, if I remember correctly there is some evidence that Combinatorial Optimisation actually works best if you down-sample to, say, minutely.

If you're planning what sample rate to use for a new metering installation then I'd say your best bet is to go for the highest your hardware is capable of (storage is cheap).  You can always down-sample later.
