### ISSUE TITLE
Electric:plot() should allow multiple measurements on the same graph

### ISSUE THREAD

**Issue by JackKelly** [nilmtk/nilmtk#410]
following on from #405 

e.g. we could have a `measurements` parameter which accepts a list of measurements.  e.g. you'd call `elec['fridge'].plot(measurements=[('power', 'reactive'), ('power', 'active')])`.  And perhaps we should also allow `measurements='all'` to plot all available measurements.

Any thoughts?

**Comment by gjwo** [comment]
Sounds useful, the whole point of me wanting to see both on one plot was to see how reactive played in (I haven't looked at this before) it should help differentiate motor type loads from heaters etc. I haven't looked at how the tool kit handles features yet so you may have already covered that aspect. I think component recognition probably ought to be a stage in the disaggregation pipeline. looking at graphs is a good way of making sure the software is doing the right thing.
