### ISSUE TITLE
Cross reference the Dataframe column headings with the description in the metadata and give a warning if they don't match

### ISSUE THREAD

**Issue by JackKelly** [nilmtk/nilmtk#418]
From #416

**Comment by nipunreddevil** [comment]
Another case where this might be useful. It took me some time to debug this :)

I had buildingx.yaml for more number of buildings than for which I had data in the HDFStore. Thus, while iterating on ds.buildings, I would get error as data doesn't exist in the store while the metadata does!

Ofcourse, this remains low priority, unless someone can come up with a PR.
