### ISSUE TITLE
Are dataframes loaded from HDF5 files assumed to be sorted?

### ISSUE THREAD

**Issue by oliparson** [nilmtk/nilmtk#421]
I think NILMTK assumes that dataframes are sorted by index (timestamp) when loaded from HDF5 files, e.g. in hdfdatastore.py:
```python
@doc_inherit
    def get_timeframe(self, key):
        """
        Returns
        -------
        nilmtk.TimeFrame of entire table after intersecting with self.window.
        """
        data_start_date = self.store.select(key, [0]).index[0]
        data_end_date = self.store.select(key, start=-1).index[0]
        timeframe = TimeFrame(data_start_date, data_end_date)
        return self.window.intersection(timeframe)
```
though I didn't find this mentioned in the [Writing a dataset converter](https://github.com/nilmtk/nilmtk/blob/master/docs/manual/development_guide/writing_a_dataset_converter.md) tutorial. If this is the case, should we add it there?

**Comment by nipunreddevil** [comment]
I guess we should. I've had issues in the past when I didn't check that my index was sorted. Infact, we should put an assert somewhere to check that the index is sorted.

**Comment by oliparson** [comment]
Good point, where would this asset go? After the converter has run, or one a dataset has been loaded?

**Comment by JackKelly** [comment]
I'd suggest it should be the responsibility of the converter to make sure the index is sorted.  It's quite a computationally expensive thing to do on a large dataset so I don't think we want to do this every time the data is loaded.  And yes, please can someone add a note to the dataset converter docs to say that all converters need to make sure the index is sorted?  (the REDD converter does this because the index in REDD isn't always sorted)

**Comment by oliparson** [comment]
It's the same for HES too, and it just tripped me up. I'll add to the docs then.

**Comment by oliparson** [comment]
Docs have been updated. I guess if we had some sort of inheritance in the `dataset_converters` then this could be in a superclass somewhere, but until then let's just leave it in the docs.

**Comment by JackKelly** [comment]
good work

> I guess if we had some sort of inheritance in the dataset_converters

yeah, I always imagined leaving the dataset_converters as 'free form' as possible to make it as easy as possible for others to implement (including implementations not in Python).  But if there's a clean way to make it OOP then by all means suggest it :)

**Comment by oliparson** [comment]
Yeah I agree it's nice to have them as stand alone scripts. How does the metadata validation work? I guess we could always make a `Datastore.validate()` method which takes care of this stuff.

**Comment by JackKelly** [comment]
> How does the metadata validation work?

there is no validator for the metadata (other than a few quick tests I wrote by hand!).  One day I might write a formal, machine readable schema.  Which would then give us a validator.

> I guess we could always make a Datastore.validate() method which takes care of this stuff.

yeah, I think that's a good idea.   I think there might even be an ancient feature request for something similar on the issue queue...
