### ISSUE TITLE
HDF5 Error

### ISSUE THREAD

**Issue by lutianqi** [nilmtk/nilmtk#422]
Excuse me, when I want to do this job:

``` javascript
import time
start=time.time()
fhmm = fhmm_exact.FHMM()
fhmm.train(train_elec, sample_period=60)
end=time.time()
print end-start

disag_filename = join(data_dir, 'redd-disag-fhmm.h5')
output = HDFDataStore(disag_filename, 'w')
fhmm.disaggregate(elec.mains(), output)
output.close()
```

 then, error happens like the this:

```
Exception tables.exceptions.HDF5ExtError: HDF5ExtError('Problems closing the Group None',) in
```

I use the REDD dataset, and I converted the data into hdf5 format.
Could you give me some suggestions? Thanks!

**Comment by nipunreddevil** [comment]
I've seen such an error when the HDF5 file gets damaged due to some reason. Can you regenerate the HDF5 and try?

**Comment by lutianqi** [comment]
You mean regenerate the file ```'redd-disag-fhmm.h5'```,or the```'redd.h5'```?

**Comment by nipunreddevil** [comment]
That would depend on where you get the error. I'd suggest starting afresh and step by step. Like:

1. Convert to redd.h5
2. Train
3. Disaggregate

Let us know in which step you get the error.

**Comment by lutianqi** [comment]
OK, I will have a try. Thank you for your suggestions!

**Comment by lutianqi** [comment]
Even though I regenerate these file, I still get this error, always when I do the disaggregate job.

**Comment by JackKelly** [comment]
@lutianqi please can you copy-and-paste the entire error message (including the entire trace-back so we can see which lines of code are involved in the error).

**Comment by nipunbatra** [comment]
@lutianqi : any update on this? Can we close this?

**Comment by PMeira** [comment]
Since it's been a few years, I'm closing the issue. If anyone faces this again, feel free to reopen.
