### ISSUE TITLE
Error while running test

### ISSUE THREAD

**Issue by neekeeta** [nilmtk/nilmtk#425]
While running NILMTK tests using nosetests command I got following error

CalledProcessError: Command 'git checkout -- C:\Users\Nikita Patel\Anaconda\nilmtk\data' returned non-zero exit status 128
![error](https://cloud.githubusercontent.com/assets/13886041/9399253/4c634742-47cf-11e5-88e1-b63518a35d4e.JPG)

**Comment by nipunreddevil** [comment]
Hi Nikita,
Have you seen the following issue: https://github.com/nilmtk/nilmtk/issues/387

Also, if you don't intend to contribute code, but, rather get started with nilmtk, you can safely ignore this step for now.

**Comment by neekeeta** [comment]
I get following error while running
"fhmm.train(top_5_train_elec, sample_period=60)"

Error:
Training model for submeter 'ElecMeter(instance=5, building=1, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])'
Traceback (most recent call last):

  File "<ipython-input-32-8af3dc2b6748>", line 1, in <module>
    fhmm.train(top_5_train_elec, sample_period=60)

  File "c:\users\nikita patel\anaconda\nilmtk\nilmtk\disaggregate\fhmm_exact.py", line 213, in train
    learnt_model[meter].fit([X])

  File "build\bdist.win-amd64\egg\hmmlearn\base.py", line 400, in fit
    X = check_array(X)

  File "C:\Users\Nikita Patel\Anaconda\lib\site-packages\sklearn\utils\validation.py", line 350, in check_array
    array.ndim)

ValueError: Found array with dim 3. Expected <= 2

**Comment by nipunreddevil** [comment]
Please can you open a new issue giving complete details, including the code
you ran.
