### ISSUE TITLE
Modify FHMM to use new API in HMMLearn 0.2.0

### ISSUE THREAD

**Issue by JackKelly** [nilmtk/nilmtk#427]
See #426 for details

**Comment by WangChunyi** [comment]
I use the command: pip install hmmlearn. But the version of hmmlearn is 0.2.0 .
I have no method to install hmmlearn 0.1.1. Do you have the source.
Can you spend your valuable time to help me answer this question. Thank you very much

**Comment by PMeira** [comment]
hmmlearn, while still developed, hasn't seen a release for a long time. We're now using a tested git revision.

For future reference, our [`environment.yml`](https://github.com/nilmtk/nilmtk/blob/master/environment.yml) (used for conda installs) should always list the recommended version.
