### ISSUE TITLE
Algorithm - active and apparent power

### ISSUE THREAD

**Issue by HarllanAndrye** [nilmtk/nilmtk#429]
Hi.

I am analyzing the NILMTK algorithms for my studies at the university. I did some tests and suggest some questions:
- I'm trying to use active and apparent power, however, after disaggregating the data, only show active power (https://drive.google.com/file/d/0B5U6hPXEfisxcWdJSE4tbFpIRHM/view?usp=sharing / https://drive.google.com/file/d/0B5U6hPXEfisxbEtQQ0N1aFAzRHM/view?usp=sharing). I would like to analyze the algorithms with the two powers. The algorithms use only one power for training and disaggregation?
- As a disaggregation works, detecting the events of the appliances?

Can you help me?

**Comment by JackKelly** [comment]
@nipunreddevil's answer:

Hi there,
Thanks for writing. I’ve had a chance to look into your fork of nilmtk. Interesting!
* CO and FHMM implementations currently can only handle single dimensional data. However, Hart’s algorithm can handle both 1d and 2d data.
* CO and FHMM will give a state sequence (or power sequence). From this event sequence can trivially be computed. Hart’s algorithm can explicitly return appliance events.

Hope this helps :)

Nipun Batra
PhD scholar IIIT Delhi
http://nipunbatra.github.io/

**Comment by HarllanAndrye** [comment]
I'm trying to use the Hart's algorithm, 
```
from nilmtk.disaggregate import hart_85
hart = hart_85.Hart85()
hart.train(top_3_train_elec, sample_period=32, cols=[('power', 'active')])
end=time.time()

output = HDFDataStore(disag_filename, 'w')
hart.disaggregate(test_elec.mains(), output, sample_period=32)
output.close()

disag_hart = DataSet(disag_filename)
disag_hart_elec = disag_hart.buildings[building].elec
```
but when I use the f-score shows the following error:
```
from nilmtk.metrics import f1_score
f1_hart = f1_score(disag_hart_elec, test_elec)
f1_hart.index = disag_hart_elec.get_labels(f1_hart.index)
```
```
KeyError                                  Traceback (most recent call last)
<ipython-input-28-7fe83e1504d2> in <module>()
      1 #Métrica f-score, onde é retornado uma pontuação entre 0 e 1.
      2 from nilmtk.metrics import f1_score
----> 3 f1_hart = f1_score(disag_hart_elec, test_elec)
      4 f1_hart.index = disag_hart_elec.get_labels(f1_hart.index)

/home/harllan/nilmtk/nilmtk/metrics.pyc in f1_score(predictions, ground_truth)
    215     f1_scores = {}
    216     both_sets_of_meters = iterate_through_submeters_of_two_metergroups(
--> 217         predictions, ground_truth)
    218     for pred_meter, ground_truth_meter in both_sets_of_meters:
    219         scores_for_meter = pd.DataFrame(columns=['score', 'n_samples'])

/home/harllan/nilmtk/nilmtk/metergroup.pyc in iterate_through_submeters_of_two_metergroups(master, slave)
   1681     for master_meter in master.submeters().meters:
   1682         slave_identifier = replace_dataset(master_meter.identifier, slave.dataset())
-> 1683         slave_meter = slave[slave_identifier]
   1684         zipped.append((master_meter, slave_meter))
   1685     return zipped

/home/harllan/nilmtk/nilmtk/metergroup.pyc in __getitem__(self, key)
    218                     if meter.identifier == key:
    219                         return meter
--> 220             raise KeyError(key)
    221         elif isinstance(key, MeterGroupID):
    222             key_meters = set(key.meters)

KeyError: ElecMeterID(instance=5, building=1, dataset='LAB')
```

Can someone help me?

**Comment by JackKelly** [comment]
The metrics functions compare each meter in the disaggregation output with
each meter in the ground truth.  That error message suggests that meter 5
is in the disag output but isn't in the ground truth.

Are you doing disag on the same building on which you trained? (I'm afraid
the metrics can't yet handle the situation where you train and test on
different houses. Which we plan to fix! But we're all very busy at the
moment)

Also, in general, it's best to start a new issue for each different
problem. But don't worry about it this time :)

**Comment by HarllanAndrye** [comment]
I using the same building.
The dataset has active and reactive power, I have to specify the power in the disag equal in training?

If you want, I can put this in a new issue.

**Comment by nipunreddevil** [comment]
Please create a new issue. Also, I wonder how we can reproduce this error, if this occurs only on your data set.

**Comment by HarllanAndrye** [comment]
Done: #432
