### ISSUE TITLE
How plot() calculates Active Power for the main meters if it isn't in available_columns()?

### ISSUE THREAD

**Issue by haderazzini** [nilmtk/nilmtk#430]
Hello,

I'm trying to use the Active Power of main meter for the REDD dataset but it isn't in available_columns(). But when I use the plot() for the main meter it gives to me a figure of the Active Power. As show in that code:

![image](https://cloud.githubusercontent.com/assets/13726816/9713217/3ef5907c-5550-11e5-9592-bbb1ef612ecc.png)

Do you know how to get the Active Power?

Regards,

Hader

**Comment by JackKelly** [comment]
REDD, as far as we are aware, records apparent power for both mains 'legs'.  Assuming this is true, there is no way to get active power for the REDD mains. Unless you calculate it yourself from REDD's high frequency data (which NILMTK can't do yet).

> But when I use the plot() for the main meter it gives to me a figure of the Active Power.

I'm confused as to why you think `plot()` gives active power?  The blue and green lines in the plot are for the two 'splits' for the (apparent) mains power.  (domestic houses in the US have two 120V 'legs')

**Comment by haderazzini** [comment]
Hello JackKelly,

Thank you very much for the quick answer. I'm thinking this because when I try to plot() the Apparent Power the picture is different:

![image](https://cloud.githubusercontent.com/assets/13726816/9713854/76a376f2-5554-11e5-91a8-6b18895683e3.png)

![image](https://cloud.githubusercontent.com/assets/13726816/9713870/8b1af416-5554-11e5-9395-da59136457f9.png)

Am I doing something wrong?

**Comment by JackKelly** [comment]
those two plots are for the two separate mains 'legs'.  If you are unsure about mains wiring in America, I recommend this short guide: https://en.wikipedia.org/wiki/Split-phase_electric_power

**Comment by haderazzini** [comment]
I have read the guide and I understand that those two plots are for the two separate mains 'legs' but I don't understand what means the blue and green lines in the first plot.

Could you explain to me how the plot() works?

I have already took a look at that links but I didn't understand:
https://github.com/nilmtk/nilmtk/tree/master/docs/manual
http://nilmtk.github.io/nilmtk/master/nilmtk.html

**Comment by JackKelly** [comment]
> Could you explain to me how the plot() works?

Sure :)

So, `redd.buildings[1].elec.mains()` returns a `MeterGroup` object which contains two `ElecMeter` objects (meters 1 and 2).  We do this because, for most purposes, we don't care that REDD records the mains as two separate legs and instead we want to sum those two splits together to get the total, aggregate mains consumption.  `MeterGroup` and `ElecMeter` have the same API, where possible.

The default behaviour of [`MeterGroup.plot()`](http://nilmtk.github.io/nilmtk/master/nilmtk.html?highlight=plot#nilmtk.metergroup.MeterGroup.plot) is to plot separate lines, one for each `ElecMeter` in that `MeterGroup`.  If you want to plot the sum then do `plot(kind='sum')`.

**Comment by haderazzini** [comment]
Thank you for the explanation. 

So, to plot the apparent power of the main meters is better use plot(kind='sum') or the second way a did (using load(physical_quantity='power',ac_type='apparent').next() ) ?

**Comment by JackKelly** [comment]
Well, `redd.buildings[1].elec.mains().plot()` will plot the *apparent* power of the *two individual mains meters*.  `redd.buildings[1].elec.mains().plot(kind='sum')` will plot the *apparent* power of the sum of the two mains meters.

`redd.buildings[1].elec.mains().load(physical_quantity='power',ac_type='apparent').next()` will get the *sum* of the apparent power (although I'd suggest using `redd.buildings[1].elec.mains().power_series_all_data()`) if you want a pandas Series object with the sum of the apparent power across both meters)

**Comment by haderazzini** [comment]
Thank you.

I will use the redd.buildings[1].elec.mains().plot() because I want to deal with the main meters separately. I want to detect the events in each leg.

By the way, I tried to do that loop but didn't work:

![image](https://cloud.githubusercontent.com/assets/13726816/9717415/d9978a50-5572-11e5-8746-47f558bfaaaa.png)

Do you have some suggestion to do it without knowing the number of main meters? Because I will try to use others datasets too.

**Comment by JackKelly** [comment]
ah, I'm afraid you can't iterate though a `MeterGroup` like that (although I agree that you should be able to and I think we have a feature request active to enable that behaviour!)

Try replacing your inner `for` loop with `for main_redd in redd.buildings[building].elec.mains().meters:`

(`meters` is a list)

**Comment by haderazzini** [comment]
Thank you very much Jack Kelly!

**Comment by JackKelly** [comment]
You're welcome! I'll close this issue for now but please re-open it if necessary.
