### ISSUE TITLE
setup.py doesn't compile with local modules

### ISSUE THREAD

**Issue by tonicebrian** [nilmtk/nilmtk#44]
Hi,

   I haven't the time to check this but I have my numpy installation in $HOME/.local/lib/python2.7 and the build process fails to find the numpy headers. I try

```
python setup.py config --include-dirs ~/.local/lib/python2.7
```

but has no effect on the `python setup.py build` command. Do you know how to allow user installations when building the package?

**Comment by mrkitravee** [comment]
File "setup.py", line 68, in <module>
    import numpy as np
ImportError: No module named 'numpy'

Error show when i install

**Comment by JackKelly** [comment]
Please see nilmtk's installation instructions for how to install nilmtk.

**Comment by mrkitravee** [comment]
Very sorry , i used python 3
