### ISSUE TITLE
Advice on Hart training parameters

### ISSUE THREAD

**Issue by gjwo** [nilmtk/nilmtk#440]
Looking at the code for train()
```python

    def train(self, metergroup, cols=[('power', 'active')],
              buffer_size=20, noise_level=70, state_threshold=15,
              min_tolerance=100, percent_tolerance=0.035,
              large_transition=1000, **kwargs):
        """
        Train using Hart85. Places the learnt model in `model` attribute.

        Parameters
        ----------
        metergroup : a nilmtk.MeterGroup object
        cols: nilmtk.Measurement, should be one of the following
            [('power','active')]
            [('power','apparent')]
            [('power','reactive')]
            [('power','active'), ('power', 'reactive')]
        buffer_size: int, optional
            size of the buffer to use for finding edges
        min_tolerance: int, optional
            variance in power draw allowed for pairing a match
        percent_tolerance: float, optional
            if transition is greater than large_transition,
            then use percent of large_transition
        large_transition: float, optional
            power draw of a Large transition
        """
```
The parameters noise_level and state_threshold are not explained in the comments, what are these for, and how were the initial values selected?

Why was a relatively high value of 100 selected for min_tolerance?

**Comment by gjwo** [comment]
I found the following in the Hart paper
1.   p27 - "Select a noise level for significant appliances. Appliance transitions below this level will be ignored (We have used 70 watts)"
2.  Also p27  "Select a threshold power level for defining steady-state periods. Repeated measurements of a steady load are expected to vary less that this threshold. (We have used 15 watts as this level.)"
3. p37/38  min_tolerance looks like the minimum allowable unassigned power or residual power (simply the unassigned power after all possible pairing are made).

@nipunreddevil  can you confirm this is correct (in particular point 3) so I can close this one?

**Comment by nipunreddevil** [comment]
@gjwo : I think you are right on all 3 points. I am sorry I forgot to tell you about the notes I had made from the paper: http://nipunbatra.github.io/2014/08/hart,%20nilm,%20nilmtk/

I might rephrase point three as the tolerance allowed in matching rising and falling edges. For eg. if fridge rising edge is +100 W and falling is -90W, they'll get paired if the absolute values of the rising and falling edge are within specified tolerance. Changing this parameter can affect the pairing process. Too high tolerance would pair different appliances, too low tolerance may not pair edges from a single appliance!

Thanks loads for all the efforts you've put in. I'll hopefully add these docstrings to code sometime soon.

**Comment by gjwo** [comment]
Thanks, I was half way through doing the same thing, so that has saved me some effort.
I need to think about point 3 as this is different to what I thought (which was probably wrong). So you are saying it is also the minimum gap needed to differentiate between devices, so it will affect clustering?

**Comment by gjwo** [comment]
I know where the confusion has arisen, in Hart's paper the minimum tolerance was 35W not 100W I now understand what you are saying. My original question could be clarified as why did you chose the default for this to be 100W instead of the 35W Hart used?

**Comment by nipunreddevil** [comment]
I think I used this threshold as the default based on my observation that appliances would often be separated by more than 35W.

**Comment by gjwo** [comment]
Interestingly when I change this from 100 to 35 on my quiet week I go from 4 centroids down to 2 which seems counter intuitive
