### ISSUE TITLE
set_window doesn't effect plot, should it?

### ISSUE THREAD

**Issue by gjwo** [nilmtk/nilmtk#441]
I was using set_window to limit the range for disaggregation (I had trained on two months of data), before running disaggregation I though I would check that the correct window was set by plotting the graph but the range of the plot wasn't changed. Should it have been? Is set window the right function to set a disaggregation period of interest? I thought testing should generally be done out of sample to training (although this example is actually in sample).

```python
Set two days for Disaggregation period of interest
Inspect the data during a quiet period when we were on holiday, should only be autonomous appliances such as fridge, freeze and water heating + any standby devices not unplugged.
In [14]:

gjw.set_window = TimeFrame(start='2015-07-13 00:00:00+01:00', end='2015-07-14 00:00:00+01:00')
elec = gjw.buildings[building_number].elec
mains = elec.mains()
mains.plot()
​
Out[14]:
<matplotlib.axes._subplots.AxesSubplot at 0x2d25d5c0>
```
Graph produced covered the two months rather than the two days specified above

**Comment by JackKelly** [comment]
could you show us the plot?  Does it actually include two months of *data*?  Or is it just that the x-axis range is 2 months?

**Comment by gjwo** [comment]
It has 2 months of data in it
![image](https://cloud.githubusercontent.com/assets/12109990/10334540/b83bc074-6ce2-11e5-93c8-ccc3cf3658f9.png)

**Comment by gjwo** [comment]
It also looks like it's not limiting the disaggregate step, as it has been running for a while now!

**Comment by JackKelly** [comment]
Oh, wait, I think you might be using `set_window` wrong?  It's supposed to work like this:

```python
gjw.set_window('2015-07-13 00:00:00', '2015-07-14 00:00:00')
```

(`set_window` will sort out the timezone for you)

**Comment by gjwo** [comment]
Guess again :smile: 
![image](https://cloud.githubusercontent.com/assets/12109990/10334747/22583950-6ce4-11e5-9b1c-3b398e983d75.png)

**Comment by gjwo** [comment]
or even 
![image](https://cloud.githubusercontent.com/assets/12109990/10334785/6c6546c8-6ce4-11e5-9b21-2f6f9e431cdc.png)

**Comment by JackKelly** [comment]
Have you tried doing

```python
gjw.set_window('2015-07-13 00:00:00', '2015-07-14 00:00:00')
```

instead of 

```python
gjw.set_window = TimeFrame(start='2015-07-13 00:00:00+01:00', end='2015-07-14 00:00:00+01:00')
```

?

**Comment by gjwo** [comment]
I have now
```python
Set two days for Disaggregation period of interest
Inspect the data during a quiet period when we were on holiday, should only be autonomous appliances such as fidge, freeze and water heating + any standby devices not unplugged.
In [19]:

gjw.set_window('2015-07-13 00:00:00','2015-07-14 00:00:00')
elec = gjw.buildings[building_number].elec
mains = elec.mains()
mains.plot()
​
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-7086295c0e8d> in <module>()
----> 1 gjw.set_window('2015-07-13 00:00:00','2015-07-14 00:00:00')
      2 elec = gjw.buildings[building_number].elec
      3 mains = elec.mains()
      4 mains.plot()

TypeError: 'TimeFrame' object is not callable
```

**Comment by gjwo** [comment]
it appeared to set the timeframe when I used it like this eariler
![image](https://cloud.githubusercontent.com/assets/12109990/10334971/debf75a8-6ce5-11e5-8c36-839d33fb3b2e.png)

**Comment by gjwo** [comment]
does store affect this?
```python
In [4]:

gjw.set_window = TimeFrame(start='2015-05-01 00:00:00+01:00', end='2015-08-31 00:00:00+01:00')
elec = gjw.buildings[building_number].elec
mains = elec.mains()
mains.plot()

gjw.store.window = TimeFrame(start='2015-05-01 00:00:00+01:00', end='2015-08-31 00:00:00+01:00')
gjw.set_window = TimeFrame(start='2015-05-01 00:00:00+01:00', end='2015-08-31 00:00:00+01:00')
elec = gjw.buildings[building_number].elec
mains = elec.mains()
mains.plot()
```

**Comment by JackKelly** [comment]
> TypeError: 'TimeFrame' object is not callable

Yes, that's because you've assigned `gjw.set_window` to a TimeFrame object.  You'll need to re-construct your `gjw` object.  (Probably safest to restart Python).

To summarise:

`DataSet.set_window()` is the correct public API for setting the window.  It does some sanity checking and takes care of the timezone and then sets `DataSet.store.window` for you.

If you really want to you can directly set `DataSet.store.window = TimeFrame(...)` but I wouldn't recommend it.

**Do not** do `DataSet.set_window = TimeFrame(...)` as that will replace the `DataSet.set_window()` method with your `TimeFrame` which will cause all manor of problems!

**Comment by gjwo** [comment]
Thanks, I will try that now, I thought I was following one of Nipun's examples, but I might have done messed it up

**Comment by JackKelly** [comment]
Yeah, sorry some of this stuff isn't brilliantly documented (and, indeed, has changed over time).

If you do find an incorrect example then let us know because it needs fixing!

**Comment by gjwo** [comment]
Will do. while I am waiting for the training to complete, is there a way to store and reload training to save running it repeatedly?

**Comment by JackKelly** [comment]
> is there a way to store and reload training to save running it repeatedly?

it's planned but not yet implemented, sorry.

you could try using [Python's built-in pickle library](https://docs.python.org/2/library/pickle.html) to pickle the `model` attribute.

**Comment by gjwo** [comment]
Thanks, my usage of set_window is now correct, sorry for the distraction!
![image](https://cloud.githubusercontent.com/assets/12109990/10335662/47ba60a0-6cea-11e5-95d3-2952c65e4ec9.png)
