### ISSUE TITLE
Hart_85 training - scatter and centroid questions

### ISSUE THREAD

**Issue by gjwo** [nilmtk/nilmtk#444]
Looking at training results for Hart_85 using active & reactive data over 4 days in a holiday period with low appliance usage I get the following:
![image](https://cloud.githubusercontent.com/assets/12109990/10388884/9a74b7ec-6e65-11e5-9d94-8ba2d807fb33.png)
 and
![image](https://cloud.githubusercontent.com/assets/12109990/10388897/b427d3c2-6e65-11e5-814e-138eacaea26d.png)
Training then leads to this
![image](https://cloud.githubusercontent.com/assets/12109990/10388908/d3874a04-6e65-11e5-819d-7b034e2b2a78.png)

Which leads to a number of questions:
1. I presume the Centroids are the power characteristics of individual appliances, which would explain why the values are smaller than the clusters they should relate to which would include other (vampire) devices. Is this correct? 
2. Does the algorithm store the value clouds from which the the centroids are calculated so I could plot these as the true signature clouds?
3. If 2 is true how do I access these? (I would like to scatter plot each cloud in different colours)
4. if 3 is possible has anybody worked out how to plot the confidence ellipsoids for the clouds.
5. Why no centroid for the bottom cluster?

For a busy period the large negative reactive values also seem to be ignored see below
![image](https://cloud.githubusercontent.com/assets/12109990/10389175/7358753e-6e67-11e5-9950-c98433c33bd0.png)

**Comment by JackKelly** [comment]
Any thoughts, @simonleigh and @nipunreddevil? (two very busy people so don't necessarily expect a reply I'm afraid, @gjwo!)

**Comment by nipunreddevil** [comment]
Hart's algorithm (in the current implementation) does the following:

1. Segments time series into steady and unsteady states
2. Finds transitions corresponding to first differences in steady states
3. Pairs the rising and falling edges of transitions 
4. Cluster these pairs. Currently, the implementation uses MeanShift technique which is non-parametric. Automatically finds optimum number of clusters

I would suggest you to look at the `pair_df` attribute of Hart85 disaggregator to gain some additional insights. Remaining questions can be answered by looking at: https://github.com/nilmtk/nilmtk/blob/master/nilmtk/feature_detectors/cluster.py#L142

Once you get the above flow, your questions are effectively scikit-learn questions, where you are trying to scatter plot with different colors for different clusters. Look at the example here: http://scikit-learn.org/stable/auto_examples/cluster/plot_dbscan.html

Aside: Interesting work and questions @gjwo . Too bad I'm hard pressed for time and can only answer so much for now.

**Comment by gjwo** [comment]
@nipunreddevil thanks for the reply I know you are busy. I see the implementation is Hart's original algorithm, in his paper he suggested that an improvement might be to cluster before pairing (observation not question!).

**Comment by nipunreddevil** [comment]
Right, I do recall reading that line and marking it to try some day in the future :)

**Comment by gjwo** [comment]
I managed to do something quite interesting with pair_df (see below), this was for active data only so I looked at duration to produce a scatter (which needed a log scale). If 'T1 Active' and 'T2 Active' are transition heights rather than steady state levels, this is what I was after - is that the correct interpretation? Still not seeing a relationship to the centroid & therefore appliance though.
![image](https://cloud.githubusercontent.com/assets/12109990/10397667/c99962da-6ea0-11e5-966e-ba250fc0bdcf.png)

**Comment by gjwo** [comment]
Looking at the holiday data these do seem to match the centroids Whoop!
![image](https://cloud.githubusercontent.com/assets/12109990/10398489/3e96d366-6ea5-11e5-8b23-aebc3509449a.png)

**Comment by nipunreddevil** [comment]
Must be taken with a grain of salt, that there exists no perfect algorithm to find the optimal number of clusters. Maybe, what you are seeing is a consequence of that. Two appliances could get merged in one clusters, or, an appliance having large variation get split into multiple clusters. 

Thus, whenever I use this algorithm, I do make a point to see the `pair_df`.

**Comment by gjwo** [comment]
I agree, I think my fridge and freezer are merged into one centroid (at about 90W), instead of one at 80w and another at 100w. I haven't yet worked out how to tweak the training parameters to improve this (all advice welcome).
It also occurs to me that pair_df has no direct data linkage to the centroids (like an appliance number) to enable the scatter dots to be coloured for separate appliances.
