### ISSUE TITLE
How to synchronize two different data frames?

### ISSUE THREAD

**Issue by haderazzini** [nilmtk/nilmtk#445]
I have two different data frames. The first is the power active of Washer Dryer and the second is an estimation of power active of Washer Dryer. I would like to subtract the two data frames to get the error between measurement and estimation. How to synchronize them?
![image](https://cloud.githubusercontent.com/assets/13726816/10429185/17b6b69a-70f7-11e5-8dd6-cb39f8845d5d.png)
![image](https://cloud.githubusercontent.com/assets/13726816/10429190/21ee924a-70f7-11e5-8e23-62597f8dbc1c.png)
![image](https://cloud.githubusercontent.com/assets/13726816/10429195/29495020-70f7-11e5-92bb-b9b3d8842385.png)

**Comment by JackKelly** [comment]
the problem is that the two dataframes have different time bases (one has a sample once a second, the other has a sample once every 6 seconds).  So you need to resample.  Something like this:

```
difference_washer = df_washer - df_washer_estimation.resample('6S')
```

**Comment by haderazzini** [comment]
Keeps popping up a lot of Nan.

![image](https://cloud.githubusercontent.com/assets/13726816/10429641/55c5e052-70fa-11e5-8673-6eaaea199c7b.png)

**Comment by JackKelly** [comment]
I assume that's because df_washer also needs to be resampled?

I'd suggest that you don't do `df_washer = elec['washer dryer'].load().next()` instead do `df_washer = elec['washer dryer'].power_series().next()`

I think that will automatically ensure that `df_washer` will be resampled to 6-secondly data.

**Comment by haderazzini** [comment]
No, it didn't work.
![image](https://cloud.githubusercontent.com/assets/13726816/10429916/604b46a0-70fc-11e5-9724-b58ab3d8ff18.png)

Even if I do

df_washer = elec['washer dryer'].power_series().next()
difference_washer = df_washer.resample('6S') - df_washer_estimation.resample('6S')
difference_washer

Keeps showing some few Nan. I believe it will disappear if the indexes are the same for both data frames.

**Comment by JackKelly** [comment]
Well, first you'll need to figure out which of those two dataframes have NaNs.  It's possible that there isn't any data for the washer dryer for the times when you're getting NaNs. You could do `fillna(0)` to fill the NaNs with zeros (if that is what you want to do!)

If you haven't done so already, I'd suggest reading the Pandas docs.  This is a Pandas question more than a NILMTK question, really.

**Comment by haderazzini** [comment]
It looks like the problem is in 'resample':
![image](https://cloud.githubusercontent.com/assets/13726816/10688954/42edbf1e-7978-11e5-9aa2-2280c73b61a2.png)
![image](https://cloud.githubusercontent.com/assets/13726816/10688976/557798f8-7978-11e5-9d75-391a4d803fee.png)
![image](https://cloud.githubusercontent.com/assets/13726816/10688991/681df9fc-7978-11e5-9062-16e871ad5a60.png)
![image](https://cloud.githubusercontent.com/assets/13726816/10688994/6d8d126a-7978-11e5-847e-97204a4d0f8b.png)

**Comment by JackKelly** [comment]
I'm very sorry but this is a purely Pandas issue and so please see the Pandas docs and issue queue for more help with Pandas.   I wish we could help with every NILMTK issue but please remember that we've  our own work to do and so can only afford to spend a small amount of time each week on the NILMTK issue queue.

**Comment by haderazzini** [comment]
No problem Jack, I understand and I'm looking in Pandas documentation.  As soon as I get a answer, I will it put here. I appreciate a lot your help and I wish I could help others people like you do.

**Comment by haderazzini** [comment]
I'm using interpolate and looks like it works for the moment.

I did in that way:

df_washer = elec['washer dryer'].power_series().next()
difference_washer = df_washer.resample('6S').interpolate() - df_washer_estimation.resample('6S').interpolate()
difference_washer
