### ISSUE TITLE
AmbiguousTimeError: Cannot infer dst time from Timestamp

### ISSUE THREAD

**Issue by athenawisdoms** [nilmtk/nilmtk#450]
Hi all, I tried importing my own data into a `DataSet` using `convert_redd` to output the HDF5 file which is read using `DataSet()`. My data set consists of 2 columns without headers, the first column is the timestamp in unix time in seconds, the second column is the power, making this similar to `channel_1.dat` in the REDD data set.

    1325376600 52.1147
    1325376900 50.9517
    1325377200 49.8164
    1325377500 49.1795
    1325377800 47.6288

However when trying to create a `pandas.DataFrame`

    test = DataSet('./data/test/test.h5')
    mains = test.buildings[1].elec.mains()
    mains_df = mains.load().next()

I'm getting the error

    pandas/tslib.pyx in pandas.tslib.tz_localize_to_utc (pandas/tslib.c:64516)()

    AmbiguousTimeError: Cannot infer dst time from Timestamp('2012-11-04 01:00:00'), try using the 'ambiguous' argument

Why is this happening? Did something go wrong in the creating of our own `DataSet`?

**Comment by athenawisdoms** [comment]
---------------------------------------------------------------------------
    AmbiguousTimeError                        Traceback (most recent call last)
    <ipython-input-10-51f183cc9fd1> in <module>()
    ----> 1 test.buildings[1].elec.mains().plot()

    /Users/x/Dropbox/Code/Equota/nilmtk/nilmtk/electric.pyc in plot(self, ax, timeframe, plot_legend, unit, plot_kwargs, **kwargs)
        179         kwargs['sections'] = [timeframe]
        180         kwargs = self._set_sample_period(timeframe, **kwargs)
    --> 181         power_series = self.power_series_all_data(**kwargs)
        182         if power_series is None or power_series.empty:
        183             return ax

    /Users/x/Dropbox/Code/Equota/nilmtk/nilmtk/electric.pyc in power_series_all_data(self, **kwargs)
        105     def power_series_all_data(self, **kwargs):
        106         chunks = []
    --> 107         for series in self.power_series(**kwargs):
        108             if len(series) > 0:
        109                 chunks.append(series)

    /Users/x/Dropbox/Code/Equota/nilmtk/nilmtk/electric.pyc in load_series(self, **kwargs)
        626         physical_quantity = kwargs['physical_quantity']
        627         generator = self.load(**kwargs)
    --> 628         for chunk in generator:
        629             if chunk.empty:
        630                 yield chunk

    /Users/x/Dropbox/Code/Equota/nilmtk/nilmtk/preprocessing/apply.pyc in process(self)
         12     def process(self):
         13         self.check_requirements()
    ---> 14         for chunk in self.upstream.process():
         15             new_chunk = self.func(chunk)
         16             new_chunk.timeframe = chunk.timeframe

    /Users/x/Dropbox/Code/Equota/nilmtk/nilmtk/datastore/hdfdatastore.pyc in load(self, key, cols, sections, n_look_ahead_rows, chunksize, verbose)
        120 
        121                 data = self.store.select(key=key, columns=cols,
    --> 122                                          start=chunk_start_i, stop=chunk_end_i)
        123 
        124                 # if len(data) <= 2:

    /Users/athena/anaconda/envs/disaggregation/lib/python2.7/site-packages/pandas/io/pytables.pyc in select(self, key, where, start, stop, columns, iterator, chunksize, auto_close, **kwargs)
        680                            auto_close=auto_close)
        681 
    --> 682         return it.get_result()
        683 
        684     def select_as_coordinates(

    /Users/athena/anaconda/envs/disaggregation/lib/python2.7/site-packages/pandas/io/pytables.pyc in get_result(self, coordinates)
       1363 
       1364         # directly return the result
    -> 1365         results = self.func(self.start, self.stop, where)
       1366         self.close()
       1367         return results

    /Users/athena/anaconda/envs/disaggregation/lib/python2.7/site-packages/pandas/io/pytables.pyc in func(_start, _stop, _where)
        673             return s.read(start=_start, stop=_stop,
        674                           where=_where,
    --> 675                           columns=columns, **kwargs)
        676 
        677         # create the iterator

    /Users/athena/anaconda/envs/disaggregation/lib/python2.7/site-packages/pandas/io/pytables.pyc in read(self, where, columns, **kwargs)
       4029             else:
       4030                 values = a.cvalues.T
    -> 4031                 index_ = Index(index, name=getattr(index, 'name', None))
       4032                 cols_ = cols
       4033 

    /Users/athena/anaconda/envs/disaggregation/lib/python2.7/site-packages/pandas/core/index.pyc in __new__(cls, data, dtype, copy, name, fastpath, tupleize_cols, **kwargs)
        124             if issubclass(data.dtype.type, np.datetime64) or is_datetimetz(data):
        125                 from pandas.tseries.index import DatetimeIndex
    --> 126                 result = DatetimeIndex(data, copy=copy, name=name, **kwargs)
        127                 if dtype is not None and _o_dtype == dtype:
        128                     return Index(result.to_pydatetime(), dtype=_o_dtype)

    /Users/athena/anaconda/envs/disaggregation/lib/python2.7/site-packages/pandas/util/decorators.pyc in wrapper(*args, **kwargs)
         87                 else:
         88                     kwargs[new_arg_name] = new_arg_value
    ---> 89             return func(*args, **kwargs)
         90         return wrapper
         91     return _deprecate_kwarg

    /Users/athena/anaconda/envs/disaggregation/lib/python2.7/site-packages/pandas/tseries/index.pyc in __new__(cls, data, freq, start, end, periods, copy, name, tz, verify_integrity, normalize, closed, ambiguous, dtype, **kwargs)
        342                     ints = subarr.view('i8')
        343                     subarr = tslib.tz_localize_to_utc(ints, tz,
    --> 344                                                       ambiguous=ambiguous)
        345 
        346                 subarr = subarr.view(_NS_DTYPE)

    pandas/tslib.pyx in pandas.tslib.tz_localize_to_utc (pandas/tslib.c:64516)()

    AmbiguousTimeError: Cannot infer dst time from Timestamp('2012-11-04 01:00:00'), try using the 'ambiguous' argument

**Comment by nipunreddevil** [comment]
I think this is a Pandas issue which crops up when data spans multiple DST changes. I think Pandas devs resolved it in the latest release. I’d suggest to give the following a try:
1. Upgrade to latest Pandas version
2. Regenerate your data set
3. Do the operation which resulted in this error

I hope that the issue will be resolved by version upgrade.

Nipun Batra
PhD scholar IIIT Delhi
https://www.iiitd.edu.in/~nipunb/

**Comment by athenawisdoms** [comment]
@nipunreddevil Thanks for the quick reply!

I checked that I'm using pandas 0.17.0 which is the latest stable version. Tried regenerating the data set and doing the same operation as suggested, but the same problem persists.

Any ideas?

**Comment by JackKelly** [comment]
Unfortunately the Pandas bug is still present in 0.17.  See this issue: https://github.com/pydata/pandas/issues/10117

We have some code in NILMTK which worked around this issue in Pandas < 0.17.  This code in NILMTK is in [nilmtk.utils.safe_resample](https://github.com/nilmtk/nilmtk/blob/3a5ab8061b4e3e04e31efd8f075e95b519a00e45/nilmtk/utils.py#L381).  Not sure why the NILMTK code is no longer working around this issue.  If I get time then I'll look into it.  Not sure when or it I'll get time to do that though!...

**Comment by JackKelly** [comment]
Actually, on looking closer at this bug report, I'm not entirely sure that this current bug is exactly the same as the Pandas bug 10117 that I linked to above. 

@athenawisdoms did you specify a `timezone` in the metadata for your dataset?  Could you share the metadata that you wrote for your dataset, please?

**Comment by jingkungao** [comment]
@JackKelly I think this is the same issue  [nilmtk#456](https://github.com/nilmtk/nilmtk/issues/456) I am having. The most recent traceback goes to  
```
hdfdatastore.py", line 123, in load start=chunk_start_i, stop=chunk_end_i)
```

**Comment by JackKelly** [comment]
@athenawisdoms there was definitely [a bug in Pandas 0.17 which has just been fixed today](https://github.com/pydata/pandas/issues/11626).  Please try either installing Pandas 0.16.2 or install pandas 0.17.0+210.g91407ff from git using something like this:

```bash
pip uninstall pandas
pip install -e git+https://github.com/pydata/pandas.git@91407ffd5f6d497949239b2ab956368dec2ac32b#egg=pandas
```

**Comment by nipunreddevil** [comment]
Great work @JackKelly on creating an example for Jeff to fix!

**Comment by oliparson** [comment]
+1 for the detective work @JackKelly

**Comment by nipunbatra** [comment]
Can we close this @jingkungao, @athenawisdoms , given that the Pandas bug has been resolved?

**Comment by jingkungao** [comment]
Yes, please do. I think it's resolved. Thanks!

**Comment by hscbsc** [comment]
I know this is closed, but this is for the viewers like me searching for resolution of this bug. Please update to pandas 0.19.

**Comment by nipunbatra** [comment]
Thanks a lot @hscbsc!
