### ISSUE TITLE
Plot sum of disaggregated components

### ISSUE THREAD

**Issue by vertangelx** [nilmtk/nilmtk#451]
After disaggregation, I am able to plot the aggregated data from the site meter together with the disaggregated data. Is it possible to plot the aggregated data together with the sum of the disaggregated data, so we can visualize the errors?

Currently my code to draw the plot is below, which draws a chart similar to the one below the code.

```
disag_fhmm = DataSet(disag_filename)
disag_fhmm_elec = disag_fhmm.buildings[1].elec
disag_fhmm_elec.plot()
```

![image](https://cloud.githubusercontent.com/assets/8826684/11163048/5955a992-8a8f-11e5-8428-38c40bb8c8a7.png)

**Comment by nipunbatra** [comment]
Two ways to go about this:

1. You manually get the data from the submeters, like `disag_elec.submeters()` and sum up the data frames
2. nilmtk provides an internal method to sum up meters inside a meter group. @JackKelly: I can't recall- I think we had such a functionality somewhere?

**Comment by MartinNeighbours** [comment]
If I've understood correctly you've created a new dataset of the disaggregated data along with the original mains reading and loaded this back in to query.

This is connected to some things that I've been looking into, so thought I'd document the solution as there are a couple of quirks to be aware of:

1. down-sampling in the nilmtk plot - it can be worked around using the width parameter, but can be confusing if you don't know that it's there
2. When using the width parameter in nilmtk plots, the order of plotting is important (see 2b below)
3. The difference between a meter group plot and meter group load
4. Pandas DataFrame plots not carrying through labels specified in the plot - Pandas Series do.

I've outlined 2 possible solutions below.  The first just loads the data into a dataframe and reproduces the plot.  Pandas date formatting (used by nilmtk) is much neater and lower maintenance than the native pyplot options.  The second approach combines nilmtk output with a dataframe

# Method 1

```
# a sub meter load sums the individual meters in the group
# a sub meter plot will plot each meter

df_sub_meters = sub_meters.load(sample_period=60).next() # single column

# to get a dataframe of individual meters use sub_meters.dataframe_of_meters()
# this will apply the dataset sample period if not supplied with sample_period

df_indiv_sub_meters = sub_meters.dataframe_of_meters(sample_period=60) # multiple columns

# method 1 using DataFrames
df_mains = train_elec.mains().load(sample_period=60).next()

# due to a "bug" in pandas, labels do not carry through in dataframe plots
# so you need to explicitly state the column (effectively plotting a series)

fig = plt.figure()
ax = fig.add_subplot(111)
df_mains['power']['active'].plot(ax =ax,label='Mains',c='darkgreen')
df_sub_meters['power']['active'].plot(ax=ax,label='Sub meter total',c='salmon')
ax.set_title('DataFrame plot, sample_period = 60')
ax.set_ylabel('Power (W)')
ax.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
```
This produces something like:

![image](https://user-images.githubusercontent.com/33223741/33068564-a50937e0-cea9-11e7-93e6-1a67d25b9e42.png)

# Method 2a

```
# method 2a
# use a mix of series plot and nilm-tk plot

# the nilm-tk plot down-samples depending on the duration of the plot to stop
# the system hanging (nice if you haven't saved a model, but can be problematic 
# if you don't know it's there when looking at some devices)
duration = train_elec.get_timeframe().timedelta.total_seconds()
width = 800 # the default width
secs_per_pixel = int(round(duration/width))


fig = plt.figure()
#note the pass through plot keyword aruments are as a dictionary
ax = train_elec.mains().plot(plot_kwargs={'c':'darkgreen'})
df_sub_meters['power']['active'].plot(ax=ax,**{'c':'salmon','label':'sub meters total'} )
ax.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
ax.set_title ('Mixed plot with mains sampled at %0.f seconds and sub-meter sampled at 60s'  %secs_per_pixel)
```

This produces the following - there is very little difference between the two for such a short duration, but you may need to consider adjusting the width parameter for longer duration plots.  Matplotlib can handle some pretty big plots (and will downsample if necessary) as long as you're patient enough.

![image](https://user-images.githubusercontent.com/33223741/33068680-ee4b8610-cea9-11e7-9db9-614eca27ac7c.png)

# Method 2b

The nilmtk sample rate can be changed quite simply:
```

new_width = int(duration/60)

fig = plt.figure()
ax = fig.add_subplot(111)
#note the pass through plot keyword aruments are as a dictionary
# note also the change in order of plotting to preserve the axis labels when the width argument is used
# not sure why this happens!
df_sub_meters['power']['active'].plot(ax=ax,**{'c':'salmon','label':'sub meters total'} )
train_elec.mains().plot(ax = ax, width = new_width, plot_kwargs={'c':'darkgreen'})
ax.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
ax.set_title('Mixed plot with mains sampled at 60 seconds and sub-meter sampled at 60s')

```
Producing the following:

![image](https://user-images.githubusercontent.com/33223741/33069972-373548e4-ceae-11e7-850a-2af5e2a38170.png)
