### ISSUE TITLE
Are the disaggregation results constrained by the submetered training data

### ISSUE THREAD

**Issue by meteorjs3000** [nilmtk/nilmtk#453]
If a FHMM model is trained using submetered data that all peaks at 100W, will the disaggregation produce a prediction that has energy usage above 100W?

In other words, if the site meter shows an aggregated level of 1000W, and my training data is a single appliance that peaks at 100W, will the disaggregated data ever be greater than 100W?

**Comment by nipunreddevil** [comment]
Hi,
No, the disaggregated power will never be greater than 100W for that particular appliance.

**Comment by meteorjs3000** [comment]
@nipunreddevil Ah... then how do we handle a situation where we have the submeter data of an appliance like a 100W lamp, but we do not know how many 100W lamps are in the house in question.

**Comment by nipunreddevil** [comment]
I guess you may have to do a "survey" to find out how many 100 W lamps exist. Or, use some manual tagging.

**Comment by meteorjs3000** [comment]
@nipunreddevil I see. I'm wondering how do home energy monitors perform their energy disaggregation to provide an appliance level itemized bill if they do not know how many of an appliance is in the house.

**Comment by nipunreddevil** [comment]
I'm not sure what you mean by home energy monitors. They could mean: meters you attach to individual appliances. Then, you associate each meter with an appliance name and you can get energy consumption of that appliance. Actually, you get the energy consumption of whatever is attached to that meter.

If you are talking about disaggregation systems, some companies ask the users to tell them roughly about the nature and number of appliances. Other approaches may try to disaggregate only a subset of appliances. There is really no single answer to this question yet! 

Hope this helps :)
