### ISSUE TITLE
Time at which appliances are turned on and off

### ISSUE THREAD

**Issue by meteorjs3000** [nilmtk/nilmtk#454]
when training a FHMM model using submetered data of an appliance, will the time of the day/week/etc at which it turns on and off matters? How about the duration of time it is turned on or turned off? 

If this does not matter, why is it so? Thanks in advance!

**Comment by nipunreddevil** [comment]
HMM has 3 parameters:

1. Initial probability (Pi)
2. Transition matrix (A)
3. Emission matrix (B)

Time of day will not impact either of the 3 parameters. Duration of usage will have an indirect impact in transition matrix (prob. of OFF-> ON, ON->ON, etc.). A Hidden Semi Markov Model would also incorporate usage durations as a part of the model.

**Comment by nipunbatra** [comment]
Can we close this @meteorjs3000?
