### ISSUE TITLE
matplotlib inline produce syntax error

### ISSUE THREAD

**Issue by hazlyamir-tmrnd** [nilmtk/nilmtk#455]
i have this problem right now. Any idea how to solve this?
This is the error
>>> %matplotlib inline
  File "<stdin>", line 1
    %matplotlib inline
    ^
SyntaxError: invalid syntax

**Comment by nipunreddevil** [comment]
Are you trying to use matplotlib inline in your Python script? If yes, it won't work. It will work only on an IPython environment.

**Comment by hazlyamir-tmrnd** [comment]
thanks nipunreddevil
