### ISSUE TITLE
Closing remaining open files:E:/metertest/REDD/redd.h5...done

### ISSUE THREAD

**Issue by dragonGreat** [nilmtk/nilmtk#464]
Hi all;
  I has a problem on Windows10 when I use nilmtk.

![1](https://cloud.githubusercontent.com/assets/11920170/11991094/271e00fa-aa51-11e5-8a05-7451df0b58b5.png)

 I don't know how to fix it.

**Comment by nipunreddevil** [comment]
This isn't a problem. When you're done with the conversion, you close the HDF5. Is it preventing any further code from executing?

**Comment by dragonGreat** [comment]
Thanks for your attention.
when i done with the conversion,everything looks fine .

**Comment by dragonGreat** [comment]
Thanks for your attention. I have a poor network ,sorry about point  close button.

when i done with the conversion, everything looks fine .
![2](https://cloud.githubusercontent.com/assets/11920170/11991397/0ce16692-aa55-11e5-9abc-4e2a2b5b66a3.png)

but,
![3](https://cloud.githubusercontent.com/assets/11920170/11991429/5e8f7448-aa55-11e5-8674-b0591d93d55d.png)

I don't know where close the HDF5.what should I do about this issue?

**Comment by dragonGreat** [comment]
thanks for all!
