### ISSUE TITLE
Where should 'cutting edge' NILM algorithms live?

### ISSUE THREAD

**Issue by JackKelly** [nilmtk/nilmtk#466]
There are several options:
### 1) All NILM algorithms live in the NILMTK master branch

Advantages:
- Keeps all NILM algorithms in one place

Disadvantages:
- The number of dependencies for NILMTK will increase significantly (which makes life harder for users and for developers... more moving parts, more things to fail... everyone has to install the union of the set of dependencies across all NILM algorithms, even if some people don't want to use all NILM algorithms).  This issue is especially important for NILM algorithms with dependencies which require a license (e.g. in #465) - especially for commercial organisations who will need to _pay_ for licenses and hence would have to pay for these third party licenses just to use NILMTK.
- It pulls ownership of NILM algorithms from the original developers towards the NILMTK developers, which is probably bad for everyone: it might make original developers feel less able to contribute patches to their own algorithms; and it also increases work for the NILMTK core developers
### 2) Cutting edge NILM algorithms for NILMTK live in the original author's github repository and we host a NILMTK wiki page listing all compatible NILM algorithms

Advantages:
- Users and devs only have to install the NILM algorithms they require; hence only have to install the dependencies they require
- Each NILM algorithm author gets to maintain full control over their algorithm (although others are free to fork the algo, of course)

Disadvantages:
- To do this 'properly', each algorithm developer would have to do a little bit of additional work to make their algorithm installable (i.e. write a `setup.py` script).  But that's easy. And perhaps not strictly necessary
### 3) We create a nilmtk/algorithms repository specifically for storing individual algorithms

Advantages:
- Keeps all algorithms in one place
- Users only have to install the NILM algorithms (and hence dependencies) that they require

Disadvantages:
- Possibly combines all the disadvantages from options 1) and 2)!
### 4) All algorithms live in NILMTK's master branch (as per option 1) but, by default, our test suite wont test 'cutting edge' algorithms

This means that we can keep all NILM algorithms together in one place but users only need to install dependencies for the NILM algorithms they plan to use (because even though the code for all algorithms exists in the NILMTK repository, some of the NILM algorithms wont be tested be default)

This feels like a bad idea because, if we're being well-behaved, then we should really aim to have a test suite which tests pretty much all functions in the entire of NILMTK.

**Comment by JackKelly** [comment]
I think my vote would be for option 2 :)

What do you guys think?

**Comment by JackKelly** [comment]
I've just added a 4th option to the post above.

**Comment by nipunbatra** [comment]
I am in favour of option 4. We can probably have two variants of tests- one for regular users, and one for users who want to use all algorithms. I think packages such as Pandas provide some additional functionality (like using `xsel` for clipboard operations). I wonder how they manage extra optional dependencies.

**Comment by JackKelly** [comment]
Thanks for the reply.  I suppose one of my main concerns about keeping other people's algorithms in NILMTK is that it puts extra responsibility on us (the core developers) to maintain those algorithms.  We hardly have time to maintain the 'core' NILMTK code, let alone other peoples' algorithms.  What do you think about this issue?

**Comment by nipunbatra** [comment]
@JackKelly : I agree that maintenance would be a concern. But, I suppose the algorithm developer will own up? I believe scikit learn does adopt a strategy similar to 2.

**Comment by nipunbatra** [comment]
Hi @JackKelly, @oliparson 

I'd say that we go with option 2 for now- authors maintain their algos on their own accounts and we link them from wiki. It is expected that the algorithm author at the very least provide an example (IPython notebook) on a publicly available data set (REDD preferred) showing the usage of their algorithm.

It is also left to the author to provide detailed installation details. There are a lot of advanced algorithms which could not go in scikit-learn. These are maintained by individual authors, who follow the scikit-learn API. I think scikit-learn only allows papers having a large number of citations to be in their base package. 

A couple of examples of advanced algorithms which follows scikit-learn API, and are not yet in the main repo:

1. https://github.com/mblondel/lightning
2. https://gist.github.com/omangin/8801846

How does this sound @MingjunZhong? I'd be happy to help you to create an installable version of your algorithm which adheres to nilmtk API.

**Comment by JackKelly** [comment]
I agree @nipunbatra.  I think option 2 is my preference, at least for now.

**Comment by nipunbatra** [comment]
I had a word with @MingjunZhong. We felt that it is best that cutting-edge algos be kept in authors' repositories.

@MingjunZhong: Let's close the PR on LBM. Instead, can you please create a repository containing the same nilmtk formatted code for LBM and relaxed FHMM. We'll soon add a wiki to link to external algorithms. We'll also add a small notebook showing how to use your algorithms. Both your implementations are a big plus to the community! Really grateful! If not for Mosek licensing, we would very well like to use your FHMM implementation over the current one! I think that I might use your FHMM more than current nilmtk one.

@oliparson : I believe you implemented the maximum likelihood based NILM algorithm. Do we want to keep it as a nilmtk benchmark? If not, can you move it to another repo? We should link it up from our wiki.

@smakonin: Let's try and get your algo also to be fully nilmtk compatible. You should host it in a repo of your own. I think that NILM 2016 workshop might be the best time to get this done, unless, someone is willing to help us :)

Todos:

- [ ]  Create a wiki on nilmtk compatible algorithms- link Jack's NeuralNILM, Stephen's SparseNILM, Oli's Max. Likelihood, Mingjun's LBM and relaxed FHMM.
- [ ] Create a blog post on the evolution of the nilmtk ecosystem- data set curators, NILM researchers, NILM users (who want to use NILM's output, but not work on NILM). Some time in the future draft a journal paper.
- [ ] Put up some guidelines/template for algorithms contributors

@JackKelly, @oliparson : Please let me know if I've missed something. Or, if you have a different opinion.

**Comment by JackKelly** [comment]
sounds perfect :)

Just for reference, here's a link to the NILMTK wiki: https://github.com/nilmtk/nilmtk/wiki

**Comment by PMeira** [comment]
For future reference: https://github.com/nilmtk/nilmtk-contrib
