### ISSUE TITLE
Command '%matplotlib inline' returns an ImportError exception

### ISSUE THREAD

**Issue by brunomb91** [nilmtk/nilmtk#469]
Something's wrong when I type '%matplotlib inline':

In [1]: %matplotlib inline
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-2b1da000a957> in <module>()
----> 1 get_ipython().magic(u'matplotlib inline')

//anaconda/envs/nilmtk-env/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2334         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2335         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2336         return self.run_line_magic(magic_name, magic_arg_s)
   2337 
   2338     #-------------------------------------------------------------------------

//anaconda/envs/nilmtk-env/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2255                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2256             with self.builtin_trap:
-> 2257                 result = fn(*args,**kwargs)
   2258             return result
   2259 

//anaconda/envs/nilmtk-env/lib/python2.7/site-packages/IPython/core/magics/pylab.pyc in matplotlib(self, line)

//anaconda/envs/nilmtk-env/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, *a, **k: f(*a, **k)
    194 
    195         if callable(arg):

//anaconda/envs/nilmtk-env/lib/python2.7/site-packages/IPython/core/magics/pylab.pyc in matplotlib(self, line)
     98             print("Available matplotlib backends: %s" % backends_list)
     99         else:
--> 100             gui, backend = self.shell.enable_matplotlib(args.gui)
    101             self._show_matplotlib_backend(args.gui, backend)
    102 

//anaconda/envs/nilmtk-env/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in enable_matplotlib(self, gui)
   3130                 gui, backend = pt.find_gui_and_backend(self.pylab_gui_select)
   3131 
-> 3132         pt.activate_matplotlib(backend)
   3133         pt.configure_inline_support(self, backend)
   3134 

//anaconda/envs/nilmtk-env/lib/python2.7/site-packages/IPython/core/pylabtools.pyc in activate_matplotlib(backend)
    272     matplotlib.rcParams['backend'] = backend
    273 
--> 274     import matplotlib.pyplot
    275     matplotlib.pyplot.switch_backend(backend)
    276 

//anaconda/envs/nilmtk-env/lib/python2.7/site-packages/matplotlib/pyplot.py in <module>()
    112 
    113 from matplotlib.backends import pylab_setup
--> 114 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    115 
    116 _IP_REGISTERED = None

//anaconda/envs/nilmtk-env/lib/python2.7/site-packages/matplotlib/backends/__init__.pyc in pylab_setup()
     30     # imports. 0 means only perform absolute imports.
     31     backend_mod = __import__(backend_name,
---> 32                              globals(),locals(),[backend_name],0)
     33 
     34     # Things we pull in from all backends

ImportError: No module named ipykernel.pylab.backend_inline

**Comment by JackKelly** [comment]
Thank you for posting this issue.

However, this does not look like a NILMTK issue to me.  Please use the relevant IPython notebook documentation to resolve this issue.  My hunch is that IPython hasn't been installed correctly.

**Comment by jhyun0919** [comment]
I'm having the same error issue here.
I've tried uninstalled and install again iPython but it did not help.
Guess it's not just a simple problem concerned in installing python correctly.
Any other advice??

**Comment by nipunbatra** [comment]
This really isn't a nilmtk issue. I think you'll have to seek help from IPython community for this.
Otherwise, you could not use `%matplotlib inline` and do a `plt.show()` each time you make a plot.

**Comment by BrownUniversityArchitectureDug** [comment]
This may just be due to the fact that you aren't using a jupyter notebook @jhyun0919  and @brunomb91 if you are using ipython notebook or jupyter notebook you can have inline plots, but on ipython in the bash shell, use the line %matplotlib to activate automatic plots so you don't have to type plt.show() every time.

**Comment by rawwar** [comment]
try doing `pip install ipython jupyter`.

**Comment by yousefvand** [comment]
If you want to use [ipython](http://ipython.org/) without jupyter for drawing graphs, use ipython in the _pylab_ mode:

```
remisa@laptop:~> ipython
Python 3.8.1 (default, Dec 20 2019, 19:24:24) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.2 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %pylab

Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib

In [2]: x = randn(10000)

In [3]: hist(x, 100);
```

![Figure_1](https://user-images.githubusercontent.com/18329462/71444896-43edf780-272a-11ea-8629-687476f03fc1.png)

Reference: https://matplotlib.org/3.1.1/users/shell.html
