### ISSUE TITLE
Failed on 'nosetests'

### ISSUE THREAD

**Issue by bundit786** [nilmtk/nilmtk#473]
Hi,

  I have installed NILMTK up to the final step but to verify the installation with nosetests, it got fail as below
![image](https://cloud.githubusercontent.com/assets/7457132/12392151/6612680a-be1f-11e5-9e28-9d45ecf9b99d.png)
Please guide me how to fix this issue.
Thanks.

**Comment by nipunbatra** [comment]
@bundit786 : This is a long standing issue. But, none of us are likely to have time to solve this anytime soon. I'd suggest you to not worry about this and directly use nilmtk. I'll close this issue as a duplicate already exists.
