### ISSUE TITLE
ERROR: Failure: ImportError (No module named hmmlearn) during nilmtk installation

### ISSUE THREAD

**Issue by arif-irawan** [nilmtk/nilmtk#482]
I follow the instruction in "Experimental but probably easiest installation procedure for Unix or OSX" but after I run nosetests, the output like this:
   from hmmlearn import hmm
ImportError: No module named hmmlearn

======================================================================
ERROR: Failure: ImportError (No module named hmmlearn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/arif/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/arif/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/arif/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/arif/nilmtk/nilmtk/tests/test_fhmm.py", line 9, in <module>
    from nilmtk.disaggregate import FHMM
  File "/home/arif/nilmtk/nilmtk/disaggregate/__init__.py", line 3, in <module>
    from .fhmm_exact import FHMM
  File "/home/arif/nilmtk/nilmtk/disaggregate/fhmm_exact.py", line 10, in <module>
    from hmmlearn import hmm
ImportError: No module named hmmlearn

----------------------------------------------------------------------
Ran 44 tests in 14.623s

FAILED (errors=3)
Closing remaining open files:/home/arif/nilmtk/data/energy.h5...done

Please help me, would should I do?

**Comment by JackKelly** [comment]
Looks like hmmlearn failed to install.

were there any errors during installation?

What happens if you try running `pip install hmmlearn==0.1.1` and then re-running the NILMTK tests?

**Comment by arif-irawan** [comment]
yes, after installing dependencies, It can't find hmmlearn.

**Comment by JackKelly** [comment]
please provide more information to help us to help you.

did the command `pip install hmmlearn=0.1.1` succeed?  were there any warnings or errors?

what happens if you start ipython and type `import hmmlearn`?

**Comment by arif-irawan** [comment]
I run pip install hmmlearn==0.1.1 and success to run NILMTK tests. Thanks

**Comment by Zouhour03** [comment]
![image](https://user-images.githubusercontent.com/17108132/37768442-ed4c49ce-2dcd-11e8-896a-d4d8f3e4ffc1.png)
 how can i run nosetests and import nilmtk??
