### ISSUE TITLE
Error Disagregation using CO

### ISSUE THREAD

**Issue by arif-irawan** [nilmtk/nilmtk#486]
Hi,
I was going through the tutorials/documentation.In [https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/disaggregation_and_metrics.ipynb](url). After I finished disaggregation with CO, I execute this:

disag_filename = 'redd-disag-co.h5'
output = HDFDataStore(disag_filename, 'w')
co.disaggregate(test_elec.mains(), output, sample_period=60)
output.close()

But resulting index eror, This is the complete result after execution:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-21-36762a58a569> in <module>()
      2 output = HDFDataStore(disag_filename, 'w')
      3 # Note that we have mentioned to disaggregate after converting to a sample period of 60 seconds
----> 4 co.disaggregate(test_elec.mains(), output, sample_period=60)
      5 output.close()

/home/arif/nilmtk/nilmtk/disaggregate/combinatorial_optimisation.pyc in disaggregate(self, mains, output_datastore, vampire_power, **load_kwargs)
    146 
    147         load_kwargs.setdefault('sample_period', 60)
--> 148         load_kwargs.setdefault('sections', mains.good_sections())
    149 
    150         timeframes = []

/home/arif/nilmtk/nilmtk/metergroup.pyc in good_sections(self, **kwargs)
    903                      " return the intersection of the good sections for all"
    904                      " meters.  This will be fixed...")
--> 905             return self.meters[0].good_sections(**kwargs)
    906         else:
    907             return []

/home/arif/nilmtk/nilmtk/elecmeter.pyc in good_sections(self, **loader_kwargs)
    630         results_obj = GoodSections.results_class(self.device['max_sample_period'])
    631         return self._get_stat_from_cache_or_compute(
--> 632             nodes, results_obj, loader_kwargs)        
    633 
    634     def _get_stat_from_cache_or_compute(self, nodes, results_obj, loader_kwargs):

/home/arif/nilmtk/nilmtk/elecmeter.pyc in _get_stat_from_cache_or_compute(self, nodes, results_obj, loader_kwargs)
    684         if loader_kwargs.get('preprocessing') is None:
    685             cached_stat = self.get_cached_stat(key_for_cached_stat)
--> 686             results_obj.import_from_cache(cached_stat, sections)
    687 
    688             def find_sections_to_compute():

/home/arif/nilmtk/nilmtk/stats/goodsectionsresults.pyc in import_from_cache(self, cached_stat, sections)
    116                     timeframes = []
    117                     for _, row in sections_df.iterrows():
--> 118                         section_start = tz_localize_naive(row['section_start'], tz)
    119                         section_end = tz_localize_naive(row['section_end'], tz)
    120                         timeframes.append(TimeFrame(section_start, section_end))

/home/arif/anaconda2/lib/python2.7/site-packages/pandas/core/series.pyc in __getitem__(self, key)
    555     def __getitem__(self, key):
    556         try:
--> 557             result = self.index.get_value(self, key)
    558 
    559             if not np.isscalar(result):

/home/arif/anaconda2/lib/python2.7/site-packages/pandas/core/index.pyc in get_value(self, series, key)
   1778         s = getattr(series,'_values',None)
   1779         if isinstance(s, Index) and lib.isscalar(key):
-> 1780             return s[key]
   1781 
   1782         s = _values_from_object(series)

/home/arif/anaconda2/lib/python2.7/site-packages/pandas/tseries/base.pyc in __getitem__(self, key)
     98         getitem = self._data.__getitem__
     99         if np.isscalar(key):
--> 100             val = getitem(key)
    101             return self._box_func(val)
    102         else:

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

and this is my show version:
INSTALLED VERSIONS
------------------
commit: None
python: 2.7.11.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-77-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8

pandas: 0.17.1
nose: 1.3.7
pip: 8.0.2
setuptools: 19.6.2
Cython: 0.23.4
numpy: 1.10.4
scipy: 0.17.0
statsmodels: 0.6.1
IPython: 4.1.1
sphinx: 1.3.5
patsy: 0.4.0
dateutil: 2.4.1
pytz: 2015.7
blosc: None
bottleneck: 1.0.0
tables: 3.2.2
numexpr: 2.4.6
matplotlib: 1.5.1
openpyxl: 2.3.2
xlrd: 0.9.4
xlwt: 1.0.0
xlsxwriter: 0.8.4
lxml: 3.5.0
bs4: 4.4.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.11
pymysql: None
psycopg2: 2.6.1 (dt dec pq3 ext lo64)
Jinja2: None
None

Date: 2016-02-19 19:17:08.562307
Platform: Linux-3.13.0-77-generic-x86_64-with-debian-jessie-sid
System version: 2.7
nilmtk version: 0.2.0.dev-035fe79
nilm_metadata version: 0.2.0.dev-000207d
numpy version: 1.10.4
matplotlib version: 1.5.1
pandas version: 0.17.1
sklearn version: 0.17
hmmlearn version: 0.1.1

Is my installation correct, cause sometime resulting same error with FHMM. Thanks for your help

**Comment by nipunbatra** [comment]
I believe this is a mirror of #471 
Please do as stated in that issue. That should hopefully resolve. This is due to a small bug in Pandas. That bug is fixed now.

**Comment by arif-irawan** [comment]
work well after I downgrade panda to 16.2
thank you
