### ISSUE TITLE
resample kwarg is overwritten when passed to metergroup.dataframe_of_meters()

### ISSUE THREAD

**Issue by oliparson** [nilmtk/nilmtk#488]
When using `metergroup.dataframe_of_meters(resample=False)`, the function loads the `sample_period` kwarg from metadata, which is ultimately passed to `elecmeter.load()` and causes the `resample` kward to be overwritten:
```python
if 'sample_period' in kwargs:
    kwargs['resample'] = True
```
Should `elecmeter.load()` check if `resample` has been specified before overwriting it?

**Comment by JackKelly** [comment]
If `sample_period` is set by the user then it is appropriate to always set
`resample` to True, isn't it? Or have I missed something?

**Comment by JackKelly** [comment]
Oh, sorry, my bad! I see what you're saying. Yes, that sounds like a bug...
Yes, I agree, we should check if resample is False. Do you want to change
it or should I?

**Comment by oliparson** [comment]
I'm happy to have a go at it tomorrow. I might even submit a pull request if you're lucky ;)

**Comment by nipunbatra** [comment]
Can we close this issue now?

**Comment by JackKelly** [comment]
Yes, I think so.  @oliparson please re-open if necessary!
