### ISSUE TITLE
test fhmm correctness issue

### ISSUE THREAD

**Issue by shirantha27** [nilmtk/nilmtk#490]
# i have installed according to the given instructions in nilmtk site. i have wind 7 64 bit machine.

during the installation i had to install hmm through git bash
and also i had to install visual c++ 9 due to an error message i got during the installation. 

installation finished with this:
_______________________________________________________
HP@shirantha-PC MINGW64 /c/anaconda2
$ git clone https://github.com/nilmtk/nilmtk.git
Cloning into 'nilmtk'...

remote: Counting objects: 10666, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 10666 (delta 5), reused 0 (delta 0), pack-reused 10653
Receiving objects: 100% (10666/10666), 48.93 MiB | 681.00 KiB/s, done.
Resolving deltas: 100% (7622/7622), done.
Checking connectivity... done.

HP@shirantha-PC MINGW64 /c/anaconda2
$

HP@shirantha-PC MINGW64 /c/anaconda2
$ cd nilmtk

HP@shirantha-PC MINGW64 /c/anaconda2/nilmtk (master)
$ python setup.py develop
running develop
running egg_info
creating nilmtk.egg-info
writing nilmtk.egg-info\PKG-INFO
writing top-level names to nilmtk.egg-info\top_level.txt
writing dependency_links to nilmtk.egg-info\dependency_links.txt
writing manifest file 'nilmtk.egg-info\SOURCES.txt'
reading manifest file 'nilmtk.egg-info\SOURCES.txt'
writing manifest file 'nilmtk.egg-info\SOURCES.txt'
running build_ext
Creating c:\anaconda2\lib\site-packages\nilmtk.egg-link (link to .)
Adding nilmtk 0.2.0.dev-e104401 to easy-install.pth file

Installed c:\anaconda2\nilmtk
Processing dependencies for nilmtk===0.2.0.dev-e104401
Finished processing dependencies for nilmtk===0.2.0.dev-e104401
C:\Anaconda2\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools\dist.py:29                                                                                                                4: UserWarning: The version specified ('0.2.0.dev-e104401') is an invalid versio                                                                                                                n, this may not work as expected with newer versions of setuptools, pip, and PyP                                                                                                                I. Please see PEP 440 for more details.
__________________________________________________________

**# finally when i have tried the nilmtk - > nosetests following lengthy  thing came out with two errors**

C:\Anaconda2\lib\site-packages\IPython\terminal\ipapp.py:268: DeprecationWarning                                                                                                                : metadata {'config': True} was set from the constructor.  Metadata should be se                                                                                                                t using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
  file or command."""
.......................E....................Unlink of file 'data/energy.h5' fail                                                                                                                ed. Should I try again? (y/n) y
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) y
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) y
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) n
error: unable to unlink old 'data/energy.h5' (Invalid argument)
E
======================================================================
ERROR: test_fhmm_correctness (nilmtk.tests.test_fhmm.TestFHMM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\anaconda2\nilmtk\nilmtk\tests\test_fhmm.py", line 26, in test_fhmm_co                                                                                                                rrectness
    fhmm.train(elec)
  File "C:\anaconda2\nilmtk\nilmtk\disaggregate\fhmm_exact.py", line 283, in tra                                                                                                                in
    learnt_model[meter].fit([X])
  File "build\bdist.win-amd64\egg\hmmlearn\base.py", line 420, in fit
    X = check_array(X)
  File "C:\Anaconda2\lib\site-packages\sklearn\utils\validation.py", line 396, i                                                                                                                n check_array
    % (array.ndim, estimator_name))
ValueError: Found array with dim 3. Estimator expected <= 2.
-------------------- >> begin captured stdout << ---------------------
Training model for submeter 'ElecMeter(instance=2, building=1, dataset=None, app                                                                                                                liances=[])'

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: test suite for <module 'nilmtk' from 'C:\anaconda2\nilmtk\nilmtk\__init__                                                                                                                .py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\nose\suite.py", line 228, in run
    self.tearDown()
  File "C:\Anaconda2\lib\site-packages\nose\suite.py", line 351, in tearDown
    self.teardownContext(ancestor)
  File "C:\Anaconda2\lib\site-packages\nose\suite.py", line 367, in teardownCont                                                                                                                ext
    try_run(context, names)
  File "C:\Anaconda2\lib\site-packages\nose\util.py", line 471, in try_run
    return func()
  File "C:\anaconda2\nilmtk\nilmtk\__init__.py", line 29, in teardown_package
    output = subprocess.check_output(cmd, shell=True, cwd=data_dir())
  File "C:\Anaconda2\lib\subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'git checkout -- C:\anaconda2\nilmtk\data' returned                                                                                                                 non-zero exit status 255

----------------------------------------------------------------------
Ran 44 tests in 189.594s

FAILED (errors=2)
Closing remaining open files:C:\anaconda2\nilmtk\data\energy.h5...done

# can you help me to install the nilmtk properly

thank you very much 
shirantha welikala

**Comment by JackKelly** [comment]
Hi! Welcome to the NILMTK issue queue. Please tell us which version of
hmmlearn is installed on your system?

**Comment by JackKelly** [comment]
As a follow-up: I think you are experiencing two known issues:

The issue along the lines of "error: unable to unlink old 'data/energy.h5'" and  "CalledProcessError: Command 'git checkout -- C:\anaconda2\nilmtk\data' returned non-zero exit status 255" is issue #387.  Don't worry about it as it only affects the unit tests.

The "ValueError: Found array with dim 3. Estimator expected <= 2" error suggests that you don't have the correct version of hmmlearn installed.  Please see #467 for more details.

**Comment by shirantha27** [comment]
thanks for the quick reply jack.

i used " git clone https://github.com/hmmlearn/hmmlearn.git" and installed it using git bash . so i think it is the most latest version of hmmlearn.
 when i tried to run install all packages at once 


("[Anaconda2] C:\SPB_Data>conda install --yes pip numpy scipy six scikit-learn pan
das numexpr pytables dateutil matplotlib networkx hmmlearn
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Error: No packages found in current win-64 channels matching: hmmlearn

You can search for this package on anaconda.org with

    anaconda search -t conda hmmlearn
')

 thats why i seperately installed it.

thanks.

**Comment by shirantha27** [comment]
#  according to your instruction in the other thread i have installed hmmlearn 0.11 version

**now when i install the nilmtk again it gives:'**
**now when i install the nilmtk again it gives:'**

""
HP@shirantha-PC MINGW64 ~/nilmtk (master)
$ python setup.py develop
running develop
running egg_info
creating nilmtk.egg-info
writing nilmtk.egg-info\PKG-INFO
writing top-level names to nilmtk.egg-info\top_level.txt
writing dependency_links to nilmtk.egg-info\dependency_links.txt
writing manifest file 'nilmtk.egg-info\SOURCES.txt'
reading manifest file 'nilmtk.egg-info\SOURCES.txt'
writing manifest file 'nilmtk.egg-info\SOURCES.txt'
running build_ext
Creating c:\anaconda2\lib\site-packages\nilmtk.egg-link (link to .)
Adding nilmtk 0.2.0.dev-e104401 to easy-install.pth file

Installed c:\spb_data\nilmtk
Processing dependencies for nilmtk===0.2.0.dev-e104401
Finished processing dependencies for nilmtk===0.2.0.dev-e104401
C:\Anaconda2\lib\site-packages\setuptools-20.1.1-py2.7.egg\setuptools\dist.py:29                                                                                                                4: UserWarning: The version specified ('0.2.0.dev-e104401') is an invalid versio                                                                                                                n, this may not work as expected with newer versions of setuptools, pip, and PyP                                                                                                                I. Please see PEP 440 for more details.
""



**# When i ran the nose tests - **


Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) n\
Sorry, I did not understand your answer. Please type 'y' or 'n'
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) n
error: unable to unlink old 'data/energy.h5' (Invalid argument)
E
======================================================================
ERROR: test suite for <module 'nilmtk' from 'C:\SPB_Data\nilmtk\nilmtk\__init__.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\nose\suite.py", line 228, in run
    self.tearDown()
  File "C:\Anaconda2\lib\site-packages\nose\suite.py", line 351, in tearDown
    self.teardownContext(ancestor)
  File "C:\Anaconda2\lib\site-packages\nose\suite.py", line 367, in teardownContext
    try_run(context, names)
  File "C:\Anaconda2\lib\site-packages\nose\util.py", line 471, in try_run
    return func()
  File "C:\SPB_Data\nilmtk\nilmtk\__init__.py", line 29, in teardown_package
    output = subprocess.check_output(cmd, shell=True, cwd=data_dir())
  File "C:\Anaconda2\lib\subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'git checkout -- C:\SPB_Data\nilmtk\data' returned non-zero exit status 255

----------------------------------------------------------------------
Ran 44 tests in 92.419s

FAILED (errors=1)
Closing remaining open files:C:\SPB_Data\nilmtk\data\energy.h5...done


how to get rid of this 1 error. or is it ok to keep this error and proceed to try out the nilmtk? .

thank you very much for the assistance

**Comment by shirantha27** [comment]
i have followed the instructions found in https://github.com/nilmtk/nilmtk/issues/361
now nosetests runs fine. and i am searching a simple example to start using nilmtk. can you give a hint?

**Comment by nipunbatra** [comment]
See this: https://github.com/nilmtk/nilmtk/tree/master/docs/manual

I'll close the original issue now.
