### ISSUE TITLE
Installing the nilmtk package doesn't copy required yaml metadata files

### ISSUE THREAD

**Issue by tonicebrian** [nilmtk/nilmtk#491]
I was trying to create the H5 version of the Redd dataset and NILMTK failed because of some metadata missing. In order to reproduce it, just clone the repository and perform:

```
$ python setup.py install --user
```

You can then check that there is no folder called metadata in `$HOME/.local/lib/python2.7/site-packages/nilmtk-0.2.0.dev_e104401-py2.7.egg/nilmtk/dataset_converters/redd` and because of that this code:

```python
from nilmtk.dataset_converters import convert_redd
convert_redd('/home/cebrian/data/ReddData/low_freq', '/home/cebrian/data/ReddData/redd.h5')                                                                                                          
```

Fails with this stack trace:

```
Loading house 1... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 
Loading house 2... 1 2 3 4 5 6 7 8 9 10 11 
Loading house 3... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 
Loading house 4... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 
Loading house 5... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 
Loading house 6... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-4-0cb9eec147a1> in <module>()
----> 1 convert_redd('/home/cebrian/data/ReddData/low_freq', '/home/cebrian/data/ReddData/redd.h5')

/home/cebrian/.local/lib/python2.7/site-packages/nilmtk-0.2.0.dev_e104401-py2.7.egg/nilmtk/dataset_converters/redd/convert_redd.pyc in convert_redd(redd_path, output_filename, format)
     49                               'redd',
     50                               'metadata'),
---> 51                          store)
     52     store.close()
     53 

/home/cebrian/GIT/nilm_metadata/nilm_metadata/convert_yaml_to_hdf5.pyc in save_yaml_to_datastore(yaml_dir, store)
     71     """
     72 
---> 73     assert isdir(yaml_dir)
     74 
     75     # Load Dataset and MeterDevice metadata

AssertionError: 
```

It can be solved by issuing the following command from the GIT folder

```
for folder in `find nilmtk -name metadata`
do 
   cp --parents -r $folder /home/cebrian/.local/lib/python2.7/site-packages/nilmtk-0.2.0.dev_e104401-py2.7.egg/
done
```

but it would be useful if the `setup.py` could do it by itself.

With a bit of guidance I could create also a PR that solves this but I don't know anything about python-setuptools.

**Comment by nipunbatra** [comment]
Hi @tonicebrian,
Thanks for crafting the issue following all the guidelines! I believe the installation instructions suggest to install using `python setup.py develop`. Can you install `nilmtk` and `nilm-metadata` in `develop` mode and retry?

**Comment by tonicebrian** [comment]
Hi @nipunbatra , yep that solves the issue. I saw the `setup.py` and just jumped in without reading the docs. My fault :smile:

**Comment by nipunbatra** [comment]
Sometime in the future, we need to do the following:

1. Ensure that nilmtk works across Python 2 and 3
2. Make nilmtk conda and pip installable

At the moment, none of these are high priority to the core developers. PRs are more than welcome though!

pinging @JackKelly @oliparson

**Comment by oliparson** [comment]
Totally agree Nipun!
