### ISSUE TITLE
FHMM Multiple States?

### ISSUE THREAD

**Issue by eelionel** [nilmtk/nilmtk#492]
I am doing disaggregation on a dryer and I am having issues with the FHMM model assigning the wrong state for the dryer. I am training the model on the period from 2012-10-28 to 2015-06-01 on building 871 of the dataport dataset and attached is the notebook I am using. Is it because the dryer has three state and the FHMM model doesn’t handle appliances with multiple states well?

[notebook.zip](https://github.com/nilmtk/nilmtk/files/184706/notebook.zip)

**Comment by nipunbatra** [comment]
Can you please link your notebook somewhere (like nbviewer), so that we don't have to download and run locally?

**Comment by eelionel** [comment]
Here is the link to nbviewer:
http://nbviewer.jupyter.org/gist/eelionel/fbd3783515cf8673a91e

**Comment by nipunbatra** [comment]
To me the prediction looks fine. Since you're modelling the aggregate as an additive FHMM *only* on the dryer, the dryer will try to cover up as much as possible of the aggregate.
