### ISSUE TITLE
Disaggregation Algorithms

### ISSUE THREAD

**Issue by JeroenIoT** [nilmtk/nilmtk#494]
Hello,

I came across the NILMTK a couple of days ago. And before diving into the details I would like to understand which algorithms are currently supported and what is in the pipeline.

In the ACM e-Energy NILMTK paper the CO and FHMM are described in the context of benchmarking purposes. Do you have other algorithms in the pipeline (or on the wishlist :-)) for benchmarking?

Rgds,
Jeroen

**Comment by JackKelly** [comment]
Hi Jeroen,

Welcome to the NILMTK github issue queue :)   It was me who was replying to your tweets.

To answer your question, I have just started a wiki page with a list of NILM algorithms which work with NILMTK: https://github.com/nilmtk/nilmtk/wiki/NILM-Algorithms

@nipunbatra do you know of any other NILMTK-compatible algorithms that are just around the corner or are ready yet?

**Comment by nipunbatra** [comment]
I don't recall any other algorithms being close. I think that Stephen's [SparseNILM](https://github.com/smakonin/SparseNILM) algorithm are probably the closest, since it is written in Python and the code doesn't need to be rewritten for most parts.

**Comment by nipunbatra** [comment]
Also, must be noted that Mingjun's code also has approximate FHMM implementation.

**Comment by JeroenIoT** [comment]
Thanks Jack. The wiki page provides a good overview. 

I like your idea of being able to benchmark different NILM algorithms.Do you know if there are more "commonly known" algorithms which are worth to implement in NILMTK?

I will look into it and start to play with it in the coming days - I find your algorithm using deep learning (neural networks) very interesting.

**Comment by JackKelly** [comment]
> I will look into it and start to play with it in the coming days - I find your algorithm using deep learning (neural networks) very interesting.

I'm glad you like it.  I must mention though that my Neural NILM code is very immature and painful to use.  It's very definitely 'research code'!  Sorry!

**Comment by JeroenIoT** [comment]
> I'm glad you like it. I must mention though that my Neural NILM code is very immature and painful to use. It's very definitely 'research code'! Sorry!

Let's see ... I did some neural research a long time ago so it gives me the opportunity to refresh my know-how. From my pov neural network (cloud based) aggregation is the way forward (probably in combination with "traditional" algorithms and pre-processing)

**Comment by JackKelly** [comment]
> From my pov neural network (cloud based) aggregation is the way forward (probably in combination with "traditional" algorithms and pre-processing)

I agree :)

**Comment by JeroenIoT** [comment]
For the disaggreation algorithms you mentioned on wiki - is there also a "high scores" list (to trigger some kind of competition between people?)

**Comment by oliparson** [comment]
Nope, but it would be an awesome project if you fancy the challenge ;)

**Comment by JeroenIoT** [comment]
I like the challenge - not sure how many people would be interested to join ;-)

Different kind of technical challenges:
- Appliance identification (e.g. simple off-on and on-off transitions)
- Energy estimations per appliance
- ............

The score would be based on publically available appliance datasets (e.g. in case of neural network 20% of the dataset is used to test the algorithm and 80% is being used to train or design the algorithm).

**Comment by JackKelly** [comment]
Validation of NILM algorithms is a hot topic and if you can solve it then the community will be very thankful!  Some quite thoughts:

It's likely that a single metric will not be sufficient.  I think it might be useful to think in terms of 'use cases' for NILM and then come up with one or two sensible metrics per use case.  For example, if the use case is generating an itemised energy bill once per month then you don't care too much if the NILM algorithm gets the exact on/off timings correct but you do care if the NILM algorithm gets the total energy consumption correct.  On the other hand, if the use case is telling users which appliances are active, in real time, then you care about timings but maybe you don't care so much about energy consumption.

BTW, are you coming to the [NILM Workshop in Vancouver in May](http://nilmworkshop.org/2016/index.html)?

**Comment by JeroenIoT** [comment]
Hi Jack, agree that benchmarking must be done in categories (or use cases). Will need to have some thoughts about it / how to set it up and if I want to commit to set it up :)
Food for thoughts during my holiday next week ....

PS: No, not going to Vancouver ...
