### ISSUE TITLE
Problem with converting REDD

### ISSUE THREAD

**Issue by rmhalb** [nilmtk/nilmtk#496]
HI,

I am trying to convert REDD low freq files into h5 file ('convert_redd' command).
After load all houses it is collapse on the error of-
 File "C:\Anaconda2\lib\site-packages\nilm_metadata\file_management.py", line 45, in _path_to_directory
    assert isdir(path_to_directory)
AssertionError

( from your example it should print : Done converting YAML metadata to HDF5!
                                                          Done converting REDD to HDF5! )

I didn't do anything special, the command is as follow: 
     convert_redd('C:\REDD\low_freq', 'C:\REDD\redd_test.h5')

Please help,

Thanks,
Ram

**Comment by rmhalb** [comment]
Hi,

I changed     return _path_to_directory('central_metadata', 'appliance_types')
and it start to work.
some porblem with this link path in the code.

Makes sense?

**Comment by JackKelly** [comment]
Hmm, that shouldn't be necessary.  And that bit of code is quite well
tested. But well done for getting it to work on your system.

Is there any chance you could show us the full stack trace for the original
error, please?

Plea

**Comment by rmhalb** [comment]
Hi,

in C:\Anaconda2\lib\site-packages\nilm_metadata\file_management.py
there is the function -
def _get_appliance_types_directory():
    return _path_to_directory('..','central_metadata', 'appliance_types')

while I run the next script:
    from nilmtk.dataset_converters import convert_redd
    convert_redd('C:\\REDD\\low_freq', 'C:\\REDD\\redd_test_bug.h5')

I get the next trace:
File "C:\Anaconda2\lib\site-packages\nilm_metadata\file_management.py", line 45, in _path_to_directory
assert isdir(path_to_directory)
AssertionError


maybe the reason for this problem is bacause I insert 'central_metadata' folder into 'nilm_metadata' as subfolder instead of it to be in site-packages folder ?

Ram.

**Comment by JackKelly** [comment]
How did you install nilm_metadata?  Did you use

python setup.py develop

?

**Comment by rmhalb** [comment]
Hi,

Yes , I did use - python setup.py develop.

After TK was setup I paste the folder to Anaconda/Lib/site-packages

**Comment by nipunbatra** [comment]
Can you try using the following installation procedure for Windows: https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install.md#install-on-windows

**Comment by PMeira** [comment]
Closing this as it should work as expected right now. 

Also note that 
```python
convert_redd('C:\REDD\low_freq', 'C:\REDD\redd_test.h5')
```
is probably wrong. You'd need to escape the slashes or use raw strings:
```python
convert_redd('C:\\REDD\\low_freq', 'C:\\REDD\\redd_test.h5')
```
I usually use the forward slash when it's just a file path even on Windows. If you're passing the file path to a subprocess as a command argument, you may need to use backward slashes.
