### ISSUE TITLE
Problem installing Nilmtk and Nilm_metadata

### ISSUE THREAD

**Issue by Bergmam** [nilmtk/nilmtk#497]
I follow the guide for installing on Linux at https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install.md#install-on-ubuntu-like-linux-variants-debian-based-or-osx, but when I am trying to run 

`nosetests`

I get the following error:

```
======================================================================
ERROR: Failure: ImportError (No module named nilm_metadata)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bergman/.conda/envs/nilmtk-env/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/bergman/.conda/envs/nilmtk-env/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/bergman/.conda/envs/nilmtk-env/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/bergman/Documents/Master Thesis Work/nilmtk/nilmtk/__init__.py", line 8, in <module>
    from nilmtk.elecmeter import ElecMeter
  File "/home/bergman/Documents/Master Thesis Work/nilmtk/nilmtk/elecmeter.py", line 10, in <module>
    from .preprocessing import Clip
  File "/home/bergman/Documents/Master Thesis Work/nilmtk/nilmtk/preprocessing/__init__.py", line 1, in <module>
    from .clip import Clip
  File "/home/bergman/Documents/Master Thesis Work/nilmtk/nilmtk/preprocessing/clip.py", line 3, in <module>
    from ..node import Node
  File "/home/bergman/Documents/Master Thesis Work/nilmtk/nilmtk/node.py", line 2, in <module>
    from nilm_metadata import recursively_update_dict
ImportError: No module named nilm_metadata
```

What's going on? I follow the guide every step.

**Comment by JackKelly** [comment]
were there any errors during the installation process?

**Comment by Bergmam** [comment]
Not that I noticed.

**Comment by Bergmam** [comment]
None whatsoever.

**Comment by JackKelly** [comment]
and what happens if you run `import nilm_metadata` inside an IPython shell?

**Comment by Bergmam** [comment]
It complained that I did not have yaml for Python. I ran

`pip install pyyaml` outside the IPython shell, and now it does not tell me anything when running

`import nilm_metadata ` inside the IPython shell.
 
However, I am still getting the same error when running

`nosetests`

**Comment by JackKelly** [comment]
did you install nilm_metadata and pyyaml inside your nilmtk-env virtual environment?

**Comment by Bergmam** [comment]
Yes

**Comment by JackKelly** [comment]
Just to be sure, please can you try running `import nilm_metadata` in IPython inside your `nilmtk-env` virtual environment?

If `nilm_metadata` is definitely installed in the same virtual environment as NILMTK; and if you are definitely running `nosetests` inside that virtual environment, then I have no idea why `nosetests` can't find `nilm-metadata`.

**Comment by Bergmam** [comment]
Running `import nilm_metadata` in `/nilm_metadata` works without problem. 

Running it in `/nilmtk` does not, however, as I get an error 
`ImportError: No module named nilm_metadata`

I am always in the `nilmtk-env` environment.

**Comment by JackKelly** [comment]
Then `nilm_metadata` has not installed corrected in the `nilmtk-env` environment

**Comment by Bergmam** [comment]
How would I go about installing it correctly? 

Running `sudo python setup.py develop` in `/nilm_metadata` and `nilmtk-env` still gives:
`running develop
running egg_info
writing requirements to nilm_metadata.egg-info/requires.txt
writing nilm_metadata.egg-info/PKG-INFO
writing top-level names to nilm_metadata.egg-info/top_level.txt
writing dependency_links to nilm_metadata.egg-info/dependency_links.txt
writing requirements to nilm_metadata.egg-info/requires.txt
writing nilm_metadata.egg-info/PKG-INFO
writing top-level names to nilm_metadata.egg-info/top_level.txt
writing dependency_links to nilm_metadata.egg-info/dependency_links.txt
reading manifest file 'nilm_metadata.egg-info/SOURCES.txt'
writing manifest file 'nilm_metadata.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python2.7/dist-packages/nilm-metadata.egg-link (link to .)
nilm-metadata 0.2.0 is already the active version in easy-install.pth

Installed /home/bergman/Documents/Master Thesis Work/nilm_metadata
Processing dependencies for nilm-metadata==0.2.0
Searching for PyYAML==3.11
Best match: PyYAML 3.11
Processing PyYAML-3.11-py2.7-linux-x86_64.egg
PyYAML 3.11 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/PyYAML-3.11-py2.7-linux-x86_64.egg
Finished processing dependencies for nilm-metadata==0.2.0
`

But I still get the same problem when trying to run `nosetests` in `/nilmtk`

**Comment by JackKelly** [comment]
not sure, TBH.

Maybe try uninstalling it first (and then delete `/usr/local/lib/python2.7/dist-packages/nilm-metadata.*`).

Are you *absolutely* sure that `nilmtk-env` is **active** when you're installing `nilm_metadata`? :)

**Comment by Bergmam** [comment]
100%! (At least it says `(nilmtk-env)` after running `source activate nilmtk-env`

I'll try uninstalling and reinstalling :)

**Comment by Bergmam** [comment]
Not sure if I managed to remove it or not. Should not both `nilm_metadata` and `nilmtk` be shown when running `pip list` after running `python setup.py develop` in their respective folders? I don't know how I would remove them with pip otherwise.

**Comment by Bergmam** [comment]
Ok, I must have seriously messed something up. I now tried the other part of the guide, "Old installation procedure for Unix or OSX", and I get exactly the same problem. 

I can import `nilm_metadata `without problems in `/nilm_metadata`, but it can't seem to find the module in `/nilmtk`.

**Comment by JackKelly** [comment]
maybe try throwing away your `nilmtk-env` environment and starting again?!?  (or have you tried that already?)

**Comment by codingneo** [comment]
Facing the same issue when try to install nilmtk on my Mac

**Comment by outsiderOnion** [comment]
Hi,guy.
I get the same problem.When i run the sentence "from nilmtk import DataSet" ,"No module named nilm_metadata " appears.Do you resolve the problem  now?Can we talk about this?

**Comment by MartinNeighbours** [comment]
outsiderOnion as your comment is recent ...  I hope this is of some help - comment back if it solves the issue!

How did you install nilm_metadata?  If you did a GitHub clone - you'll get a directory structure like this:

nilm_metadata
    - nilm_meta_data

Which will probably explain why you are getting the error.

In the site_packages directory of your environment, you should end up with

nilm_metadata
nilm_metadata_0.2.2 py2.7.egg-info
nilmtk

Within nilm_metadata there should be no sub-directory nilm_metadata (i.e. it is the subdirectory in the clone).  I installed following the instructions on the site on Windows 10 and Mac - which I think is the best option.

**Comment by PMeira** [comment]
If you're not using the official `environment.yml` via conda (as described on https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install_user.md), you have to make sure all related dependencies at installed and they're compatible with the versions listed there. 

Note that you don't *need* to create a separate environment, it's just easier for newcomers and our own testing.

**Comment by AbidHussain70** [comment]
I fixed this problem by just removing the last "/" from the following line.
   git clone https://github.com/nilmtk/nilm_metadata/
like 
git clone https://github.com/nilmtk/nilm_metadata
