### ISSUE TITLE
ERROR: test_fhmm_correctness

### ISSUE THREAD

**Issue by saeedaghabozorgi** [nilmtk/nilmtk#498]
Hi, I have installed the package, but when I run the unit test nosetests it throws the following error:

======================================================================
ERROR: test_fhmm_correctness (nilmtk.tests.test_fhmm.TestFHMM)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Saeed/xxxx/nilmtk/nilmtk/tests/test_fhmm.py", line 26, in test_fhmm_correctness
    fhmm.train(elec)
  File "/Users/Saeed/xxxx/nilmtk/nilmtk/disaggregate/fhmm_exact.py", line 283, in train
    learnt_model[meter].fit([X])
  File "/Users/Saeed/.local/lib/python2.7/site-packages/hmmlearn/base.py", line 420, in fit
    X = check_array(X)
  File "/Users/Saeed/anaconda/envs/nilmtk-env/lib/python2.7/site-packages/sklearn/utils/validation.py", line 396, in check_array
    % (array.ndim, estimator_name))
ValueError: Found array with dim 3. Estimator expected <= 2.
-------------------- >> begin captured stdout << ---------------------
Training model for submeter 'ElecMeter(instance=2, building=1, dataset=None, appliances=[])'

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 43 tests in 12.287s

FAILED (errors=1)
Closing remaining open files:/Users/Saeed/xxxx/nilmtk/data/energy.h5...done

**Comment by JackKelly** [comment]
which version of hmmlearn did you install?

**Comment by saeedaghabozorgi** [comment]
thanks Jack for quick reply,

the installed hmmlearn is '0.2.0'

**Comment by JackKelly** [comment]
ah, yes, that's very likely to be the issue.  NILMTK needs hmmlearn v0.1.1

**Comment by saeedaghabozorgi** [comment]
oh, thanks. I will give a try again with v0.1.1

**Comment by saeedaghabozorgi** [comment]
Thanks Jack, hmmlearn v0.1.1 worked for me.

**Comment by JackKelly** [comment]
Great, thanks for the reply :)  Glad it worked.
