### ISSUE TITLE
Can't run the Installation setup

### ISSUE THREAD

**Issue by anushcbe** [nilmtk/nilmtk#500]
Was trying to install the file but it shows the error. while running the command python setup.py develop

/setuptools/dist.py:294: UserWarning: The version specified ('0.2.0.dev-8103b09') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.

what i have to look at to correct the error.

Thank you

**Comment by oliparson** [comment]
I think this is a warning rather than an error. Are you having any problems using the toolkit?

**Comment by anushcbe** [comment]
yes cant able to import nilmtk

**Comment by nipunbatra** [comment]
I'm afraid there's very little information you've currently provided us to help you out!

**Comment by anushcbe** [comment]
Following is the page am getting wile running the python setup.py delevop.



E:\PhD_Backup\nilmtk>python setup.py develop
C:\Anaconda2\lib\site-packages\setuptools-20.3-py2.7.egg\setuptools\dist.py:294:
 UserWarning: The version specified ('0.2.0.dev-8103b09') is an invalid version,
 this may not work as expected with newer versions of setuptools, pip, and PyPI.
 Please see PEP 440 for more details.
running develop
running egg_info
writing nilmtk.egg-info\PKG-INFO
writing top-level names to nilmtk.egg-info\top_level.txt
writing dependency_links to nilmtk.egg-info\dependency_links.txt
reading manifest file 'nilmtk.egg-info\SOURCES.txt'
writing manifest file 'nilmtk.egg-info\SOURCES.txt'
running build_ext
Creating c:\anaconda2\lib\site-packages\nilmtk.egg-link (link to .)
nilmtk 0.2.0.dev-8103b09 is already the active version in easy-install.pth

Installed e:\phd_backup\nilmtk
Processing dependencies for nilmtk===0.2.0.dev-8103b09
Finished processing dependencies for nilmtk===0.2.0.dev-8103b09

E:\PhD_Backup\nilmtk>


if am using the nilmtk-env


[nilmtk-env] E:\PhD_Backup\nilmtk>python setup.py develop
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\setuptools-20.7.0-py2.7.egg\setup
tools\dist.py:294: UserWarning: The version specified ('0.2.0.dev-8103b09') is a
n invalid version, this may not work as expected with newer versions of setuptoo
ls, pip, and PyPI. Please see PEP 440 for more details.
running develop
running egg_info
writing nilmtk.egg-info\PKG-INFO
writing top-level names to nilmtk.egg-info\top_level.txt
writing dependency_links to nilmtk.egg-info\dependency_links.txt
reading manifest file 'nilmtk.egg-info\SOURCES.txt'
writing manifest file 'nilmtk.egg-info\SOURCES.txt'
running build_ext
Creating c:\anaconda2\envs\nilmtk-env\lib\site-packages\nilmtk.egg-link (link to
 .)
nilmtk 0.2.0.dev-8103b09 is already the active version in easy-install.pth

Installed e:\phd_backup\nilmtk
Processing dependencies for nilmtk===0.2.0.dev-8103b09
Finished processing dependencies for nilmtk===0.2.0.dev-8103b09

[nilmtk-env] E:\PhD_Backup\nilmtk>



probelm is nilmk import wont work.  if i try to import

error

C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
242: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  debug = CBool(False, config=True)
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
256: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  """
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
259: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  help="Don't call post-execute functions that have failed in the past."
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
273: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  ipython_dir= Unicode('', config=True) # Set to get_ipython_dir() in __init__
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
289: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  """
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
294: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  """
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
300: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  """
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
303: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  config=True)
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
307: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  """
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
310: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  help="Save multi-line entries as one entry in readline history"
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
314: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  will be displayed as regular output instead."""
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
320: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  help="Deprecated, will be removed in IPython 5.0, use PromptManager.in_templat
e")
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
322: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  help="Deprecated, will be removed in IPython 5.0, use PromptManager.in2_templa
te")
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
324: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  help="Deprecated, will be removed in IPython 5.0, use PromptManager.out_templa
te")
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
326: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  help="Deprecated, will be removed in IPython 5.0, use PromptManager.justify")
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
349: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  help="Show rewritten input, e.g. for autocall."
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
352: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  quiet = CBool(False, config=True)
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
354: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  history_length = Integer(10000, config=True)
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
360: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  """
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
365: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  readline_use = CBool(True, config=True)
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
366: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  readline_remove_delims = Unicode('-/~', config=True)
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
383: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  ], config=True)
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
396: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  run interactively (displaying output from expressions).""")
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
400: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  separate_in = SeparateUnicode('\n', config=True)
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
401: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  separate_out = SeparateUnicode('', config=True)
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
402: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  separate_out2 = SeparateUnicode('', config=True)
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
403: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  wildcards_case_sensitive = CBool(True, config=True)
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\interactiveshell.py:
405: DeprecationWarning: metadata {'config': True} was set from the constructor.
  Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
 key2='value2')
  default_value='Context', config=True)
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\terminal\interactiveshell
.py:290: DeprecationWarning: metadata {'config': True} was set from the construc
tor.  Metadata should be set using the .tag() method, e.g., Int().tag(key1='valu
e1', key2='value2')
  help="auto editing of files with syntax errors.")
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\terminal\interactiveshell
.py:295: DeprecationWarning: metadata {'config': True} was set from the construc
tor.  Metadata should be set using the .tag() method, e.g., Int().tag(key1='valu
e1', key2='value2')
  you can force a direct exit without any confirmation.""",
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\terminal\interactiveshell
.py:305: DeprecationWarning: metadata {'config': True} was set from the construc
tor.  Metadata should be set using the .tag() method, e.g., Int().tag(key1='valu
e1', key2='value2')
  help="Set the editor used by IPython (default to $EDITOR/vi/notepad)."
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\terminal\interactiveshell
.py:308: DeprecationWarning: metadata {'config': True} was set from the construc
tor.  Metadata should be set using the .tag() method, e.g., Int().tag(key1='valu
e1', key2='value2')
  help="The shell program to be used for paging.")
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\terminal\interactiveshell
.py:320: DeprecationWarning: metadata {'config': True} was set from the construc
tor.  Metadata should be set using the .tag() method, e.g., Int().tag(key1='valu
e1', key2='value2')
  default.""",
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\terminal\interactiveshell
.py:323: DeprecationWarning: metadata {'config': True} was set from the construc
tor.  Metadata should be set using the .tag() method, e.g., Int().tag(key1='valu
e1', key2='value2')
  help="Enable auto setting the terminal title."
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\completer.py:276: De
precationWarning: metadata {'config': True} was set from the constructor.  Metad
ata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='
value2')
  """
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\completer.py:556: De
precationWarning: metadata {'config': True} was set from the constructor.  Metad
ata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='
value2')
  """
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\completer.py:568: De
precationWarning: metadata {'config': True} was set from the constructor.  Metad
ata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='
value2')
  """
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\completer.py:578: De
precationWarning: metadata {'config': True} was set from the constructor.  Metad
ata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='
value2')
  """
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\magics\script.py:89:
 DeprecationWarning: metadata {'config': True} was set from the constructor.  Me
tadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key
2='value2')
  """,
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\magics\script.py:116
: DeprecationWarning: metadata {'config': True} was set from the constructor.  M
etadata should be set using the .tag() method, e.g., Int().tag(key1='value1', ke
y2='value2')
  """
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\shellapp.py:139: Dep
recationWarning: metadata {'config': True} was set from the constructor.  Metada
ta should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='v
alue2')
  help="A list of dotted module names of IPython extensions to load."
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\shellapp.py:142: Dep
recationWarning: metadata {'config': True} was set from the constructor.  Metada
ta should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='v
alue2')
  help="dotted module name of an IPython extension to load."
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\shellapp.py:148: Dep
recationWarning: metadata {'config': True} was set from the constructor.  Metada
ta should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='v
alue2')
  help="Reraise exceptions encountered loading IPython extensions?",
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\shellapp.py:152: Dep
recationWarning: metadata {'config': False} was set from the constructor.  Metad
ata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='
value2')
  default_extensions = List(Unicode(), [u'storemagic'], config=False)
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\shellapp.py:156: Dep
recationWarning: metadata {'config': True} was set from the constructor.  Metada
ta should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='v
alue2')
  be hidden from tools like %who?"""
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\shellapp.py:160: Dep
recationWarning: metadata {'config': True} was set from the constructor.  Metada
ta should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='v
alue2')
  help="""List of files to run at IPython startup."""
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\shellapp.py:164: Dep
recationWarning: metadata {'config': True} was set from the constructor.  Metada
ta should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='v
alue2')
  variable at IPython startup."""
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\shellapp.py:167: Dep
recationWarning: metadata {'config': True} was set from the constructor.  Metada
ta should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='v
alue2')
  help="""A file to be run""")
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\shellapp.py:170: Dep
recationWarning: metadata {'config': True} was set from the constructor.  Metada
ta should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='v
alue2')
  help="""lines of code to run at IPython startup."""
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\shellapp.py:173: Dep
recationWarning: metadata {'config': True} was set from the constructor.  Metada
ta should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='v
alue2')
  help="Execute the given command string."
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\shellapp.py:176: Dep
recationWarning: metadata {'config': True} was set from the constructor.  Metada
ta should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='v
alue2')
  help="Run the module as a script."
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\shellapp.py:179: Dep
recationWarning: metadata {'config': True} was set from the constructor.  Metada
ta should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='v
alue2')
  help="Enable GUI event loop integration with any of {0}.".format(gui_keys)
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\shellapp.py:184: Dep
recationWarning: metadata {'config': True} was set from the constructor.  Metada
ta should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='v
alue2')
  the default matplotlib backend."""
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\shellapp.py:190: Dep
recationWarning: metadata {'config': True} was set from the constructor.  Metada
ta should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='v
alue2')
  """
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\core\shellapp.py:197: Dep
recationWarning: metadata {'config': True} was set from the constructor.  Metada
ta should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='v
alue2')
  """
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\extensions\storemagic.py:
80: DeprecationWarning: metadata {'config': True} was set from the constructor.
 Metadata should be set using the .tag() method, e.g., Int().tag(key1='value1',
key2='value2')
  """
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\terminal\ipapp.py:245: De
precationWarning: metadata {'config': True} was set from the constructor.  Metad
ata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='
value2')
  help="""Start IPython quickly by skipping the loading of config files."""
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\terminal\ipapp.py:252: De
precationWarning: metadata {'config': True} was set from the constructor.  Metad
ata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='
value2')
  help="Whether to display a banner upon starting IPython."
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\IPython\terminal\ipapp.py:260: De
precationWarning: metadata {'config': True} was set from the constructor.  Metad
ata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='
value2')
  file or command."""

**Comment by anushcbe** [comment]
Hope i have to edit the file to change the syntax or have to downgrade some tools or software to run this.

i have no idea which i one i have to.

Am running python 2.7 not python 3.x.

rest of the package i just installed using conda env create command. didn't install seperatly.

have tried to run in linux but no luck there too.

Thank you.

**Comment by JackKelly** [comment]
Hmm.  Both installation logs include the line `nilmtk 0.2.0.dev-8103b09 is already the active version in easy-install.pth` which suggests that NILMTK *is* installed.

> probelm is nilmk import wont work. if i try to import error

Please can you confirm that you are running `import nilmtk` from within Python (or IPython) from within your virtual environment?

Please can you show us the exact error?

**Comment by anushcbe** [comment]
In [1]: import nilm_metadata

In [2]: import nilmtk
C:\Anaconda2\envs\nilmtk-env\lib\site-packages\matplotlib\backends\qt_compat.py:
84: ImportWarning: Not importing directory 'C:\Anaconda2\envs\nilmtk-env\sip': m
issing __init__.py
  import sip

In [3]:



I have tried import nilmtk error pops up but nilm_metadata has complied correctly.

Thank you for helping me.

**Comment by JackKelly** [comment]
That looks like just  a warning.  What happens if you run "from
nilmtk.utils import show_versions(); show_versions()"

If that fails then please ensure that the Python package "sip" is installed
and try again.

**Comment by anushcbe** [comment]
Package installed in my system are their version correct?

[nilmtk-env] E:\Anush\2016-2017\PhD\nilm_metadata>conda list
# packages in environment at D:\Anaconda2\envs\nilmtk-env:
#
backports                 1.0                      py27_0
backports.shutil-get-terminal-size 1.0.0                     <pip
bottleneck                1.0.0               np110py27_0
bzip2                     1.0.6                     vc9_2  [vc9]
coverage                  4.0.3                    py27_0
coveralls                 1.1                       <pip>
cycler                    0.10.0                   py27_0
cython                    0.24                     py27_0
decorator                 4.0.9                    py27_0
docopt                    0.6.2                     <pip>
get_terminal_size         1.0.0                    py27_0
hdf5                      1.8.15.1                  vc9_4  [vc9]
hmmlearn                  0.1.1                     <pip>
ipython                   4.2.0                    py27_0
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py27_0
jpeg                      8d                        vc9_0  [vc9]
libpng                    1.6.17                    vc9_1  [vc9]
libtiff                   4.0.6                     vc9_1  [vc9]
matplotlib                1.5.1               np110py27_0
mkl                       11.3.1                        0
networkx                  1.11                     py27_0
nilm-metadata (e:\anush\2016-2017\phd\nilm_metadata) 0.2.0
pip>
nilmtk (e:\anush\2016-2017\phd\nilmtk) 0.2.0.dev 8103b09
nose                      1.3.7                    py27_0
numexpr                   2.5.2               np110py27_0
numpy                     1.10.4                   py27_0
openssl                   1.0.2h                    vc9_0  [vc9]
pandas                    0.18.1              np110py27_0
path.py                   8.2.1                    py27_0
pickleshare               0.5                      py27_0
pip                       8.1.1                    py27_1
psycopg2                  2.6.1                     <pip>
pyparsing                 2.1.1                    py27_0
pyqt                      4.11.4                   py27_5
pyreadline                2.1                      py27_0
pytables                  3.2.2               np110py27_2
python                    2.7.11                        4
python-dateutil           2.5.2                    py27_0
pytz                      2016.3                   py27_0
pyyaml                    3.11                      <pip>
qt                        4.8.7                     vc9_7  [vc9]
requests                  2.10.0                    <pip>
scikit-learn              0.17.1              np110py27_0
scipy                     0.17.0              np110py27_1
setuptools                20.7.0                   py27_0
simplegeneric             0.8.1                    py27_0
sip                       4.16.9                   py27_2
six                       1.10.0                   py27_0
tables                    3.2.2                     <pip>
tk                        8.5.18                    vc9_0  [vc9]
traitlets                 4.2.1                    py27_0
vs2008_runtime            9.00.30729.1                  0
vs2010_runtime            10.00.40219.1                 0
wheel                     0.29.0                   py27_0
zlib                      1.2.8                     vc9_2  [vc9]

**Comment by anushcbe** [comment]
Running a demo notebook 
![error on importing](https://cloud.githubusercontent.com/assets/922320/15171772/c7862c18-176e-11e6-965c-6c8af0483d9e.png)

cant able to run it. any other place i have to look at !

Tank you for your time.

**Comment by JackKelly** [comment]
Are you sure you are running IPython with your nilmtk-env active?

**Comment by anushcbe** [comment]
Horray! i got it running.

I uninstalled my conda and its package then followed you tutorial not am able to run the nilmtk file.

Sadly just now relaized i don't have to dataset or database to run the tool too sad. 

anyway thank you for your support. i belive i was running in wrong env in previous case & another issue was hmmlearn has to installed sperately since conda does not supporting installation form their server. Then psycopg2 (hope spell is correct) this has to be installed speratly using PIP command. 

Finally am able to run the tookkit 
thanks alot for your support.  

One more question but it's not correct thread to ask. how to get those 6 data bases ??? any link or should i ask the respective authors for the access!!

**Comment by JackKelly** [comment]
Glad it's working! I'll close this issue for now.

> One more question but it's not correct thread to ask. how to get those 6 data bases ??? any link or should i ask the respective authors for the access!!

Yeah, you mostly need to search the websites of the relevant datasets.  Most (if not all) datasets are available to download straight from the authors' websites.  Here are two datasets to get you started :)

* http://iawe.github.io/
* http://www.doc.ic.ac.uk/~dk3810/data/

**Comment by oliparson** [comment]
Also, I wrote a blog post which lists all the data sets I'm aware of:
http://blog.oliverparson.co.uk/2012/06/public-data-sets-for-nialm.html
