### ISSUE TITLE
Converter nilm_metadata.convert_yaml_to_hdf5 is  false

### ISSUE THREAD

**Issue by bluemin** [nilmtk/nilmtk#511]
@nipunbatra @JackKelly @tonicebrian @pilillo 

I follow the NILMTK documentation "if the dataset is already described in YAML using the NILM Metadata schema then just call nilm_metadata.convert_yaml_to_hdf5()". But this is false!
I created YAML dataset and then I call convert_yaml_to_hdf5(yaml_dir, hdfh5file). And I get the hdf5 file only with metadata and the file doesn't contain the recording data  meter{i}.csv . The method convert_yaml_to_hdf5  doesn't contain the commands for saving the raw data.     Furthermore my question:  what does a method save_yaml_to_hdf5 perform ? Probably it saves the raw data. What means the second parameter "store" of the save_yaml_to_hdf5(yaml_dir, store) ? 
Please clarify these questions. Thanks. Best regards.

**Comment by nipunbatra** [comment]
Please refer to existing converters. An easy example is the following:

https://github.com/nilmtk/nilmtk/tree/master/nilmtk/dataset_converters/refit

**Comment by JackKelly** [comment]
Please also see the NILM Metadata tutorial: http://nilm-metadata.readthedocs.io/en/latest/tutorial.html

`save_yaml_to_hdf5` doesn't touch the raw timeseries data.  Instead it imports your YAML metadata to your HDF5 file.

`save_yaml_to_hdf5` has documentation in the code: https://github.com/nilmtk/nilm_metadata/blob/master/nilm_metadata/convert_yaml_to_hdf5.py#L62
