### ISSUE TITLE
testing CO error:   KeyError: 'No object named ../building1/elec/meter2 in the file'

### ISSUE THREAD

**Issue by bluemin** [nilmtk/nilmtk#515]
@nipunbatra 
I am trying to test Combinatorial Optimisation with redd data and get the follow error:
## ERROR: test_co_correctness (**main**.TestCO)

Traceback (most recent call last):
  File "C:/algo-research/nilmtk-project/nilmtk/nilmtk/tests/test_combinatorial_optimisation.py", line 66, in test_co_correctness
    df1 = output.store.get('../building1/elec/meter{}'.format(meter))
  File "C:\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 627, in get
    raise KeyError('No object named %s in the file' % key)
## KeyError: 'No object named ../building1/elec/meter2 in the file'

Thanks for the help.

Regards
L.Belenki

**Comment by nipunbatra** [comment]
I am sorry I don't fully understand how you're using `test_CO` function on REDD data. The test function is supposed to be an internal test and works on simulated data.

**Comment by bluemin** [comment]
I have got this error running Combinatorial Optimization using the script _test_combinatorial_optimisation.py_ on REDD data. 
The disaggregation steps with sample_period =1 min are fine (I get a graph f-score) 
until I want to call the meter-part:
----------
for meter in range(2, 4):
    df1 = output.store.get('../building1/elec/meter{}'.format(meter))
    df2 = self.dataset.store.store.get(
        '/building1/elec/meter{}'.format(meter))
    self.assertEqual((df1 == df2).sum().values[0], len(df1.index))
    self.assertEqual(len(df1.index), len(df2.index))
output.close()
-----------------------
![disag-co2-redd_sample_1_min](https://cloud.githubusercontent.com/assets/20658513/17545758/d5e5449e-5ede-11e6-8cbe-74ab7913f202.png)

What I do false ?
Thanks for help.

**Comment by JackKelly** [comment]
like @nipunbatra says, those scripts are meant for use by the automated unit testing system :)
