### ISSUE TITLE
CO for BUILDING =2: AttributeError: Attribute 'metadata' does not exist in node:

### ISSUE THREAD

**Issue by bluemin** [nilmtk/nilmtk#516]
@nipunbatra  @JackKelly 
I try to test  the CO model by script test_combinatorial_optimisation.py  for BUILDING=2.
I get an error:

**\* ELEC:           MeterGroup(meters=
  ElecMeter(instance=1, building=2, dataset='REDD', site_meter, appliances=[])
  ElecMeter(instance=2, building=2, dataset='REDD', site_meter, appliances=[])
  ElecMeter(instance=3, building=2, dataset='REDD', appliances=[Appliance(type='sockets', instance=1)])
  ElecMeter(instance=4, building=2, dataset='REDD', appliances=[Appliance(type='light', instance=1)])
  ElecMeter(instance=5, building=2, dataset='REDD', appliances=[Appliance(type='electric stove', instance=1)])
  ElecMeter(instance=6, building=2, dataset='REDD', appliances=[Appliance(type='microwave', instance=1)])
  ElecMeter(instance=7, building=2, dataset='REDD', appliances=[Appliance(type='washer dryer', instance=1)])
  ElecMeter(instance=8, building=2, dataset='REDD', appliances=[Appliance(type='sockets', instance=2)])
  ElecMeter(instance=9, building=2, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])
  ElecMeter(instance=10, building=2, dataset='REDD', appliances=[Appliance(type='dish washer', instance=1)])
  ElecMeter(instance=11, building=2, dataset='REDD', appliances=[Appliance(type='waste disposal unit', instance=1)])
)
Training model for submeter 'ElecMeter(instance=3, building=2, dataset='REDD', appliances=[Appliance(type='sockets', instance=1)])'
Training model for submeter 'ElecMeter(instance=4, building=2, dataset='REDD', appliances=[Appliance(type='light', instance=1)])'
Training model for submeter 'ElecMeter(instance=5, building=2, dataset='REDD', appliances=[Appliance(type='electric stove', instance=1)])'
Training model for submeter 'ElecMeter(instance=6, building=2, dataset='REDD', appliances=[Appliance(type='microwave', instance=1)])'
Training model for submeter 'ElecMeter(instance=7, building=2, dataset='REDD', appliances=[Appliance(type='washer dryer', instance=1)])'
Training model for submeter 'ElecMeter(instance=8, building=2, dataset='REDD', appliances=[Appliance(type='sockets', instance=2)])'
Training model for submeter 'ElecMeter(instance=9, building=2, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])'
Training model for submeter 'ElecMeter(instance=10, building=2, dataset='REDD', appliances=[Appliance(type='dish washer', instance=1)])'
Training model for submeter 'ElecMeter(instance=11, building=2, dataset='REDD', appliances=[Appliance(type='waste disposal unit', instance=1)])'
Done training!
**\* MAINS:           MeterGroup(meters=
  ElecMeter(instance=1, building=2, dataset='REDD', site_meter, appliances=[])
  ElecMeter(instance=2, building=2, dataset='REDD', site_meter, appliances=[])
)
C:\NILMTK\nilmtk\nilmtk\metergroup.py:905: UserWarning: As a quick implementation we only get Good Sections from the first meter in the meter group.  We should really return the intersection of the good sections for all meters.  This will be fixed...
  warn("As a quick implementation we only get Good Sections from"
Loading data for meter ElecMeterID(instance=2, building=2, dataset='REDD')  
Done loading data all meters for this chunk.
Loading data for meter ElecMeterID(instance=2, building=2, dataset='REDD')  
Done loading data all meters for this chunk.
Loading data for meter ElecMeterID(instance=2, building=2, dataset='REDD')  
Done loading data all meters for this chunk.

Traceback (most recent call last):
  File "C:/algo-research/nilmtk-project/nilmtk/nilmtk/tests/test_combinatorial_optimisation.py", line 57, in test_co_correctness
    disag = DataSet(redd_disag_co)
  File "C:\NILMTK\nilmtk\nilmtk\dataset.py", line 44, in **init**
    self.import_metadata(get_datastore(filename, format))
  File "C:\NILMTK\nilmtk\nilmtk\dataset.py", line 53, in import_metadata
    self.metadata = store.load_metadata()
  File "C:\NILMTK\nilmtk\nilmtk\docinherit.py", line 46, in f
    return self.mthd(obj, _args, *_kwargs)
  File "C:\NILMTK\nilmtk\nilmtk\datastore\hdfdatastore.py", line 184, in load_metadata
    metadata = deepcopy(node._v_attrs.metadata)
  File "C:\Anaconda2\lib\site-packages\tables\attributeset.py", line 292, in __getattr__
    "'%s'" % (name, self._v__nodepath))
## **AttributeError: Attribute 'metadata' does not exist in node: '/'**

while the disaggregation for BUILDING =1 runs fine.

Thanks for your help.

**Comment by nipunbatra** [comment]
Do you still get the same error?

**Comment by PMeira** [comment]
Works fine now, closing issue.
