### ISSUE TITLE
How I identify the names of the appliances belonging to the same type?

### ISSUE THREAD

**Issue by bluemin** [nilmtk/nilmtk#517]
@JackKelly  I have two the questions:

- How I plot graphs of energy consumption over the course of a day (dependence on time of day) ?

- I am testing FHMM on data REDD via the script **test_redd.py**.  
  I plot the graphs, histograms for some types of the appliances, for a example, for "sockets" by   
  **train_elec['sockets'].plot().** 
But to a type "sockets" belonging four appliances: 7,8,15,16 (see attachment). What an appliance reproduces the graph respectively  histogram ? Is this random select?

How I identify the names of the appliances belonging to the same type?

Thanks
REgards

![apps_type_sockets_1_min_top_3](https://cloud.githubusercontent.com/assets/20658513/17560349/10ef90a6-5f22-11e6-876a-f2533160361d.png)
![apps_type_sockets_hist_1_min_top_3](https://cloud.githubusercontent.com/assets/20658513/17560389/2c03f9e0-5f22-11e6-86db-5f65631c78e7.png)

**Comment by JackKelly** [comment]
please use our [manual](https://github.com/nilmtk/nilmtk/tree/master/docs/manual) and [ipython notebooks](https://github.com/nilmtk/nilmtk/tree/master/notebooks) to learn how to use NILMTK.  Please don't use the `test_*.py` files to learn how to use NILMTK as those files are meant for the unit testing system.

**Comment by bluemin** [comment]
@JackKelly  Thank you very much. But how I identify the names of the appliances belonging to the same type by plotting?

**Comment by nipunbatra** [comment]
@bluemin : PS this notebook: https://github.com/nilmtk/nilmtk/blob/master/notebooks/BuildSys_2014_demo.ipynb

It shows how to choose appliances by type.
