### ISSUE TITLE
Timestamp Subtraction Problem

### ISSUE THREAD

**Issue by Bergmam** [nilmtk/nilmtk#521]
Hello,

I am trying to follow the guide at https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/disaggregation_and_metrics.ipynb but using my own data matched to look like the REDD data set. I encounter some issues when setting the window size as follows and trying to plot the data(my data spans 31 mar - 07 apr): 

```
train.set_window(end="2016-04-04 00:00:00")
test.set_window(start="2016-04-04 00:00:00")

train_elec = train.buildings[1].elec
test_elec = test.buildings[1].elec
train_elec.mains().plot()
```
And I get the error:
```

TypeError                                Traceback (most recent call last)
<ipython-input-29-6fb8d855af38> in <module>()
----> 1 train_elec.mains().plot()

/home/bergis/Downloads/NILMTK/nilmtk/nilmtk/electric.pyc in plot(self, ax, timeframe, plot_legend, unit, plot_kwargs, **kwargs)
    178 
    179         kwargs['sections'] = [timeframe]
--> 180         kwargs = self._set_sample_period(timeframe, **kwargs)
    181         power_series = self.power_series_all_data(**kwargs)
    182         if power_series is None or power_series.empty:

/home/bergis/Downloads/NILMTK/nilmtk/nilmtk/electric.pyc in _set_sample_period(self, timeframe, width, **kwargs)
    202     def _set_sample_period(self, timeframe, width=800, **kwargs):
    203         # Calculate the resolution for the x axis
--> 204         duration = timeframe.timedelta.total_seconds()
    205         secs_per_pixel = int(round(duration / width))
    206         kwargs.update({'sample_period': secs_per_pixel, 'resample': True})

/home/bergis/Downloads/NILMTK/nilmtk/nilmtk/timeframe.pyc in timedelta(self)
    126     def timedelta(self):
    127         if self.end and self.start:
--> 128             return self.end - self.start
    129         elif self.empty:
    130             return timedelta(0)

pandas/tslib.pyx in pandas.tslib._Timestamp.__sub__ (pandas/tslib.c:21031)()

TypeError: Timestamp subtraction must have the same timezones or no timezones

```

This is what my data looks like:
```
physical_quantity            power
type                      apparent
2016-03-31 02:35:21-04:00      5.5
2016-03-31 02:35:22-04:00      5.5
2016-03-31 02:35:23-04:00      5.5
2016-03-31 02:35:24-04:00      5.5
2016-03-31 02:35:25-04:00      5.5
```

etc

**Comment by oliparson** [comment]
Maybe try specifying a timezone for your start and end dates, e.g.
`train.set_window(end="2016-04-04 00:00:00-04:00")`

**Comment by Bergmam** [comment]
Trying to use 
`train.set_window(end="2016-04-04 00:00:00-04:00")`

Gives me this error:

```
TypeError                                Traceback (most recent call last)
<ipython-input-12-9e8ffe16b4f3> in <module>()
----> 1 train.set_window(end="2016-04-04 00:00:00-04:00")

/home/bergis/Downloads/NILMTK/nilmtk/nilmtk/dataset.pyc in set_window(self, start, end)
     83             raise RuntimeError("'timezone' is not set in dataset metadata.")
     84 
---> 85         self.store.window = TimeFrame(start, end, tz)
     86 
     87     def describe(self, **kwargs):

/home/bergis/Downloads/NILMTK/nilmtk/nilmtk/timeframe.pyc in __init__(self, start, end, tz)
     37                     self._start = self._start.tz_localize(tz)
     38                 if self._end:
---> 39                     self._end = self._end.tz_localize(tz)
     40 
     41     def copy_constructor(self, other):

pandas/tslib.pyx in pandas.tslib.Timestamp.tz_localize (pandas/tslib.c:12301)()

TypeError: Cannot localize tz-aware Timestamp, use tz_convert for conversions

```

**Comment by oliparson** [comment]
Did you try using `tz_convert` to convert to localize the Timestamp?

**Comment by Bergmam** [comment]
No, I have not. How exactly do you mean I should localize? Should I localize the timestamp where I want to cut the window or localize the values in my data set? Would you mind providing an example?

**Comment by oliparson** [comment]
If you're using `nilmtk/dataset_converters/redd/convert_redd.py` to load you're data in, you probably need to do something similar to lines 190 and 191 to ensure your timestamps can be compared.

**Comment by Bergmam** [comment]
So if I understand you correcly, I need to use `tz_convert` to create a timestamp in the proper timezone which I can then pass to `set_window`?

How would the DataFrame object look with only one timestamp? I am somewhat confused by this.

**Comment by oliparson** [comment]
Ah sorry, I've just had a closer look at the stacktrace in your second comment and it looks like the `TimeFrame` class  is trying to localize the timestamp with the timezone of the data set, so you were right not to specify a timezone with your start and end times.

Have you tried to execute the code using the actual REDD data set? This might help pinpoint the error to either your data or the nilmtk code.

**Comment by Bergmam** [comment]
Yeah I just tried the REDD data set and it has no problems at all. The window is scaled according to what I specify in `set_window` and there are no errors at all.

So where could I have done something wrong with my own data? From what I can see there are no large differences in either the actual data or the metadate files, but I have probably missed something.

**Comment by oliparson** [comment]
Okay that's encouraging. Are your timestamps in the raw CSV data specified as UTC unix timestamps? Also, did you edit the timezone in either the dataset.yaml metadata or line 44 of convert_redd.py? We probably shouldn't have the timezone specified in two different places and I know this has tripped me up before...

**Comment by Bergmam** [comment]
I apparently had changed to GMT timezone in dataset.yaml, so changing that back to US/Eastern just to test made it work again! 

So I guess I should be able to change line 44 in convert_redd.py to GMT and it should work that way as well?

**Comment by oliparson** [comment]
Ah great, glad we got to the bottom of it. Yeah those timezones need to match, as I think the converter determines the timezone of the data, while the yaml determines which timezone is used when you specify those start and end dates. To be honest, the converter should read the timezone from the in-memory metadata, so feel free to submit a pull request if you fancy it!

**Comment by Bergmam** [comment]
Thanks a lot :)
