### ISSUE TITLE
Minimum sample_period

### ISSUE THREAD

**Issue by kramerjul** [nilmtk/nilmtk#525]
Hi,

i'm currently working on my masterthesis and i'm really glad for finding NILMTK. This is awesome! I tried a few things and i think this toolkit will push my thesis alot.

Because i'm working on transient signal features i'm really interessted in reducing the sample_period < 1. Is this possible? i'll need at least 0.5s sample_period. Can i just adjust the metadata of the meterdevice?

Furthermore the opinion to add new measurements would be great. Is this possible?

**Comment by nipunbatra** [comment]
@JackKelly : this should be possible, right? To use data with more than 1 Hz frequency in NILMTK?

**Comment by JackKelly** [comment]
It should be possible to reduce the sample_period to less than 1; I'm not certain though I'm afraid.
