### ISSUE TITLE
NILMTK Nosetests issue - Importerror <No module named 'past'>

### ISSUE THREAD

**Issue by gokulshriyam** [nilmtk/nilmtk#529]
Plz help me .. While installing hmmlearn as it is mentioned in installation i'm getting some errors. Please help me to solve it...!!!

![hmmlearn1](https://cloud.githubusercontent.com/assets/13610905/20311368/8ee53836-ab75-11e6-9a13-59944b338926.jpg)
![hmmlearn2](https://cloud.githubusercontent.com/assets/13610905/20311374/95a0f3a4-ab75-11e6-9e4d-ff4d1e72f664.jpg)
![hmmlearn3](https://cloud.githubusercontent.com/assets/13610905/20311394/a8988be8-ab75-11e6-97a8-c522db28aae1.jpg)
![hmmlearn4](https://cloud.githubusercontent.com/assets/13610905/20311408/bac05846-ab75-11e6-88c9-92f3f16055d5.jpg)

**Comment by gokulshriyam** [comment]
HI, I had installed microsoft visual c++ setup tools and successfully installed hymmlearn.
After that i developed the setup.py and tried to run nosetests. But i'm getting following error. Please help me..!

![nosetests1](https://cloud.githubusercontent.com/assets/13610905/20318192/467ba14c-ab8f-11e6-9b87-5558d7a6824b.jpg)
![nosetests2](https://cloud.githubusercontent.com/assets/13610905/20318198/4f000f10-ab8f-11e6-8313-11d57b45c14d.jpg)

**Comment by JackKelly** [comment]
please run `pip install future`

**Comment by gokulshriyam** [comment]
Yeah thanks for the info, i have installed future and ran nosetests. But i'm not familiar whether this is the right output of it.. Please check the code...! Some error it saying..!

`(C:\Users\GoKuL\Anaconda3) C:\Users\GoKuL\nilmtk>nosetests
...................................F........Unlink of file 'data/energy.h5' fail
ed. Should I try again? (y/n) y
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) y
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) y
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) y
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) y
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) y
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) y
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) y
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) y
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) y
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) y
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) y
Unlink of file 'data/energy.h5' failed. Should I try again? (y/n) n
error: unable to unlink old 'data/energy.h5': Invalid argument
E
======================================================================
ERROR: test suite for <module 'nilmtk' from 'C:\\Users\\GoKuL\\nilmtk\\nilmtk\\_
_init__.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\GoKuL\Anaconda3\lib\site-packages\nose\suite.py", line 229, in
run
    self.tearDown()
  File "C:\Users\GoKuL\Anaconda3\lib\site-packages\nose\suite.py", line 352, in
tearDown
    self.teardownContext(ancestor)
  File "C:\Users\GoKuL\Anaconda3\lib\site-packages\nose\suite.py", line 368, in
teardownContext
    try_run(context, names)
  File "C:\Users\GoKuL\Anaconda3\lib\site-packages\nose\util.py", line 471, in t
ry_run
    return func()
  File "C:\Users\GoKuL\nilmtk\nilmtk\__init__.py", line 29, in teardown_package
    subprocess.check_output(cmd, shell=True, cwd=data_dir())
  File "C:\Users\GoKuL\Anaconda3\lib\subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "C:\Users\GoKuL\Anaconda3\lib\subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'git checkout -- C:\Users\GoKuL\nilmtk\da
ta' returned non-zero exit status 255

======================================================================
FAIL: test_wiring_graph (nilmtk.tests.test_metergroup.TestMeterGroup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\GoKuL\nilmtk\nilmtk\tests\test_metergroup.py", line 66, in test
_wiring_graph
    self.assertEqual(wiring_graph.nodes(), [meter2, meter3, meter1])
AssertionError: Lists differ: [ElecMeter(instance=3, building=1, dataset='REDD',
 appliances[144 chars]=[])] != [ElecMeter(instance=2, building=1, dataset='REDD'
, appliances[144 chars]=[])]

First differing element 0:
ElecMeter(instance=3, building=1, dataset='REDD', appliances=[])
ElecMeter(instance=2, building=1, dataset='REDD', appliances=[])

Diff is 652 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 44 tests in 202.811s

FAILED (errors=1, failures=1)
Closing remaining open files:C:\Users\GoKuL\nilmtk\data\energy.h5...done

(C:\Users\GoKuL\Anaconda3) C:\Users\GoKuL\nilmtk>`
