### ISSUE TITLE
Out of core, preprocessing and more stats error & Disaggregation Error

### ISSUE THREAD

**Issue by MuhammadAbdullahKhalid** [nilmtk/nilmtk#532]
Kindly help me. I am having following issues and errors:

# **Pre-processing errors:**
1)**# timeframes_from_periodindex** not found.

2) **nilmtk-env) C:\Users\Nuhammad\Desktop>python PreP. py :\Program Files\Anaconda2\envs\nilmtk-env\lib\site-packages\matplotlib\backends\qt_compat.py:84: ImportWarning: Not importing directory 'C:\Program Files\Anaconda2\envs\nilmtk-env\sip': missing init .py import sip :\windows\system32\nilmtk\nilmtk\stats\totalenergyresults.py:41: FutureWarning: convert_objects is deprecated. Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric. return self._data.fillna(0).convert_objects() :\windows\system32\nilmtk\nilmtk\stats\goodsectionsresults.py:145: FutureWarning: convert_objects is deprecated. Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric. return df. convert_objects() raceback (most recent call last): File "PreP.py", line 57, in <module> dropout_rate2.run() File "c:\windows\system32\nilmtk\nilmtk\node.py", line 43, in run for _ in self.process(): File "c:\windows\system32\nilmtk\nilmtk\stats\dropoutrate.py", line 16, in process metadata = self.upstream.get_metadata() File "c:\windows\system32\nilmtk\nilmtk\node.py", line 81, in get_metadata metadata = self. upstream.get_metadata() File "c:\windows\system32\nilmtk\nilmtk\node.py", line 76, in get_metadata results_dict = self.results.to_dict() File "c:\windows\system32\nilmtk\nilmtk\stats\dropoutrateresults.py-, line 39, in to_dict return (*statistics': {'dropout_rate': self.combined())) File "c:\windows\system32\nilmtk\nilmtk\stats\dropoutrateresults.py", line 24, in combined tot_samples = self._datarn_samplesi.sum() File "C:\Program Files\Anaconda2\envs\nilmtk-env\lib\site-packages\pandas\core\frame.py", line 2059, in __getitem return self._getitem_column(key) File "C:\Program Files\Anaconda2\envs\nilmtk-env\lib\site-packages\pandas\core\frame.py", line 2066, in _getitem_column return self._get_item_cache(key) File "C:\Program Files\Anaconda2\envs\nilmtk-env\lib\site-packages\pandas\core\generic.py", line 1386, in _get_item_cache values = self._data.get(item) File "C:\Program Files\Anaconda2\envs\nilmtk-env\lib\site-packages\pandas\core\internals.py", line 3541, in get loc = self.items.get_loc(item) File "C:\Program Files\Anaconda2\envs\nilmtk-env\lib\site-packages\pandas\indexes\base.py", line 2136, in get_loc return self._engine.get_loc(self._maybe_cast_indexer(key)) File "pandas\index.pyx", line 139, in pandas.index.IndexEngine.get_loc (pandas\index.c:4443) File "pandas\index.pyx", line 161, in pandas.index.IndexEngine.get_loc (pandas\index.c:4289) File "pandas\src\hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:13733) File "pandas\src\hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectNashTable.get_item (pandas\hashtable.c:13687) eyError: 'n samples' losing remaining open files:C:\Users\Nuhammad\Desktop\REDD\redd.h5...done** 
 

# **Disaggregation error**:
**Loading data for meter ElecMeterlD(instance=2, building=1, dataset='REDD') ••ne loading data all meters for this chunk. Loading data for meter ElecMeterlD(instance=2, building=1, dataset='REDD') ••ne loading data all meters for this chunk. 
traceback (most recent call last): File -MTrain.py-, line 60, in <module> fhmm.disaggregate(test_elec.mains(), output, sample_period=60) File "c:\windows\system32\nilmtk\nilmtk\disaggregate\fhmm_exact.py-, line 410, in disaggregate value=pd.DataFrame(chunk, columns=cols)) File -c:\windows\system32\nilmtk\nilmtk\docinherit.py-, line 46, in f return self.mthd(obj, •args, "kwargs) File -c:\windows\system32\nilmtk\nilmtk\datastore\hdfdatastore.py-, line 154, in append self. store. append(key=key, value=value) File "C:\Program Files\Anaconda2\envs\nilmtk-env\lib\site-packages\pandas\io\pytables.py-, line 970, in append "kwargs) File "C:\Program Files\Anaconda2\envs\nilmtk-env\lib\site-packages\pandas\io\pytables.py-, line 1315, in _write_to_group s.write(obj=value, append=append, complib=complib, "kwargs) File "C:\Program Files\Anaconda2\envs\nilmtk-env\lib\site-packages\pandas\io\pytables.py-, line 3853, in write "kwargs) File "C:\Program Files\Anaconda2\envs\nilmtk-env\lib\site-packages\pandas\io\pytables.py-, line 3542, in create_axes self. validate(existing_table) File "C:\Program Files\Anaconda2\envs\nilmtk-env\lib\site-packages\pandas\io\pytables.py-, line 2988, in validate -vs current table (%sr % (c, sax, oax)) alueError: invalid combinate of (values_axes] on appending data (name->values_block_0, cname->values_block_0,dtype->float64, kind->float, shape->(1, 1878)] vs current table (name->va/ues_b/ock_0,cname->va/ues_b/ock_0,dtype->f/ •at32,kind->float,shape->None] losing remaining open files:C:\Users\Muhammad\Desktop\REDD\fhmm.h5...doneC:\Users\Muhammad\Desktop\REDD\redd.h5...doneC:\Users\Muhammad\Desktop\REDD\redd.h5...done 
(nilmtk-env) C: \Users \Muhammad \Desktop> 
**

**Comment by nipunbatra** [comment]
Can you give a minimum working example to illustrate this behaviour?

**Comment by MuhammadAbdullahKhalid** [comment]
Well it works till the preprocessing step but during preprocessing it returns error as following:

**# timeframes_from_periodindex** not available in case of preprocessing and afterwards # **dropout_rate2.run()** is not working.

In disaggregation step **# fhmm.disaggregate(test_elec.mains(), output, sample_period=60)** returns error.

 The error in complete details are already mentioned above.

**Comment by MuhammadAbdullahKhalid** [comment]
Kindly Guide us

**Comment by MuhammadAbdullahKhalid** [comment]
![preprocessing](https://cloud.githubusercontent.com/assets/24221679/21743723/f21dc9da-d529-11e6-81c4-092443810d64.PNG)
![training](https://cloud.githubusercontent.com/assets/24221679/21743724/f2209426-d529-11e6-823c-4b04351b5d2c.PNG)

**Comment by nipunbatra** [comment]
I'm afraid, we still don't know what code you're running. These are just the error messages.

**Comment by MuhammadAbdullahKhalid** [comment]
For preprocessing we are using this code in the below link https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/pipeline_preprocessing_more_stats.ipynb  
For dissagregation we are using this code in the below link
https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/disaggregation_and_metrics.ipynb

**Comment by nipunbatra** [comment]
I have tried this code on OSX and Linux and it works perfect. The last time I used it on Windows, it worked fine. I wonder if there's some Pandas related bug on Windows causing this behaviour. If you have access to a Linux machine, I'd suggest giving it a try there and then reporting if you get the error or not.

**Comment by nipunbatra** [comment]
@MuhammadAbdullahKhalid 

Can you please reinstall nilmtk and try again. Please use the following instructions: https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install.md#install-on-windows

I was able to correctly use nilmtk following these instructions.

**Comment by nipunbatra** [comment]
@MuhammadAbdullahKhalid : Can you confirm if this worked?
