### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by iamharshit** [nilmtk/nilmtk#533]
In python shell when i first do `import nilmtk` then it shows a huge error message 
![image](https://cloud.githubusercontent.com/assets/15041829/21048713/b14c048a-be36-11e6-80fc-f250428b19e6.png)

but when i again write the same line `import nilmtk` then it imports it with no error.
![image](https://cloud.githubusercontent.com/assets/15041829/21048738/d07dd41e-be36-11e6-8302-30f79e5a4263.png)

what may be the problem?

**Comment by JackKelly** [comment]
Thanks for your interest in NILMTK.  I think those "error messages" aren't error messages. They are warnings. So you can ignore them.
