### ISSUE TITLE
using convert_redd() function

### ISSUE THREAD

**Issue by iamharshit** [nilmtk/nilmtk#534]
while getting the dataset eg REDD dataset using the convert_redd() function it shows error
![image](https://cloud.githubusercontent.com/assets/15041829/21048865/80eff87c-be37-11e6-81c9-ffbb0835963e.png)
what may be the possible problem?

**Comment by nipunbatra** [comment]
You don't have the REDD data set in /data/REDD. Please download it from the data set page and put it in /data/REDD. Or, change the path to where you have the data set downloaded.
