### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by Logistic11** [nilmtk/nilmtk#537]
I followed the installation procedure for Windows as mentioned in the nilmtk documentation.
But when I run in jupyter notebook, I get the following error:
ImportError: No module named electricity.building

![image](https://cloud.githubusercontent.com/assets/25018420/21793294/8aecf73a-d6b5-11e6-9c18-774eb18a8e3c.png)

from nilmtk.cross_validation import train_test_split
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-a8d9a301ec02> in <module>()
----> 1 from nilmtk.cross_validation import train_test_split

ImportError: No module named cross_validation

import nilmtk.preprocessing.electricity.building as prepb
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-0c186cba75d9> in <module>()
----> 1 import nilmtk.preprocessing.electricity.building as prepb

ImportError: No module named electricity.building

**Comment by Logistic11** [comment]
@JackKelly @nipunbatra @tonicebrian @oliparson @pilillo  please tell me why

**Comment by nipunbatra** [comment]
You're referring to older documentation.

PS- https://github.com/nilmtk/nilmtk/tree/master/docs/manual

**Comment by Logistic11** [comment]
Hi @nipunbatra   could you tell me how to deal with this module?
![image](https://cloud.githubusercontent.com/assets/25018420/22162710/5fc596c6-df15-11e6-9ce3-d5b6ed8d4d15.png)

**Comment by nipunbatra** [comment]
As I said before, you're running older documentation. Please see:  https://github.com/nilmtk/nilmtk/tree/master/docs/manual

**Comment by Logistic11** [comment]
@nipunbatra but it's still in the IPython notebook demos.

**Comment by nipunbatra** [comment]
We apologise. 
@JackKelly : Can we remove the [2014 NILM workshop demo](https://github.com/nilmtk/nilmtk/blob/master/notebooks/NILM_Workshop_2014_demo.ipynb) as it uses the older version of nilmtk?
