### ISSUE TITLE
convert_redd error

### ISSUE THREAD

**Issue by Logistic11** [nilmtk/nilmtk#538]
I don't know how to deal with the problem?
please help.
![image](https://cloud.githubusercontent.com/assets/25018420/21818375/318b3e2c-d72d-11e6-97fe-d10718a4dff2.png)
![image](https://cloud.githubusercontent.com/assets/25018420/21818392/420550b2-d72d-11e6-8593-f08a27d6a9cc.png)
![image](https://cloud.githubusercontent.com/assets/25018420/21818397/4883b190-d72d-11e6-8758-feb3606f2765.png)

**Comment by JackKelly** [comment]
Please see the documentation for `convert_redd`: http://nilmtk.github.io/nilmtk/master/nilmtk.dataset_converters.redd.html#module-nilmtk.dataset_converters.redd.convert_redd

**Comment by Logistic11** [comment]
@JackKelly  I saw it, but  I still do not know where is the error.

**Comment by Logistic11** [comment]
![image](https://cloud.githubusercontent.com/assets/25018420/21820501/87f76a1c-d735-11e6-86a4-65bfe6541508.png)
![image](https://cloud.githubusercontent.com/assets/25018420/21820516/93ece57c-d735-11e6-89ac-2fcdfd07461b.png)

BUT, the data exists here.
![image](https://cloud.githubusercontent.com/assets/25018420/21820562/ca627ebe-d735-11e6-9e66-637be98f60bc.png)

**Comment by Logistic11** [comment]
Then I run these code:
![image](https://cloud.githubusercontent.com/assets/25018420/21821272/8d335808-d738-11e6-9684-19d8810712ac.png)
![image](https://cloud.githubusercontent.com/assets/25018420/21821284/97cfa744-d738-11e6-8bd7-cb19d3723956.png)
![image](https://cloud.githubusercontent.com/assets/25018420/21821302/a774c436-d738-11e6-82e5-8c997747189d.png)
![image](https://cloud.githubusercontent.com/assets/25018420/21821318/b4e76664-d738-11e6-99d6-a3c10efedc43.png)
 
I really do not know what to do.

**Comment by JackKelly** [comment]
are you using [the REDD dataset](http://redd.csail.mit.edu/)?

**Comment by Logistic11** [comment]
@JackKelly  No, I do not have the username and password, could you send it to me. email: lyan11@hawk.iit.edu thanks.

**Comment by nipunbatra** [comment]
I'm afraid you will have to find the username and password on your own by referring to the instructions on the dataset website. I'm closing this issue now.

**Comment by Logistic11** [comment]
but how can I convert this dataset?

**Comment by nipunbatra** [comment]
Please see: https://github.com/nilmtk/nilmtk/blob/master/docs/manual/development_guide/writing_a_dataset_converter.md
