### ISSUE TITLE
AttributeError: Attribute 'metadata' does not exist in node: '/'

### ISSUE THREAD

**Issue by qingshuimonk** [nilmtk/nilmtk#540]
Hi, I'm trying to run FHMM on my dataset. It's just a subset of REDD, I manually divide them into 10 folds and training them on different sampling rates.
So my code is like:

    train = DataSet(join(in_data_dir, 'train', 'REDD_%d.h5' % foldNum))
    train_elec = train.buildings[building_num].elec
    fhmm = fhmm_exact.FHMM()

    fhmm.train(train_elec, sample_period=Rate, resample=True)

    print('Disaggregating...')
    disag_filename = join(out_data_dir, 'disag_fhmm' + infoStr + 'fold' + str(foldNum) + '.h5')
    output = HDFDataStore(disag_filename, 'w')
    fhmm.disaggregate(test_elec.mains(), output, sample_period=Rate, resample=True)
    output.close()
    disag = DataSet(disag_filename)
    disag_elec = disag.buildings[building_num].elec

And I got the error message:
` Traceback (most recent call last):
   File "/home/lab/Research/generalPackages/nilm/dukeNilm/]tasks/2017.01.02.hbh.RefactorCodes/runFHMM_REDD.py", line 41, in <module>
    disag = DataSet(disag_filename)
  File "/home/lab/Research/ttmp/NilmBH/SandBox/nilmtk/nilmtk/dataset.py", line 46, in __init__
    self.import_metadata(get_datastore(filename, format))
  File "/home/lab/Research/ttmp/NilmBH/SandBox/nilmtk/nilmtk/dataset.py", line 55, in import_metadata
    self.metadata = store.load_metadata()
  File "/home/lab/Research/ttmp/NilmBH/SandBox/nilmtk/nilmtk/docinherit.py", line 46, in f
    return self.mthd(obj, *args, **kwargs)
  File "/home/lab/Research/ttmp/NilmBH/SandBox/nilmtk/nilmtk/datastore/hdfdatastore.py", line 176, in load_metadata
    metadata = deepcopy(node._v_attrs.metadata)
  File "/home/lab/Research/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/tables/attributeset.py", line 291, in __getattr__
    "'%s'" % (name, self._v__nodepath))
AttributeError: Attribute 'metadata' does not exist in node: '/'`
I tried different sampling rates from 6s to 15min. And this error message only occurs in some folds when sampling rate goes high (like 10min or 15min). 

I took a look at #340 #373  and #452 , but it seems like we are not having the same problem. I suspect it's because when sampling rates goes high, I do not have enough data for training?

**Comment by nipunbatra** [comment]
On the fold you get an error, can you check the following:

```python
df = test_elec.mains().load(sample_period=Rate).next()
print df.head()
print df.describe()
```

This will give the first chunk dataframe that will be disaggregated.

```python
fhmm.disaggregate_chunk(df)
```

**Comment by qingshuimonk** [comment]
Hi, thanks for your reply. I tired at sample rate of 900s and it gives me this:

>   data = data.resample(**resample_kwargs)
physical_quantity            power
type                      apparent
2011-04-16 01:00:00-04:00      NaN
2011-04-16 01:15:00-04:00    124.0
2011-04-16 01:30:00-04:00      7.0
2011-04-16 01:45:00-04:00    830.0
2011-04-16 02:00:00-04:00      8.0
physical_quantity        power
type                  apparent
count               186.000000
mean                111.274193
std                 227.723297
min                   6.000000
25%                   8.000000
50%                   9.000000
75%                 124.000000
max                1434.000000

**Comment by nipunbatra** [comment]
I think what you need to test is that when you get the error, for that particular setting, run 

```python
df = test_elec.mains().load(sample_period=Rate).next()
print df.head()
print df.describe()

fhmm.disaggregate_chunk(df)
```

**Comment by qingshuimonk** [comment]
This is the code I use:
~~~~
    print('Training Model...')
    train = DataSet(join(in_data_dir, 'train', 'REDD_%d.h5' % foldNum))
    train_elec = train.buildings[building_num].elec
    fhmm = fhmm_exact.FHMM()
    fhmm.train(train_elec, sample_period=Rate, resample=True)

    test = DataSet(join(in_data_dir, 'test', 'REDD_%d.h5' % foldNum))
    test_elec = test.buildings[building_num].elec
    df = test_elec.mains().load(sample_period=Rate).next()
    print df.head()
    print df.describe()
    print('Disaggregating...')
    disag_filename = join(out_data_dir, 'disag_fhmm' + infoStr + 'fold' + str(foldNum) + '.h5')
    output = HDFDataStore(disag_filename, 'w')
    fhmm.disaggregate(test_elec.mains(), output, sample_period=Rate, resample=True)
~~~~
And this is what I got:
~~~~
Training Model...
/home/lab/Research/ttmp/NilmBH/SandBox/nilmtk/nilmtk/utils.py:390: FutureWarning: fill_method is deprecated to .resample()
the new syntax is .resample(...).ffill(limit=1)
  data = data.resample(**resample_kwargs)
Training model for submeter 'ElecMeter(instance=7, building=3, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])'
Training model for submeter 'ElecMeter(instance=9, building=3, dataset='REDD', appliances=[Appliance(type='dish washer', instance=1)])'
Training model for submeter 'ElecMeter(instance=10, building=3, dataset='REDD', appliances=[Appliance(type='electric furnace', instance=1)])'
Training model for submeter 'ElecMeter(instance=13, building=3, dataset='REDD', appliances=[Appliance(type='washer dryer', instance=1)])'
Training model for submeter 'ElecMeter(instance=16, building=3, dataset='REDD', appliances=[Appliance(type='microwave', instance=1)])'
Training model for submeter 'ElecMeter(instance=20, building=3, dataset='REDD', appliances=[Appliance(type='unknown', instance=1)])'
physical_quantity            power
type                      apparent
2011-04-16 01:00:00-04:00      NaN
2011-04-16 01:15:00-04:00    124.0
2011-04-16 01:30:00-04:00      7.0
2011-04-16 01:45:00-04:00    830.0
2011-04-16 02:00:00-04:00      8.0
physical_quantity        power
type                  apparent
count               186.000000
mean                111.274193
std                 227.723297
min                   6.000000
25%                   8.000000
50%                   9.000000
75%                 124.000000
max                1434.000000
Disaggregating...
Traceback (most recent call last):
  File "/home/lab/Research/generalPackages/nilm/dukeNilm/]tasks/2017.01.02.hbh.RefactorCodes/runFHMM_REDD.py", line 67, in <module>
    disag = DataSet(disag_filename)
  File "/home/lab/Research/ttmp/NilmBH/SandBox/nilmtk/nilmtk/dataset.py", line 46, in __init__
    self.import_metadata(get_datastore(filename, format))
  File "/home/lab/Research/ttmp/NilmBH/SandBox/nilmtk/nilmtk/dataset.py", line 55, in import_metadata
    self.metadata = store.load_metadata()
  File "/home/lab/Research/ttmp/NilmBH/SandBox/nilmtk/nilmtk/docinherit.py", line 46, in f
    return self.mthd(obj, *args, **kwargs)
  File "/home/lab/Research/ttmp/NilmBH/SandBox/nilmtk/nilmtk/datastore/hdfdatastore.py", line 176, in load_metadata
    metadata = deepcopy(node._v_attrs.metadata)
  File "/home/lab/Research/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/tables/attributeset.py", line 291, in __getattr__
    "'%s'" % (name, self._v__nodepath))
AttributeError: Attribute 'metadata' does not exist in node: '/'

~~~~

**Comment by nipunbatra** [comment]
I wonder if there's some issue with the same HDFStore being opened multiple times. 
Can you try

```python
import time
disag_filename =str(time.time())+'.h5'
```

keeping everything else the same.

**Comment by qingshuimonk** [comment]
It's still not working, here are the codes I'm running now:
~~~~
    print('Training Model...')
    train = DataSet(join(in_data_dir, 'train', 'REDD_%d.h5' % foldNum))
    train_elec = train.buildings[building_num].elec
    fhmm = fhmm_exact.FHMM()
    fhmm.train(train_elec, sample_period=Rate, resample=True)

    test = DataSet(join(in_data_dir, 'test', 'REDD_%d.h5' % foldNum))
    test_elec = test.buildings[building_num].elec
    df = test_elec.mains().load(sample_period=Rate).next()
    print df.head()
    print df.describe()
    print('Disaggregating...')
    # disag_filename = join(out_data_dir, 'disag_fhmm' + infoStr + 'fold' + str(foldNum) + '.h5')
    import time
    disag_filename = str(time.time()) + '.h5'
    output = HDFDataStore(disag_filename, 'w')
    fhmm.disaggregate(test_elec.mains(), output, sample_period=Rate, resample=True)

    output.close()
    disag = DataSet(disag_filename)
    disag_elec = disag.buildings[building_num].elec
~~~~
And I get the same error message:
~~~~
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
----------Testing on fold 1 in 900s----------
Training Model...
/home/lab/Research/ttmp/NilmBH/SandBox/nilmtk/nilmtk/utils.py:390: FutureWarning: fill_method is deprecated to .resample()
the new syntax is .resample(...).ffill(limit=1)
  data = data.resample(**resample_kwargs)
Training model for submeter 'ElecMeter(instance=7, building=3, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])'
Training model for submeter 'ElecMeter(instance=9, building=3, dataset='REDD', appliances=[Appliance(type='dish washer', instance=1)])'
Training model for submeter 'ElecMeter(instance=10, building=3, dataset='REDD', appliances=[Appliance(type='electric furnace', instance=1)])'
Training model for submeter 'ElecMeter(instance=13, building=3, dataset='REDD', appliances=[Appliance(type='washer dryer', instance=1)])'
Training model for submeter 'ElecMeter(instance=16, building=3, dataset='REDD', appliances=[Appliance(type='microwave', instance=1)])'
Training model for submeter 'ElecMeter(instance=20, building=3, dataset='REDD', appliances=[Appliance(type='unknown', instance=1)])'
physical_quantity            power
type                      apparent
2011-04-16 01:00:00-04:00      NaN
2011-04-16 01:15:00-04:00    124.0
2011-04-16 01:30:00-04:00      7.0
2011-04-16 01:45:00-04:00    830.0
2011-04-16 02:00:00-04:00      8.0
physical_quantity        power
type                  apparent
count               186.000000
mean                111.274193
std                 227.723297
min                   6.000000
25%                   8.000000
50%                   9.000000
75%                 124.000000
max                1434.000000
Disaggregating...
Traceback (most recent call last):
  File "/home/lab/Research/generalPackages/nilm/dukeNilm/]tasks/2017.01.02.hbh.RefactorCodes/runFHMM_REDD.py", line 69, in <module>
    disag = DataSet(disag_filename)
  File "/home/lab/Research/ttmp/NilmBH/SandBox/nilmtk/nilmtk/dataset.py", line 46, in __init__
    self.import_metadata(get_datastore(filename, format))
  File "/home/lab/Research/ttmp/NilmBH/SandBox/nilmtk/nilmtk/dataset.py", line 55, in import_metadata
    self.metadata = store.load_metadata()
  File "/home/lab/Research/ttmp/NilmBH/SandBox/nilmtk/nilmtk/docinherit.py", line 46, in f
    return self.mthd(obj, *args, **kwargs)
  File "/home/lab/Research/ttmp/NilmBH/SandBox/nilmtk/nilmtk/datastore/hdfdatastore.py", line 176, in load_metadata
    metadata = deepcopy(node._v_attrs.metadata)
  File "/home/lab/Research/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/tables/attributeset.py", line 291, in __getattr__
    "'%s'" % (name, self._v__nodepath))
AttributeError: Attribute 'metadata' does not exist in node: '/'

~~~~

**Comment by nipunbatra** [comment]
This is strange! Do you notice any difference in the output for the folds that work fine and the one that doesn't? That might be the key to tracing this bug!

**Comment by nipunbatra** [comment]
Also, if you can help us reproduce this bug!

**Comment by qingshuimonk** [comment]
The output files are just empty, I can't find the difference.
I've uploaded the files in google drive, you can access them via https://drive.google.com/drive/folders/0B9lODqEVz5crRHlQN3RPaUt1SUk?usp=sharing
Thanks for your help!

**Comment by nipunbatra** [comment]
Does the error come on fold#1? That way I don't have to download the entire dataset? Can you please upload the minimum data that I need to use to test the bug?

**Comment by qingshuimonk** [comment]
Sorry, I should've been more specific.
Yes, the error come on fold 1. So you just need to train on 'REDD_1.h5' in 'train' folder and test on 'REDD_1.h5' in test folder. The error occurs when I resample in 900s.

**Comment by nipunbatra** [comment]
I am able to reproduce the bug. While I am debugging, can you meanwhile use the following code:

```python

fhmm.disaggregate_chunk(test_elec.mains().load(sample_period=Rate).next())
```

This will return a disaggregated DF.

**Comment by qingshuimonk** [comment]
Great, thanks! Looking forward to hearing back : )

**Comment by nipunbatra** [comment]
Ok. I think I have some idea. The data is highly discontiguous. The contiguous data has very few samples, like of length 10, 20.. In nilmtk, we only process chunks of length 100 or more. 
I think it may be okay to just use 
`fhmm.disaggregate_chunk(test_elec.mains().load(sample_period=Rate).next())` for now.

**Comment by nipunbatra** [comment]
I'd suggest using the following notebook as an example code:
https://github.com/nilmtk/nilmtk/blob/master/notebooks/issues/546.ipynb
