### ISSUE TITLE
 ImportError: cannot import name REDD

### ISSUE THREAD

**Issue by WittmannF** [nilmtk/nilmtk#541]
I am trying to learn how to use the NILMTK using the following example: https://github.com/nilmtk/nilmtk/blob/master/notebooks/NILM_Workshop_2014_demo.ipynb

When I try to run the code:
```
from nilmtk.dataset import REDD

redd = REDD()
redd.load('/data/REDD/low_freq/')

# Note increase in system memory usage.
# NILMTK v0.2 does not eagerly load data like v0.1 does.
```

I get the following error:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-466fea3f9aa0> in <module>()
----> 1 from nilmtk.dataset import REDD
      2 
      3 redd = REDD()
      4 redd.load('/data/REDD/low_freq/')
      5 

ImportError: cannot import name REDD
```

**Comment by nipunbatra** [comment]
Is nilmtk correctly installed?

**Comment by WittmannF** [comment]
It was missing to run the first line of the example. However, I got other errors when trying to run it. It seems that the module `from nilmtk.disaggregate.co_1d import CO_1d` is not present on NILMTK anymore, or it was updated to `combinatorial_optimization`. 

I changed to another guide to learn the NILMTK (https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/data.ipynb). Everything is working fine no far.

**Comment by manojm18** [comment]
I am having the same error
```python
C:\Users\MANOJ\Anaconda2\lib\site-packages\ipykernel\__main__.py:8: ImportWarning: Not importing directory 'C:\Users\MANOJ\Anaconda2\lib\site-packages\nilmtk': missing __init__.py
C:\Users\MANOJ\Anaconda2\lib\site-packages\nilmtk\nilmtk\node.py:3: ImportWarning: Not importing directory 'C:\Users\MANOJ\Anaconda2\lib\site-packages\nilm_metadata': missing __init__.py
  from nilm_metadata import recursively_update_dict
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-3b5d66eae323> in <module>()
      6 import calendar
      7 
----> 8 from nilmtk.disaggregate.co_1d import CO_1d
      9 from nilmtk.cross_validation import train_test_split
     10 import nilmtk.preprocessing.electricity.building as prepb

ImportError: No module named co_1d
```

the module ```python nilmtk.disaggregate.co_1d import CO_1``` is not found in the NILMTK directory

**Comment by manojm18** [comment]
Also 
nilmtk.cross_validation import train_test_split,
nilmtk.preprocessing.electricity.building as prepb
nilmtk.stats.electricity.building as bstats
 nilmtk.stats.electricity.single as sstats
nilmtk.dataset import DataSet
nilmtk.dataset import REDD
nilmtk.plots import plot_series
nilmtk.sensors.electricity import Measurement
 nilmtk.metrics

seem to be missing from the NILMTK folder.... i have installed NILMTK as per instructions on [page](https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install.md#install-on-windows)

**Comment by nipunbatra** [comment]
@manojm18 : I'd suggest you reinstall, or, rather repeat the NILMTK install procedure.

**Comment by manojm18** [comment]
Thank you @nipunbatra  
Reinstalling solved the issue.
Also I have tried successfully to disaggregate a building data from Pecan Dataport. However, i am required to convert the disaggregated data into csv format to use for other purpose. how can it be done ?
is there a way of converting into pandas dataframe and then write to CSV ?
I tried to follow the instruction in issue [424](https://github.com/nilmtk/nilmtk/issues/424) to get a pandas dataframe.
```Python
disag_filename = join(data_dir, 'pecan_6636_July-disag.h5')
output = HDFDataStore(disag_filename, 'w')
co.disaggregate(elec.mains(), output)
output.close()

disag = DataSet(disag_filename)
disag_elec = disag.buildings[building_number].elec
disag_elec.plot()
plt.xlabel("Time")
disag.store.close()


disag = DataSet(disag_filename)
disag_elec = disag.buildings[building_number].elec
disag_elec.power_series_all_data()
```

the following error shows up for the last line of the code
```Python
Loading data for meter ElecMeterID(instance=1, building=1, dataset='CO')     Traceback (most recent call last):

  File "<ipython-input-73-04e89fe68912>", line 1, in <module>
    disag_elec.power_series().next()

  File "c:\users\manoj\nilmtk\nilmtk\electric.py", line 629, in load_series
    for chunk in generator:

  File "c:\users\manoj\nilmtk\nilmtk\metergroup.py", line 686, in load
    index, columns, self.meters, kwargs)

  File "c:\users\manoj\nilmtk\nilmtk\metergroup.py", line 1774, in combine_chunks_from_generators
    physical_quantities = chunk_from_next_meter.columns.get_level_values('physical_quantity')

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\pandas\core\index.py", line 4567, in get_level_values
    num = self._get_level_number(level)

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\pandas\core\index.py", line 4422, in _get_level_number
    raise KeyError('Level %s not found' % str(level))

KeyError: 'Level physical_quantity not found'```

**Comment by nipunbatra** [comment]
I am increasingly pushing to minimise the use of HDFStore for storing the output. Please see https://github.com/nilmtk/nilmtk/blob/master/notebooks/issues/546.ipynb

This notebook directly outputs the predicted dataframe. So, there should be less hassles.

**Comment by manojm18** [comment]
@nipunbatra  Thanks a lot. 
I was able to generate pandas dataframe.
However the codes in [546](https://github.com/nilmtk/nilmtk/blob/master/notebooks/issues/546.ipynb) works ( diaggreagtes) for PECAN dataport only if i use FHMM but not with CO. any particular reason ?

**Comment by nipunbatra** [comment]
@manojm18 Please open a new issue with the minimum code to reproduce the error.

**Comment by Zouhour03** [comment]
![image](https://user-images.githubusercontent.com/17108132/37901643-2b6daa3c-30f2-11e8-94a4-0137b50e7993.png)
I have this problem

**Comment by nipunbatra** [comment]
@Zouhour03 : I don't know which version of documentation you're using. This seems to be from a very old version. Please see: https://github.com/nilmtk/nilmtk/tree/master/docs/manual for the latest version.

Also, please can you open the issues in pertinent threads only?

**Comment by Shibumi497** [comment]
> @manojm18 : I'd suggest you reinstall, or, rather repeat the NILMTK install procedure.

Hi
I reinstalled, and I still have the same problem : 
![Screenshot 2020-02-26 at 17 35 18](https://user-images.githubusercontent.com/60926736/75365996-5cab9280-58be-11ea-8f1b-ce307cdfce40.png)
 thank you in advance
