### ISSUE TITLE
 I cannot import timeframes_from_periodindex

### ISSUE THREAD

**Issue by lyan11** [nilmtk/nilmtk#543]
![image](https://cloud.githubusercontent.com/assets/23707810/22700600/d22c8e7c-ed20-11e6-840e-06d8f732cc0f.png)
how to deal with this problem?

**Comment by nipunbatra** [comment]
What code/documentation are you referring? I don't think you need to use timeframe internals for general disaggregation.

**Comment by lyan11** [comment]
I never use it, but I saw it in the demo you have given.  I want to run it, but it doesn't work. You know, it appear one in the out of core, preprocessing and more stats in the user guide.

**Comment by nipunbatra** [comment]
Does from `nilmtk import *` work for you?

**Comment by lyan11** [comment]
@nipunbatra  Yes, it works well

**Comment by lyan11** [comment]
@nipunbatra  Can I print all the dataset?

**Comment by nipunbatra** [comment]
Thanks. That was some old code. I have removed it from the documentation.

**Comment by nipunbatra** [comment]
>Can I print all the dataset? 
What do you mean by that? I'd suggest skimming though the documentation to check if your query is already resolved there.

**Comment by lyan11** [comment]
Now I have redd dataset, I want to have a look at how it looks like, like the dataframe or series in pandas.like this one:
![image](https://cloud.githubusercontent.com/assets/23707810/22703812/1c09988c-ed2b-11e6-80d3-205afe5c5a65.png)

**Comment by lyan11** [comment]
one more question, When i run this code, 
![image](https://cloud.githubusercontent.com/assets/23707810/22704164/53a0cf26-ed2c-11e6-9e68-520f5d9c299a.png)
It shows this:
![image](https://cloud.githubusercontent.com/assets/23707810/22704189/6b1f1cd4-ed2c-11e6-85de-4528b0d6613f.png)
![image](https://cloud.githubusercontent.com/assets/23707810/22704197/734ebc84-ed2c-11e6-8a31-6a8f413c0058.png)
 what's wrong?

**Comment by nipunbatra** [comment]
Please push separate issues in separate threads. Also, please search other threads for similar problems. This particular issue has been solved before.

**Comment by lyan11** [comment]
ok
 thanks
