### ISSUE TITLE
Disaggregation errors with REFIT dataset when using CO

### ISSUE THREAD

**Issue by bczhao1991** [nilmtk/nilmtk#545]
Hi,

I am using nilmtk for obtaining benchmarks. The dataset I choose is REFIT dataset, downloaded from: https://pure.strath.ac.uk/portal/en/datasets/refit-electrical-load-measurements(31da3ece-f902-4e95-a093-e0a9536983c4).html. The original data file is called 'REFITPowerData111215.7z'. I have converted the csv files to h5 files using:

```
from nilmtk.dataset_converters import convert_refit
convert_refit('data/REFIT/', 'data/REFIT/refit.h5')
```
and the size of 'refit.h5' is 7.76GB. Then I test CO as following:

```
Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

from __future__ import print_function, division
import time
from matplotlib import rcParams
import matplotlib.pyplot as plt
# matplotlib inline
rcParams['figure.figsize'] = (13, 6)
plt.style.use('ggplot')

from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
from nilmtk.disaggregate import CombinatorialOptimisation


train = DataSet('data/REFIT/refit.h5')
test = DataSet('data/REFIT/refit.h5')


building = 2

train.set_window("10-7-2014","10-14-2014")
test.set_window("9-30-2014","26-10-2014")


train_elec = train.buildings[2].elec
test_elec = test.buildings[2].elec


mains = train_elec.mains()
mains_df = mains.load().next()
mains_df.head()
top_9_train_elec = train_elec.submeters().select_top_k(k=9)

9/9 ElecMeter(instance=10, building=2, dataset='REFIT', appliances=[Appliance(type='fan', instance=1)])])e=1)]))])

co = CombinatorialOptimisation()

co.train(top_9_train_elec, sample_period=8)
Training model for submeter 'ElecMeter(instance=8, building=2, dataset='REFIT', appliances=[Appliance(type='audio system', instance=1)])'
Training model for submeter 'ElecMeter(instance=7, building=2, dataset='REFIT', appliances=[Appliance(type='toaster', instance=1)])'
Training model for submeter 'ElecMeter(instance=4, building=2, dataset='REFIT', appliances=[Appliance(type='dish washer', instance=1)])'
Training model for submeter 'ElecMeter(instance=2, building=2, dataset='REFIT', appliances=[Appliance(type='fridge freezer', instance=1)])'
Training model for submeter 'ElecMeter(instance=9, building=2, dataset='REFIT', appliances=[Appliance(type='kettle', instance=1)])'
Training model for submeter 'ElecMeter(instance=5, building=2, dataset='REFIT', appliances=[Appliance(type='television', instance=1)])'
Training model for submeter 'ElecMeter(instance=10, building=2, dataset='REFIT', appliances=[Appliance(type='fan', instance=1)])'
Training model for submeter 'ElecMeter(instance=6, building=2, dataset='REFIT', appliances=[Appliance(type='microwave', instance=1)])'
Training model for submeter 'ElecMeter(instance=3, building=2, dataset='REFIT', appliances=[Appliance(type='washing machine', instance=1)])'
Done training!

disag_filename = 'data/REFIT/refit-disag-coh2.h5'

output = HDFDataStore(disag_filename, 'w')

co.disaggregate(test_elec.mains(), output, sample_period=8)
Including vampire_power = 84.0 watts to model...
Estimating power demand for 'ElecMeter(instance=8, building=2, dataset='REFIT', appliances=[Appliance(type='audio system', instance=1)])'
Estimating power demand for 'ElecMeter(instance=7, building=2, dataset='REFIT', appliances=[Appliance(type='toaster', instance=1)])'
Estimating power demand for 'ElecMeter(instance=4, building=2, dataset='REFIT', appliances=[Appliance(type='dish washer', instance=1)])'
Estimating power demand for 'ElecMeter(instance=2, building=2, dataset='REFIT', appliances=[Appliance(type='fridge freezer', instance=1)])'
Estimating power demand for 'ElecMeter(instance=9, building=2, dataset='REFIT', appliances=[Appliance(type='kettle', instance=1)])'
Estimating power demand for 'ElecMeter(instance=5, building=2, dataset='REFIT', appliances=[Appliance(type='television', instance=1)])'
Estimating power demand for 'ElecMeter(instance=10, building=2, dataset='REFIT', appliances=[Appliance(type='fan', instance=1)])'
Estimating power demand for 'ElecMeter(instance=6, building=2, dataset='REFIT', appliances=[Appliance(type='microwave', instance=1)])'
Estimating power demand for 'ElecMeter(instance=3, building=2, dataset='REFIT', appliances=[Appliance(type='washing machine', instance=1)])'
Including vampire_power = 80.0 watts to model...
Estimating power demand for 'ElecMeter(instance=8, building=2, dataset='REFIT', appliances=[Appliance(type='audio system', instance=1)])'
Estimating power demand for 'ElecMeter(instance=7, building=2, dataset='REFIT', appliances=[Appliance(type='toaster', instance=1)])'
Estimating power demand for 'ElecMeter(instance=4, building=2, dataset='REFIT', appliances=[Appliance(type='dish washer', instance=1)])'
Estimating power demand for 'ElecMeter(instance=2, building=2, dataset='REFIT', appliances=[Appliance(type='fridge freezer', instance=1)])'
Estimating power demand for 'ElecMeter(instance=9, building=2, dataset='REFIT', appliances=[Appliance(type='kettle', instance=1)])'
Estimating power demand for 'ElecMeter(instance=5, building=2, dataset='REFIT', appliances=[Appliance(type='television', instance=1)])'
Estimating power demand for 'ElecMeter(instance=10, building=2, dataset='REFIT', appliances=[Appliance(type='fan', instance=1)])'
Estimating power demand for 'ElecMeter(instance=6, building=2, dataset='REFIT', appliances=[Appliance(type='microwave', instance=1)])'
Estimating power demand for 'ElecMeter(instance=3, building=2, dataset='REFIT', appliances=[Appliance(type='washing machine', instance=1)])'
Including vampire_power = 41.0 watts to model...
Estimating power demand for 'ElecMeter(instance=8, building=2, dataset='REFIT', appliances=[Appliance(type='audio system', instance=1)])'
Estimating power demand for 'ElecMeter(instance=7, building=2, dataset='REFIT', appliances=[Appliance(type='toaster', instance=1)])'
Estimating power demand for 'ElecMeter(instance=4, building=2, dataset='REFIT', appliances=[Appliance(type='dish washer', instance=1)])'
Estimating power demand for 'ElecMeter(instance=2, building=2, dataset='REFIT', appliances=[Appliance(type='fridge freezer', instance=1)])'
Estimating power demand for 'ElecMeter(instance=9, building=2, dataset='REFIT', appliances=[Appliance(type='kettle', instance=1)])'
Estimating power demand for 'ElecMeter(instance=5, building=2, dataset='REFIT', appliances=[Appliance(type='television', instance=1)])'
Estimating power demand for 'ElecMeter(instance=10, building=2, dataset='REFIT', appliances=[Appliance(type='fan', instance=1)])'
Estimating power demand for 'ElecMeter(instance=6, building=2, dataset='REFIT', appliances=[Appliance(type='microwave', instance=1)])'
Estimating power demand for 'ElecMeter(instance=3, building=2, dataset='REFIT', appliances=[Appliance(type='washing machine', instance=1)])'
Estimating power demand for 'ElecMeter(instance=8, building=2, dataset='REFIT', appliances=[Appliance(type='audio system', instance=1)])'
Estimating power demand for 'ElecMeter(instance=7, building=2, dataset='REFIT', appliances=[Appliance(type='toaster', instance=1)])'
Estimating power demand for 'ElecMeter(instance=4, building=2, dataset='REFIT', appliances=[Appliance(type='dish washer', instance=1)])'
Estimating power demand for 'ElecMeter(instance=2, building=2, dataset='REFIT', appliances=[Appliance(type='fridge freezer', instance=1)])'
Estimating power demand for 'ElecMeter(instance=9, building=2, dataset='REFIT', appliances=[Appliance(type='kettle', instance=1)])'
Estimating power demand for 'ElecMeter(instance=5, building=2, dataset='REFIT', appliances=[Appliance(type='television', instance=1)])'
Estimating power demand for 'ElecMeter(instance=10, building=2, dataset='REFIT', appliances=[Appliance(type='fan', instance=1)])'
Estimating power demand for 'ElecMeter(instance=6, building=2, dataset='REFIT', appliances=[Appliance(type='microwave', instance=1)])'
Estimating power demand for 'ElecMeter(instance=3, building=2, dataset='REFIT', appliances=[Appliance(type='washing machine', instance=1)])'
Traceback (most recent call last):

  File "<ipython-input-11-75a5283d8ebc>", line 1, in <module>
    co.disaggregate(test_elec.mains(), output, sample_period=8)

  File "nilmtk\disaggregate\combinatorial_optimisation.py", line 177, in disaggregate
    output_datastore.append(key, df)

  File "nilmtk\docinherit.py", line 46, in f
    return self.mthd(obj, *args, **kwargs)

  File "nilmtk\datastore\hdfdatastore.py", line 154, in append
    self.store.append(key=key, value=value)

  File "D:\Anaconda\lib\site-packages\pandas\io\pytables.py", line 912, in append
    **kwargs)

  File "D:\Anaconda\lib\site-packages\pandas\io\pytables.py", line 1268, in _write_to_group
    s.write(obj=value, append=append, complib=complib, **kwargs)

  File "D:\Anaconda\lib\site-packages\pandas\io\pytables.py", line 3775, in write
    **kwargs)

  File "D:\Anaconda\lib\site-packages\pandas\io\pytables.py", line 3469, in create_axes
    self.validate(existing_table)

  File "D:\Anaconda\lib\site-packages\pandas\io\pytables.py", line 2925, in validate
    "vs current table [%s]" % (c, sax, oax))

ValueError: invalid combinate of [values_axes] on appending data [name->values_block_0,cname->values_block_0,dtype->int32,kind->integer,shape->(1, 196774)] vs current table [name->values_block_0,cname->values_block_0,dtype->float64,kind->float,shape->None]
```

When I change the sampling rate of disaggregation to 60 sec, it works. However, when the sampling rate is set below 60 sec, this error appears. 

After reading issue #493, I have tried to modify the  line 180 in 'combinatorial_optimisation.py' to:
 
``` 
mains_df = pd.DataFrame(chunk, columns=cols,dtype="float64")
```

but it dose not work.

Here is the package versions:

```
from nilmtk.utils import show_versions
show_versions()

D:\Anaconda\lib\site-packages\matplotlib\__init__.py:1357: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Windows
OS-release: 8.1
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en

pandas: 0.16.2
nose: 1.3.7
Cython: 0.24.1
numpy: 1.11.3
scipy: 0.18.1
statsmodels: 0.6.1
IPython: 5.1.0
sphinx: 1.4.6
patsy: 0.4.1
dateutil: 2.4.1
pytz: 2016.6.1
bottleneck: 1.1.0
tables: 3.2.2
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: 2.6.2 (dt dec pq3 ext lo64)
None

Date: 2017-03-01 03:59:03.591000
Platform: Windows-8.1-6.3.9600
System version: 2.7
nilmtk version: 0.2.0.dev-f35c464
nilm_metadata version: 0.2.0.dev-2d0196c
numpy version: 1.11.3
matplotlib version: 1.5.3
pandas version: 0.16.2
sklearn version: 0.18.1
hmmlearn version: 0.1.1
```
Thank you for helping me.

**Comment by nipunbatra** [comment]
Can you show the output of:
```
train_elec.mains().load().next().head()
```

At this moment, it is hard to ascertain whether this bug is due to Pandas' changes, or, something in NILMTK.

**Comment by nipunbatra** [comment]
Ref: https://github.com/pandas-dev/pandas/issues/6487

I think I may want to verify if we're using the same data type throughout NILMTK.

**Comment by bczhao1991** [comment]
Thanks for replying. The results are shown as:

train_elec.mains().load().next().head()
Out[3]: 
physical_quantity          power
type                      active
Timestamp                       
2014-10-07 00:00:07+01:00    227
2014-10-07 00:00:15+01:00    227
2014-10-07 00:00:23+01:00    226
2014-10-07 00:00:31+01:00    226
2014-10-07 00:00:39+01:00    226

**Comment by bczhao1991** [comment]
import os, sys
   ...: from datetime import datetime
   ...: import numpy as np # will use a lot in examples
   ...: randn = np.random.randn
   ...: from pandas import DataFrame, Series,date_range
   ...: from pandas.util.print_versions import show_versions
   ...: import pandas as pd
   ...: 
   ...: 
   ...: print('versions:')
   ...: show_versions()
   ...: 
   ...: def append_test(fname, key, df1, df2):
   ...:     try: os.unlink(fname)
   ...:     except: pass
   ...: 
   ...:     store = pd.HDFStore(fname)
   ...:     store.append(key, df1, format='table')
   ...:     store.close()
   ...: 
   ...:     df3 = df1.combine_first(df2)
   ...:     print('index type:\ndf1: %r\ndf2: %r\ndf3: %r' % (type(df1.index[0]), type(df2.index[0]), type(df3.index[0])))
   ...:     print('df1: %r\ndf2: %r\ndf3: %r' % (df1, df2, df3))
   ...: 
   ...:     store = pd.HDFStore(fname)
   ...:     store.append(key, df3, format='table')
   ...:     store.close()
   ...: 
   ...: fname = 'test_table.h5'
   ...: key = 'df'
   ...: sz=5

versions:
D:\Anaconda\lib\site-packages\matplotlib\__init__.py:1357: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.12.final.0
python-bits: 64
OS: Windows
OS-release: 8.1
machine: AMD64
processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en

pandas: 0.16.2
nose: 1.3.7
Cython: 0.24.1
numpy: 1.11.3
scipy: 0.18.1
statsmodels: 0.6.1
IPython: 5.1.0
sphinx: 1.4.6
patsy: 0.4.1
dateutil: 2.4.1
pytz: 2016.6.1
bottleneck: 1.1.0
tables: 3.2.2
numexpr: 2.6.1
matplotlib: 1.5.3
openpyxl: 2.3.2
xlrd: 1.0.0
xlwt: 1.1.2
xlsxwriter: 0.9.3
lxml: 3.6.4
bs4: 4.5.1
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: 1.0.13
pymysql: None
psycopg2: 2.6.2 (dt dec pq3 ext lo64)

df1 = DataFrame(dict(A=list(range(sz)), B=list(range(sz))))
   ...: df2 = df1 + 1
   ...: append_test(fname, key, df1, df2)

index type:
df1: <type 'numpy.int64'>
df2: <type 'numpy.int64'>
df3: <type 'numpy.int64'>
df1:    A  B
0  0  0
1  1  1
2  2  2
3  3  3
4  4  4
df2:    A  B
0  1  1
1  2  2
2  3  3
3  4  4
4  5  5
df3:    A  B
0  0  0
1  1  1
2  2  2
3  3  3
4  4  4

df1 = DataFrame(dict(A=list(range(sz)), B=list(range(sz))))
   ...: df2 = df1.copy()
   ...: df2.index = df2.index + 1
   ...: append_test(fname, key, df1, df2)

index type:
df1: <type 'numpy.int64'>
df2: <type 'numpy.int64'>
df3: <type 'numpy.int64'>
df1:    A  B
0  0  0
1  1  1
2  2  2
3  3  3
4  4  4
df2:    A  B
1  0  0
2  1  1
3  2  2
4  3  3
5  4  4
df3:    A  B
0  0  0
1  1  1
2  2  2
3  3  3
4  4  4
5  4  4
Traceback (most recent call last):

  File "<ipython-input-6-3868c2fb1175>", line 4, in <module>
    append_test(fname, key, df1, df2)

  File "<ipython-input-4-ca74f9dcd847>", line 26, in append_test
    store.append(key, df3, format='table')

  File "D:\Anaconda\lib\site-packages\pandas\io\pytables.py", line 912, in append
    **kwargs)

  File "D:\Anaconda\lib\site-packages\pandas\io\pytables.py", line 1268, in _write_to_group
    s.write(obj=value, append=append, complib=complib, **kwargs)

  File "D:\Anaconda\lib\site-packages\pandas\io\pytables.py", line 3775, in write
    **kwargs)

  File "D:\Anaconda\lib\site-packages\pandas\io\pytables.py", line 3469, in create_axes
    self.validate(existing_table)

  File "D:\Anaconda\lib\site-packages\pandas\io\pytables.py", line 2925, in validate
    "vs current table [%s]" % (c, sax, oax))

ValueError: invalid combinate of [values_axes] on appending data [name->values_block_0,cname->values_block_0,dtype->float64,kind->float,shape->(2, 6)] vs current table [name->values_block_0,cname->values_block_0,dtype->int64,kind->integer,shape->None]

**Comment by nipunbatra** [comment]
Can you try the following:

```python
import pandas as pd
import numpy as np

pred = {}
gt= {}

for i, chunk in enumerate(test_elec.mains().load(sample_period=8)):
    chunk_drop_na = chunk.dropna()
    pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)
    gt[i]={}
    
    for meter in test_elec.submeters().meters:
        # Only use the meters that we trained on (this saves time!)    
        gt[i][meter] = meter.load(sample_period=8).next()
    gt[i] = pd.DataFrame({k:v.squeeze() for k,v in gt[i].iteritems()}, index=gt[i].values()[0].index).dropna()


# If everything can fit in memory
gt_overall = pd.concat(gt)
gt_overall.index = gt_overall.index.droplevel()
pred_overall = pd.concat(pred)
pred_overall.index = pred_overall.index.droplevel()

# Having the same order of columns
gt_overall = gt_overall[pred_overall.columns]

from sklearn.metrics import mean_squared_error

rmse={}
for col in pred_overall.columns:
    rmse[col] = np.sqrt(mean_squared_error(gt_overall[col], pred_overall[col]))

pd.Series(rmse).plot(kind="barh")
```

**Comment by bczhao1991** [comment]
I think the memory is not enough to run this:


import pandas as pd
import numpy as np

pred = {}
gt= {}

for i, chunk in enumerate(test_elec.mains().load(sample_period=8)):
    chunk_drop_na = chunk.dropna()
    pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)
    gt[i]={}

    for meter in test_elec.submeters().meters:
        # Only use the meters that we trained on (this saves time!)    
        gt[i][meter] = meter.load(sample_period=8).next()
    gt[i] = pd.DataFrame({k:v.squeeze() for k,v in gt[i].iteritems()}, index=gt[i].values()[0].index).dropna()
    
ERROR: execution aborted

import pandas as pd
import numpy as np

pred = {}
gt= {}

for i, chunk in enumerate(test_elec.mains().load(sample_period=8)):
    chunk_drop_na = chunk.dropna()
    pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)
    gt[i]={}

    for meter in test_elec.submeters().meters:
        # Only use the meters that we trained on (this saves time!)    
        gt[i][meter] = meter.load(sample_period=8).next()
    gt[i] = pd.DataFrame({k:v.squeeze() for k,v in gt[i].iteritems()}, index=gt[i].values()[0].index).dropna()
    
Traceback (most recent call last):

  File "<ipython-input-10-bff62abdc0c6>", line 9, in <module>
    pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)

  File "nilmtk\disaggregate\fhmm_exact.py", line 334, in disaggregate_chunk
    learnt_states_array.append(self.model.predict(temp))

  File "D:\Anaconda\lib\site-packages\hmmlearn\base.py", line 283, in predict
    _, state_sequence = self.decode(obs, algorithm)

  File "D:\Anaconda\lib\site-packages\hmmlearn\base.py", line 266, in decode
    logprob, state_sequence = decoder[algorithm](obs)

  File "D:\Anaconda\lib\site-packages\hmmlearn\base.py", line 199, in _decode_viterbi
    framelogprob = self._compute_log_likelihood(obs)

  File "D:\Anaconda\lib\site-packages\hmmlearn\hmm.py", line 185, in _compute_log_likelihood
    obs, self._means_, self._covars_, self._covariance_type)

  File "D:\Anaconda\lib\site-packages\sklearn\utils\deprecation.py", line 71, in wrapped
    return fun(*args, **kwargs)

  File "D:\Anaconda\lib\site-packages\sklearn\mixture\gmm.py", line 72, in log_multivariate_normal_density
    X, means, covars)

  File "D:\Anaconda\lib\site-packages\sklearn\mixture\gmm.py", line 719, in _log_multivariate_normal_density_full
    log_prob = np.empty((n_samples, nmix))

MemoryError

**Comment by bczhao1991** [comment]
Sorry, I forgot to say that the memory of my PC is 16GB.

**Comment by nipunbatra** [comment]
Ok, this is due to the fact that the learnt model is very large. How many appliances are you training on? I'd suggest choosing top-k.

**Comment by bczhao1991** [comment]
In this house, the 'k' for 'top-k' was set as 9 for all appliances. Now it works for FHMM when I reduce 'k', say, 5. For CO, there is the same error. Based on the suggestion in the ref. you added above, shall we change the data type using 'astype' somewhere?

**Comment by nipunbatra** [comment]
I agree that we might have to choose float32 instead of float64 at several places. I doubt we'd need the double precision. Would be great if you want to do a Pull Request. 

For now, I'd suggest manually setting the chunksize. So, replace the calls to load with something like the following:

`test_elec.mains().load(sample_period=8, chunksize=1000).next()`

**Comment by nipunbatra** [comment]
PS the code below. You seem to have made use of the `disaggregate` method. As I showed in the example above, I'm pushing for the use of `disagggregate_chunk`.

```python

for i, chunk in enumerate(test_elec.mains().load(sample_period=8, chunksize=1000)):
    chunk_drop_na = chunk.dropna()
    pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)
    gt[i]={}
    
    for meter in test_elec.submeters().meters:
        # Only use the meters that we trained on (this saves time!)    
        gt[i][meter] = meter.load(sample_period=8, chunksize=1000).next()
    gt[i] = pd.DataFrame({k:v.squeeze() for k,v in gt[i].iteritems()}, index=gt[i].values()[0].index).dropna()
```

**Comment by manojm18** [comment]
@nipunbatra  Just wanted to know, 
disaggregate() method has output argument to save to a H5 file. 
But how do u output the disaggregate_chunk() to the H5 ?
Thanks,

**Comment by nipunbatra** [comment]
Disaggregate_chunk outputs a pandas dataframe. Search online for pandas + h5

**Comment by manojm18** [comment]
I did try to write using the pandas HDF5 instructions page
```python
for i, chunk in enumerate(test_elec.mains().load(sample_period=60)):
           chunk_drop_na = chunk.dropna()
           pred[i] = co.disaggregate_chunk(chunk_drop_na)
           gt[i] = {}
                           
           for meter in test_elec.submeters().meters:
                     gt[i][meter] = meter.load(sample_period=60).next()
           gt[i] = pd.DataFrame({k:v.squeeze() for k,v in gt[i].iteritems()},index=gt[i].values()[0].index).dropna()
disagg_output = pd.HDFStore(join(disagg_dir,file_name_output),mode='w')
disagg_output.append('df', pred[0], data_columns=['Prediction'], index=False)
disagg_output.close()
```
I am receiving the following error and couldn't find any work around. is there an alternate way to save the pred to HDF5
```python
 File "<ipython-input-1-296801985232>", line 1, in <module>
    runfile('C:/Users/MANOJ/Dropbox/Manoj Thesis/NILMTK DataSets/Pecan Street (Wiki Energy)/notebook/base disaggregation codes/Disaggregate_CO_write_CSV_automation.py', wdir='C:/Users/MANOJ/Dropbox/Manoj Thesis/NILMTK DataSets/Pecan Street (Wiki Energy)/notebook/base disaggregation codes')

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/MANOJ/Dropbox/Manoj Thesis/NILMTK DataSets/Pecan Street (Wiki Energy)/notebook/base disaggregation codes/Disaggregate_CO_write_CSV_automation.py", line 179, in <module>
    disagg_output.append('df', pred[0], data_columns=['Prediction'], index=False)

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 907, in append
    **kwargs)

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 1252, in _write_to_group
    s.write(obj=value, append=append, complib=complib, **kwargs)

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 3771, in write
    self.set_attrs()

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\pandas\io\pytables.py", line 3028, in set_attrs
    self.attrs.non_index_axes = self.non_index_axes

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\tables\attributeset.py", line 461, in __setattr__
    self._g__setattr(name, value)

  File "C:\Users\MANOJ\Anaconda2\lib\site-packages\tables\attributeset.py", line 403, in _g__setattr
    self._g_setattr(self._v_node, name, stvalue)

  File "tables\hdf5extension.pyx", line 711, in tables.hdf5extension.AttributeSet._g_setattr (tables\hdf5extension.c:7821)

  File "C:\Users\MANOJ\Anaconda2\lib\copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__

TypeError: can't pickle File objects
```

**Comment by nipunbatra** [comment]
I think the error is clear. I would suggest writing a minimal pandas
dataframe to HDF5 first.

**Comment by MartinNeighbours** [comment]
Not sure if this is still current, but for future users.

I've been playing around with the datasets also.  As for REFIT - you need to use the cleaned version as the Powerdata dataset has index duplicates - I'm surprised that this didn't come up with an error when you sampled the data.

The format of the clean data is different and you'll need to amend the converter to accommodate:

- The file naming convention
- 2 additional columns 
    - a non-UTC timestamp which can be dropped
    - an issues column where the mains meter is registering less than the total on the sub-meters (I dropped this column)

I've got a version of the converter which seems to work just fine with this dataset and would be happy to include if I knew how.

I'm not convinced of the virtue of using the FHMM (haven't tried CO yet) as any kind of benchmark as the sub-metered data is only c. 40% of the mains usage.  Unless I'm doing something wrong FHMM just seems to produce some non-sensical answers c.f. dish washer in the top 5 of building 1 - look at the proportion of states in the test data versus reality - zeros is the easiest place to start.

Also in evaluating the results I'm not sure that an RSQ measure tells us much apart from the fact that the disaggregator has filled in some values.

**Comment by nipunbatra** [comment]
>I've been playing around with the datasets also. As for REFIT - you need to use the cleaned version as the Powerdata dataset has index duplicates - I'm surprised that this didn't come up with an error when you sampled the data.

>The format of the clean data is different and you'll need to amend the converter to accommodate:

>The file naming convention
2 additional columns
a non-UTC timestamp which can be dropped
an issues column where the mains meter is registering less than the total on the sub-meters (I dropped this column)

Thanks. You'd need to open a [pull request](https://help.github.com/articles/about-pull-requests/) to submit the pertinent code. It's hard for us to keep up with the changes in the data set formats, etc. So, thanks for your efforts :)

>I'm not convinced of the virtue of using the FHMM (haven't tried CO yet) as any kind of benchmark as the sub-metered data is only c. 40% of the mains usage. Unless I'm doing something wrong FHMM just seems to produce some non-sensical answers c.f. dish washer in the top 5 of building 1 - look at the proportion of states in the test data versus reality - zeros is the easiest place to start.

Good question. FHMM still continues to be used as a baseline algorithm in top-tier ML/AI papers. The problem you've mentioned is present in total-load models like CO, FHMM and similar models. But, there's no one size fits all. Edge detection models would have their own problems, like if you miss one edge, the future will have wrong prediction as well. 

We're more than happy if you'd know of more/better baseline algorithms and would be willing to help include them in NILMTK. We do have 1-2 Python based algorithms that I have not had the time to integrate yet!


>Also in evaluating the results I'm not sure that an RSQ measure tells us much apart from the fact that the disaggregator has filled in some values.

Different use cases call for different metrics. Again, no one metric would be perfect.

**Comment by MartinNeighbours** [comment]
Great, thanks for your reply.  Good to see this is still alive - I’ll investigate the pull request as you’ve suggested as well as some other fixes that I’ve found which I think are related to new releases of modules that are allowed to float in the environment.yaml file.

I will try and feed back my thoughts as they develop (by no means an expert in the field, but have many years of analytics experience and it’s always good to have someone come from a fresh angle).  I think I’d like to compare an average model as the baseline - similar to the gains curve.

Many thanks again

Martin

On 10 Nov 2017, at 15:44, Nipun Batra <notifications@github.com<mailto:notifications@github.com>> wrote:


I've been playing around with the datasets also. As for REFIT - you need to use the cleaned version as the Powerdata dataset has index duplicates - I'm surprised that this didn't come up with an error when you sampled the data.

The format of the clean data is different and you'll need to amend the converter to accommodate:

The file naming convention
2 additional columns
a non-UTC timestamp which can be dropped
an issues column where the mains meter is registering less than the total on the sub-meters (I dropped this column)

Thanks. You'd need to open a pull request<https://help.github.com/articles/about-pull-requests/> to submit the pertinent code. It's hard for us to keep up with the changes in the data set formats, etc. So, thanks for your efforts :)

I'm not convinced of the virtue of using the FHMM (haven't tried CO yet) as any kind of benchmark as the sub-metered data is only c. 40% of the mains usage. Unless I'm doing something wrong FHMM just seems to produce some non-sensical answers c.f. dish washer in the top 5 of building 1 - look at the proportion of states in the test data versus reality - zeros is the easiest place to start.

Good question. FHMM still continues to be used as a baseline algorithm in top-tier ML/AI papers. The problem you've mentioned is present in total-load models like CO, FHMM and similar models. But, there's no one size fits all. Edge detection models would have their own problems, like if you miss one edge, the future will have wrong prediction as well.

We're more than happy if you'd know of more/better baseline algorithms and would be willing to help include them in NILMTK. We do have 1-2 Python based algorithms that I have not had the time to integrate yet!

Also in evaluating the results I'm not sure that an RSQ measure tells us much apart from the fact that the disaggregator has filled in some values.

Different use cases call for different metrics. Again, no one metric would be perfect.

**Comment by nipunbatra** [comment]
Sure. Thanks. This sounds interesting and useful. Keep me updated.

**Comment by MartinNeighbours** [comment]
I appreciate that this issue is closed, but I've now managed to complete the baseline comparison for the REFIT dataset.

I've used the same methodology of taking the top 5 appliances for building one as the script above.
train.set_window(start="11-07-2013",end="31-12-2013")
test.set_window(start="03-08-2014",end="2015-03-28") # pandas bug on British Summer Time

I've noticed that pandas doesn't like the localisation change to British Summer Time, so cut the test set short before the clocks changed.

This uses 3 comparisons:
- FHMM with mains as input
- FHMM with sub-metered total as input - bearing in mind that on this dataset, only 40% of energy for building 1 is sub-metered
- using an average energy for each meter from the training dataset and applying this across test dataset

The average is taken from:
epm = top_5_train_elec.energy_per_meter('min')

The comparison is shown in the graph below:

![image](https://user-images.githubusercontent.com/33223741/32844377-2b76f180-ca1a-11e7-9c9c-6eb87b0943da.png)

This tends to suggest that FHMM isn't really a useful benchmark for this dataset as you may as well guess.  It's only when the sub-metered data is used that improvements can be seen.

It'd be nice if there was an easy way to feed in just the total energy for the top5 meters (or any collection of meters to understand when the performance of the FHMM model deteriorates).

Therefore I'd suggest that perhaps the average model is taken as the benchmark?  Obviously this isn't going to give anything meaningful in terms of other metrics such as determining whether the device is on or off, but perhaps it's a good starting point.

**Comment by nipunbatra** [comment]
Interesting work. A few quick points.

1. FHMM performing badly would’ve been expected since the loads are less
than half of the aggregate. Did you check where the errors were? I’d assume
throughout the time series the appliances would be presented to be ON more
than they are in ground truth.
2. I like the fact that FHMM still does reasonably well on space heater.
I’d assume it to be the most significant load? The performance using sub
metered is substantially better than average.
3. A few papers indeed use the artificial aggregate. I’m not a fan of it!
4. Models such as FHMM can be tough to model. Too many appliances and the
model gets incredibly complex. Too few and the model is likely to predict
appliances ON most of the times.
5. Average prediction can be a sanity check! In fact, there’s another
baseline you may try- max likelihood. I think it associates the probability
an appliance is ON at a particular time of the day.

Happy to discuss more over Skype.
