### ISSUE TITLE
ModuleNotFoundError: No module named 'past'

### ISSUE THREAD

**Issue by WangChunyi** [nilmtk/nilmtk#548]
![22](https://cloud.githubusercontent.com/assets/20987129/23742595/70b6c998-04e8-11e7-9777-18d2fc98f105.PNG)
can you help me solve the problem?

**Comment by nipunbatra** [comment]
Run `pip install future` on the command line.

**Comment by JSLSHf** [comment]
I already installed future, but still exit the problem

**Comment by WangChunyi** [comment]
what is you problem？

发自我的 iPhone

**Comment by kaiko-www** [comment]
> ModuleNotFoundError Traceback (most recent call last)
> in ()
> 6 from cs231n.classifiers.fc_net import *
> 7 from cs231n.data_utils import get_CIFAR10_data
> ----> 8 from cs231n.gradient_check import eval_numerical_gradient, eval_numerical_gradient_array
> 9 from cs231n.solver import Solver
> 10
> 
> ~/member/zhangpan/spring1718_assignment2_v2/cs231n/gradient_check.py in ()
> 1 from **future** import print_function
> 2 from builtins import range
> ----> 3 from past.builtins import xrange
> 4
> 5 import numpy as np
> 
> ModuleNotFoundError: No module named 'past'

same problem. working on it.
