### ISSUE TITLE
Method plot produces different graph from plotting powerseries.

### ISSUE THREAD

**Issue by OdysseasKr** [nilmtk/nilmtk#552]
I have noticed that plotting an elecmeter using its `plot` function produces different output than plotting the power series (using `power_series` method). Is there is a reason for this? Does plot perform any kind of down-sampling or smoothing?

Have I completely lost the point and I'm looking at two different graphs?

**Comment by nipunbatra** [comment]
That's right. `plot` function of the elecmeter can down-sample the data in order to prevent system hanging. In case you wish to plot the entire data, using the [load API](https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/loading_data_into_memory.ipynb)

**Comment by OdysseasKr** [comment]
Great thank you very much
