### ISSUE TITLE
nosetests errors

### ISSUE THREAD

**Issue by congyi** [nilmtk/nilmtk#553]
Hi!

I ran into two issues during nosetests that I haven't been able to solve. Was hoping to get some help with them please.

Things I've tried:

1. I couldn't find a precedence for `KeyError: 0` in `ERROR: test_co_correctness`.

2. For `ERROR: test_fhmm_correctness`:

- I downgraded from `hmmlearn 2.0` to `hmmlearn 0.1.1` to solve another previous error related to array sizes.

- To solve this current error: `ValueError: The file 'output.h5' is already opened.  Please close it before reopening in write mode.`, I think I should downgrade to `pytables 3.0.0` from `pytables 3.3.0` , but I ran into a whole chain reaction of dependency conflicts when I tried that. Is there another way around this?

 
Thanks in advance for any advice, and also for this nilmtk box of wonders! The error log is reproduced below for reference.

## ERROR: test_co_correctness (nilmtk.tests.test_combinatorial_optimisation.TestCO)
----------------------------------------------------------------------

> Traceback (most recent call last):
>   File "/Users/cy/nilmtk/nilmtk/tests/test_combinatorial_optimisation.py", line 29, in test_co_correctness
>     co.disaggregate(mains, output, sample_period=1)
>   File "/Users/cy/nilmtk/nilmtk/disaggregate/combinatorial_optimisation.py", line 161, in disaggregate
>     appliance_power = appliance_powers[i]
>   File "/Users/cy/anaconda/envs/nilmtk-env/lib/python2.7/site-packages/pandas/core/frame.py", line 2059, in __getitem__
>     return self._getitem_column(key)
>   File "/Users/cy/anaconda/envs/nilmtk-env/lib/python2.7/site-packages/pandas/core/frame.py", line 2066, in _getitem_column
>     return self._get_item_cache(key)
>   File "/Users/cy/anaconda/envs/nilmtk-env/lib/python2.7/site-packages/pandas/core/generic.py", line 1386, in _get_item_cache
>     values = self._data.get(item)
>   File "/Users/cy/anaconda/envs/nilmtk-env/lib/python2.7/site-packages/pandas/core/internals.py", line 3543, in get
>     loc = self.items.get_loc(item)
>   File "/Users/cy/anaconda/envs/nilmtk-env/lib/python2.7/site-packages/pandas/indexes/base.py", line 2136, in get_loc
>     return self._engine.get_loc(self._maybe_cast_indexer(key))
>   File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
>   File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
>   File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)
>   File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)
> KeyError: 0
> -------------------- >> begin captured stdout << ---------------------
> Training model for submeter 'ElecMeter(instance=2, building=1, dataset=None, appliances=[])'
> Training model for submeter 'ElecMeter(instance=3, building=1, dataset=None, appliances=[])'
> Done training!
> Estimating power demand for 'ElecMeter(instance=2, building=1, dataset=None, appliances=[])'
> Estimating power demand for 'ElecMeter(instance=3, building=1, dataset=None, appliances=[])'
> 
> --------------------- >> end captured stdout << ----------------------
> 

## ERROR: test_fhmm_correctness (nilmtk.tests.test_fhmm.TestFHMM)
----------------------------------------------------------------------

> Traceback (most recent call last):
>   File "/Users/cy/nilmtk/nilmtk/tests/test_fhmm.py", line 28, in test_fhmm_correctness
>     output = HDFDataStore('output.h5', 'w')
>   File "/Users/cy/nilmtk/nilmtk/docinherit.py", line 46, in f
>     return self.mthd(obj, *args, **kwargs)
>   File "/Users/cy/nilmtk/nilmtk/datastore/hdfdatastore.py", line 22, in __init__
>     self.store = pd.HDFStore(filename, mode, complevel=9, complib='blosc')
>   File "/Users/cy/anaconda/envs/nilmtk-env/lib/python2.7/site-packages/pandas/io/pytables.py", line 448, in __init__
>     self.open(mode=mode, **kwargs)
>   File "/Users/cy/anaconda/envs/nilmtk-env/lib/python2.7/site-packages/pandas/io/pytables.py", line 612, in open
>     raise e
> ValueError: The file 'output.h5' is already opened.  Please close it before reopening in write mode.
> -------------------- >> begin captured stdout << ---------------------
> Training model for submeter 'ElecMeter(instance=2, building=1, dataset=None, appliances=[])'
> Training model for submeter 'ElecMeter(instance=3, building=1, dataset=None, appliances=[])'
> 
> --------------------- >> end captured stdout << ----------------------

**Comment by nipunbatra** [comment]
Thanks for reporting. I'll try and close this by the end of day. In the meanwhile, you can use NILMTK without passing the tests.

**Comment by congyi** [comment]
Thank you!

I didn't realize that NILMTK could still work without the unit tests passing...

Just to report, I installed NILMTK on my Windows machine and these two errors pop up there as well.
