### ISSUE TITLE
ImportError: No module named nilm_metadata

### ISSUE THREAD

**Issue by congyi** [nilmtk/nilmtk#556]
Hi,

While running an IPython notebook (in nilmtk-env), I kept getting the error `ImportError: No module named nilm_metadata`

I placed my IPython notebook under /nilmtk, and `nosetests` seems to run fine for me too. Also, anaconda navigator clearly lists "nilm-metadata (0.2.0)" installed under nilmtk-env. So, I can't figure out why nilm-metadata can't be found by iPython.

I suspect it may be related to #497, but for my case nosetests did not fail.

Can anyone help please? I've attached the relevant info below.

Thanks!

## pip list
> (nilmtk-env) CY:~ cy$ pip list
> DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
> appnope (0.1.0)
> backports.shutil-get-terminal-size (1.0.0)
> Bottleneck (1.2.0)
> coverage (4.3.4)
> coveralls (1.1)
> cycler (0.10.0)
> Cython (0.25.2)
> decorator (4.0.11)
> docopt (0.6.2)
> enum34 (1.1.6)
> functools32 (3.2.3.post2)
> future (0.16.0)
> hmmlearn (0.1.1)
> ipython (5.3.0)
> ipython-genutils (0.1.0)
> matplotlib (2.0.0)
> networkx (1.11)
> nilm-metadata (0.2.0, /Users/cy/nilm_metadata)
> nilmtk (0.2.0.dev-2f09501, /Users/cy/nilmtk)
> nose (1.3.7)
> numexpr (2.6.2)
> numpy (1.12.1)
> pandas (0.19.2)
> pathlib2 (2.2.0)
> pexpect (4.2.1)
> pickleshare (0.7.4)
> pip (9.0.1)
> prompt-toolkit (1.0.13)
> psycopg2 (2.7.1)
> ptyprocess (0.5.1)
> Pygments (2.2.0)
> pyparsing (2.1.4)
> python-dateutil (2.6.0)
> pytz (2016.10)
> PyYAML (3.12)
> requests (2.13.0)
> scandir (1.5)
> scikit-learn (0.18.1)
> scipy (0.19.0)
> setuptools (27.2.0)
> simplegeneric (0.8.1)
> six (1.10.0)
> subprocess32 (3.2.7)
> tables (3.3.0)
> traitlets (4.3.2)
> wcwidth (0.1.7)
> wheel (0.29.0)
> 

## nosetests results

> (nilmtk-env) CY:nilmtk cy$ nosetests
> ...........................................
> Ran 43 tests in 22.677s
> 
> OK
> Closing remaining open files:/Users/cy/nilmtk/data/energy.h5...done

**Comment by nipunbatra** [comment]
Can you please try importing code in Ipython shell (and not notebook) in the nilmtk-env? please also refer to: https://www.youtube.com/watch?v=XZJH0CHxIMA

**Comment by congyi** [comment]
nipunbatra, you solved the problem :)

I followed your Youtube guide to the T, and it worked. It turns out I wasn't using iPython correctly.

The only extra step I had to take was this:

`$ python -m pip install ipykernel`

in between Steps 2 and 3 of your guide [here](https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install_user.md)

Thank you so much for saving the day again.

**Comment by nipunbatra** [comment]
Yes, I didn't realise this would be an issue until I had spent 6+ hours scratching my head when getting continuous integration to work on my system. Glad it works.

**Comment by andysama79** [comment]
working on it in 2023, I am also facing the same problem.
here is the stacktrace:

Traceback (most recent call last):
  File "gen.py", line 12, in <module>
    from nilmtk import DataSet
  File "/home/schecter/miniconda3/envs/nilmtk-env/lib/python3.8/site-packages/nilmtk/__init__.py", line 9, in <module>
    from nilmtk.elecmeter import ElecMeter
  File "/home/schecter/miniconda3/envs/nilmtk-env/lib/python3.8/site-packages/nilmtk/elecmeter.py", line 6, in <module>
    from .preprocessing import Clip
  File "/home/schecter/miniconda3/envs/nilmtk-env/lib/python3.8/site-packages/nilmtk/preprocessing/__init__.py", line 1, in <module>
    from .clip import Clip
  File "/home/schecter/miniconda3/envs/nilmtk-env/lib/python3.8/site-packages/nilmtk/preprocessing/clip.py", line 2, in <module>
    from ..node import Node
  File "/home/schecter/miniconda3/envs/nilmtk-env/lib/python3.8/site-packages/nilmtk/node.py", line 2, in <module>
    from nilm_metadata import recursively_update_dict
ModuleNotFoundError: No module named 'nilm_metadata'

**Comment by amiapatel26** [comment]
> working on it in 2023, I am also facing the same problem. here is the stacktrace:
> 
> Traceback (most recent call last): File "gen.py", line 12, in from nilmtk import DataSet File "/home/schecter/miniconda3/envs/nilmtk-env/lib/python3.8/site-packages/nilmtk/**init**.py", line 9, in from nilmtk.elecmeter import ElecMeter File "/home/schecter/miniconda3/envs/nilmtk-env/lib/python3.8/site-packages/nilmtk/elecmeter.py", line 6, in from .preprocessing import Clip File "/home/schecter/miniconda3/envs/nilmtk-env/lib/python3.8/site-packages/nilmtk/preprocessing/**init**.py", line 1, in from .clip import Clip File "/home/schecter/miniconda3/envs/nilmtk-env/lib/python3.8/site-packages/nilmtk/preprocessing/clip.py", line 2, in from ..node import Node File "/home/schecter/miniconda3/envs/nilmtk-env/lib/python3.8/site-packages/nilmtk/node.py", line 2, in from nilm_metadata import recursively_update_dict ModuleNotFoundError: No module named 'nilm_metadata'
> 
> i really need help with this

I am having the same issue. Has anyone found a solution to this?

**Comment by talexander99** [comment]
Have you tried turning it off and turning it back on again (restarting your device)

**Comment by farlonsouto** [comment]
To whom it may concern, 

I've just fixed the error "ModuleNotFoundError: No module named 'nilm_metadata" by executing  the command line

`pip install git+https://github.com/nilmtk/nilm_metadata`

from inside my nilmtk-env (the conda environment ,as suggested in the NILM TK installation guide).

My environment: 
- Ubuntu 22.04.4 LTS (release 6.5.0-21-generic)
- Python 3.8.18
- conda 24.1.2

I wish you all the best of luck.

**Comment by MatthewCarryOn** [comment]
**Just follow the official instruction and @farlonsouto 's advice. I fixed it correctly.**
