### ISSUE TITLE
Evolution of NILM

### ISSUE THREAD

**Issue by abirbah** [nilmtk/nilmtk#559]
Hello everyone,
I just joined  your community. In fact, I am trainee in charge of designing a system to identify domestic appliances from their energy consumption: resort to NILM !! I am new in the field and I wanted to know if it is possible to find some sort of summary that summarizes the evolution of these techniques and products marketed well the principles of these products.

Thank you in advance !!

**Comment by nipunbatra** [comment]
Hi @abirbah 
I'd suggest going through some survey papers on NILM.
Examples
1. http://www.mdpi.com/1424-8220/12/12/16838/htm
2. http://www.sciencedirect.com/science/article/pii/S0301421512007446
