### ISSUE TITLE
Error with elec.draw_wiring_graph()

### ISSUE THREAD

**Issue by congyi** [nilmtk/nilmtk#560]
Hi,

There appears to be a problem with the `draw_wiring_graph() ` function , and I've attached the error log below for reference.

I think this may be related to the update to networkx v.1.11 in January 2016, as mentioned in this thread here: http://stackoverflow.com/questions/35279733/what-could-cause-networkx-pygraphviz-to-work-fine-alone-but-not-together

I'm new to this though, so I can't say for sure. Would appreciate some expert input on this.

Thanks a mighty bunch in advance.

>  ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-10-f8da587fc511> in <module>()
> ----> 1 elec.draw_wiring_graph()
> 
> /Users/cy/nilmtk/nilmtk/metergroup.py in draw_wiring_graph(self, show_meter_labels)
>     588         graph = self.wiring_graph()
>     589         meter_labels = {meter: meter.instance() for meter in graph.nodes()}
> --> 590         pos = nx.graphviz_layout(graph, prog='dot')
>     591         nx.draw(graph, pos, labels=meter_labels, arrows=False)
>     592         if show_meter_labels:
> 
> AttributeError: 'module' object has no attribute 'graphviz_layout'

**Comment by PMeira** [comment]
Fixed in the major dependency upgrade.
