### ISSUE TITLE
Elaborate a Database

### ISSUE THREAD

**Issue by abirbah** [nilmtk/nilmtk#562]
Hi everyone,
During my work to develop a device allowing the identification of electrical appliances from their electrical consumption (based of course on NILM) I am in the process of listing all the devices that can exist in a house and determine the signatures that can allow to  identify this device. This is in the framework of elaborating a database of our own product and to decide which signature we will use for the identification (power, harmonics ...).
But in fact, it is a bit long and hard to cite all the devices and these features, so I wanted to know if there are documents or links that can help me.
(Operation of devices, old databases and apparatuses cited.)

Thank you !!

**Comment by nipunbatra** [comment]
I'd suggest @JackKelly [metadata paper](https://arxiv.org/abs/1403.5946) as a starting point.
