### ISSUE TITLE
ValueError: Found array with dim 3. Estimator expected <= 2.

### ISSUE THREAD

**Issue by WangChunyi** [nilmtk/nilmtk#563]
please help me, the following are my code and problem. Thank you.
start = time.time()
from nilmtk.disaggregate import fhmm_exact
fhmm = fhmm_exact.FHMM()
# Note that we have given the sample period to downsample the data to 1 minute. 
# If instead of top_5 we wanted to train on all appliance, we would write 
# fhmm.train(train_elec, sample_period=60)
fhmm.train(top_5_train_elec, sample_period=60)
end = time.time()
print("Runtime =", end-start, "seconds.")

Traceback (most recent call last):

  File "<ipython-input-19-cd2d929408fe>", line 7, in <module>
    fhmm.train(top_5_train_elec, sample_period=60)

  File "/home/xian/wsx/nilmtk/nilmtk/disaggregate/fhmm_exact.py", line 287, in train
    learnt_model[meter].fit([X])

  File "/home/xian/下载/hmmlearn-0.2.0/hmmlearn/base.py", line 420, in fit
    X = check_array(X)

  File "/home/xian/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py", line 405, in check_array
    % (array.ndim, estimator_name))

ValueError: Found array with dim 3. Estimator expected <= 2.

**Comment by nipunbatra** [comment]
You need to install hmmlearn 0.1.1

**Comment by WangChunyi** [comment]
I just installed hmmlearn 0.1.1, but there is the problem.
Found array with dim 3. Estimator expected <= 2.

**Comment by nipunbatra** [comment]
I am afraid, I can't reproduce the problem with hmmlearn 0.1.1 

See [this](https://github.com/nilmtk/nilmtk/blob/master/docs/manual/development_guide/contributing.md) to provide more information on the bug.

**Comment by WangChunyi** [comment]
Can you give me the source of hmmlearn 0.1.1 , I don not find this version .
I just installed this. https://github.com/hmmlearn/hmmlearn.
Thank you so much

**Comment by WangChunyi** [comment]
I use the command: pip install hmmlearn. But the version of hmmlearn is 0.2.0 .
I have no method to install hmmlearn 0.1.1.
Can you  spend your valuable time to help me answer this question. Thank you very much

**Comment by nipunbatra** [comment]
```pip install hmmlearn==0.1.1```

**Comment by WangChunyi** [comment]
thank you very,I slove my problem, I think I am lucky boy, Thank you.

**Comment by vikash512** [comment]
how did you solve your problem i am also getting the same error,but i am using MLP classifier ,the code is


lsi_vector1=lsi_model[tfidf_vector1]
print type(lsi_vector1)

filename = 'model1.lsi'
pickle.dump(lsi_vector1, open(filename, 'wb'))
loaded_model = pickle.load(open(filename, 'rb'))
print type(loaded_model)

the is saved in my current working directory as " model1.lsi"
the output for print type(loaded_model) is ---- <class
'gensim.interfaces.TransformedCorpus'>

Here I want to give the vector values of lsi model to a multi neural network
as

from sklearn.neural_network import MLPClassifier
classifier = MLPClassifier(activation='relu',alpha = 0.7, max_iter=400)

classifier.fit(lsi_vector1, y_train)

the error Traceback (most recent call last):
  File "/home/vikash/gen/toyfile1.py", line 141, in <module>
    classifier.fit(lsi_vector1, y_train)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/neural_network/multilayer_perceptron.py",
line 973, in fit
    hasattr(self, "classes_")))
  File "/usr/local/lib/python2.7/dist-packages/sklearn/neural_network/multilayer_perceptron.py",
line 331, in _fit
    X, y = self._validate_input(X, y, incremental)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/neural_network/multilayer_perceptron.py",
line 910, in _validate_input
    multi_output=True)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py",
line 573, in check_X_y
    ensure_min_features, warn_on_dtype, estimator)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py",
line 451, in check_array
    % (array.ndim, estimator_name))
ValueError: Found array with dim 3. Estimator expected <= 2.


can you get me any solution.

**Comment by PMeira** [comment]
@vikash512 The issue on the original ticket was related to `hmmlearn`, not `sklearn` itself (which seems to be your case).

**Comment by dignatia** [comment]
I have exactly the same error (ValueError: Found array with dim 3. Estimator expected <= 2.) and I have hmmlearn 0.2.1. 
Do I also need to install hmmlearn 0.1.1 ? I can not find this version with pip install hmmlearn==0.1.1
Thank you

**Comment by cansoy** [comment]
> `pip install hmmlearn==0.1.1`

God bless you 🙂

**Comment by Tejaswanikoyyana** [comment]
i am also having same error but pip install hmmlearn==0.1.1 is not working for me what i should do plss help me
