### ISSUE TITLE
unhashable type: 'MeterGroup'

### ISSUE THREAD

**Issue by Tingguo** [nilmtk/nilmtk#564]
Hi there,

When I am trying nilmtk on iAWE dataset, like

    from nilmtk import DataSet
    iawe = DataSet("/ecocentric/nilmtk-master/data/iawe.h5")
    iawe.buildings[1].elec
    iawe.buildings[1].elec.draw_wiring_graph()

or 

    import time
    start = time.time()
    print(elec.proportion_of_energy_submetered())
    end = time.time()
    print(end - start, "s")

the problem pop up as

     'TypeError: unhashable type: 'MeterGroup''

Did anybody face this problem and any solutions? Thanks a lot

**Comment by nipunbatra** [comment]
Can you give complete code example to help debug?

**Comment by adrinjalali** [comment]
I seems that in `iawe` dataset, some `upstream_meter`s are a `MeterGroup`, and that case is not handled properly in the `wiring_graph` function.

**Comment by adrinjalali** [comment]
@nipunbatra you can basically use the `elecmeter_and_metergroup` notebook, and change the dataset to iAWE. Here's the piece of code producing the above error:
```
from matplotlib import rcParams
import matplotlib.pyplot as plt
%matplotlib inline
rcParams['figure.figsize'] = (13, 6)
plt.style.use('ggplot')
from nilmtk import DataSet


redd = DataSet('/path/to/iawe.h5')
elec = redd.buildings[1].elec

elec.proportion_of_energy_submetered()
```

I've changed to code to raise an exception to get more info, and it seems that there are two main meters in this dataset. 
```
Running MeterGroup.proportion_of_energy_submetered...

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-3cbee878059b> in <module>()
----> 1 elec.proportion_of_energy_submetered()

~/Projects/eon/nilm/.venv/lib/python3.6/site-packages/nilmtk/metergroup.py in proportion_of_energy_submetered(self, **loader_kwargs)
   1046         print("Running MeterGroup.proportion_of_energy_submetered...")
   1047         mains = self.mains()
-> 1048         downstream_meters = self.meters_directly_downstream_of_mains()
   1049         proportion = 0.0
   1050         verbose = loader_kwargs.get('verbose')

~/Projects/eon/nilm/.venv/lib/python3.6/site-packages/nilmtk/metergroup.py in meters_directly_downstream_of_mains(self)
    793     def meters_directly_downstream_of_mains(self):
    794         """Returns new MeterGroup."""
--> 795         meters = nodes_adjacent_to_root(self.wiring_graph())
    796         assert isinstance(meters, list)
    797         return MeterGroup(meters)

~/Projects/eon/nilm/.venv/lib/python3.6/site-packages/nilmtk/metergroup.py in wiring_graph(self)
    584                             raise RuntimeError("We don't support a MeterGroup as the upstream meter of a meter.\nMeter: %s\nupstream meter: %s" % (str(meter), str(upstream_meter)))
    585                         wiring_graph.add_edge(upstream_meter, meter)
--> 586         _build_wiring_graph(self.meters)
    587         return wiring_graph
    588 

~/Projects/eon/nilm/.venv/lib/python3.6/site-packages/nilmtk/metergroup.py in _build_wiring_graph(meters)
    582                                 break
    583                         if isinstance(upstream_meter, MeterGroup):
--> 584                             raise RuntimeError("We don't support a MeterGroup as the upstream meter of a meter.\nMeter: %s\nupstream meter: %s" % (str(meter), str(upstream_meter)))
    585                         wiring_graph.add_edge(upstream_meter, meter)
    586         _build_wiring_graph(self.meters)

RuntimeError: We don't support a MeterGroup as the upstream meter of a meter.
Meter: ElecMeter(instance=3, building=1, dataset='iAWE', appliances=[Appliance(type='fridge', instance=1)])
upstream meter: MeterGroup(meters=
  ElecMeter(instance=1, building=1, dataset='iAWE', site_meter, appliances=[])
  ElecMeter(instance=2, building=1, dataset='iAWE', site_meter, appliances=[])
)
```

From the FAQ on their [website](https://iawe.github.io/) I get: 
> 
> Question 13. In the electricity data, do the first two files i.e., 1.csv and 2.csv (they have been marked both as “mains” in “label.dat” file ) are same? I opened both the files and their found their VLNs and fs are matching at the same time-stamp, while there are differences between respective columns. If my observations are correct, could you please let us know what and why those differences have been occurred ?
> 
> Answer: The instrumented home had 2 meters installed by the utility. 1.csv and 2.csv correspond to these two meters. Now, the frequency and voltage measured by them is the same as both of them get the same supply from the grid. These meters cater to disjoint set of loads within the home. For instance, the two Acs are on different meters.

So to me, there are two problems here:

1. The main meters are upstream meters of different submiters, but somehow this information is lost in the process:
```
[m.metadata.get('submeter_of', -1) for m in elec.meters]
[-1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```
2. Even if we fix this problem, some parts of the code assume the structure of meters to be a tree with a single root, which is not the case here.

**Comment by nipunbatra** [comment]
Please allow me some time to look into this.

**Comment by PMeira** [comment]
The original issue (unhashable type: 'MeterGroup') is handled by https://github.com/nilmtk/nilmtk/commit/1e6a6f3c4f7a5374eaea7b8456a5a67aa6968b9b 

I created a new issue pointing to this one so that the meter topology is not lost.
