### ISSUE TITLE
how to download wikienergy.h5

### ISSUE THREAD

**Issue by crosofg** [nilmtk/nilmtk#566]
How to download wikienergy.h5? Where is this hosted? Cant find the website

**Comment by nipunbatra** [comment]
see: https://github.com/nilmtk/nilmtk/blob/master/nilmtk/dataset_converters/dataport/download_dataport.py

**Comment by crosofg** [comment]
Where to get the username and password

**Comment by nipunbatra** [comment]
https://dataport.cloud/
