### ISSUE TITLE
Problems to Install NILMTK

### ISSUE THREAD

**Issue by haderazzini** [nilmtk/nilmtk#568]
Hi,

We have been trying to install NILMTK on different machines, but we got different types of error. 

We have followed those instructions:

https://github.com/nilmtk/nilmtk/blob/723156c1150209ae47ba25ec96ada96a0243852f/docs/manual/user_guide/install_user.md

And those:

https://github.com/nilmtk/nilmtk/blob/c6f12ff5a75a3ef0af6be98efff9a093b442b375/docs/manual/user_guide/install_dev.md

But both bring errors. We have spent many hours trying to solve the errors, but we haven't succeeded.

Is there another way to install?

Is there a simpler way?

Regards

**Comment by zhiweiSunday** [comment]
I'm the same as your situation，but there are different places.
The install is no error now.But when I running the project,it also tell me not found dependencies.
Finally,I'm sure the Installation process is no error.The windows cmd doesn't show me the Traceback. 
**install_user.md：**
Followed this way,PyCharm showed not found notebook.notebook...and I open the "cmd",input "pip install jupyter",it showed me the jupyter is already installed.
I really don't know what should  I do with this.
**install_dev.md：**
Followed this,Using PyCharm  in a .ipynb file ,“import DataSet..and other object...from nilmtk”，PyCharm shows error.

**Comment by nipunbatra** [comment]
Can you please inform what errors you got while trying: https://github.com/nilmtk/nilmtk/blob/723156c1150209ae47ba25ec96ada96a0243852f/docs/manual/user_guide/install_user.md

I'm trying to make things as simple as possible. However, my bandwidth is also limited :( 
Would love if someone could help!

**Comment by haderazzini** [comment]
Finally worked! We first tried in cmd but didn't work. The problem was related to encoding.  We had tried in Git Bash, and it worked.

We download and install  VS C++ compiler for Python version. After we manually download environment.yml and save in folder  C:\Users\hader\Desktop\nilmtk.

After when we do conda env create in cmd:

`C:\WINDOWS\system32>cd C:\Users\hader\Desktop\nilmtk

C:\Users\hader\Desktop\nilmtk>conda env create
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........
Fetching packages ...
mkl-2017.0.1-0 100% |###############################| Time: 0:00:11  11.82 MB/s
vs2008_runtime 100% |###############################| Time: 0:00:00  11.07 MB/s
jpeg-9b-vc9_0. 100% |###############################| Time: 0:00:00   7.43 MB/s
openssl-1.0.2k 100% |###############################| Time: 0:00:00  11.97 MB/s
python-2.7.13- 100% |###############################| Time: 0:00:02  11.83 MB/s
backports_abc- 100% |###############################| Time: 0:00:00   0.00  B/s
colorama-0.3.9 100% |###############################| Time: 0:00:00   0.00  B/s
coverage-4.3.4 100% |###############################| Time: 0:00:00   8.02 MB/s
cython-0.25.2- 100% |###############################| Time: 0:00:00  11.86 MB/s
decorator-4.0. 100% |###############################| Time: 0:00:00   0.00  B/s
future-0.16.0- 100% |###############################| Time: 0:00:00  10.86 MB/s
ipython_genuti 100% |###############################| Time: 0:00:00   0.00  B/s
libpng-1.6.27- 100% |###############################| Time: 0:00:00  10.42 MB/s
mistune-0.7.4- 100% |###############################| Time: 0:00:00  10.71 MB/s
numpy-1.12.1-p 100% |###############################| Time: 0:00:00  10.88 MB/s
pandocfilters- 100% |###############################| Time: 0:00:00   0.00  B/s
path.py-10.3.1 100% |###############################| Time: 0:00:00   3.20 MB/s
pygments-2.2.0 100% |###############################| Time: 0:00:00  10.73 MB/s
pytz-2017.2-py 100% |###############################| Time: 0:00:00   6.42 MB/s
pyzmq-16.0.2-p 100% |###############################| Time: 0:00:00   8.74 MB/s
scandir-1.5-py 100% |###############################| Time: 0:00:00   1.86 MB/s
subprocess32-3 100% |###############################| Time: 0:00:00   0.00  B/s
bottleneck-1.2 100% |###############################| Time: 0:00:00   6.61 MB/s
html5lib-0.999 100% |###############################| Time: 0:00:00   5.65 MB/s
jinja2-2.9.6-p 100% |###############################| Time: 0:00:00  10.00 MB/s
jsonschema-2.6 100% |###############################| Time: 0:00:00   6.93 MB/s
numexpr-2.6.2- 100% |###############################| Time: 0:00:00   9.03 MB/s
pathlib2-2.2.1 100% |###############################| Time: 0:00:00   0.00  B/s
prompt_toolkit 100% |###############################| Time: 0:00:00   7.18 MB/s
python-dateuti 100% |###############################| Time: 0:00:00   7.67 MB/s
qt-5.6.2-vc9_4 100% |###############################| Time: 0:00:04  11.79 MB/s
scipy-0.19.0-n 100% |###############################| Time: 0:00:01  11.67 MB/s
traitlets-4.3. 100% |###############################| Time: 0:00:00   7.99 MB/s
bleach-1.5.0-p 100% |###############################| Time: 0:00:00   0.00  B/s
entrypoints-0. 100% |###############################| Time: 0:00:00   0.00  B/s
jupyter_core-4 100% |###############################| Time: 0:00:00   7.58 MB/s
pandas-0.19.2- 100% |###############################| Time: 0:00:02   3.28 MB/s
pyqt-5.6.0-py2 100% |###############################| Time: 0:00:00  11.57 MB/s
pytables-3.2.2 100% |###############################| Time: 0:00:00  11.36 MB/s
scikit-learn-0 100% |###############################| Time: 0:00:00  11.65 MB/s
testpath-0.3-p 100% |###############################| Time: 0:00:00   0.00  B/s
tornado-4.5.1- 100% |###############################| Time: 0:00:00   9.02 MB/s
ipython-5.3.0- 100% |###############################| Time: 0:00:00   9.66 MB/s
jupyter_client 100% |###############################| Time: 0:00:00   5.10 MB/s
matplotlib-2.0 100% |###############################| Time: 0:00:00  11.68 MB/s
nbformat-4.3.0 100% |###############################| Time: 0:00:00   9.10 MB/s
ipykernel-4.6. 100% |###############################| Time: 0:00:00   8.62 MB/s
nbconvert-5.1. 100% |###############################| Time: 0:00:00   8.85 MB/s
jupyter_consol 100% |###############################| Time: 0:00:00   4.70 MB/s
notebook-5.0.0 100% |###############################| Time: 0:00:00  11.55 MB/s
qtconsole-4.3. 100% |###############################| Time: 0:00:00   4.72 MB/s
widgetsnbexten 100% |###############################| Time: 0:00:00  11.67 MB/s
ipywidgets-6.0 100% |###############################| Time: 0:00:00   4.06 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[qt                  ]|#################################                 |  66%
C:\Users\hader\Desktop\nilmtk>setlocal enabledelayedexpansion

C:\Users\hader\Desktop\nilmtk>pushd "C:\Program Files\Anaconda\envs\nilmtk-env\Scripts\\..\"

C:\Program Files\Anaconda\envs\nilmtk-env>set "FORWARD_SLASHED_PREFIX=C:/Program Files/Anaconda/envs/nilmtk-env"

C:\Program Files\Anaconda\envs\nilmtk-env>chcp 65001  1>NUL

C:\Program Files\Anaconda\envs\nilmtk-env>if not exist "C:\Program Files\Anaconda\envs\nilmtk-env\Library" mkdir "C:\Program Files\Anaconda\envs\nilmtk-env\Library"

C:\Program Files\Anaconda\envs\nilmtk-env>if not exist "C:\Program Files\Anaconda\envs\nilmtk-env\Library\bin" mkdir "C:\Program Files\Anaconda\envs\nilmtk-env\Library\bin"

C:\Program Files\Anaconda\envs\nilmtk-env>cmd.exe /c set /p "=﻿"  1>"C:\Program Files\Anaconda\envs\nilmtk-env\Library\bin\qt.conf" 0<NUL

C:\Program Files\Anaconda\envs\nilmtk-env>echo [Paths] 1>>"C:\Program Files\Anaconda\envs\nilmtk-env\Library\bin\qt.conf"

C:\Program Files\Anaconda\envs\nilmtk-env>echo Prefix = C:/Program Files/Anaconda/envs/nilmtk-env/Library 1>>"C:\Program Files\Anaconda\envs\nilmtk-env\Library\bin\qt.conf"

C:\Program Files\Anaconda\envs\nilmtk-env>echo Binaries = C:/Program Files/Anaconda/envs/nilmtk-env/Library/bin 1>>"C:\Program Files\Anaconda\envs\nilmtk-env\Library\bin\qt.conf"

C:\Program Files\Anaconda\envs\nilmtk-env>echo Libraries = C:/Program Files/Anaconda/envs/nilmtk-env/Library/lib 1>>"C:\Program Files\Anaconda\envs\nilmtk-env\Library\bin\qt.conf"

C:\Program Files\Anaconda\envs\nilmtk-env>echo Headers = C:/Program Files/Anaconda/envs/nilmtk-env/Library/include/qt 1>>"C:\Program Files\Anaconda\envs\nilmtk-env\Library\bin\qt.conf"

C:\Program Files\Anaconda\envs\nilmtk-env>copy "C:\Program Files\Anaconda\envs\nilmtk-env\Library\bin\qt.conf" "C:\Program Files\Anaconda\envs\nilmtk-env\qt.conf"
        1 arquivo(s) copiado(s).
[      COMPLETE      ]|##################################################| 100%
Traceback (most recent call last):
  File "C:\Program Files\Anaconda\envs\nilmtk-env\Scripts\pip-script.py", line 3, in <module>
    import pip
  File "C:\Program Files\Anaconda\envs\nilmtk-env\lib\site-packages\pip\__init__.py", line 28, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Program Files\Anaconda\envs\nilmtk-env\lib\site-packages\pip\vcs\mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "C:\Program Files\Anaconda\envs\nilmtk-env\lib\site-packages\pip\download.py", line 37, in <module>
    from pip.utils.ui import DownloadProgressBar, DownloadProgressSpinner
  File "C:\Program Files\Anaconda\envs\nilmtk-env\lib\site-packages\pip\utils\ui.py", line 57, in <module>
    _BaseBar = _select_progress_class(IncrementalBar, Bar)
  File "C:\Program Files\Anaconda\envs\nilmtk-env\lib\site-packages\pip\utils\ui.py", line 50, in _select_progress_class
    six.text_type().join(characters).encode(encoding)
LookupError: unknown encoding: cp65001
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Program Files\Anaconda  (writable)
    default environment : C:\Program Files\Anaconda
       envs directories : C:\Program Files\Anaconda\envs
          package cache : C:\Program Files\Anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False



`$ C:\Program Files\Anaconda\Scripts\conda-env-script.py create`




    Traceback (most recent call last):
      File "C:\Program Files\Anaconda\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda\lib\site-packages\conda_env\cli\main_create.py", line 111, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "C:\Program Files\Anaconda\lib\site-packages\conda_env\installers\pip.py", line 8, in install
        pip_cmd = pip_args(prefix) + ['install', ] + specs
      File "C:\Program Files\Anaconda\lib\site-packages\conda_env\pip_util.py", line 30, in pip_args
        pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
      File "C:\Program Files\Anaconda\lib\subprocess.py", line 574, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    CalledProcessError: Command '['C:\\Program Files\\Anaconda\\envs\\nilmtk-env\\python.exe', 'C:\\Program Files\\Anaconda\\envs\\nilmtk-env\\Scripts\\pip-script.py', '-V']' returned non-zero exit status 1

C:\Users\hader\Desktop\nilmtk>`

After that, we tried in Git Bash, and it worked.

Regards,

**Comment by nipunbatra** [comment]
Thanks a ton. I'll clarify in the documentation that it's recommended to use git bash.
