### ISSUE TITLE
Problem with period on iAWE dataset

### ISSUE THREAD

**Issue by usermartin** [nilmtk/nilmtk#569]
When i try to run this Code:
`from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
dataset = DataSet('C:\Users\***\Desktop\iawe.h5')
elec = dataset.buildings[1].elec
metadata = dataset.metadata
fridge_meter = elec['fridge']
df = fridge_meter.load().next()
`
i get the following error message:
  File "C:\Users\****\AppData\Local\Continuum\Anaconda2\envs\nilmtk-env\lib\site-packages\nilmtk\timeframegroup.py", line 15, in __init__
    if isinstance(timeframes, pd.tseries.period.PeriodIndex):
AttributeError: 'module' object has no attribute 'period'

I am using the iAWE dataset nilmtk hdf5 from their github page (http://iawe.github.io/) on a Windows 10 Laptop.
The variables elec, metadata and fridge_meter are shown correctly. 
But the error occures every time i want to use a time aspect.
I also tried to use dataset.set_window(start"", end=""). 

Any ideas how to solve the issue?

**Comment by nipunbatra** [comment]
Can you please provide the complete code example to illustrate this bug.

**Comment by usermartin** [comment]
i tried your example: https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/loading_data_into_memory.ipynb
`
from nilmtk import DataSet
iawe = DataSet('PATH/iawe.h5')
elec = iawe.buildings[1].elec
elec
fridge = elec['fridge']
fridge.available_columns()
df = fridge.load().next()
df.head()
`
so that is basically the complete code i ran yet
and the error occures when i want to assign df to fridge.load().next()

**Comment by nipunbatra** [comment]
I just tried the code on OSX and it works good.

```python

~                                                                                                                                         
▶ source activate nilmtk-env
(nilmtk-env) 
~                                                                                                                                         
▶ ipython
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from nilmtk import DataSet
   ...: 
   ...: iawe = DataSet('/data/iawe/iawe.h5')
   ...: elec = iawe.buildings[1].elec
   ...: elec
   ...: 
Out[1]: 
MeterGroup(meters=
  ElecMeter(instance=1, building=1, dataset='iAWE', site_meter, appliances=[])
  ElecMeter(instance=2, building=1, dataset='iAWE', site_meter, appliances=[])
  ElecMeter(instance=3, building=1, dataset='iAWE', appliances=[Appliance(type='fridge', instance=1)])
  ElecMeter(instance=4, building=1, dataset='iAWE', appliances=[Appliance(type='air conditioner', instance=1)])
  ElecMeter(instance=5, building=1, dataset='iAWE', appliances=[Appliance(type='air conditioner', instance=2)])
  ElecMeter(instance=6, building=1, dataset='iAWE', appliances=[Appliance(type='washing machine', instance=1)])
  ElecMeter(instance=7, building=1, dataset='iAWE', appliances=[Appliance(type='computer', instance=1)])
  ElecMeter(instance=8, building=1, dataset='iAWE', appliances=[Appliance(type='clothes iron', instance=1)])
  ElecMeter(instance=9, building=1, dataset='iAWE', appliances=[Appliance(type='unknown', instance=1)])
  ElecMeter(instance=10, building=1, dataset='iAWE', appliances=[Appliance(type='television', instance=1)])
  ElecMeter(instance=11, building=1, dataset='iAWE', appliances=[Appliance(type='wet appliance', instance=1)])
  ElecMeter(instance=12, building=1, dataset='iAWE', appliances=[Appliance(type='motor', instance=1)])
)

In [2]: fridge = elec['fridge']
   ...: fridge.available_columns()
   ...: 
Out[2]: 
[('voltage', None),
 ('power', 'apparent'),
 ('power factor', None),
 ('frequency', None),
 ('power', 'active'),
 ('current', None),
 ('power', 'reactive')]

In [3]: df = fridge.load().next()
   ...: df.head()
   ...: 
Out[3]: 
physical_quantity             voltage    power  frequency  power current  \
type                                  apparent            active           
2013-06-07 05:30:00+05:30  235.070007    2.486  50.070000  0.111   0.011   
2013-06-07 05:30:01+05:30  235.020004    2.555  50.080002  0.200   0.011   
2013-06-07 05:30:02+05:30  234.979996    2.485  50.080002  0.152   0.011   
2013-06-07 05:30:03+05:30  235.000000    2.449  50.060001  0.159   0.010   
2013-06-07 05:30:04+05:30  234.949997    2.519  50.060001  0.215   0.011   

physical_quantity            power  
type                      reactive  
2013-06-07 05:30:00+05:30    2.483  
2013-06-07 05:30:01+05:30    2.547  
2013-06-07 05:30:02+05:30    2.480  
2013-06-07 05:30:03+05:30    2.444  
2013-06-07 05:30:04+05:30    2.510 
```

I dug up a bit more and realised that Pandas changed internals. 

https://github.com/influxdata/influxdb-python/issues/446

>references to "pd.tseries.period.PeriodIndex" should be replaced by "pd.PeriodIndex"

The quickfix I can suggest you for now is to run the following in your nilmtk-env

`conda install pandas=0.19.2`

This is the till the time I come up with a permanent fix. 

BTW, @haderazzini and @zhiweiSunday had some issues installing NILLMTK on windows. Wondering if you had any such issues? and if yes, how you got across those?

**Comment by usermartin** [comment]
thank you for the fast answer! 
Now it works!

**Comment by zhiweiSunday** [comment]
Many thanks，the nilmtk-env is works well now.
