### ISSUE TITLE
AttributeError: 'module' object has no attribute 'period'

### ISSUE THREAD

**Issue by llhz666** [nilmtk/nilmtk#571]
Hello.
I try to install the developer version of NILMTK according to the user's guide. 
In the end, after i put 'nosetests' , it tells me this error"AttributeError: 'module' object has no attribute 'period'", can you give me some advice? Thank you.

**Comment by llhz666** [comment]
I  don't  care of the previous error and run the demo with pycharm, but there is a new problem.
%matplotlib inline
import scipy
import numpy as np
import pandas as pd
import pywt
import matplotlib.pyplot as plt
from matplotlib import rcParams
rcParams['figure.figsize'] = (15,9)
plt.style.use('ggplot')
from __future__ import print_function, division
import time
from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
from nilmtk.disaggregate import FHMM



ImportErrorTraceback (most recent call last)
<ipython-input-3-2fc639b3cf12> in <module>()
     10 from __future__ import print_function, division
     11 import time
---> 12 from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
     13 from nilmtk.disaggregate import FHMM

ImportError: No module named nilmtk

why is there no module named nilmtk?

**Comment by nipunbatra** [comment]
I'm afraid I don't understand how nilmtk worked (your first comment) and then doesn't (second comment)

**Comment by anasvaf** [comment]
There is an issue with the pandas library (period is now part of the pandas.core). Try installing a different version of pandas (e.g. 0.19.2)
