### ISSUE TITLE
'module' object has no attribute 'period' in Loading data into memory 

### ISSUE THREAD

**Issue by sirawichj** [nilmtk/nilmtk#573]
I got problem in this line of code it showned AttributeError: 'module' object has no attribute 'period'

 df = fridge.load().next()

I tried to update version of pandas but still doesn't work

any suggestion ? 
Thanks

**Comment by nipunbatra** [comment]
Have you done: conda install pandas=0.19.2

Ref:  https://github.com/nilmtk/nilmtk/issues/569
