### ISSUE TITLE
'module' object has no attribute 'graphviz_layout'  in MeterGroup, ElecMeter, selection and basic statistics

### ISSUE THREAD

**Issue by sirawichj** [nilmtk/nilmtk#574]
In [21]:
elec.draw_wiring_graph()

seem to be my problem, the error is AttributeError: 'module' object has no attribute 'graphviz_layout'.
I've tried to install Graphviz via  sudo apt-get install graphviz but it still not working.
Anyone encounter this problem before could you please help me 

Thank you

**Comment by nipunbatra** [comment]
What documentation are you following?

**Comment by sirawichj** [comment]
I follow NILMTK Documentation > User Guide > Meter selection and basic statistics
in this link https://github.com/nilmtk/nilmtk/tree/master/docs/manual

Thank you

**Comment by nipunbatra** [comment]
Please ignore this for now. I anyway planned to remove this as it is not adding much information

**Comment by sirawichj** [comment]
Thank you so much for fast response
