### ISSUE TITLE
can't load all available columns for AMPds  dataset

### ISSUE THREAD

**Issue by oaa3wf** [nilmtk/nilmtk#575]
Hi, 

I am not able to load all the available columns for the AMPds dataset. Below is some of my code. Am I doing something wrong? Any help is appreciated. 
[Untitled1.pdf](https://github.com/nilmtk/nilmtk/files/1082048/Untitled1.pdf)

**Comment by nipunbatra** [comment]
Can you please put your code up here in Github issue? That'll make it
searchable in case anyone else has the same issues.

**Comment by oaa3wf** [comment]
Here is the code, I was initially reluctant to put it up because I'm not sure how to get a jupyter notebook to display properly. I guess this will suffice for now.

## Load and plot data (this works) :


`from __future__ import print_function
import seaborn as sns
from IPython.core.display import HTML
from IPython.display import Image
import pandas as pd
import calendar`



`from nilmtk.dataset_converters import convert_ampds
from nilmtk import DataSet
from nilmtk.utils import print_dict`

`import matplotlib.pyplot as plt
from pylab import rcParams`

`import mpld3`


`rcParams['figure.figsize'] = (14,6)`

`plt.style.use('ggplot')`

`ampds = DataSet("/Users/oafolabi/Documents/code/energy_disaggregation/data/AMPds/1.h5")
print(ampds.buildings)`

`elec = ampds.buildings[1].elec
item = 18
tv = elec.meters.__getitem__(item)
print(tv)
print(tv.appliances[0].metadata.get('original_name'))
ax = tv.plot()
ax.legend(title=tv.appliances[0].metadata.get('original_name'))`

## View available columns: 

`tv.available_columns()`
Result:
`[('current', 'apparent'),
 ('power factor', 'real'),
 ('power', 'apparent'),
 ('cumulative energy', 'apparent'),
 ('power factor', 'apparent'),
 ('power', 'active'),
 ('voltage', 'apparent'),
 ('cumulative energy', 'active'),
 ('power', 'reactive'),
 ('frequency', 'apparent'),
 ('cumulative energy', 'reactive')]`

## Load all columns:
`tv_data = tv.load()
real_tv_data = tv_data.next()
real_tv_data.head()`

## Result:

|*physical_quantity* |	*power*|	*power factor*|	*power*|  |
| ----------------- | ------------ | ----------- | ---------- | ---- |
|*type*|	*apparent* |	*apparent*|	*active*|	*reactive*|
|*unix_ts*	|		                                                      
*2012-04-01 00:00:00-07:00*|	60.0|	0.62|	37.0|	14.0
*2012-04-01 00:01:00-07:00*|	59.0|	0.62|	37.0|	14.0
*2012-04-01 00:02:00-07:00*|	59.0|	0.64|	37.0|	14.0
*2012-04-01 00:03:00-07:00*|	58.0|	0.63|	37.0|	14.0
*2012-04-01 00:04:00-07:00*|	59.0|	0.63|	37.0|	14.0

Notice that only the power readings show up.

If I inspect the data however,
`st = pd.HDFStore("/Users/oafolabi/Documents/code/energy_disaggregation/data/AMPds/1.h5")
st.keys()
st['/building1/elec/meter19'].head()`

 The other readings show up:

| *physical_quantity*|	*voltage*|	*current*	|*frequency* |	*pf*|	*power factor*|	*power* |	*energy*|	*power*| 	*energy*|	*power*| 	*energy*|
| ------- | ----- | ------ | ----- | ----- | ----- | ------ | ------- | ------- | ------- | ----- | ----- |
|*type*|	 |   |   |			*d*|	 *apparent*| 	*active*| 	*active*| 	*reactive*|	*reactive*|	*apparent*| *apparent*|
|*unix_ts*|											
|*2012-04-01 00:00:00-07:00*|	118.000000|	0.5|	60.|	|0.93	 |0.62   |37.0|	35350.0       |	14.0|	10154.0|	60.0|	49915.0|
|*2012-04-01 00:01:00-07:00*|	118.500000|	0.5|	60.0 |	0.93|	0.62|	37.0|	35351.0	|14.0	|10154.0	|59.0	|49916.0|

**Comment by PMeira** [comment]
The issue here is that the metadata lists `('voltage', 'apparent')` while the converter inserts `('voltage', '')`:

https://github.com/nilmtk/nilmtk/blob/c4c1938a4945b578d0f25d2fe60d0828b5e9d866/nilmtk/dataset_converters/ampds/metadata/meter_devices.yaml#L9-L10

https://github.com/nilmtk/nilmtk/blob/c4c1938a4945b578d0f25d2fe60d0828b5e9d866/nilmtk/dataset_converters/ampds/convert_ampds.py#L14

This seems to affect some of the other datasets too.
