### ISSUE TITLE
How to modify NILMTK to use with real data from smart plug?

### ISSUE THREAD

**Issue by sirawichj** [nilmtk/nilmtk#578]
right now,I have  installed nilmtk  according to the NILMTK user documentation,  I'm  still confused  about using the  toolkit  to run   real  data from  the  smart plug,  don't  know which folders   that I  have  to modify

Thank you so much

**Comment by nipunbatra** [comment]
Have you referred the documentation?

**Comment by sirawichj** [comment]
I follow  all codes in the user guide but still confuse with folder nilmtk( https://github.com/nilmtk/nilmtk ) whether how it is related with the document

Thank you so much

**Comment by nipunbatra** [comment]
Don't need to modify nilmtk folder. The documentation should be sufficient.
