### ISSUE TITLE
Error converting data from redd to h5 using the convert_redd method

### ISSUE THREAD

**Issue by MasoodGit** [nilmtk/nilmtk#579]
I am using below sample to  convert redd dataset to h5 format. 
However I am getting the below error
**AttributeError: 'NoneType' object has no attribute '_v_attrs'**

Please see the strack trace, below

I have followed the install steps described here [user install](https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install_user.md)

Could you please suggest , what steps need to include for the conversion to work.

`import nilmtk
from nilmtk import *
from nilmtk.dataset_converters import convert_redd
convert_redd('/vagrant/nilmtk-work/nilmtk/data/redd/low_freq/house_2', '/vagrant/nilmtk-work/nilmtk/data/redd/house_2b.h5')`

> Loaded metadata
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-5afc8910e95a> in <module>()
      2 from nilmtk import *
      3 from nilmtk.dataset_converters import convert_redd
----> 4 convert_redd('/vagrant/nilmtk-work/nilmtk/data/redd/low_freq/house_2', '/vagrant/nilmtk-work/nilmtk/data/redd/house_2b.h5')

/vagrant/nilmtk-work/nilmtk/nilmtk/dataset_converters/redd/convert_redd.py in convert_redd(redd_path, output_filename, format)
     55                               'redd',
     56                               'metadata'),
---> 57                          store)
     58     store.close()
     59 

/home/vagrant/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/nilm_metadata/convert_yaml_to_hdf5.pyc in save_yaml_to_datastore(yaml_dir, store)
     94         _sanity_check_meters(elec_meters, meter_devices)
     95         _sanity_check_appliances(building_metadata)
---> 96         store.save_metadata('/'+building, building_metadata)
     97 
     98     store.close()

/vagrant/nilmtk-work/nilmtk/nilmtk/docinherit.py in f(*args, **kwargs)
     44         @wraps(self.mthd, assigned=('__name__', '__module__'))
     45         def f(*args, **kwargs):
---> 46             return self.mthd(obj, *args, **kwargs)
     47 
     48         return self.use_parent_doc(f, overridden)

/vagrant/nilmtk-work/nilmtk/nilmtk/datastore/hdfdatastore.py in save_metadata(self, key, metadata)
    184             node = self.store.get_node(key)
    185 
--> 186         node._v_attrs.metadata = metadata
    187         self.store.flush()
    188 

**AttributeError: 'NoneType' object has no attribute '_v_attrs'**

**Comment by nipunbatra** [comment]
Can you give path till /low_freq/ instead of giving individual home number.
The converter is looking for the directory.

**Comment by MasoodGit** [comment]
I get the below error now.

Also i have used the steps mentioned in the Install_dev (new)during the installation. I hope its not the issue.

`from nilmtk.dataset_converters import convert_redd
convert_redd('/vagrant/nilmtk-work/nilmtk/data/redd/low_freq', '/vagrant/nilmtk-work/nilmtk/data/redd/redd_1.h5')`

> Loading house 1... 1 
---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)
<ipython-input-3-8820111167ab> in <module>()
      1 from nilmtk.dataset_converters import convert_redd
----> 2 convert_redd('/vagrant/nilmtk-work/nilmtk/data/redd/low_freq', '/vagrant/nilmtk-work/nilmtk/data/redd/redd_1.h5')

/vagrant/nilmtk-work/nilmtk/nilmtk/dataset_converters/redd/convert_redd.pyc in convert_redd(redd_path, output_filename, format)
     42 
     43     # Convert raw data to DataStore
---> 44     _convert(redd_path, store, _redd_measurement_mapping_func, 'US/Eastern')
     45 
     46     s=join(get_module_directory(),

/vagrant/nilmtk-work/nilmtk/nilmtk/dataset_converters/redd/convert_redd.pyc in _convert(input_path, store, measurement_mapping_func, tz, sort_index)
     96             if sort_index:
     97                 df = df.sort_index() # raw REDD data isn't always sorted
---> 98             store.put(str(key), df)
     99         print()
    100 

/vagrant/nilmtk-work/nilmtk/nilmtk/docinherit.pyc in f(*args, **kwargs)
     44         @wraps(self.mthd, assigned=('__name__', '__module__'))
     45         def f(*args, **kwargs):
---> 46             return self.mthd(obj, *args, **kwargs)
     47 
     48         return self.use_parent_doc(f, overridden)

/vagrant/nilmtk-work/nilmtk/nilmtk/datastore/hdfdatastore.pyc in put(self, key, value)
    160                        expectedrows=len(value), index=False)
    161         self.store.create_table_index(key, columns=['index'], 
--> 162                                       kind='full', optlevel=9)
    163         self.store.flush()
    164 

/home/vagrant/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/pandas/io/pytables.pyc in create_table_index(self, key, **kwargs)
   1073             raise TypeError(
   1074                 "cannot create table index on a Fixed format store")
-> 1075         s.create_index(**kwargs)
   1076 
   1077     def groups(self):

/home/vagrant/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/pandas/io/pytables.pyc in create_index(self, columns, optlevel, kind)
   3270                             'the columns containing complex values to '
   3271                             'data_columns when initializing the table.')
-> 3272                     v.create_index(**kw)
   3273 
   3274     def read_axes(self, where, **kwargs):

/home/vagrant/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/tables/table.pyc in create_index(self, optlevel, kind, filters, tmp_dir, _blocksizes, _testmode, _verbose)
   3596                              "elements")
   3597         idxrows = _column__create_index(self, optlevel, kind, filters,
-> 3598                                         tmp_dir, _blocksizes, _verbose)
   3599         return SizeType(idxrows)
   3600 

/home/vagrant/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/tables/table.pyc in _column__create_index(self, optlevel, kind, filters, tmp_dir, blocksizes, verbose)
    327     if table.nrows > 0:
    328         indexedrows = table._add_rows_to_index(
--> 329             self.pathname, 0, table.nrows, lastrow=True, update=False)
    330     else:
    331         indexedrows = 0

/home/vagrant/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/tables/table.pyc in _add_rows_to_index(self, colname, start, nrows, lastrow, update)
   2540             index.append(
   2541                 [self._read(startLR, startLR + slicesize, 1, colname)],
-> 2542                 update=update)
   2543             indexedrows += slicesize
   2544             startLR += slicesize

/home/vagrant/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/tables/index.pyc in append(self, xarr, update)
    685         # Save ranges & bounds
    686         ranges.append([[arr[0], larr]])
--> 687         bounds.append([arr[cs::cs]])
    688         abounds.append(arr[0::cs])
    689         zbounds.append(arr[cs - 1::cs])

/home/vagrant/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/tables/earray.pyc in append(self, sequence)
    211         # If the size of the nparr is zero, don't do anything else
    212         if nparr.size > 0:
--> 213             self._append(nparr)
    214 
    215     def _g_copy_with_stats(self, group, name, start, stop, step,

tables/hdf5extension.pyx in tables.hdf5extension.Array._append (tables/hdf5extension.c:17436)()

HDF5ExtError: HDF5 error back trace

  File "H5Dio.c", line 271, in H5Dwrite
    can't prepare for writing data
  File "H5Dio.c", line 352, in H5D__pre_write
    can't write data
  File "H5Dio.c", line 795, in H5D__write
    can't write data
  File "H5Dchunk.c", line 2006, in H5D__chunk_write
    unable to read raw data chunk
  File "H5Dchunk.c", line 2900, in H5D__chunk_lock
    unable to read raw data chunk
  File "H5Fio.c", line 120, in H5F_block_read
    read through metadata accumulator failed
  File "H5Faccum.c", line 263, in H5F__accum_read
    driver read request failed
  File "H5FDint.c", line 211, in H5FD_read
    driver read request failed
  File "H5FDsec2.c", line 707, in H5FD_sec2_read
    file read failed: time = Thu Jun 29 12:31:55 2017
, filename = '/vagrant/nilmtk-work/nilmtk/data/redd/pytables-S7jKME.tmp', file descriptor = 66, errno = 71, error message = 'Protocol error', buf = 0x3f95d50, total read size = 21764, bytes this sub-read = 21764, bytes actually read = 18446744073709551615, offset = 414033

End of HDF5 error back trace

Problems appending the elements

**Comment by nipunbatra** [comment]
To be honest, I have never seen this error before. 
Can you list out the entire process you followed from install to setting the environment etc.

**Comment by MasoodGit** [comment]
I recreated the env using the install_users steps and i get the same error as above.

**Comment by MasoodGit** [comment]
Sure,
#I am using ubuntu virtual box with vagrant.

#Installed Anaconda using "Anaconda2-4.4.0-Linux-x86_64.sh"

#Created dir nilmtk-work
#Downloaded and copied the environment.yml file to the shared folder/nilmtk-work
#ran the command 

conda env create

# this downloaded all the packages needed.

# activated the env, using the below command
source activate nilmtk-env

# ran the below command from the same folder

python -m ipykernel install --user --name nilmtk-env --display-name "Python (nilmtk)"

**Comment by MasoodGit** [comment]
Here is output from `nilmtk.utils.show_versions()`

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 64
OS: Linux
OS-release: 3.13.0-121-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: None.None

pandas: 0.19.2
nose: 1.3.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.25.2
numpy: 1.12.1
scipy: 0.19.1
statsmodels: None
xarray: None
IPython: 5.3.0
sphinx: None
patsy: None
dateutil: 2.6.0
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.3.0
numexpr: 2.6.2
matplotlib: 2.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: 2.7.1 (dt dec pq3 ext lo64)
jinja2: 2.9.6
boto: None
pandas_datareader: None
None

Date: 2017-06-29 13:39:22.453130
Platform: Linux-3.13.0-121-generic-x86_64-with-debian-jessie-sid
System version: 2.7
nilmtk version: 0.2.1
nilm_metadata version: 0.2.2
numpy version: 1.12.1
matplotlib version: 2.0.2
pandas version: 0.19.2
sklearn version: 0.18.2
hmmlearn version: 0.1.1

**Comment by nipunbatra** [comment]
What after these steps? Running in IPython shell? or Jupyter notebook, or how?

**Comment by MasoodGit** [comment]
Running Jupyter notebook

**Comment by nipunbatra** [comment]
Can you restart kernel and run all?

**Comment by MasoodGit** [comment]
Still get the HDF5ExtError

**Comment by MasoodGit** [comment]
phew works , had to change the write(destination) path to /home/vagrant/..
the dataset is getting converted to h5 format

Thanks nipun

**Comment by nipunbatra** [comment]
Great. Can you close the issue?
