### ISSUE TITLE
Disaggregation using one_house data

### ISSUE THREAD

**Issue by suni9915** [nilmtk/nilmtk#580]
I follow  your document, and now trying to use the one_house data to train and test the disaggregation algorithm, could you please advise how I should go about doing it and what should the output look like?  There was an error when I tried to run it.  
 Thank you very much.

**Comment by nipunbatra** [comment]
I'm afraid your question is not specific enough in its current form for me to help you.
What have you tried? Which documentation you followed? What error you get, etc.
