### ISSUE TITLE
Dataport download error

### ISSUE THREAD

**Issue by sunisajaichuen** [nilmtk/nilmtk#581]
I  tried to  do dataport download wikienergy.h5, but received error "password  authentication  failed".  I have the user-id , password and used windows 10.    Could you please help  me  fix this problem? Thank  you very much.

**Comment by nipunbatra** [comment]
Does the user id, password work on Dataport website/their DB. If not, you should contact Dataport folks/

**Comment by sunisajaichuen** [comment]
Yes, the user id , password work fine on the Dataport website.  I will contact Dataport then, thank you so much.


________________________________
จาก: Nipun Batra <notifications@github.com>
ส่ง: 2 กรกฎาคม 2560 8:49
ถึง: nilmtk/nilmtk
สำเนาถึง: sunisajaichuen; Author
ชื่อเรื่อง: Re: [nilmtk/nilmtk] Dataport download error (#581)


Does the user id, password work on Dataport website/their DB. If not, you should contact Dataport folks/

**Comment by nipunbatra** [comment]
Just be sure you're using the DB username and password. That is *different*
from the website username and password.

**Comment by Geckao** [comment]
Hello, 

I have been looking around, but you are the only one I have seen mention a DB username and password. How are they different from the website username and password ?
I have the same problem, being unable to download data from Dataport using NILMTK.

Thank you
