### ISSUE TITLE
wikienergy.h5 

### ISSUE THREAD

**Issue by suni9915** [nilmtk/nilmtk#582]
I would like to know if I can use other data instead of wikienergy.h5 to run nilmtk/notebooks/co_fhmm.ipynb.  Thank you very much.

**Comment by nipunbatra** [comment]
You can use any other dataset. See here for dataset converters: https://github.com/nilmtk/nilmtk/tree/master/nilmtk/dataset_converters

Some datasets (iAWE, UK-Dale) have .h5 available. You should be able to google the links.
