### ISSUE TITLE
Fhmm.train error

### ISSUE THREAD

**Issue by suni9915** [nilmtk/nilmtk#585]
print ('Out [15]')
start = time.time()
from nilmtk.disaggregate import fhmm_exact
fhmm = fhmm_exact.FHMM()
fhmm.train(train_elec, sample_period=60)
end = time.time()
print("Runtime =", end-start, "seconds.")
--------------------------------------------------------------------------------------------------------
Out [15]
Traceback (most recent call last):
  File "C:/Users/User/Desktop/nilmtk-master/disagorigianl.py", line 140, in <module>
    fhmm.train(train_elec, sample_period=60)
  File "C:\Users\User\Desktop\nilmtk-master\nilmtk\disaggregate\fhmm_exact.py", line 280, in train
    states = cluster(meter_data, max_num_clusters)
  File "C:\Users\User\Desktop\nilmtk-master\nilmtk\feature_detectors\cluster.py", line 26, in cluster
    data = _transform_data(X)
  File "C:\Users\User\Desktop\nilmtk-master\nilmtk\feature_detectors\cluster.py", line 64, in _transform_data
    return resampled.reshape(MAX_NUMBER_OF_SAMPLES, 1)
ValueError: cannot reshape array of size 0 into shape (2000,1)
Closing remaining open files:data/REDD/tuktest.h5...donedata/REDD/tuktest.h5...done

Process finished with exit code 1
---------------------------------------------------------------------------------------------------

I got the above error when tried to run fhmm.train for building1 which consists of only 4 channels, 1=mains  2= fridge  3=oven  and 4= laptop computer.   Could you please help me figure out what could I have done wrong?  Thank you so much.

--------------------------------------------------------------------------------------------------
**Below is the complete code.**

""             Disaggregation           """
# In [1]:
from __future__ import print_function, division
import time
from matplotlib import rcParams
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import warnings
# warnings.filterwarnings('ignore')
# # matplotlib inline
#
rcParams['figure.figsize'] = (13, 6)

from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
from nilmtk.disaggregate import CombinatorialOptimisation

print ('Out [1]')
print ('\n')

## Dividing data into train and test set

# In [2]:
print ('Out [2]')
train = DataSet('data/REDD/tuktest.h5')
test  = DataSet('data/REDD/tuktest.h5')
print ('\n')

# In [3]:
print ('Out [3]')
building = 1
print ('\n')

# In [4]:
print ('Out [4]')
train.set_window(end="30-4-2011")
test.set_window(start="30-4-2011")

train_elec = train.buildings[building].elec
test_elec = test.buildings[building].elec
print ('\n')

# In [7]:
print ('Out [7]')
laptop_computer_meter = train_elec['laptop computer']
print ('\n')

# In [8]:
print ('Out [8]')
laptop_computer_df = laptop_computer_meter.load().next()
print ('\n')

# In [9]:
print ('Out [9]   laptop')
print (laptop_computer_df.head())
print ('\n')

# In [10]:
print ('Out [10]')
mains = train_elec.mains()
print ('\n')

# In [11]:
print ('Out [11]')
mains_df = mains.load().next()
print ('\n')

# In [12]:
print ('Out [12 mains]')
print (mains_df.head())
print ('\n')

# In [13]:
print ('Out [13]')
train_elec = train_elec.submeters()
print ('\n')

# In [14]:
print ('Out [14]  train submeter')
print (train_elec)
print ('\n')

# Training and disaggregation
# In [15]:
print ('Out [15]')
start = time.time()
from nilmtk.disaggregate import fhmm_exact
fhmm = fhmm_exact.FHMM()
fhmm.train(train_elec, sample_period=60)
end = time.time()
print("Runtime =", end-start, "seconds.")
print ('\n')

# In [16]:
print ('Out [16]')
pred = {}
gt = {}

for i, chunk in enumerate(test_elec.mains().load(sample_period=60)):
    chunk_drop_na = chunk.dropna()
    pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)
    gt[i] = {}

    for meter in test_elec.submeters().meters:
        # Only use the meters that we trained on (this saves time!)
        gt[i][meter] = meter.load(sample_period=60).next()
    gt[i] = pd.DataFrame({k: v.squeeze() for k, v in gt[i].iteritems()}, index=gt[i].values()[0].index).dropna()

print ('\n')

# In[17]:
print ('Out [17]')
# If everything can fit in memory
gt_overall = pd.concat(gt)
gt_overall.index = gt_overall.index.droplevel()
pred_overall = pd.concat(pred)
pred_overall.index = pred_overall.index.droplevel()

# Having the same order of columns
gt_overall = gt_overall[pred_overall.columns]
print ('\n')

# In [18]:
print ('Out [18]')
#Intersection of index
gt_index_utc = gt_overall.index.tz_convert("UTC")
pred_index_utc = pred_overall.index.tz_convert("UTC")
common_index_utc = gt_index_utc.intersection(pred_index_utc)
print ('\n')

# In [19]:
print ('Out [19]')
local_timezone = train.metadata['timezone']
print ('\n')

# In [20]:
print ('Out [20]')
common_index_local = common_index_utc.tz_convert(local_timezone)
print ('\n')

# In [21]:
print ('Out [21]')
gt_overall = gt_overall.ix[common_index_local]
pred_overall = pred_overall.ix[common_index_local]
print ('\n')

# In [22]:
print ('Out [22]')
print (gt_overall.head())
print ('\n')

# In [23]:
print ('Out [23]')
appliance_labels = [m.label() for m in gt_overall.columns.values]
gt_overall.columns = appliance_labels
pred_overall.columns = appliance_labels
print ('\n')

# In [24]:
print ('Out [24]')
print (pred_overall.head())
print ('\n')

# In [25]:      show graph
print ('Out [25]')
plt.figure(3)
#pred_overall['Fridge'].head(1000).plot(label="Pred")
#gt_overall['Fridge'].head(1000).plot(label="GT")
pred_overall['laptop computer'].head(1000).plot(label="Pred")
gt_overall['laptop computer'].head(1000).plot(label="GT")
plt.legend()
print ('\n')

# In [26]:
print ('Out [26]')
from sklearn.metrics import mean_squared_error
print ('\n')

# In [27]:
print ('Out [27]')
rms_error = {}
for appliance in gt_overall.columns:
    rms_error[appliance] = np.sqrt(mean_squared_error(gt_overall[appliance], pred_overall[appliance]))
print ('\n')

# In [28]:
print ('Out [28]')
print (pd.Series(rms_error))
print ('\n')

**Comment by nipunbatra** [comment]
Please provide complete code.
