### ISSUE TITLE
Appliance Model Import and Export

### ISSUE THREAD

**Issue by suni9915** [nilmtk/nilmtk#587]
"NILMTK provides a model module which encapsulates the results  of the training module required by the disaggregation module".

Is this module included in the FHMM and CO approaches?  And I would like to know how to deal with the problem if the appliance is not in that model module.   I'm quite new to the energy disaggregation topic and python, please excuse me if I ask silly questions. 
Thank you.

**Comment by nipunbatra** [comment]
>Is this module included in the FHMM and CO approaches?

The answer would be yes and no. It would depend on what you want to achieve. Please elaborate on that.

**Comment by nipunbatra** [comment]
Should I close this issue?
