### ISSUE TITLE
REDD conversion for high frequency

### ISSUE THREAD

**Issue by KonstantinaBakti** [nilmtk/nilmtk#588]
Is there any convert method to use for the REDD dataset for high frequency? The convert_redd() can only take the low frequency dataset.

API for convert_redd():
> Parameters: 
> redd_path : str
> **The root path of the REDD low_freq dataset.**
> output_filename : str
> The destination filename (including path and suffix).
> format : str 
> format of output. Either ‘HDF’ or ‘CSV’. Defaults to ‘HDF’

These are my commands:
```
from nilmtk.dataset_converters import convert_redd
convert_redd('C:/Users/Konstantina/Documents/NILM/Datasets/REDD/high_freq', 'C:/Users/Konstantina/nilmtk/data/REDD/redd_high.h5')
```

When trying to run them, I'm having this error:

Loading house 3... 
Loading house 5... 
Loaded metadata
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-55414b3ac34d> in <module>()
      1 from nilmtk.dataset_converters import convert_redd
----> 2 convert_redd('C:/Users/Konstantina/Documents/NILM/Datasets/REDD/high_freq', 'C:/Users/Konstantina/nilmtk/data/REDD/redd_high.h5')

c:\users\konstantina\nilmtk\nilmtk\dataset_converters\redd\convert_redd.pyc in convert_redd(redd_path, output_filename, format)
     55                               'redd',
     56                               'metadata'),
---> 57                          store)
     58     store.close()
     59 

c:\users\konstantina\nilm_metadata\nilm_metadata\convert_yaml_to_hdf5.pyc in save_yaml_to_datastore(yaml_dir, store)
     94         _sanity_check_meters(elec_meters, meter_devices)
     95         _sanity_check_appliances(building_metadata)
---> 96         store.save_metadata('/'+building, building_metadata)
     97 
     98     store.close()

c:\users\konstantina\nilmtk\nilmtk\docinherit.pyc in f(*args, **kwargs)
     44         @wraps(self.mthd, assigned=('__name__', '__module__'))
     45         def f(*args, **kwargs):
---> 46             return self.mthd(obj, *args, **kwargs)
     47 
     48         return self.use_parent_doc(f, overridden)

c:\users\konstantina\nilmtk\nilmtk\datastore\hdfdatastore.pyc in save_metadata(self, key, metadata)
    184             node = self.store.get_node(key)
    185 
--> 186         node._v_attrs.metadata = metadata
    187         self.store.flush()
    188 

**AttributeError: 'NoneType' object has no attribute '_v_attrs'**

**Comment by nipunbatra** [comment]
That's right. NILMTK only supports low frequency REDD data.

**Comment by KonstantinaBakti** [comment]
So if I can, I have to write my own converter for high frequency data, right?

**Comment by nipunbatra** [comment]
That's correct. However, if you wish to keep the converter in the scope of NILMTK, you'd have to ensure that the representation is time series based, and not based on frequency domain (like, harmonics, etc.)

**Comment by KonstantinaBakti** [comment]
Alright, thank you very much for your time.

**Comment by PMeira** [comment]
Closing in favor of #172

**Comment by ikrambennasrbennasr** [comment]
@nipunbatra  i work with the same converter for the low frequency and i got the same error.
AttributeError: 'NoneType' object has no attribute '_v_attrs'
Any help please and thanks

**Comment by PMeira** [comment]
@ikrambennasrbennasr The converter is working fine; assuming you installed NILMTK according to the recommendations, have the REDD files and pointed the correct path, it should work without issues. Have you checked the example notebooks? e.g.
https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/data.ipynb

If you still face errors, please open a new issue and try to provide more information (OS, Python distribution, how NILMTK was installed, etc.), otherwise we're not able to provide any answers. Avoid commenting on closed issues since the default issue filter excludes them and it triggers a notification to everyone involved, besides muddling the topics.
