### ISSUE TITLE
Sub-meters in 

### ISSUE THREAD

**Issue by suni9915** [nilmtk/nilmtk#589]
Hi , could you please explain about the sub-meters concept in NILMTK , is it used to record appliance-speciﬁc consumption patterns and used as a model in the disaggregation step?  Don’t you have like signature database of the appliances that anyone can use.   I am confused because the concept of NILM , you only need the aggregated power from the mains meter.  Thank you so much.

**Comment by nipunbatra** [comment]
>is it used to record appliance-speciﬁc consumption patterns
Sub-meter is a meter down the main line. It could be a household circuit, or a home phase, or individual appliance meter.

>Don’t you have like signature database of the appliances that anyone can use
Feel free to use public energy databases to create signatures. NILMTK provides all the tools.
