### ISSUE TITLE
Problem when running select_top_k twice

### ISSUE THREAD

**Issue by haderazzini** [nilmtk/nilmtk#593]
Hello,
I'm trying to run the the code:

```python
from nilmtk import DataSet
dataset =  DataSet('G://ukdale2//ukdale.h5')
dataset.set_window(start='2014-11-05',end='2014-11-06')
metergroup=dataset.buildings[1].elec
new_metergroup=metergroup.select_top_k(k=8)
```

    1/53 ElecMeter(instance=2, building=1, dataset='UK-DALE', appliances=[Appliance(type='boiler', instance=1)])

    C:\Program Files\Anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\stats\totalenergyresults.py:41: FutureWarning: convert_objects is deprecated.  Use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
      return self._data.fillna(0).convert_objects()
    

    53/53 ElecMeter(instance=54, building=1, dataset='UK-DALE', site_meter, appliances=[Appliance(type='immersion heater', instance=1), Appliance(type='water pump', instance=1), Appliance(type='security alarm', instance=1), Appliance(type='fan', instance=2), Appliance(type='drill', instance=1), Appliance(type='laptop computer', instance=2)])

    C:\Program Files\Anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\metergroup.py:1301: FutureWarning: sort is deprecated, use sort_values(inplace=True) for INPLACE sorting
      top_k_series.sort(ascending=asc)
    

## Some warnings appear but everything works

```python
new_metergroup.meters
```

    [ElecMeter(instance=8, building=1, dataset='UK-DALE', appliances=[Appliance(type='light', instance=1), Appliance(type='light', instance=2)]),
     ElecMeter(instance=5, building=1, dataset='UK-DALE', appliances=[Appliance(type='washer dryer', instance=1)]),
     ElecMeter(instance=9, building=1, dataset='UK-DALE', appliances=[Appliance(type='HTPC', instance=1)]),
     ElecMeter(instance=10, building=1, dataset='UK-DALE', appliances=[Appliance(type='kettle', instance=1), Appliance(type='food processor', instance=1), Appliance(type='toasted sandwich maker', instance=1)]),
     ElecMeter(instance=12, building=1, dataset='UK-DALE', appliances=[Appliance(type='fridge freezer', instance=1)]),
     ElecMeter(instance=2, building=1, dataset='UK-DALE', appliances=[Appliance(type='boiler', instance=1)]),
     ElecMeter(instance=25, building=1, dataset='UK-DALE', appliances=[Appliance(type='light', instance=16)]),
     ElecMeter(instance=54, building=1, dataset='UK-DALE', site_meter, appliances=[Appliance(type='immersion heater', instance=1), Appliance(type='water pump', instance=1), Appliance(type='security alarm', instance=1), Appliance(type='fan', instance=2), Appliance(type='drill', instance=1), Appliance(type='laptop computer', instance=2)])]

## When I try to apply select_top_k again an error occurs. And even if I restart the kernel the problem continues. It stops only replacing the ukdale.h5 file for a new one.

```python
new2_metergroup=metergroup.select_top_k(k=6)
```

    3/53 ElecMeter(instance=4, building=1, dataset='UK-DALE', appliances=[Appliance(type='laptop computer', instance=1), Appliance(type='laptop computer', instance=3)])

    ---------------------------------------------------------------------------

    AttributeError                            Traceback (most recent call last)

    <ipython-input-3-1c33e3fea592> in <module>()
    ----> 1 new2_metergroup=metergroup.select_top_k(k=6)
    

    C:\Program Files\Anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\metergroup.pyc in select_top_k(self, k, by, asc, group_remainder, **kwargs)
       1298         """
       1299         function_map = {'energy': self.fraction_per_meter, 'entropy': self.entropy_per_meter}
    -> 1300         top_k_series = function_map[by](**kwargs)
       1301         top_k_series.sort(ascending=asc)
       1302         top_k_elec_meter_ids = top_k_series[:k].index
    

    C:\Program Files\Anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\metergroup.pyc in fraction_per_meter(self, **load_kwargs)
       1177         Each value is a float in the range [0,1].
       1178         """
    -> 1179         energy_per_meter = self.energy_per_meter(**load_kwargs).max()
       1180         total_energy = energy_per_meter.sum()
       1181         return energy_per_meter / total_energy
    

    C:\Program Files\Anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\metergroup.pyc in energy_per_meter(self, per_period, mains, use_meter_labels, **load_kwargs)
       1125             stdout.flush()
       1126             if per_period is None:
    -> 1127                 meter_energy = meter.total_energy(**load_kwargs)
       1128             else:
       1129                 load_kwargs.setdefault('use_uptime', False)
    

    C:\Program Files\Anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\elecmeter.pyc in total_energy(self, **loader_kwargs)
        584         nodes = [Clip, TotalEnergy]
        585         return self._get_stat_from_cache_or_compute(
    --> 586             nodes, TotalEnergy.results_class(), loader_kwargs)
        587 
        588     def dropout_rate(self, ignore_gaps=True, **loader_kwargs):
    

    C:\Program Files\Anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\elecmeter.pyc in _get_stat_from_cache_or_compute(self, nodes, results_obj, loader_kwargs)
        677         if loader_kwargs.get('preprocessing') is None:
        678             cached_stat = self.get_cached_stat(key_for_cached_stat)
    --> 679             results_obj.import_from_cache(cached_stat, sections)
        680 
        681             def find_sections_to_compute():
    

    C:\Program Files\Anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\results.pyc in import_from_cache(self, cached_stat, sections)
        164                     append_row(rows_matching_start, section)
        165                 else:
    --> 166                     for row_i in range(rows_matching_start.shape[0]):
        167                         row = rows_matching_start.iloc[row_i]
        168                         append_row(row, section)
    

    AttributeError: 'Timestamp' object has no attribute 'shape'

```python

```
How can I solve this problem? 

Regards,

Hader

**Comment by PMeira** [comment]
It works fine now, I guess the updated dependencies took care of the error.
