### ISSUE TITLE
Submetered training

### ISSUE THREAD

**Issue by suni9915** [nilmtk/nilmtk#594]
I would like to know whether NILMTK is capable of doing disaggregation when you do not have submetered training data.  And can the CO and FHMM learn the model from other houses apart from the ones that we intend to disaggregate?    Thanks for your kind help.

**Comment by nipunbatra** [comment]
>I would like to know whether NILMTK is capable of doing disaggregation when you do not have submetered training data.

DIsaggregation always happens without submetered data. I think you mean if we can learn the model without submetered training data.

One would need to use unsupervised methods for the same. CO and FHMM implementations are supervised in nature. Hart's algorithm works in unsupervised settings too.


> And can the CO and FHMM learn the model from other houses apart from the ones that we intend to disaggregate?

Yes. That's possible. As an example see: https://github.com/nipunbatra/Gemello/blob/master/code/fhmm_minutes.py
