### ISSUE TITLE
import nilmtk not working in Jupyter

### ISSUE THREAD

**Issue by kotchetkoff** [nilmtk/nilmtk#596]
Hello,

I am trying to run nilmtk in my Win 10 64bits machine using Anaconda Prompt.

When I try to import nilmtk in the Jupyter notebook ( in Pyhton (nilmtk) ) I get the following error:

ImportError                               Traceback (most recent call last)
<ipython-input-1-34c348a98f20> in <module>()
----> 1 import nilmtk

![image](https://user-images.githubusercontent.com/30989096/29254016-12b20b6e-8062-11e7-9e47-08b59356bbd0.png)

ImportError: No module named nilmtk

When I import nilmtk in my Jupyter notebook ( Python, without the "(nilmtk)") I do not get this error, I can read the version but nilmtk does not pass the nosetests.

When I try to import nilmtk in ipython I have to import sip before it.

I have succesfully installed the nilmtk environment (at least I think so) and reinstalled it several times. I am sure I am running everything in the nilmtk-env.

Could someone help me?

**Comment by nipunbatra** [comment]
What installation guide did you follow?

**Comment by ikrambennasrbennasr** [comment]
@nipunbatra Hello , please how we can import neuralnilm to nilmtk? Should we create an environment neuralnilm with anaconda prompt as we did for nilmtk or downloading the project neuralnilm and put it in nilmtk can solve the problem? Thanks

**Comment by nipunbatra** [comment]
@ikrambennasrbennasr Please check with Neural NILM folks.

**Comment by mzhuang1** [comment]
I have the same issue with "ImportError: No module named nilmtk" only in notebook.

**Comment by dion0511** [comment]
> What installation guide did you follow?

Mr nipun I also getting error, I already follow your guide video in youtube.
so how to fix that error ?
