### ISSUE TITLE
Bug in predict method

### ISSUE THREAD

**Issue by wesinalves** [nilmtk/nilmtk#598]
Hi,
I am trying reproduce the code 'comparing_nilm_algorithms.py' using ukdale dataset. 
I just have edited set_window method and sample_period variable like this:
```python
from __future__ import print_function, division
import time
from matplotlib import rcParams
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
#matplotlib inline

rcParams['figure.figsize'] = (13, 6)

from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
from nilmtk.disaggregate import CombinatorialOptimisation, FHMM

#dividing data in train and tes set
train = DataSet('ukdale.h5')
test = DataSet('ukdale.h5')

#defining the building of interest. to change for more than one buildings
building = 2

#set window of interest. perhaps timestamp is thrwoing an error
train.set_window(start="1-4-2013",end="30-8-2013")
test.set_window(start="1-9-2013",end="30-9-2013") # to change to 5 house

train_elec = train.buildings[building].elec
test_elec = test.buildings[building].elec

#selecting top applience. Change to kettle, fridge, washing machine, microwave and dish washer
top_5_train_elec = train_elec.submeters().select_top_k(k=5)
#top_5_train_elec = train_elec.submeters().select_using_appliances(type=['fridge', 'kettle', 'washing machine', 'microwave','dish washer'])

#Training and disaggregation

def predict(clf, test_elec, sample_period, timezone):
    pred = {}
    gt= {}

    for i, chunk in enumerate(test_elec.mains().load(sample_period=sample_period)):
        chunk_drop_na = chunk.dropna()
        pred[i] = clf.disaggregate_chunk(chunk_drop_na)
        gt[i]={}

        for meter in test_elec.submeters().meters:
            # Only use the meters that we trained on (this saves time!)    
            gt[i][meter] = meter.load(sample_period=sample_period).next()
        gt[i] = pd.DataFrame({k:v.squeeze() for k,v in gt[i].iteritems()}, index=gt[i].values()[0].index).dropna()
        
    # If everything can fit in memory
    gt_overall = pd.concat(gt)
    gt_overall.index = gt_overall.index.droplevel()
    pred_overall = pd.concat(pred)
    pred_overall.index = pred_overall.index.droplevel()

    # Having the same order of columns
    gt_overall = gt_overall[pred_overall.columns]
    
    #Intersection of index
    gt_index_utc = gt_overall.index.tz_convert("UTC")
    pred_index_utc = pred_overall.index.tz_convert("UTC")
    common_index_utc = gt_index_utc.intersection(pred_index_utc)
    
    
    common_index_local = common_index_utc.tz_convert(timezone)
    gt_overall = gt_overall.ix[common_index_local]
    pred_overall = pred_overall.ix[common_index_local]
    appliance_labels = [m.label() for m in gt_overall.columns.values]
    gt_overall.columns = appliance_labels
    pred_overall.columns = appliance_labels
    return gt_overall, pred_overall

#Run classifiers CO and FHMM
classifiers = {'CO':CombinatorialOptimisation(), 'FHMM':FHMM()}
predictions = {}
sample_period = 6
for clf_name, clf in classifiers.iteritems():
    print("*"*20)
    print(clf_name)
    print("*" *20)
    clf.train(top_5_train_elec, sample_period=sample_period)
    gt, predictions[clf_name] = predict(clf, test_elec, 6, train.metadata['timezone'])

#Evaluate algorithms by rmse metric
def compute_rmse(gt, pred):
    from sklearn.metrics import mean_squared_error
    rms_error = {}
    for appliance in gt.columns:
        rms_error[appliance] = np.sqrt(mean_squared_error(gt[appliance], pred[appliance]))
    return pd.Series(rms_error)

rmse = {}
for clf_name in classifiers.keys():
    rmse[clf_name] = compute_rmse(gt, predictions[clf_name])

rmse = pd.DataFrame(rmse)

print(rmse)
```
For buildings 3,4 it runs without errors, but for buildings 2, i get:

> C:\Anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\utils.py:390: FutureWarning: fill_method is deprecated to .resample()
the new syntax is .resample(...).ffill(limit=1)
  data = data.resample(**resample_kwargs)
Traceback (most recent call last):
  File "comparing.py", line 82, in <module>
    gt, predictions[clf_name] = predict(clf, test_elec, 6, train.metadata['timezone'])
  File "comparing.py", line 42, in predict
    pred[i] = clf.disaggregate_chunk(chunk_drop_na)
  File "C:\Anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\disaggregate\fhmm_exact.py", line 333, in disaggregate_chunk
    temp = test_mains.values.reshape(length, 1)
ValueError: cannot reshape array of size 5636862 into shape (1878954,1)
Closing remaining open files:ukdale.h5...doneukdale.h5...done

and for building 1, i get

> C:\Anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\utils.py:390: FutureWarning: fill_method is deprecated to .resample()
the new syntax is .resample(...).ffill(limit=1)
  data = data.resample(**resample_kwargs)
Traceback (most recent call last):
  File "comparing.py", line 82, in <module>
    gt, predictions[clf_name] = predict(clf, test_elec, 6, train.metadata['timezone'])
  File "comparing.py", line 40, in predict
    for i, chunk in enumerate(test_elec.mains().load(sample_period=sample_period)):
  File "C:\Anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\preprocessing\apply.py", line 15, in process
    new_chunk = self.func(chunk)
  File "C:\Anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\electric.py", line 145, in resample_func
    return safe_resample(df, **resample_kwargs)
  File "C:\Anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\utils.py", line 390, in safe_resample
    data = data.resample(**resample_kwargs)
  File "C:\Anaconda\envs\nilmtk-env\lib\site-packages\pandas\core\generic.py", line 4216, in resample
    limit=limit)
  File "C:\Anaconda\envs\nilmtk-env\lib\site-packages\pandas\tseries\resample.py", line 601, in _maybe_process_deprecations
    r = r.aggregate(fill_method, limit=limit)
  File "C:\Anaconda\envs\nilmtk-env\lib\site-packages\pandas\tseries\resample.py", line 320, in aggregate
    result, how = self._aggregate(arg, *args, **kwargs)
  File "C:\Anaconda\envs\nilmtk-env\lib\site-packages\pandas\core\base.py", line 432, in _aggregate
    return getattr(self, arg)(*args, **kwargs), None
  File "C:\Anaconda\envs\nilmtk-env\lib\site-packages\pandas\tseries\resample.py", line 451, in pad
    return self._upsample('pad', limit=limit)
  File "C:\Anaconda\envs\nilmtk-env\lib\site-packages\pandas\tseries\resample.py", line 739, in _upsample
    limit=limit)
  File "C:\Anaconda\envs\nilmtk-env\lib\site-packages\pandas\core\frame.py", line 2821, in reindex
    **kwargs)
  File "C:\Anaconda\envs\nilmtk-env\lib\site-packages\pandas\core\generic.py", line 2259, in reindex
    fill_value, copy).__finalize__(self)
  File "C:\Anaconda\envs\nilmtk-env\lib\site-packages\pandas\core\frame.py", line 2767, in _reindex_axes
    fill_value, limit, tolerance)
  File "C:\Anaconda\envs\nilmtk-env\lib\site-packages\pandas\core\frame.py", line 2775, in _reindex_index
    tolerance=tolerance)
  File "C:\Anaconda\envs\nilmtk-env\lib\site-packages\pandas\indexes\base.py", line 2543, in reindex
    raise ValueError("cannot reindex a non-unique index "
ValueError: cannot reindex a non-unique index with a method or limit
Closing remaining open files:ukdale.h5...doneukdale.h5...done 

my show_versions() results is:

commit: None
python: 2.7.13.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 61 Stepping 4, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.19.2
nose: 1.3.7
pip: 9.0.1
setuptools: 27.2.0
Cython: 0.26
numpy: 1.12.1
scipy: 0.19.1
statsmodels: None
xarray: None
IPython: 5.3.0
sphinx: None
patsy: None
dateutil: 2.6.1
pytz: 2017.2
blosc: None
bottleneck: 1.2.1
tables: 3.4.2
numexpr: 2.6.2
matplotlib: 2.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: 0.999
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: 2.7.3 (dt dec pq3 ext lo64)
jinja2: 2.9.6
boto: None
pandas_datareader: None
None

Date: 2017-08-24 20:56:14.075000
Platform: Windows-10-10.0.10586
System version: 2.7
nilmtk version: 0.2.1
nilm_metadata version: 0.2.2
numpy version: 1.12.1
matplotlib version: 2.0.2
pandas version: 0.19.2
sklearn version: 0.18.2
hmmlearn version: 0.1.1`
`

I guess the error is inside predict method in line 40.
Please, help to solve this bug.

**Comment by nipunbatra** [comment]
Based on the error trace, I think there is a lot of missing data in the specified time window?

**Comment by wesinalves** [comment]
it is one possibility, but i don't know.

**Comment by wesinalves** [comment]
I changed the specified time window and it's all right now. Additionally, i set ac_type in load method for house 2.
```python
test_elec.mains().load(ac_type='active', sample_period=sample_period)
```
Thanks!
