### ISSUE TITLE
Remove the usage of **argv 

### ISSUE THREAD

**Issue by BaluJr** [nilmtk/nilmtk#606]
I would remove all `**argv` in the function signatures in favour of named parameters. This is also the paradigm in SciKit learn and makes things much more readable. 
Eg. `loader_kwargs` will still be a dictionary in the algorithm's signatures, but at least a named one. At the moment it just collects all paramters implicitly.

**Comment by UPstartDeveloper** [comment]
I would be willing to do this! I am new to do this repo, which files are you referring to sir?

**Comment by UPstartDeveloper** [comment]
@BaluJr I am sorry sir I could not find **argv being used anywhere in the entire project. I tried using Cmd Shift F with the search term "**argv" on the entire repository, and nothing came up. Can you please clarify which files the changes should take place? Thanks very much.
