### ISSUE TITLE
Problem with creating nilmtk environment on Windows

### ISSUE THREAD

**Issue by bundit786** [nilmtk/nilmtk#607]
Hi nilmtk development team,

         **I tried to install nilmtk on Windows 10, 64 bit using the instruction by https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install_user.md. I think I could finish step 0 and 1. Now, I stuck at step 2, 'Creating nilmtk environment'. I put the code 'activate nilmtk-env' in conda command prompt, it turned out the error by below.

C:\Users\bundit\Desktop\nilmtk_work>**activate nilmtk-env**
Traceback (most recent call last):
  File "C:\Users\bundit\Anaconda2\lib\logging\__init__.py", line 872, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: 874
Logged from file exceptions.py, line 567

When I tried to use the code 'conda env create', it also turned out the error.

C:\Users\bundit\Desktop\nilmtk_work>**conda env create**
Using Anaconda API: https://api.anaconda.org

SpecNotFound: Can't process without a name

-------------------------------------------------------
Issues 567 and 568 are similar to me but I get the different results to them.
So, please advise on what's wrong with my process and how to solve it?

Thank you.
Bundit B.

**Comment by wesinalves** [comment]
is your environment.yml file in C:\Users\bundit\Desktop\nilmtk_work ??

**Comment by bundit786** [comment]
Yes, it is in nilmtk folder.
![image](https://user-images.githubusercontent.com/7457132/30309046-3d0a697a-97b3-11e7-8012-4a202547ab06.png)

**Comment by bundit786** [comment]
Thanks for the answer, Wesinalves. I have followed your comment, some additional packages had been installed but there seem to be some issues at the end. I'm not sure it is a problem or not, please verify as below.


C:\Users\bundit\Desktop\nilmtk_work\nilmtk>**conda env create**
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .............
Solving package specifications: .
mkl-2017.0.3-0 100% |###############################| Time: 0:00:29   4.44 MB/s
zlib-1.2.11-vc 100% |###############################| Time: 0:00:00 121.78 kB/s
certifi-2016.2 100% |###############################| Time: 0:00:01 214.31 kB/s
coverage-4.4.1 100% |###############################| Time: 0:00:01 180.96 kB/s
cython-0.26-py 100% |###############################| Time: 0:00:02 883.72 kB/s
decorator-4.1. 100% |###############################| Time: 0:00:01  12.37 kB/s
future-0.16.0- 100% |###############################| Time: 0:00:02 250.77 kB/s
hdf5-1.8.17-vc 100% |###############################| Time: 0:00:05   2.34 MB/s
libpng-1.6.30- 100% |###############################| Time: 0:00:04 107.76 kB/s
markupsafe-1.0 100% |###############################| Time: 0:00:00  50.74 kB/s
numpy-1.12.1-p 100% |###############################| Time: 0:00:05 634.84 kB/s
pandocfilters- 100% |###############################| Time: 0:00:00 796.87 kB/s
pyparsing-2.2. 100% |###############################| Time: 0:00:00 129.09 kB/s
wincertstore-0 100% |###############################| Time: 0:00:01  10.32 kB/s
numexpr-2.6.2- 100% |###############################| Time: 0:00:00   4.19 MB/s
pathlib2-2.3.0 100% |###############################| Time: 0:00:00 120.92 kB/s
prompt_toolkit 100% |###############################| Time: 0:00:01 195.29 kB/s
python-dateuti 100% |###############################| Time: 0:00:01 191.83 kB/s
qt-5.6.2-vc9_6 100% |###############################| Time: 0:00:19   2.95 MB/s
scipy-0.19.1-n 100% |###############################| Time: 0:00:04   3.18 MB/s
setuptools-36. 100% |###############################| Time: 0:00:00   5.41 MB/s
ssl_match_host 100% |###############################| Time: 0:00:00 296.16 kB/s
entrypoints-0. 100% |###############################| Time: 0:00:00 599.81 kB/s
pandas-0.19.2- 100% |###############################| Time: 0:00:05   1.39 MB/s
pytables-3.4.2 100% |###############################| Time: 0:00:03 866.88 kB/s
scikit-learn-0 100% |###############################| Time: 0:00:03   1.32 MB/s
testpath-0.3.1 100% |###############################| Time: 0:00:00 961.56 kB/s
tornado-4.5.2- 100% |###############################| Time: 0:00:00 715.39 kB/s
jupyter_client 100% |###############################| Time: 0:00:00 142.16 kB/s
nbformat-4.4.0 100% |###############################| Time: 0:00:01 136.29 kB/s
nbconvert-5.2. 100% |###############################| Time: 0:00:01 238.34 kB/s
jupyter_consol 100% |###############################| Time: 0:00:00  70.28 kB/s
qtconsole-4.3. 100% |###############################| Time: 0:00:02  72.58 kB/s
widgetsnbexten 100% |###############################| Time: 0:00:02 746.79 kB/s
**INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\bundit\Anaconda2\envs\nilmtk-env', env_name: 'nilmtk-env', mode: 'None', used_mode: 'user'
INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\bundit\Anaconda2\envs\nilmtk-env', env_name: 'nilmtk-env', mode: 'None', used_mode: 'user'
INFO menuinst_win32:__init__(182): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\bundit\Anaconda2\envs\nilmtk-env', env_name: 'nilmtk-env', mode: 'None', used_mode: 'user'**
Collecting coveralls
  Using cached coveralls-1.2.0-py2.py3-none-any.whl
Collecting hmmlearn==0.1.1
Collecting psycopg2
  Using cached psycopg2-2.7.3.1-cp27-cp27m-win_amd64.whl
Collecting nilm_metadata from git+https://github.com/nilmtk/nilm_metadata.git#egg=nilm_metadata
  Cloning https://github.com/nilmtk/nilm_metadata.git to c:\users\bundit\appdata\local\temp\pip-build-dd7ok2\nilm-metadata
  Error [Error 2] The system cannot find the file specified while executing command git clone -q https://github.com/nilmtk/nilm_metadata.git c:\users\bundit\appdata\local\temp\pip-build-dd7ok2\nilm-metadata
Cannot find command 'git'

CondaValueError: pip returned an error.

===============================
Thank you.

**Comment by nipunbatra** [comment]
I think the answer is in the error trace itself. Can't find git. You'd have
to configure that.

**Comment by bundit786** [comment]
I have already used git bash to clone the 2 folders of nilmtk and nilmtk_metadata into my path.
So, I'm confused what and how I have to configure with git to solve the error. Please, you help explain. Thanks.

**Comment by nipunbatra** [comment]
I think you'd have to figure out why you're getting git not found. It's not
a nilmtk related error.

**Comment by wesinalves** [comment]
Try to use this [https://git-scm.com/download/win](url) if not using yet. Otherwise, check your environment variable Path in system properties. You need a entry like this 'C:\Program Files\Git\cmd'

**Comment by bundit786** [comment]
The process of creating environment seems to work now. I re-installed Git by using the option "Run Git from the Windows Command Prompt" in Git Setup step and confirmed the variable path setting. But when all the packages had been download, using "activate nilmtk-env", faced the error as below.

_Successfully installed PyYAML-3.12 asn1crypto-0.22.0 certifi-2017.7.27.1 cffi-1.10.0 chardet-3.0.4 coveralls-1.2.0 cryptography-2.0.3 docopt-0.6.2 hmmlearn-0.1.1 idna-2.6 ipaddress-1.0.18 nilm-metadata-0.2.2 nilmtk-0.2.1 psycopg2-2.7.3.1 pyOpenSSL-17.2.0 pycparser-2.18 requests-2.18.4 urllib3-1.22_
#
# To activate this environment, use:
# > activate nilmtk-env
#
# To deactivate an active environment, use:
# > deactivate
#
# * for power-users using bash, you must source
#


C:\Users\bundit\Desktop\nilmtk_work\nilmtk>**activate nilmtk-env**

_Traceback (most recent call last):
  File "C:\Users\bundit\Anaconda2\lib\logging\__init__.py", line 872, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: 874
Logged from file exceptions.py, line 592
Traceback (most recent call last):
  File "C:\Users\bundit\Anaconda2\lib\logging\__init__.py", line 872, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: 874
Logged from file exceptions.py, line 596
Traceback (most recent call last):
  File "C:\Users\bundit\Anaconda2\lib\logging\__init__.py", line 872, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: 874
Logged from file exceptions.py, line 597
Traceback (most recent call last):
  File "C:\Users\bundit\Anaconda2\lib\logging\__init__.py", line 872, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: 874
Logged from file exceptions.py, line 598
Traceback (most recent call last):
  File "C:\Users\bundit\Anaconda2\lib\logging\__init__.py", line 872, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: 874
Logged from file exceptions.py, line 599
=CONDA_PATH_PLACEHOLDER%" was unexpected at this time._

So, how can I fix the error? Thanks.

**Comment by bundit786** [comment]
Please help on this issue, to activate nilmtk-env. I tried to re-install from the beginning but the error after input 'activate nilmtk-env' is still the same.

**Comment by nipunbatra** [comment]
As I'd said earlier, this is not really a nilmtk issue. I think this is due
to encoding on terminal.

PS: https://github.com/conda/conda/issues/1923

**Comment by bundit786** [comment]
I get the activation done by edit Region setting following the post in https://stackoverflow.com/questions/43306103/error-in-anaconda-when-activate-env
Thanks @nipunbatra and @wesinalves for your help. I think this issue can be closed then.
