### ISSUE TITLE
Failure to write aggregate values into main folder

### ISSUE THREAD

**Issue by changfangyi** [nilmtk/nilmtk#608]
Hi NILMTK team:
Nice to meet you !
Thanks for your toolkit, and it really help me a lot. But, I have trouble converting our raw data into ***.h5. We cannot write our aggregate values into the main folder, but we successfully write each appliance's values into corresponding folder. Did I missing something?
Best,
FY

**Comment by BaluJr** [comment]
I am not one of the native NilmTK developer, but I might can give some hints.
Do I get it right, that you have problems converting your data into the NilmTK input data scheme? 
Did you have a look to the other converters? I managed to write an own importer derived from that code.

What do you mean by 'main folder' and what by corresponding folder? Did you write the metadata properly? Inside the metadata, the pathes to the different folders have to be properly set within the elec_meters' `data_location` field. The folder hierarchie is not recognized autonomously.

**Comment by nipunbatra** [comment]
I'd echo @BaluJr 
I do agree that the error mechanisms aren't as good as we'd like to. If you've got some cycles, feel free to step in!

**Comment by PMeira** [comment]
Closing this, feel free to reopen if necessary.
