### ISSUE TITLE
hart85 run Error in win10

### ISSUE THREAD

**Issue by lhx20070322** [nilmtk/nilmtk#609]
When I trying to run all hart85 examples(such as hart.ipynb in experimental fold) in windows10, got "RuntimeError: The model needs to be instantiated before calling disaggregate. For example, the model can be instantiated by running train." in the disaggregation step."  Can you help me?
Thanks!

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.13.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.16.2
nose: 1.3.7
Cython: 0.25.2
numpy: 1.13.1
scipy: 0.19.1
statsmodels: 0.8.0
IPython: 5.3.0
sphinx: 1.5.6
patsy: 0.4.1
dateutil: 2.4.1
pytz: 2017.2
bottleneck: 1.2.1
tables: 3.2.2
numexpr: 2.6.2
matplotlib: 2.0.2
openpyxl: 2.4.7
xlrd: 1.0.0
xlwt: 1.2.0
xlsxwriter: 0.9.6
lxml: 3.7.3
bs4: 4.6.0
html5lib: 0.999
httplib2: None
apiclient: None
sqlalchemy: 1.1.9
pymysql: None
psycopg2: 2.6.2 (dt dec pq3 ext lo64)
None

Date: 2017-09-14 18:23:39.437000
Platform: Windows-10-10.0.14393
System version: 2.7
nilmtk version: 0.2.1
nilm_metadata version: 0.2.2
numpy version: 1.13.1
matplotlib version: 2.0.2
pandas version: 0.16.2
sklearn version: 0.19.0
hmmlearn version: 0.1.1

**Comment by nipunbatra** [comment]
The experimental folder should not really be used. Do you face issues on the links provided in the documentation?
