### ISSUE TITLE
problem for installing on Windows

### ISSUE THREAD

**Issue by elmagnifico9** [nilmtk/nilmtk#612]
Hello.

I'm a newbie to Python and couldn't figure out how to install nilmtk on windows despite watching the install tutorial.

Here are the steps I've taken:

1- Installing anaconda for python 2.7.
2- Creating the nilmtk_work folder and putting environment.yml in that folder.
3- Trying this in cmd:
![1](https://user-images.githubusercontent.com/32112414/30617295-5b12356e-9d63-11e7-928e-b4bf4b3b480a.jpg)

I also tried to manually create the nilmtk-env folder in "anaconda2/envs/" and put the environment.yml there.
![2](https://user-images.githubusercontent.com/32112414/30617300-66e1a7c6-9d63-11e7-88e6-7c3c94f9f114.jpg)

This time I see the python(nilmtk) in Jupiter but the cannot import the nilmtk

![3](https://user-images.githubusercontent.com/32112414/30617328-895268fe-9d63-11e7-9914-9670b0d1ca96.jpg)

Thanks a lot for the help in advance!

**Comment by wesinalves** [comment]
do you call conda env create command?

**Comment by elmagnifico9** [comment]
Thanks, wesinalves! I am one step ahead, but still, after calling conda env create I'm getting an error in the middle of installing the packages for nilm metadata.

![error](https://user-images.githubusercontent.com/32112414/30663477-c7d7c2a8-9e18-11e7-9227-619703403f71.jpg)

Thanks!

**Comment by wesinalves** [comment]
you also need to install git package
https://git-scm.com/download/win

**Comment by elmagnifico9** [comment]
Thank you wesinalves . After installing git package, I managed to install everything, activate nilmtk, and also added the jupyther kernel but still getting the same error that nilmtk module is not found.

![error2](https://user-images.githubusercontent.com/32112414/30666030-0bb36aec-9e21-11e7-96f9-3eb84285c695.jpg)

![error4](https://user-images.githubusercontent.com/32112414/30666080-34547e46-9e21-11e7-98b3-a54b8c08800b.png)

**Comment by wesinalves** [comment]
try to import in command prompt to see what happens

**Comment by elmagnifico9** [comment]
I am not sure if I understood correctly but here's what I did in command prompt. It says it cannot find metadata (during the installation with conda env create I did not get any error)

![error5](https://user-images.githubusercontent.com/32112414/30695569-8ddf19d2-9ea6-11e7-901c-90fec19d1ff8.jpg)

Thanks!

**Comment by wesinalves** [comment]
i see you didn't activate nilmtk-env, did you?

**Comment by elmagnifico9** [comment]
Yes, with calling the nilmtk-env, I still get the same error. 

![image](https://user-images.githubusercontent.com/32112414/30697154-fb7a0fd8-9eab-11e7-872d-a3f47b525106.png)

**Comment by wesinalves** [comment]
let me see you environment.yml file

**Comment by elmagnifico9** [comment]
![image](https://user-images.githubusercontent.com/32112414/30697531-517c4fda-9ead-11e7-94d2-4b3eac7bbaf1.png)

Thank you for your prompt replies.

**Comment by wesinalves** [comment]
Well, seems to be alright. But, the error in jupyter kernel is different from error in prompt. Unfortunately, i don't know how i can help you anymore. Wait for help form others developers or try to reinstall all.

**Comment by elmagnifico9** [comment]
I tried it on another system and getting the same error. So I guess I'm doing one part wrong.
Anyway, thank you very much for your help.

**Comment by elmagnifico9** [comment]
Problem solved! I followed the instruction on the other link for windows and now it works.
https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install_dev.md

**Comment by wesinalves** [comment]
Great! did you find a especific problem?

**Comment by elmagnifico9** [comment]
I couldn't figure out what the problem was last time, but with the link I sent in the previous comment, everything worked smoothly.

**Comment by nipunbatra** [comment]
Sorry this was troublesome for you. We're always looking for people to help us create a `pip/conda` binary. Would be great if you'd like to contribute!
