### ISSUE TITLE
Error in downloading from dataport

### ISSUE THREAD

**Issue by elmagnifico9** [nilmtk/nilmtk#614]
Hello.

Is there a need to make a change to the default settings of dataset_converter of dataport for downloading a portion of this data set? I am following the source code for downloading from dataport 

http://nilmtk.github.io/nilmtk/master/_modules/nilmtk/dataset_converters/dataport/download_dataport.html 
and the provided example http://nilmtk.github.io/nilmtk/master/nilmtk.dataset_converters.dataport.html#nilmtk.dataset_converters.dataport.download_dataport.download_dataport

but cannot download the data.

![errordataport](https://user-images.githubusercontent.com/32112414/30750318-27586d92-9f84-11e7-9dd1-f9fd132016a6.jpg)

![errordataport2](https://user-images.githubusercontent.com/32112414/30750322-296113d2-9f84-11e7-8070-770ce816746f.jpg)

Also, the __init__.py in dataset_converters, the command line for import download_dataport is commented, but if I comment it out, I am getting the same error.

**Comment by nipunbatra** [comment]
Do any of the other converters work for you? If they do, it should be possible to resolve this bug by finding the differences in comparison to what's working.

**Comment by elmagnifico9** [comment]
No, seems others are not working either. I downloaded the entire REDD dataset, decompressed it and placed it the data folder in nilmtk but it's not working
![error5](https://user-images.githubusercontent.com/32112414/30810864-606bb84e-a1d4-11e7-811f-b0f44b093e48.png)

**Comment by elmagnifico9** [comment]
Ok, at least the converter for REDD works fine now!

I had to change 
convert_redd('/data/REDD/low_freq', '/data/REDD/redd.h5')
to 
convert_redd('/data/REDD/low_freq', 'data/REDD/redd.h5')

But for the Dataport I have the same problem as mentioned in the first post.

**Comment by nipunbatra** [comment]
I can't reproduce the bug. I get

```python
In [1]: import nilmtk

In [2]: from nilmtk.dataset_converters.dataport import download_dataport

In [3]: download_dataport
Out[3]: <module 'nilmtk.dataset_converters.dataport.download_dataport' from '/Users/nipunbatra/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/nilmtk/dataset_converters/dataport/download_dataport.pyc'>

In [4]: nilmtk.dataset_converters.dataport.download_dataport
Out[4]: <module 'nilmtk.dataset_converters.dataport.download_dataport' from '/Users/nipunbatra/anaconda2/envs/nilmtk-env/lib/python2.7/site-packages/nilmtk/dataset_converters/dataport/download_dataport.pyc'>

```

**Comment by PMeira** [comment]
I requested an account to access Dataport and test if the converter still works fine, but the original issue was just a typo in the docs. You can import and use the converter as follows:

```python
from nilmtk.dataset_converters.dataport.download_dataport import download_dataport
download_dataport('username', 'password', '/path/output_filename.h5', periods_to_load = {26: ('2014-04-01', '2014-05-01')})
```

**Comment by PMeira** [comment]
It just needed a minor fix for Python 3, done in https://github.com/nilmtk/nilmtk/commit/934970c18af492b3874f4d9b4ab341ecd582603c.
