### ISSUE TITLE
Use NILMTK to test my own data

### ISSUE THREAD

**Issue by nadyy** [nilmtk/nilmtk#616]
Hi everybody, i'm new in the using of NILMTK to test desaggregation algorithm. What i would like to do is to use my own global power collected from my own building(aggregated power), to make test with a dataset such as REDD in order to get the consumption of each appliance. Please can somebody help me on how i can proceed to afford this?

**Comment by jonathanrjpereira** [comment]
+1

**Comment by nipunbatra** [comment]
Yes. See this:
https://github.com/nipunbatra/Gemello/blob/master/code/fhmm_minutes.py
