### ISSUE TITLE
Error when loading REDD low_freq data

### ISSUE THREAD

**Issue by zhengzhuang3** [nilmtk/nilmtk#617]
Hi! I also encountered the bug as https://github.com/nilmtk/nilmtk/issues/300
the error is always " cannot find the dictionary,  ""/data/REDD does not exist", it makes me crazy.
However, It doesn't work when I did what I can according to the comments.
Anyone here can help me please?
Thank you so much!!

**Comment by zhengzhuang3** [comment]
I think I already killed this bug. 
first, I put the REDD file folder into the installing file folder of nilmtk.
Then, I used the absolute path and added 'r' ahead the path to prevent escaping.
the code is as follows:
 convert_redd(r'D:\program\nilmtk\nilmtk\data\REDD\low_freq',r'D:\program\nilmtk\nilmtk\data\REDD\redd.h5')
however, if i drop the 'r', the same error shows again. 
I suggest using the absolute path and add escape character. Hope to be helpful to others!

**Comment by drekisen** [comment]
Hi how are things.

Does it mean this is the way h5 files are created?

I have this problem that I don't know how I can generate those files or where they are generated, because the "data" folder does not exist in my nilmtk installation folder.

Greetings
