### ISSUE TITLE
Greend converter - metadata error in building0.yaml

### ISSUE THREAD

**Issue by MartinNeighbours** [nilmtk/nilmtk#618]
The appliance name is dishwasher in this metadata set and I believe it should be dish washer.  This causes the greend conversion to fail in _sanity_check_appliances.

line 94 building0.yaml

old:
- type: dishwasher
new:
- type: dish washer

**Comment by baztastic** [comment]
I believe this is actually an issue with the `nilmtk/nilm_metadata` repo

This is fixed by adding a new appliance after `dish washer` to 
`nilm_metadata/nilm_metadata/central_metadata/appliance_types/wet.yaml`
with the following code:
```
dishwasher:
  parent: dish washer
```
I'll issue a pull request to `nilm_metadata` tomorrow.
