### ISSUE TITLE
Greend: Fix dataset.yaml timezone incorrect: too many timezones in this block, create separate data columns

### ISSUE THREAD

**Issue by MartinNeighbours** [nilmtk/nilmtk#620]
The timezone in dataset.yaml is inconsistent with the timezone used in the converter.

The converter sets to CET, in dataset.yaml it is set to Europe/Vienna

Whilst these are both the same thing, it causes the codebase to fall over with an error

too many timezones in this block, create separate data columns

To solve this problem:

Change line 8 in dataset.yaml
Old:
timezone: Europe/Vienna
New:
timezone: CET

**Comment by PMeira** [comment]
Closing this as it was handled in #625
