### ISSUE TITLE
Power series all data does not return a frequency for the series

### ISSUE THREAD

**Issue by MartinNeighbours** [nilmtk/nilmtk#624]
**Impact** 

I've found that this can cause problems with plotting - see my comment 2b on #451.  The work-around is to change the plotting order as I did in 2b.

At the moment power series is returning a frequency of None because pd.concat in power_series_all_data in electric.py over-rides the index frequency in the chunks in the list.

When the data is plotted, pandas infers the frequency (if it's set to 60s the resulting graph will have an inferred axis frequency of T (minute), so this issue won't always be obvious.

To reproduce force the sample_period to 60 (see below) and plot a graph.  Then do 
ax.freq

and it should come back with T, depending on what pandas has inferred

Any subsequent plots to the graph with a different sample rate (e.g. from a dataframe sampled at 60S will result in the labels being lost as the axis is reset (this may be a bug in Pandas!)

## Fix

To fix this problem change electric.py line 119

from:

`            all_data = pd.concat(chunks)`

to:

```
            freq = chunks[0].index.freqstr    
            all_data = pd.concat(chunks)
            all_data = all_data.asfreq(freq)

```

## Test

```
from nilmtk import DataSet
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams

rcParams['figure.figsize'] = (13,6)
plt.style.use('ggplot')

train = DataSet('<your data set>')
train.set_window(start='2015-02-01',end="2015-02-02")
train_elec = train.buildings[2].elec
sub_meters = train_elec.submeters()
df_sub_meters = sub_meters.load(sample_period=60).next() 

duration = train_elec.get_timeframe().timedelta.total_seconds()
new_width = int(duration/60)

fig = plt.figure()
ax = train_elec.mains().plot( width=new_width,chunksize=1000,plot_kwargs={'c':'darkgreen'})
df_sub_meters['power']['active'].plot(ax=ax,**{'c':'salmon','label':'sub meters total'} )
ax.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
ax.set_title('Mixed plot with mains sampled at 60 seconds and sub-meter sampled at 60s')

```

Before:

![image](https://user-images.githubusercontent.com/33223741/33078913-0143d3a4-cecc-11e7-8738-5b6532131644.png)

After:

![image](https://user-images.githubusercontent.com/33223741/33078751-8c9fd4f8-cecb-11e7-932b-85a30a8f4aae.png)

**Comment by PMeira** [comment]
@MartinNeighbours Thanks for reporting, I'll take a look for v0.3. Note that the plots you attached are the same though.

**Comment by PMeira** [comment]
Looks like it's handled in Pandas for 0.25:
https://github.com/pandas-dev/pandas/issues/3232

I did wrote this (untested) from the snippet to put in nilmtk.utils -- for reference it something like this pops up again:

```python
def freq_concat(dfs, **kwargs):
    """
    Concatenate a list of dataframes, preserving the frequency attribute
    if they all match. 
    
    Pandas as of version 0.24.1 drops this information.

    Parameters
    ----------
    dfs: list of pandas.DataFrame
    
    kwargs: parameters to pandas.concat
    
    Returns
    -------
    pandas.DataFrame, concatenated data 
    """

    freqs = set(df.index.freqstr for df in dfs)
    all_data = pd.concat(dfs, **kwargs)
    if len(freqs) == 1:
        all_data = all_data.asfreq(freq)
        
    return all_data
```
