### ISSUE TITLE
When trying to plot REDD dataset

### ISSUE THREAD

**Issue by sanketvijaydesai** [nilmtk/nilmtk#628]
![image](https://user-images.githubusercontent.com/19215185/34074610-f6c73d7c-e306-11e7-9c96-abe78e218385.png)

**Comment by nipunbatra** [comment]
You can ignore this for now..I think we removed print_dict from all the notebooks.

**Comment by sanketvijaydesai** [comment]
Yes it’s not working. But now the software is working completely fine. I would also like to note the problems I faced during my successful test of the software.
1. The packages had to be downgraded in following order to remove all import errors etc.
Panda -> as specified in the file (done from conda)
Scipy -> 0.17.0 (done from conda)
2. While running in Jupiter notebook I had to import files
Import sip
Import hmmlearn
Import Nilmtk
Import nilm_metadata

Only after all these steps it has worked. 
Please let me know if I have ran it in a wrong way and suggest me possible changes
