### ISSUE TITLE
Win 10 UnicodeDecodeError: 'cp950' codec can't decode byte 0xc3 in position 1586: illegal multibyte sequence

### ISSUE THREAD

**Issue by zhengzhuang3** [nilmtk/nilmtk#634]
I did NILMTK installation as the developers' guide on Win 10,64 system, but the final "nosetests" always failed as showed in error fragment 1.
![capture](https://user-images.githubusercontent.com/32953951/35315706-d469d3dc-0108-11e8-8675-0371595e22f7.JPG)

 Then I ignored this error and continued. Another error appeared as follows.
![capture jpg2](https://user-images.githubusercontent.com/32953951/35315715-e0b40068-0108-11e8-85ee-1a9ed12705ce.JPG)

Anyone have ideas about it? please help me, thanks!

**Comment by nipunbatra** [comment]
Did this get resolved?

**Comment by zhengzhuang3** [comment]
Yes. But I forget how to fix it because it has passed a long time. Sorry about that.
