### ISSUE TITLE
The method to download environment.yml

### ISSUE THREAD

**Issue by shinji1401** [nilmtk/nilmtk#636]
Hello,

I'm a newbie to GitHub and python, I am trying to install the nilmtk according to the manual.([https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install_user.md])
But I am already stuck at #1. I am using Mac.  The situation is as following.
・Installed python 2.7 (anaconda).
・Made the  nilmtk_work  folder. 
・Input "curl https://raw.githubusercontent.com/nilmtk/nilmtk/master/environment.yml" on the terminal.
 → I assume some files should be downloaded on the nilmtk_work  folder but nothing is downloaded and instead of that, the following appears on the terminal 

name: nilmtk-env
dependencies:
- python=2.7
- Cython>=0.19.1
- bottleneck>=0.6.0
- numpy>=1.8.0
- numexpr>=2.2.2
- pytables
- pandas==0.19.2
- matplotlib
- networkx==1.9.1
- scipy>=0.16.1
- scikit-learn>=0.14
- jupyter
- ipython
- six
- future
- nose
- coverage
- pip
- pip:  # Install packages which are not in conda. Install these using pip:
    - coveralls
    - hmmlearn==0.1.1
    - psycopg2 # not available in conda for Windows.  See issue #462
    - git+https://github.com/nilmtk/nilm_metadata.git#egg=nilm_metadata
    - git+https://github.com/nilmtk/nilmtk.git#egg=nilmtk
    - ipykernel # Needed to get jupyter notebook working with different kernel

Why is this ? If I input "https://raw.githubusercontent.com/nilmtk/nilmtk/master/environment.yml" directly on the internet browser, the same sentence appears, but I don't understand what is happening. Can you help me? 
Thank you.

**Comment by nipunbatra** [comment]
Please see: https://www.youtube.com/watch?v=XZJH0CHxIMA

**Comment by shinji1401** [comment]
Sorry, it seems I made a ridiculous question. I solved it. Thank you for your answer.
