### ISSUE TITLE
Which dataset should I use?

### ISSUE THREAD

**Issue by jonathanrjpereira** [nilmtk/nilmtk#638]
I have managed to build a circuit which can calculate the current, active & reactive power of the loads connected.

I am in the process of testing out some classification algorithms using this circuit.

In order to test the system, I require a dataset which samples attributes such as current, active & reactive power with their respective labels.

Are there any datasets that can meet these requirements.

**Comment by nipunbatra** [comment]
PS: http://blog.oliverparson.co.uk/2012/06/public-data-sets-for-nialm.html

At least iAWE (http://iawe.github.io) should suit your needs.
