### ISSUE TITLE
gt_overall = gt_overall[pred_overall.columns] issue

### ISSUE THREAD

**Issue by sanketvijaydesai** [nilmtk/nilmtk#643]
![image](https://user-images.githubusercontent.com/19215185/37071680-ca982938-2211-11e8-8286-110a2bed237e.png)

**Comment by raktim2015** [comment]
Can you provide the full code?

**Comment by rajatgupta1234** [comment]
![Capture](https://user-images.githubusercontent.com/46721220/58421820-9f7dd700-80ae-11e9-9a83-6c72765e4fb3.PNG)

@sanketvijaydesai  The code works. Please try again or elaborate more about the issue.

**Comment by nipunbatra** [comment]
Closing this. @sanketvijaydesai Please provide more details if the error persists for you.
