### ISSUE TITLE
Output the Readings

### ISSUE THREAD

**Issue by sanketvijaydesai** [nilmtk/nilmtk#645]
Hello
I would like ask if there is any function to output the data from mermory to a local .dat file or .txt file
e.g. Output chunk_drop_na to apparant.txt

Thanks

**Comment by sanketvijaydesai** [comment]
%store chunk_drop_na >apparant.txt stores only few readings. not the whole object

**Comment by nipunbatra** [comment]
`chunk_drop_na` is a Pandas series/dataframe right? Just search online for writing pandas series/dataframe to CSV.
