### ISSUE TITLE
AttributeError: 'module' object has no attribute 'period'

### ISSUE THREAD

**Issue by metwebber** [nilmtk/nilmtk#646]
I am trying to run nilmtk codes by using iawe dataset. But when I call TimeFrameGroup class ( for exp, in df = next(fridge.load()) ), it is giving the error:

if isinstance(timeframes, pd.period.PeriodIndex):

AttributeError: 'module' object has no attribute 'period'

I tried "conda install pandas=0.19.2" as it is mentioned before, but it didn't fix. Can you help me?

**Comment by nipunbatra** [comment]
@PMeira updated a lot of dependencies recently. Can you please reinstall?

**Comment by PMeira** [comment]
Yep, that's one of the API changes from Pandas. The current version addresses this.
