### ISSUE TITLE
Questions about ingesting on-disk csv data

### ISSUE THREAD

**Issue by rbliu** [nilmtk/nilmtk#648]
Hi, I'm a newb here, so please forgive my ignorance.

I can go through all the steps processing the existing public datasets as shown in the tutorial. But I have no idea how to convert some on-disk csv data+ yaml metadata into the desired HDF5 format. 

So, for instance, I have a directory like:
```
data/
└── random_csv
    ├── building1
    │   └── elec
    │       ├── meter1.csv
    │       ├── meter2.csv
    │       ├── meter3.csv
    │       ├── meter4.csv
    │       └── meter5.csv
    └── metadata
        ├── building1.yaml
        ├── dataset.yaml
        └── meter_devices.yaml
```

Could anyone kindly show me explicitly how to generate the corresponding HDF5 file that can fit into the following pipeline?
Thanks!

**Comment by PMeira** [comment]
Checking the code for some of the existing dataset converters is a simple way to understand how to do that.
