### ISSUE TITLE
KeyError: 0 while disaggregating by CO

### ISSUE THREAD

**Issue by metwebber** [nilmtk/nilmtk#651]
I am getting KeyError:0 while disaggregating İAWE dataset by combinatorial optimization. Can you help about the reason of it?

```python
import nilmtk
from nilmtk import *
import matplotlib.pyplot as pl
from nilmtk.disaggregate import CombinatorialOptimisation
import numpy as np
import pandas as pd
from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
from nilmtk.disaggregate import CombinatorialOptimisation, fhmm_exact

%matplotlib inline

# Dividing into train and test
train = DataSet("nilmtk-master/data/iawe.h5")
train.set_window(start=None, end='2013-08-05')
test = DataSet("nilmtk-master/data/iawe.h5")
test.set_window(start='2013-08-05', end=None)
train_elec = train.buildings[1].elec
test_elec = test.buildings[1].elec

# CO
co = CombinatorialOptimisation()
co.train(train.buildings[1].elec)
'''
Training model for submeter 'ElecMeter(instance=3, building=1, dataset='iAWE', appliances=[Appliance(type='fridge', instance=1)])'
Training model for submeter 'ElecMeter(instance=4, building=1, dataset='iAWE', appliances=[Appliance(type='air conditioner', instance=1)])'
Training model for submeter 'ElecMeter(instance=5, building=1, dataset='iAWE', appliances=[Appliance(type='air conditioner', instance=2)])'
Training model for submeter 'ElecMeter(instance=6, building=1, dataset='iAWE', appliances=[Appliance(type='washing machine', instance=1)])'
Training model for submeter 'ElecMeter(instance=7, building=1, dataset='iAWE', appliances=[Appliance(type='computer', instance=1)])'
Training model for submeter 'ElecMeter(instance=8, building=1, dataset='iAWE', appliances=[Appliance(type='clothes iron', instance=1)])'
Training model for submeter 'ElecMeter(instance=9, building=1, dataset='iAWE', appliances=[Appliance(type='unknown', instance=1)])'
Training model for submeter 'ElecMeter(instance=10, building=1, dataset='iAWE', appliances=[Appliance(type='television', instance=1)])'
Training model for submeter 'ElecMeter(instance=11, building=1, dataset='iAWE', appliances=[Appliance(type='wet appliance', instance=1)])'
Training model for submeter 'ElecMeter(instance=12, building=1, dataset='iAWE', appliances=[Appliance(type='motor', instance=1)])'
Done training!
'''

disag_filename ='co-disag.h5'
output = HDFDataStore(disag_filename, 'w')

# Disaggregation
co.disaggregate(test_elec.mains(), output)
'''
Loading data for meter ElecMeterID(instance=2, building=1, dataset='iAWE')     
Done loading data all meters for this chunk.
Estimating power demand for 'ElecMeter(instance=3, building=1, dataset='iAWE', appliances=[Appliance(type='fridge', instance=1)])'
Estimating power demand for 'ElecMeter(instance=4, building=1, dataset='iAWE', appliances=[Appliance(type='air conditioner', instance=1)])'
Estimating power demand for 'ElecMeter(instance=5, building=1, dataset='iAWE', appliances=[Appliance(type='air conditioner', instance=2)])'
Estimating power demand for 'ElecMeter(instance=6, building=1, dataset='iAWE', appliances=[Appliance(type='washing machine', instance=1)])'
Estimating power demand for 'ElecMeter(instance=7, building=1, dataset='iAWE', appliances=[Appliance(type='computer', instance=1)])'
Estimating power demand for 'ElecMeter(instance=8, building=1, dataset='iAWE', appliances=[Appliance(type='clothes iron', instance=1)])'
Estimating power demand for 'ElecMeter(instance=9, building=1, dataset='iAWE', appliances=[Appliance(type='unknown', instance=1)])'
Estimating power demand for 'ElecMeter(instance=10, building=1, dataset='iAWE', appliances=[Appliance(type='television', instance=1)])'
Estimating power demand for 'ElecMeter(instance=11, building=1, dataset='iAWE', appliances=[Appliance(type='wet appliance', instance=1)])'
Estimating power demand for 'ElecMeter(instance=12, building=1, dataset='iAWE', appliances=[Appliance(type='motor', instance=1)])'
Traceback (most recent call last):

  File "<ipython-input-22-3edbda939fc1>", line 1, in <module>
    co.disaggregate(test_elec.mains(), output)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\envs\nilmtk-env\lib\site-packages\nilmtk\disaggregate\combinatorial_optimisation.py", line 161, in disaggregate
    appliance_power = appliance_powers[i]

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\pandas\core\frame.py", line 2139, in __getitem__
    return self._getitem_column(key)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\pandas\core\frame.py", line 2146, in _getitem_column
    return self._get_item_cache(key)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\pandas\core\generic.py", line 1842, in _get_item_cache
    values = self._data.get(item)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\pandas\core\internals.py", line 3843, in get
    loc = self.items.get_loc(item)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\pandas\core\indexes\base.py", line 2527, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))

  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc

  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc

  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item

  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item

KeyError: 0
'''
```

(EDIT BY @PMeira: formatting)

**Comment by PMeira** [comment]
The problem here was just a indexing change in Pandas: we now have to use `df.iloc` to get the column instead of a plain integer. Committing the fix soon.

Here's a faster example to reproduce the issue:

```python
from nilmtk.disaggregate import CombinatorialOptimisation
from nilmtk import DataSet, HDFDataStore

train = DataSet("/data/iawe/iawe.h5")
train.set_window(start='2013-08-01', end='2013-08-05')
train_elec = train.buildings[1].elec

test = DataSet("/data/iawe/iawe.h5")
test.set_window(start='2013-08-05', end='2013-08-10')
test_elec = test.buildings[1].elec

co = CombinatorialOptimisation()
co.train(train.buildings[1].elec)

disag_filename ='co-disag.h5'
output = HDFDataStore(disag_filename, 'w')
co.disaggregate(test_elec.mains(), output)
```

@metwebber Thanks for reporting!

**Comment by FeizNouri** [comment]
Hi i have the same issue 

i get this when i try to do: 

#disag_filename = join(data_dir, 'wikienergy-disag.h5')
output = HDFDataStore('/home/feiz/nilmtk/data/wikienergy-disag.h5', 'w')
co.disaggregate(elec.mains(), output)


i get : 

Loading data for meter ElecMeterID(instance=2, building=1, dataset='REDD')     
Done loading data all meters for this chunk.
Estimating power demand for 'ElecMeter(instance=5, building=1, dataset='REDD', appliances=[Appliance(type='fridge', instance=1)])'
Estimating power demand for 'ElecMeter(instance=6, building=1, dataset='REDD', appliances=[Appliance(type='dish washer', instance=1)])'
Estimating power demand for 'ElecMeter(instance=7, building=1, dataset='REDD', appliances=[Appliance(type='sockets', instance=1)])'
Estimating power demand for 'ElecMeter(instance=8, building=1, dataset='REDD', appliances=[Appliance(type='sockets', instance=2)])'
Estimating power demand for 'ElecMeter(instance=9, building=1, dataset='REDD', appliances=[Appliance(type='light', instance=1)])'
Estimating power demand for 'ElecMeter(instance=11, building=1, dataset='REDD', appliances=[Appliance(type='microwave', instance=1)])'
Estimating power demand for 'ElecMeter(instance=12, building=1, dataset='REDD', appliances=[Appliance(type='unknown', instance=1)])'
Estimating power demand for 'ElecMeter(instance=13, building=1, dataset='REDD', appliances=[Appliance(type='electric space heater', instance=1)])'
Estimating power demand for 'ElecMeter(instance=14, building=1, dataset='REDD', appliances=[Appliance(type='electric stove', instance=1)])'
Estimating power demand for 'ElecMeter(instance=15, building=1, dataset='REDD', appliances=[Appliance(type='sockets', instance=3)])'
Estimating power demand for 'ElecMeter(instance=16, building=1, dataset='REDD', appliances=[Appliance(type='sockets', instance=4)])'
Estimating power demand for 'ElecMeter(instance=17, building=1, dataset='REDD', appliances=[Appliance(type='light', instance=2)])'
Estimating power demand for 'ElecMeter(instance=18, building=1, dataset='REDD', appliances=[Appliance(type='light', instance=3)])'
Estimating power demand for 'ElecMeter(instance=19, building=1, dataset='REDD', appliances=[Appliance(type='unknown', instance=2)])'
Estimating power demand for 'MeterGroup(meters=
  ElecMeter(instance=3, building=1, dataset='REDD', appliances=[Appliance(type='electric oven', instance=1)])
  ElecMeter(instance=4, building=1, dataset='REDD', appliances=[Appliance(type='electric oven', instance=1)])
)'
Estimating power demand for 'MeterGroup(meters=
  ElecMeter(instance=10, building=1, dataset='REDD', appliances=[Appliance(type='washer dryer', instance=1)])
  ElecMeter(instance=20, building=1, dataset='REDD', appliances=[Appliance(type='washer dryer', instance=1)])
)'

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2524             try:
-> 2525                 return self._engine.get_loc(key)
   2526             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 0

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-67-fffeef869c07> in <module>()
      1 #disag_filename = join(data_dir, 'wikienergy-disag.h5')
      2 output = HDFDataStore('/home/feiz/nilmtk/data/wikienergy-disag.h5', 'w')
----> 3 co.disaggregate(elec.mains(), output)

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/disaggregate/combinatorial_optimisation.py in disaggregate(self, mains, output_datastore, **load_kwargs)
    159 
    160             for i, model in enumerate(self.model):
--> 161                 appliance_power = appliance_powers[i]
    162                 if len(appliance_power) == 0:
    163                     continue

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2137             return self._getitem_multilevel(key)
   2138         else:
-> 2139             return self._getitem_column(key)
   2140 
   2141     def _getitem_column(self, key):

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/frame.py in _getitem_column(self, key)
   2144         # get column
   2145         if self.columns.is_unique:
-> 2146             return self._get_item_cache(key)
   2147 
   2148         # duplicate columns & possible reduce dimensionality

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/generic.py in _get_item_cache(self, item)
   1840         res = cache.get(item)
   1841         if res is None:
-> 1842             values = self._data.get(item)
   1843             res = self._box_item_values(item, values)
   1844             cache[item] = res

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/internals.py in get(self, item, fastpath)
   3841 
   3842             if not isna(item):
-> 3843                 loc = self.items.get_loc(item)
   3844             else:
   3845                 indexer = np.arange(len(self.items))[isna(self.items)]

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2525                 return self._engine.get_loc(key)
   2526             except KeyError:
-> 2527                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2528 
   2529         indexer = self.get_indexer([key], method=method, tolerance=tolerance)

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 0


please help me understand what is df.iloc and how to use it !!!!
