### ISSUE TITLE
TypeError: cannot concatenate object of type "<type 'dict'>"

### ISSUE THREAD

**Issue by metwebber** [nilmtk/nilmtk#652]
I am using IAWE dataset in order to make disaggregation but it is giving an error as "TypeError: cannot concatenate object of type "<type 'dict'>"; only pd.Series, pd.DataFrame, and pd.Panel (deprecated) objs are valid". Do you know the reason of it?

```import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nilmtk
from nilmtk import *
import warnings
plt.style.use('ggplot')
warnings.filterwarnings('ignore')
%matplotlib inline
```
# Train and Test
```
iawe = DataSet('nilmtk-master/data/iawe.h5')
train = DataSet('nilmtk-master/data/iawe.h5')
test = DataSet('nilmtk-master/data/iawe.h5')

train.set_window(end="2013-08-05")
test.set_window(start="2013-08-05")

train_elec = train.buildings[1].elec
test_elec = test.buildings[1].elec

test_mains_df = test_elec.mains().load().next()
```
# Selecting top 5 appliances
```
top_5_train_elec= train_elec.submeters().select_top_k(k=5)
top_5_train_elec

```
# Training: FHMM
```
start = time.time()
fhmm = fhmm_exact.FHMM()
fhmm.train(top_5_train_elec, sample_period= 60)
end = time.time()
print("Runtime =", end-start, "seconds.")
```
# Disaggregation
```
pred= {}
gt= {}

for i, chunk in enumerate(test_elec.mains().load(sample_period=60, physical_quantity='power',ac_type='active')):
    chunk_drop_na = chunk.dropna()
    pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)
    gt[i]={}
    
     for meter in test_elec.submeters().meters: 
        gt[i][meter] = meter.load(sample_period=60,physical_quantity='power',ac_type='active').next()

gt_overall = pd.concat(gt)
```

```
Traceback (most recent call last):

  File "<ipython-input-7-ffeae9796b22>", line 1, in <module>
    gt_overall = pd.concat(gt)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\pandas\core\reshape\concat.py", line 212, in concat
    copy=copy)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\pandas\core\reshape\concat.py", line 272, in __init__
    raise TypeError(msg)

TypeError: cannot concatenate object of type "<type 'dict'>"; only pd.Series, pd.DataFrame, and pd.Panel (deprecated) objs are valid
```

(EDIT by @PMeira: formatting)

**Comment by metwebber** [comment]
Thank you, @PMeira . When I apply it, everything worked until:

`for appliance in gt_overall.columns:
   rms_error[appliance] = np.sqrt(mean_squared_error(gt_overall[appliance], pred_overall[appliance]))`


  File "<ipython-input-175-08c3902ae7e9>", line 2, in <module>
    rms_error[appliance] = np.sqrt(mean_squared_error(gt_overall[appliance], pred_overall[appliance]))

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\sklearn\metrics\regression.py", line 238, in mean_squared_error
    y_true, y_pred, multioutput)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\sklearn\metrics\regression.py", line 76, in _check_reg_targets
    y_true = check_array(y_true, ensure_2d=False)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\sklearn\utils\validation.py", line 453, in check_array
    _assert_all_finite(array)

  File "C:\Users\metwebber\AppData\Local\Continuum\anaconda2\lib\site-packages\sklearn\utils\validation.py", line 44, in _assert_all_finite
    " or a value too large for %r." % X.dtype)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').



How can I handle it?

**Comment by nipunbatra** [comment]
I think I know how to fix the issue. Hint- one of the two arrays gt_overal[appliance] or pred_overall[appliance] has a NaN. 

We want to compute the errors only for non NaN entries.

**Comment by metwebber** [comment]
Hi @nipunbatra, can you help me about fixing it?

**Comment by nipunbatra** [comment]
@PMeira Would you have time to look into this? I think this requires the following steps:

1. Find indices idx1, idx2 where GT and Pred have non-NaN values
2. Take intersection of idx1 and idx2. Let this be idx
3. Compute the error as MSE(GT[idx], Pred[idx])

**Comment by PMeira** [comment]
Just a quick update since I'll take more time to investigate this: the solution proposed by @nipunbatra is enough to fix that issue, but there is something else I'm investigating related to the two instances of "air conditioner". I'll be back to investigating this in a few days.

For the MSE issue per se, I ended up with the following, which should be more general. It puts the series in a temporary dataframe to align the index and drop the NaNs, with some extra checks. As the dataset has multiple instances of the same appliance, I added the column index to the output column to disambiguate them.

Since the function got a little long, it could be useful to add a variation of this to NILMTK's `utils` module later on.

```python
def compute_rmse(gt, pred):
    from sklearn.metrics import mean_squared_error
    rms_error = {}
    for app_idx, app_name in enumerate(gt.columns):
        gt_app = gt.iloc[:, app_idx]
        pred_app = pred.iloc[:, app_idx]
        if pred_app.empty: 
            continue
            
        df_app = pd.DataFrame({'gt': gt_app, 'pred': pred_app}, index=gt_app.index).dropna()
        if not df_app.empty:
            app_rms_error = np.sqrt(mean_squared_error(df_app['gt'], df_app['pred']))
        else:
            app_rms_error = np.NaN
            
        rms_error['{} (#{})'.format(app_name, app_idx)] = app_rms_error
                                       
    return pd.Series(rms_error)
```

**Comment by PMeira** [comment]
`nilmtk.utils.compute_rmse` is a more resilient version of the compute_rmse snippet listed here. The examples now use it.
