### ISSUE TITLE
CSV to NILMTK DF

### ISSUE THREAD

**Issue by ImenJarroudi** [nilmtk/nilmtk#653]
hello I'm doing research on NILM and would like to know if there's is  a tutorial on how to convert the random_csv data provided as a dataset to the nilmtk DF and (not https://raw.githubusercontent.com/nilmtk/writing/master/figures/NILMTK_UML.png)
, using the CSVDATASTORE only and note converting it to a hdf file using the HDFDATASORE)...I really appreciate any help.

**Comment by PMeira** [comment]
There's probably no tutorial for that. Just replacing the HDFDataStore instance with a CSVDataStore one should be enough for simple cases.

Personally I would not recommend using the CSV datastore though. If the dataset is small, converting to HDF would not be an issue. If the dataset is large, using the CSV datastore is a bad idea.
