### ISSUE TITLE
issue with print_dict

### ISSUE THREAD

**Issue by FeizNouri** [nilmtk/nilmtk#656]
Hi 
i'm trying to follow this demo 
https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/data.ipynb
i'm using pycharm and i have a problem with print_dict 
in the tuto it should display some data:
![image](https://user-images.githubusercontent.com/38252619/38742761-4b78c7fc-3f35-11e8-9049-687f3b138ba7.png)
but in pycharm i wrote: 
`from nilmtk.dataset_converters import convert_redd
convert_redd('/home/feiz/nilmtk/data/REDD/low_freq/', '/home/feiz/nilmtk/data/REDD/redd.h5')
from nilmtk import DataSet
from nilmtk.utils import print_dict
redd = DataSet('/home/feiz/nilmtk/data/REDD/redd.h5')
print_dict(redd.metadata)
print_dict(redd.buildings)`
and the result : 
`/home/feiz/anaconda3/envs/nilmtk-env/bin/python /home/feiz/nilmtk/myscripts/script1.py
/home/feiz/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/IPython/lib/pretty.py:91: DeprecationWarning: IPython.utils.signatures backport for Python 2 is deprecated in IPython 6, which only supports Python 3
  from IPython.utils.signatures import signature
/home/feiz/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/jedi/_compatibility.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Loading house 1... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 
Loading house 2... 1 2 3 4 5 6 7 8 9 10 11 
Loading house 3... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 
Loading house 4... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 
Loading house 5... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 
Loading house 6... 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 
Loaded metadata
Done converting YAML metadata to HDF5!
Done converting REDD to HDF5!
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
Closing remaining open files:/home/feiz/nilmtk/data/REDD/redd.h5...done

Process finished with exit code 0
`
why it wrote <IPython.core.display.HTML object>??!!

**Comment by PMeira** [comment]
@FeizNouri `print_dict()` is a utility function to pretty print on a Jupyter (formerly IPython) notebook. If you're not using a notebook, you can inspect the object directly.
