### ISSUE TITLE
problem understanding how nilmtk works

### ISSUE THREAD

**Issue by FeizNouri** [nilmtk/nilmtk#657]
hi i am new to nilm i have problems understanding how it works. i'm working on an energy monitoring project and from what i read i see that nilm will be useful to implement specially that we want our monitor to identifies the appliances just from the house consumption. but i have many questions and after two weeks of researching i still couldn't answer them:
-can i use my own database on nilm if yes how and how my database should be like in order to use nilmtk algorithms 
-couldn't understand the algorithms ( couldn't find a simple guide for people how are new to this subject and what to use nilmtk)
-should i understand the Phd's papers in order to use nilmtk ?

**Comment by PMeira** [comment]
> -can i use my own database on nilm if yes how and how my database should be like in order to use nilmtk algorithms

Besides the [docs](https://github.com/nilmtk/nilmtk/blob/master/docs/manual/development_guide/writing_a_dataset_converter.md), there are several dataset converters in NILMTK module itself and more external code from other datasets that could be used as examples. 

> -couldn't understand the algorithms ( couldn't find a simple guide for people how are new to this subject and what to use nilmtk)
> -should i understand the Phd's papers in order to use nilmtk ?

I'd recommend at least reading some papers. Ideally we should have better documentation, of course, but right now we're working on getting the code back in shape.
