### ISSUE TITLE
UKDALE disaggregation error

### ISSUE THREAD

**Issue by sanketvijaydesai** [nilmtk/nilmtk#658]
pred = {}
gt= {}

for i, chunk in enumerate(test_elec.mains().load(physical_quantity='power',ac_type='apparent',sample_period=60)):
    chunk_drop_na = chunk.dropna()
    pred[i] = cop.disaggregate_chunk(chunk_drop_na)
    gt[i]={}
    
    for meter in test_elec.submeters().meters:
        # Only use the meters that we trained on (this saves time!)    
        gt[i][meter] = next(meter.load(sample_period=60))
    gt[i] = pd.DataFrame({k:v.squeeze() for k,v in iteritems(gt[i])}, index=next(iter(gt[i].values())).index).dropna()

![image](https://user-images.githubusercontent.com/19215185/38904945-ad6bb0aa-42f0-11e8-818f-b64a4f667303.png)

**Comment by sanketvijaydesai** [comment]
gt[i][meter] = next(meter.load(ac_type='active',sample_period=60))
solved the above error giving another one

![image](https://user-images.githubusercontent.com/19215185/38905016-2c531908-42f1-11e8-986a-01a90d822621.png)

**Comment by PMeira** [comment]
@sanketvijaydesai Can you provide a minimal example (including all imports, loading the dataset, etc.)? I can investigate it in a few days.
