### ISSUE TITLE
Better handling of warnings

### ISSUE THREAD

**Issue by PMeira** [nilmtk/nilmtk#660]
Currently, warnings (at least `ImportWarning` and `DeprecationWarning`) are filtered/silenced in various places. Ideally we could either:

1. provide a central configuration, but that's redundant with the actual `warnings` module, or
2. don't mess with the `warnings` module state at all, or
3. use [context managers](https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings) to suppress warnings only in NILMTK code

I believe the last option should provide the best behavior.

**Comment by nipunbatra** [comment]
Sounds good @PMeira
