### ISSUE TITLE
meter.load question

### ISSUE THREAD

**Issue by niuwan1** [nilmtk/nilmtk#661]
hey.I have a quetion about meter.load function,I tried to load data from nilmtk
Format into DataFrame format,so I tried meter.load(sample_period = 60),I noticed the parameter 'sample period' in load function in nilmtk was set default in self.sample_period,that's why I set sample_period = 60,however,when I tried to plot the DataFrame data that I loaded from nilmtk,the curves was pretty different from the original curves in nilmtk.for example,fridge = train_elec.submeters()['fridge'], then I plot curve of fridge as follow:
fridge.plot()
But when I loaded the fridge meter to DataFrame format,I plot fridge(DataFrame format) as follow:
Fridge_df.plot(). I found something different between these two format,the peaks in the duration is totally different.

**Comment by secretdragon** [comment]
![index](https://user-images.githubusercontent.com/35625414/39124637-b8190754-472e-11e8-8294-32b55c48682a.png)
![index1](https://user-images.githubusercontent.com/35625414/39124676-dc3d6cf6-472e-11e8-9cca-d6b3a52f1275.png)

**Comment by nipunbatra** [comment]
The x-axis in the two plots doesn't seem to be the same to me!

**Comment by secretdragon** [comment]
@nipunbatra 
Thank you very much for replying. I'm sorry for putting the wrong pair images,here is my specific code and result:
`
import nimlltk 
from nilmtk import DataSet
import matplotlib.pyplot as plt

dataset = Dataset('/home/xm/Deskstop/wikienergy-20132.h5')
elec =  dataset.buildings[18].elec
dish_washer = elec.sumeters()['dish washer']
dish_washer.plot()
plt.show()
dish_washer_df = next(dish_washer.load())
dish_wahser_df.plot()
plt.show()
`
the results is as follows, the first picture is ploted from nilmtk format,and the second is the DatFrame format:

![dish ni](https://user-images.githubusercontent.com/35625414/39162459-2bfd28d4-47a8-11e8-9ed2-c9067c878db8.png)

![dish pd](https://user-images.githubusercontent.com/35625414/39162466-32237b3c-47a8-11e8-91ba-2a3efa15a026.png)
these two pictures look familiar,but they are actually different.
here is my another try:
`
sockets = elec.submeters()['sockets']

sockets.plot()

plt.show()

sockets_df = next(sockets.load())

sockets_df.plot()

plt.show()
`
here is the result, the first picture is ploted from nilmtk format,and the second is the DatFrame format:

![sockets pd](https://user-images.githubusercontent.com/35625414/39162734-942a9486-47a9-11e8-83d4-43da4875aa87.png)

![sockets pd](https://user-images.githubusercontent.com/35625414/39162999-0d12ff18-47ab-11e8-886d-9c6dd47531a5.png)



these two might seems pretty different,the peak in these two pictures are totally different. I don't know how the function of meter.load() function works, I tried to modified the elecmeter.py to satisfy my need,but the format conversion in this file is complex, I saw some examples like `sockets_df = sockets.power_series()` to get the DataFrame format of sockets,but the result is the same as above.

**Comment by nipunbatra** [comment]
@secretdragon NILMTK's `elec.plot()` method is a smart plotting interface which downsamples data in case there is too much to plot! So, you're likely to get different results.

**Comment by niuwan1** [comment]
@nipunbatra Thanks for replying again. Can I understand this way? `elec.plot()` is  plotting few data in real elec data, the loaded data from NIMLTK actually contains all the real data. If so, here is another question:
I have tried to load the mains data and six kinds of different meters from wikienergy dataset,all the data loaded from a same building,and in this building,it includes only one site meter,I loaded all the data to DataFrame format,use `data = pandas.concat([mains data, meter_1, meter_2,meter_3,meters_4,meter_5,meter_6],axis = 1)` to concat mains data and  all the meters data, then I tried the following code: `data['mains'] - data.drop(['mains']).sum(axis = 1)` , the result actually contains some negative values,that means mains data loaded from NILMTK is actually lower than the sum of all the meters if meter.load() is loading the all the real data from NILMTK,however, in my opinion, mains power should be higher than the sum power of combination meters. I wondered this problem is derived from the data itself or the data loaded from NILMTK is not  the real  data, but after NILMTK's processing.

**Comment by 2ndMessiah** [comment]
I found this issue long ago and intuitively thought the nilmtk built-in .plot method down sampled the meterdata a lot to cause the differrent appearance. For my usual usage, I prefer to load the Dataframe then plot instead of plotting them using the niltmtk's .plot.

BTW:是中国人吗？是的话能否加一下好友讨论一下？ 身边研究这个的太少了。谢谢。: )

**Comment by nipunbatra** [comment]
Assigned to @raktim2015

**Comment by raktim2015** [comment]
Use 
`next(mains.load())` to load the data directly into pandas dataframe.
Code :-
```
train_elec = train.buildings[1].elec
mains = train_elec.mains()
mains_df = next(mains.load())
mains_df.head()
mains_df.plot()
```
to load the data directly into pandas dataframe. It will give the summed up value of two site meters.
To plot each site-meter seperately, 
```
dict={}
dict[1]=next(train_elec[1].load(sample_period=60)) #storing each meter power in dictionary
dict[2]=next(train_elec[2].load(sample_period=60))
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
dict[1].plot(ax=ax, legend=True)
dict[2].plot(ax=ax, legend=True)

```

**Comment by raktim2015** [comment]
This code will load each site meter into DataFrame and plot the same.
```
from nilmtk import DataSet
from nilmtk.utils import print_dict
import matplotlib.pyplot as plt
import pandas as pd
import nilmtk
%matplotlib inline

redd = DataSet('D:\\Work\\SRIP\\low_freq.h5')
elec=redd.buildings[1].elec
train_elec = redd.buildings[1].elec
meter_readings={}
meter_readings[1]=next(train_elec[1].load()) #storing each meter power in dictionary
meter_readings[2]=next(train_elec[2].load())
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
meter_readings[1].plot(ax=ax, legend=True)
meter_readings[2].plot(ax=ax, legend=True)

```
![image](https://user-images.githubusercontent.com/25877767/58562641-4301ef80-8247-11e9-8b2a-fc534d2aef90.png)
