### ISSUE TITLE
AttributeError: Attribute 'metadata' does not exist in node: '/'

### ISSUE THREAD

**Issue by walidsliti** [nilmtk/nilmtk#662]
i'm trying to examine dissagregated data, this is the code 

`disag_filename = join(data_dir, 'redd-disag-co.h5')

disag = DataSet(disag_filename)
disag_elec = disag.buildings[building_number].elec
disag_elec.plot()
disag.store.close()
plt.title("CO");`

BUT I GOT THIS ERROR 

`AttributeError                            Traceback (most recent call last)
<ipython-input-44-ccfe547bfb2a> in <module>()
      1 disag_filename = join(data_dir, 'redd-disag-co.h5')
----> 2 disag = DataSet(disag_filename)
      3 disag_elec = disag.buildings[building_number].elec
      4 disag_elec.plot()
      5 disag.store.close()

/home/ubuntu/nilmtk/nilmtk/dataset.pyc in __init__(self, filename, format)
     44         self.metadata = {}
     45         if filename is not None:
---> 46             self.import_metadata(get_datastore(filename, format))
     47 
     48     def import_metadata(self, store):

/home/ubuntu/nilmtk/nilmtk/dataset.pyc in import_metadata(self, store)
     53         """
     54         self.store = store
---> 55         self.metadata = store.load_metadata()
     56         self._init_buildings(store)
     57         return self

/home/ubuntu/nilmtk/nilmtk/docinherit.pyc in f(*args, **kwargs)
     44         @wraps(self.mthd, assigned=('__name__', '__module__'))
     45         def f(*args, **kwargs):
---> 46             return self.mthd(obj, *args, **kwargs)
     47 
     48         return self.use_parent_doc(f, overridden)

/home/ubuntu/nilmtk/nilmtk/datastore/hdfdatastore.pyc in load_metadata(self, key)
    174             node = self.store.get_node(key)
    175 
--> 176         metadata = deepcopy(node._v_attrs.metadata)
    177         return metadata
    178 

/home/ubuntu/anaconda3/envs/nilmtk-env/lib/python2.7/site-packages/tables/attributeset.pyc in __getattr__(self, name)
    290         if not name in self._v_attrnames:
    291             raise AttributeError("Attribute '%s' does not exist in node: "
--> 292                                  "'%s'" % (name, self._v__nodepath))
    293 
    294         # Read the attribute from disk. This is an optimization to read

AttributeError: Attribute 'metadata' does not exist in node: '/'`

any help ?
![github](https://user-images.githubusercontent.com/26322476/39127158-171adc92-46fc-11e8-8026-b9d2fd37e012.PNG)
![22](https://user-images.githubusercontent.com/26322476/39127201-3acb0b76-46fc-11e8-8c44-e017fa8708ae.PNG)

**Comment by nipunbatra** [comment]
What tutorial are you referring to?

@PMeira - I think some of the issues like this one arise because we have not removed some of the older working examples.

**Comment by walidsliti** [comment]
co_Fhmm tuto is it old ?

**Comment by nipunbatra** [comment]
@walidsliti : can you point to the exact URL?

**Comment by walidsliti** [comment]
https://github.com/nilmtk/nilmtk/blob/master/notebooks/co_fhmm.ipynb

**Comment by walidsliti** [comment]
can you please check this link jack said that this issue fixed but i didn't get it 
https://github.com/nilmtk/nilmtk/issues/373

**Comment by PMeira** [comment]
@walidsliti The updated notebooks are in https://github.com/nilmtk/nilmtk/tree/master/docs/manual/user_guide -- take a look at those, and if you still find problems based on those, let me know. 

Most of the older notebooks use an older version/API so some don't work at all anymore. There's a warning in the folder but it's probably not visible enough

@nipunbatra Yeah, I think I'll move those out of the root folder, so they're not the first thing people look into.

**Comment by PMeira** [comment]
@nipunbatra I moved the folder into the `docs` folder and renamed it into `outdated`. I don't think we should remove them yet, maybe after extracting more (non-redundant) examples into the main docs. Done in https://github.com/nilmtk/nilmtk/commit/c87b3c4001132e2c9defc47197713529d5edef8e

**Comment by walidsliti** [comment]
thanks

**Comment by anosharshad** [comment]
@walidsliti How did you remove this error ?
Attribute 'metadata' does not exist in node: '/'
