### ISSUE TITLE
Hart85 disaggregation problem

### ISSUE THREAD

**Issue by metwebber** [nilmtk/nilmtk#664]
I'm trying to disaggregate IAWE dataset by using Hart85 algorithm. But it is giving "RuntimeError: The model needs to be instantiated before calling disaggregate.  For example, the model can be instantiated by running train."   while using disaggregate function.
Can you help me for this problem?

`disag_filename= 'iawe-disag-hart85-new.h5'` 
`output= HDFDataStore(disag_filename, 'w')` 
`mains= elec.mains()` 
`h.disaggregate(mains,output)`

**Comment by PMeira** [comment]
I think the error is clear enough in this case -- you need to train the model. I found another error in the training though, so I'll keep this open until I look into it (will take a few days).

**Comment by metwebber** [comment]
The error is appearing although I trained the model, so I could not understand the reason of it.

**Comment by PMeira** [comment]
I finally fixed multiple issues related to Hart85 recently but it may still need a full review. Since the original issue here is already fixed, I'm closing this in favor of #674 to reduce duplicated issues.
