### ISSUE TITLE
convert_redd error

### ISSUE THREAD

**Issue by metwebber** [nilmtk/nilmtk#665]
I am converting redd dataset to hdf5 format by;
`from nilmtk.dataset_converters import convert_redd`
`convert_redd('Desktop/REDD/low_freq', 'Desktop/REDD/redd.h5')`

However, it is giving this error. Can you help me?
  File "c:\users\metwebber\appdata\local\continuum\anaconda2\envs\nilmtk-env\lib\site-packages\nilmtk\datastore\hdfdatastore.py", line 186, in save_metadata
    node._v_attrs.metadata = metadata

AttributeError: 'NoneType' object has no attribute '_v_attrs'

**Comment by PMeira** [comment]
Check your folder structure (and pass full paths if you're not doing that yet).

E.g., try something like:

```python
from nilmtk.dataset_converters import convert_redd
convert_redd('c:/users/your_local_username/Desktop/REDD/low_freq', 'c:/users/your_local_username/Desktop/data/REDD/redd.h5')
```

Here's my file tree, your `c:/users/your_local_username/Desktop/REDD/low_freq` needs to contain the same file list:
```
C:\data\REDD\low_freq>dir /s /b
C:\data\REDD\low_freq\house_1
C:\data\REDD\low_freq\house_2
C:\data\REDD\low_freq\house_3
C:\data\REDD\low_freq\house_4
C:\data\REDD\low_freq\house_5
C:\data\REDD\low_freq\house_6
C:\data\REDD\low_freq\house_1\channel_1.dat
C:\data\REDD\low_freq\house_1\channel_10.dat
C:\data\REDD\low_freq\house_1\channel_11.dat
C:\data\REDD\low_freq\house_1\channel_12.dat
C:\data\REDD\low_freq\house_1\channel_13.dat
C:\data\REDD\low_freq\house_1\channel_14.dat
C:\data\REDD\low_freq\house_1\channel_15.dat
C:\data\REDD\low_freq\house_1\channel_16.dat
C:\data\REDD\low_freq\house_1\channel_17.dat
C:\data\REDD\low_freq\house_1\channel_18.dat
C:\data\REDD\low_freq\house_1\channel_19.dat
C:\data\REDD\low_freq\house_1\channel_2.dat
C:\data\REDD\low_freq\house_1\channel_20.dat
C:\data\REDD\low_freq\house_1\channel_3.dat
C:\data\REDD\low_freq\house_1\channel_4.dat
C:\data\REDD\low_freq\house_1\channel_5.dat
C:\data\REDD\low_freq\house_1\channel_6.dat
C:\data\REDD\low_freq\house_1\channel_7.dat
C:\data\REDD\low_freq\house_1\channel_8.dat
C:\data\REDD\low_freq\house_1\channel_9.dat
C:\data\REDD\low_freq\house_1\labels.dat
C:\data\REDD\low_freq\house_2\channel_1.dat
C:\data\REDD\low_freq\house_2\channel_10.dat
C:\data\REDD\low_freq\house_2\channel_11.dat
C:\data\REDD\low_freq\house_2\channel_2.dat
C:\data\REDD\low_freq\house_2\channel_3.dat
C:\data\REDD\low_freq\house_2\channel_4.dat
C:\data\REDD\low_freq\house_2\channel_5.dat
C:\data\REDD\low_freq\house_2\channel_6.dat
C:\data\REDD\low_freq\house_2\channel_7.dat
C:\data\REDD\low_freq\house_2\channel_8.dat
C:\data\REDD\low_freq\house_2\channel_9.dat
C:\data\REDD\low_freq\house_2\labels.dat
C:\data\REDD\low_freq\house_3\channel_1.dat
C:\data\REDD\low_freq\house_3\channel_10.dat
C:\data\REDD\low_freq\house_3\channel_11.dat
C:\data\REDD\low_freq\house_3\channel_12.dat
C:\data\REDD\low_freq\house_3\channel_13.dat
C:\data\REDD\low_freq\house_3\channel_14.dat
C:\data\REDD\low_freq\house_3\channel_15.dat
C:\data\REDD\low_freq\house_3\channel_16.dat
C:\data\REDD\low_freq\house_3\channel_17.dat
C:\data\REDD\low_freq\house_3\channel_18.dat
C:\data\REDD\low_freq\house_3\channel_19.dat
C:\data\REDD\low_freq\house_3\channel_2.dat
C:\data\REDD\low_freq\house_3\channel_20.dat
C:\data\REDD\low_freq\house_3\channel_21.dat
C:\data\REDD\low_freq\house_3\channel_22.dat
C:\data\REDD\low_freq\house_3\channel_3.dat
C:\data\REDD\low_freq\house_3\channel_4.dat
C:\data\REDD\low_freq\house_3\channel_5.dat
C:\data\REDD\low_freq\house_3\channel_6.dat
C:\data\REDD\low_freq\house_3\channel_7.dat
C:\data\REDD\low_freq\house_3\channel_8.dat
C:\data\REDD\low_freq\house_3\channel_9.dat
C:\data\REDD\low_freq\house_3\labels.dat
C:\data\REDD\low_freq\house_4\channel_1.dat
C:\data\REDD\low_freq\house_4\channel_10.dat
C:\data\REDD\low_freq\house_4\channel_11.dat
C:\data\REDD\low_freq\house_4\channel_12.dat
C:\data\REDD\low_freq\house_4\channel_13.dat
C:\data\REDD\low_freq\house_4\channel_14.dat
C:\data\REDD\low_freq\house_4\channel_15.dat
C:\data\REDD\low_freq\house_4\channel_16.dat
C:\data\REDD\low_freq\house_4\channel_17.dat
C:\data\REDD\low_freq\house_4\channel_18.dat
C:\data\REDD\low_freq\house_4\channel_19.dat
C:\data\REDD\low_freq\house_4\channel_2.dat
C:\data\REDD\low_freq\house_4\channel_20.dat
C:\data\REDD\low_freq\house_4\channel_3.dat
C:\data\REDD\low_freq\house_4\channel_4.dat
C:\data\REDD\low_freq\house_4\channel_5.dat
C:\data\REDD\low_freq\house_4\channel_6.dat
C:\data\REDD\low_freq\house_4\channel_7.dat
C:\data\REDD\low_freq\house_4\channel_8.dat
C:\data\REDD\low_freq\house_4\channel_9.dat
C:\data\REDD\low_freq\house_4\labels.dat
C:\data\REDD\low_freq\house_5\channel_1.dat
C:\data\REDD\low_freq\house_5\channel_10.dat
C:\data\REDD\low_freq\house_5\channel_11.dat
C:\data\REDD\low_freq\house_5\channel_12.dat
C:\data\REDD\low_freq\house_5\channel_13.dat
C:\data\REDD\low_freq\house_5\channel_14.dat
C:\data\REDD\low_freq\house_5\channel_15.dat
C:\data\REDD\low_freq\house_5\channel_16.dat
C:\data\REDD\low_freq\house_5\channel_17.dat
C:\data\REDD\low_freq\house_5\channel_18.dat
C:\data\REDD\low_freq\house_5\channel_19.dat
C:\data\REDD\low_freq\house_5\channel_2.dat
C:\data\REDD\low_freq\house_5\channel_20.dat
C:\data\REDD\low_freq\house_5\channel_21.dat
C:\data\REDD\low_freq\house_5\channel_22.dat
C:\data\REDD\low_freq\house_5\channel_23.dat
C:\data\REDD\low_freq\house_5\channel_24.dat
C:\data\REDD\low_freq\house_5\channel_25.dat
C:\data\REDD\low_freq\house_5\channel_26.dat
C:\data\REDD\low_freq\house_5\channel_3.dat
C:\data\REDD\low_freq\house_5\channel_4.dat
C:\data\REDD\low_freq\house_5\channel_5.dat
C:\data\REDD\low_freq\house_5\channel_6.dat
C:\data\REDD\low_freq\house_5\channel_7.dat
C:\data\REDD\low_freq\house_5\channel_8.dat
C:\data\REDD\low_freq\house_5\channel_9.dat
C:\data\REDD\low_freq\house_5\labels.dat
C:\data\REDD\low_freq\house_6\channel_1.dat
C:\data\REDD\low_freq\house_6\channel_10.dat
C:\data\REDD\low_freq\house_6\channel_11.dat
C:\data\REDD\low_freq\house_6\channel_12.dat
C:\data\REDD\low_freq\house_6\channel_13.dat
C:\data\REDD\low_freq\house_6\channel_14.dat
C:\data\REDD\low_freq\house_6\channel_15.dat
C:\data\REDD\low_freq\house_6\channel_16.dat
C:\data\REDD\low_freq\house_6\channel_17.dat
C:\data\REDD\low_freq\house_6\channel_2.dat
C:\data\REDD\low_freq\house_6\channel_3.dat
C:\data\REDD\low_freq\house_6\channel_4.dat
C:\data\REDD\low_freq\house_6\channel_5.dat
C:\data\REDD\low_freq\house_6\channel_6.dat
C:\data\REDD\low_freq\house_6\channel_7.dat
C:\data\REDD\low_freq\house_6\channel_8.dat
C:\data\REDD\low_freq\house_6\channel_9.dat
C:\data\REDD\low_freq\house_6\labels.dat
```

**Comment by metwebber** [comment]
Correcting the path solved the problem, thank you @PMeira.

**Comment by bsbk1** [comment]
@PMeira Could you please give me some help?
I am nbw converting APMds dataset to hdf5 format and always with the following error:
'NoneType' object has no attribute '_v_attrs'
Here is my code：
from nilmtk.dataset_converters import convert_redd
convert_redd('C:/Users/EDZ/Desktop/redd/AMPds/version_1/data', 'C:/Users/EDZ/Desktop/redd/AMPds/version_1/AMPds.h5')

The complete error is：
Traceback (most recent call last):
  File "C:/Users/EDZ/Desktop/redd/AMPds/version_1/py_version/AMPds.py", line 5, in <module>
    convert_redd('C:/Users/EDZ/Desktop/redd/AMPds/version_1/data', 'C:/Users/EDZ/Desktop/redd/AMPds/version_1/AMPds.h5')
  File "C:\anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\dataset_converters\redd\convert_redd.py", line 56, in convert_redd
    store)
  File "C:\anaconda\envs\nilmtk-env\lib\site-packages\nilm_metadata\convert_yaml_to_hdf5.py", line 96, in save_yaml_to_datastore
    store.save_metadata('/'+building, building_metadata)
  File "C:\anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\docinherit.py", line 46, in f
    return self.mthd(obj, *args, **kwargs)
  File "C:\anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\datastore\hdfdatastore.py", line 196, in save_metadata
    node._v_attrs.metadata = metadata
AttributeError: 'NoneType' object has no attribute '_v_attrs'
Closing remaining open files:C:/Users/EDZ/Desktop/redd/AMPds/version_1/AMPds.h5...done

**Comment by bsbk1** [comment]
@PMeira Could you please give me some help?
I am now converting APMds dataset to hdf5 format and always with the following error:
'NoneType' object has no attribute '_v_attrs'
Here is my code：
from nilmtk.dataset_converters import convert_redd
convert_redd('C:/Users/EDZ/Desktop/redd/AMPds/version_1/data', 'C:/Users/EDZ/Desktop/redd/AMPds/version_1/AMPds.h5')

The complete error is：
Traceback (most recent call last):
File "C:/Users/EDZ/Desktop/redd/AMPds/version_1/py_version/AMPds.py", line 5, in 
convert_redd('C:/Users/EDZ/Desktop/redd/AMPds/version_1/data', 'C:/Users/EDZ/Desktop/redd/AMPds/version_1/AMPds.h5')
File "C:\anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\dataset_converters\redd\convert_redd.py", line 56, in convert_redd
store)
File "C:\anaconda\envs\nilmtk-env\lib\site-packages\nilm_metadata\convert_yaml_to_hdf5.py", line 96, in save_yaml_to_datastore
store.save_metadata('/'+building, building_metadata)
File "C:\anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\docinherit.py", line 46, in f
return self.mthd(obj, *args, **kwargs)
File "C:\anaconda\envs\nilmtk-env\lib\site-packages\nilmtk\datastore\hdfdatastore.py", line 196, in save_metadata
node._v_attrs.metadata = metadata
AttributeError: 'NoneType' object has no attribute '_v_attrs'
Closing remaining open files:C:/Users/EDZ/Desktop/redd/AMPds/version_1/AMPds.h5...done
