### ISSUE TITLE
"Import nilmtk" error

### ISSUE THREAD

**Issue by metwebber** [nilmtk/nilmtk#667]
When I am trying to import nilmtk, it is giving an error. Do you know the reason?

`import nilmtk` 

Traceback (most recent call last):

  File "<ipython-input-15-067a978f12a0>", line 1, in <module>
    import nilmtk

  File "c:\users\metwebber\nilmtk\nilmtk\__init__.py", line 11, in <module>
    from nilmtk.elecmeter import ElecMeter

  File "c:\users\metwebber\nilmtk\nilmtk\elecmeter.py", line 8, in <module>
    from .preprocessing import Clip

  File "c:\users\metwebber\nilmtk\nilmtk\preprocessing\__init__.py", line 1, in <module>
    from .clip import Clip

  File "c:\users\metwebber\nilmtk\nilmtk\preprocessing\clip.py", line 3, in <module>
    from ..node import Node

  File "c:\users\metwebber\nilmtk\nilmtk\node.py", line 3, in <module>
    from nilm_metadata import recursively_update_dict

ImportError: cannot import name recursively_update_dict

**Comment by PMeira** [comment]
Did you forget to activate the correct conda environment?

**Comment by metwebber** [comment]
No, I'm activating it and then connecting to Spyder by using Anaconda Prompt.

**Comment by metwebber** [comment]
But it's not importing recursively_update_dict in ipython shell as well.

**Comment by PMeira** [comment]
Sorry, I can't reproduce that error. 

Have you tried reinstalling the package (nilm_metadata) or the whole environment?

**Comment by nipunbatra** [comment]
I think the easiest solution would be to reinstall nilmtk from scratch. I
also believe you were using python 2.x.

**Comment by metwebber** [comment]
Reinstalling it solved the problem. Thank you so much @nipunbatra and @PMeira. We can close the issue.

**Comment by dwelcaslu** [comment]
I am interested in using nilmtk with Spyder. 
Can anyone please explain how I can do it ? 

I couldnt find how to connect the nilmtk environment to spyder.

**Comment by PMeira** [comment]
@dwelcaslu You have at least two alternatives

## 1) Using a system Spyder with the nilmtk-env's interpreter

- First find where the interpreter EXE for the environment is located -- take a look at https://github.com/nilmtk/nilmtk/issues/462#issuecomment-383320508 for more info. 
- Then, in Spyder, you can set you interpreter in **"Tools > Preferences > Python interpreter** -- check **"Use the following intepreter"** and select the EXE from nilmtk-env. 

Note that you may need to install some extra packages in the environment to make Spyder happy. Spyder itself shows some instructions for that.

## 2) Using a separate Spyder installation in nilmtk-env

Open a command prompt, activate the nilmtk-env conda environment, and install Spyder:

    activate nilmtk-env
    conda install spyder

After installing, you can just run `spyder` on the activated environment to open Spyder.

If this installation don't produce Start Menu shortcuts, you can run `where spyder` to find where Spyder's EXE is located; in my case, it installed in `C:\Users\meira\AppData\Local\conda\conda\envs\nilmtk-env\Scripts\spyder.exe`. Just run this EXE directly to open the Spyder from the environment -- with the default settings, it will automatically use the env's interpreter.

**Comment by dwelcaslu** [comment]
Thank you very much @PMeira !
