### ISSUE TITLE
'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by FeizNouri** [nilmtk/nilmtk#668]
i'm testing the notebook in issue #546 
and when i get to this : 

![11](https://user-images.githubusercontent.com/38252619/39757330-6d4c978a-52c4-11e8-9718-84d0b59f65a8.jpg)

i get this error :

Loading data for meter ElecMeterID(instance=2, building=1, dataset='REDD')     
Done loading data all meters for this chunk.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-140-c6ec4fd4af84> in <module>()
      9     for meter in test_elec.submeters().meters:
     10         # Only use the meters that we trained on (this saves time!)
---> 11         gt[i][meter] = meter.load(sample_period=120).next()
     12     gt[i] = pd.DataFrame({k:v.squeeze() for k,v in gt[i].iteritems()}, index=gt[i].values()[0].index).dropna()

AttributeError: 'generator' object has no attribute 'next'

![22](https://user-images.githubusercontent.com/38252619/39757425-b6a0e29c-52c4-11e8-90c5-bf3c30fc08f7.jpg)

i tried to modify it like this

![33](https://user-images.githubusercontent.com/38252619/39757360-8086a8cc-52c4-11e8-90c2-15008b23d851.jpg)

it worked but i still get another error: 
AttributeError                            Traceback (most recent call last)
<ipython-input-141-ebe3b25be49f> in <module>()
     11         f = meter.load(sample_period=120)
     12         gt[i][meter] = next(f)
---> 13     gt[i] = pd.DataFrame({k:v.squeeze() for k,v in gt[i].iteritems()()}, index=gt[i].values()[0].index).dropna()

AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by PMeira** [comment]
Don't use the old notebooks. There are updated notebooks in the `docs/manual/user_guide` and there is equivalent code in one of them.

Either way, this kind of issue requires the end user to have some experience with Pandas and be able to understand what's happening. I'd suggest inspecting the data through all steps.
