### ISSUE TITLE
Converting Data without Metadata

### ISSUE THREAD

**Issue by Lukay1994** [nilmtk/nilmtk#671]
Hello,
I'm new to NILMTK framework and i'm trying to write a converter for my own dataset. When using the REDD dataset, the framework seems to work fine on my machine.
My dataset is just containing a building id (same as meter id), a time and active power data. No sub-metered appliance data or stuff like that. Converting the data to HDF5 Store seems to work fine. However, if i want to open my dataset with:

`irland = DataSet('./data/irland/irland.h5')`

i get this error when i don't specify metadata:
`AttributeError: Attribute 'metadata' does not exist in node: '/building6496'`

The problem is, i only have some general metadata. Is there a way to convert and use datasets without metadata?

**Comment by nipunbatra** [comment]
https://github.com/nilmtk/nilmtk/blob/master/nilmtk/tests/generate_data.py should be helpful to you to show how you can workaround.

Specifically look at: `def create_co_test_hdf5()`

**Comment by Lukay1994** [comment]
Thanks, that worked fine!
