### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by AbrahamDarefaynie** [nilmtk/nilmtk#673]
I have been trying to install NILMTK following the steps described on both https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install_user.md  and https://www.youtube.com/watch?v=XZJH0CHxIMA&t=39s, But I got a problem to install it. So anyone who has an idea please help me by giving me detail steps to install it from the beginning.

**Comment by PMeira** [comment]
> But I got a problem to install it. 

Please provide more information:
1. Which OS are you using?
2. Which Python version and distribution?
3. What is the problem?

**Comment by PMeira** [comment]
Since there was no response, I'm closing this. As of now, check #554 for an experimental way of installing using only conda.
