### ISSUE TITLE
Combinatorial Optimisation issue

### ISSUE THREAD

**Issue by jonasbuchberger** [nilmtk/nilmtk#675]
I am working with a dataset  from my university and trying to verify the disaggregation with active and apparant power using Combinatorial Optimisation.

However, it shows ValueError: sequence too large; cannot be greater than 32.
Here is the full error. It seems like the training works.

```pytb
Training model for submeter 'ElecMeter(instance=93, building=1, dataset='BLOND', appliances=[Appliance(type='mobile phone charger', instance=19), Appliance(type='laptop computer', instance=30)])'
Done training!
Loading data for meter ElecMeterID(instance=3, building=1, dataset='BLOND')
Done loading data all meters for this chunk.
Traceback (most recent call last):
  File "test.py", line 275, in <module>
    co_alt()
  File "test.py", line 182, in co_alt
    co.disaggregate(elec.mains(), output)
  File "C:\Users\Jonas\AppData\Local\conda\conda\envs\nilmtk-env\lib\site-packages\nilmtk\disaggregate\combinatorial_optimisation.py", line 158, in disaggregate
    appliance_powers = self.disaggregate_chunk(chunk)
  File "C:\Users\Jonas\AppData\Local\conda\conda\envs\nilmtk-env\lib\site-packages\nilmtk\disaggregate\combinatorial_optimisation.py", line 217, in disaggregate_chunk
    self._set_state_combinations_if_necessary()
  File "C:\Users\Jonas\AppData\Local\conda\conda\envs\nilmtk-env\lib\site-packages\nilmtk\disaggregate\combinatorial_optimisation.py", line 122, in _set_state_combinations_if_necessary
    self.state_combinations = cartesian(centroids)
  File `"C:\Users\Jonas\AppData\Local\conda\conda\envs\nilmtk-env\lib\site-packages\sklearn\utils\extmath.py",` line 488, in cartesian
    ix = np.indices(shape)
  File "C:\Users\Jonas\AppData\Local\conda\conda\envs\nilmtk-env\lib\site-packages\numpy\core\numeric.py", line 2094, in indices
    res = empty((N,)+dimensions, dtype=dtype)
ValueError: sequence too large; cannot be greater than 32
Closing remaining open files:disagg_sum_co.h5...doneconverted_sum.hdf5...done
```
EDIT (by @PMeira): formatting

**Comment by nipunbatra** [comment]
@jonasbuchberger Does it work on 1d data? i.e. does it work if you only pass it active power?

**Comment by MuenchnerWeisswurst** [comment]
@nipunbatra 
We have tried it calling it with 
`co.disaggregate(elec.mains(), output, ac_type = 'active' , physical_quantity='power',sample_period=1)`
and it stills throws the same error.

**Comment by PMeira** [comment]
@jonasbuchberger @MuenchnerWeisswurst Sorry to bother, did you guys manage to find out what was the issue? Or, since the dataset seems huge, is there a simple way to reproduce it?

**Comment by jonasbuchberger** [comment]
We reduced the amount of meters with the top_k function. Then it worked.
We could not find the actual issue. There were about 70 meters in the dataset over a 50 days period.

**Comment by nipunbatra** [comment]
@jonasbuchberger What number of top-k meters did you end up using? Given the exponential complexity and state space of the algorithm, I would not expect it to work well beyond 10-11 appliances.
