### ISSUE TITLE
ValueError: cannot reindex a non-unique index with a method or limit

### ISSUE THREAD

**Issue by walidsliti** [nilmtk/nilmtk#676]
**_i try to run this code to find F1-score_** 
```python
from __future__ import print_function, division
from nilmtk import DataSet, HDFDataStore
from nilmtk.disaggregate import fhmm_exact
from nilmtk.metrics import f1_score
from os.path import join
import matplotlib.pyplot as plt

"""
This file replicates issue #376 (which should now be fixed)
https://github.com/nilmtk/nilmtk/issues/376
"""

data_dir = '/home/ubuntu/nilmtk/data/REDD/low_freq'
building_number = 1
disag_filename = join(data_dir, 'disag-Fhmm' + str(building_number) + '.h5')

data = DataSet(join(data_dir, 'redd.h5'))
print("Loading building " + str(building_number))
elec = data.buildings[building_number].elec

top_train_elec = elec.submeters().select_top_k(k=5)
fhmm = fhmm_exact.FHMM()
fhmm.train(top_train_elec)

output = HDFDataStore(disag_filename, 'w')
fhmm.disaggregate(elec.mains(), output)
output.close()

### f1score fhmm
disag = DataSet(disag_filename)
disag_elec = disag.buildings[building_number].elec

f1 = f1_score(disag_elec, elec)
f1.index = disag_elec.get_labels(f1.index)
f1.plot(kind='barh')
plt.ylabel('appliance');
plt.xlabel('f-score');
plt.title("FHMM");
plt.savefig(join(data_dir, 'f1-fhmm' + str(building_number) + '.png'))
disag.store.close()
####
print("Finishing building " + str(building_number))



```
**_BUt i got this error_** 

```pytb
ValueError                                
Traceback (most recent call last)
<ipython-input-10-6e048b2ba29f> in <module>()
     24 
     25 output = HDFDataStore(disag_filename, 'w')
---> 26 fhmm.disaggregate(elec.mains(), output)
     27 output.close()
     28 

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/disaggregate/fhmm_exact.py in disaggregate(self, mains, output_datastore, **load_kwargs)
    390         warnings.filterwarnings("ignore", category=Warning)
    391 
--> 392         for chunk in mains.power_series(**load_kwargs):
    393 
    394             # Check that chunk is sensible size before resampling

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/electric.py in load_series(self, **kwargs)
    627         physical_quantity = kwargs['physical_quantity']
    628         generator = self.load(**kwargs)
--> 629         for chunk in generator:
    630             if chunk.empty:
    631                 yield chunk

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/metergroup.py in load(self, **kwargs)
    704                 closed='left', freq=freq)
    705             chunk = combine_chunks_from_generators(
--> 706                 index, columns, self.meters, kwargs)
    707             yield chunk
    708 

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/metergroup.py in combine_chunks_from_generators(index, columns, meters, kwargs)
   1776         generator = meter.load(**kwargs_copy)
   1777         try:
-> 1778             chunk_from_next_meter = next(generator)
   1779         except StopIteration:
   1780             continue

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/preprocessing/apply.py in process(self)
     13         self.check_requirements()
     14         for chunk in self.upstream.process():
---> 15             new_chunk = self.func(chunk)
     16             new_chunk.timeframe = chunk.timeframe
     17             if hasattr(chunk, 'look_ahead'):

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/electric.py in resample_func(df)
    143             def resample_func(df):
    144                 resample_kwargs['rule'] = '{:d}S'.format(sample_period)
--> 145                 return safe_resample(df, **resample_kwargs)
    146 
    147             kwargs.setdefault('preprocessing', []).append(

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/utils.py in safe_resample(data, **resample_kwargs)
    422 
    423     try:
--> 424         data = _resample_chain(data, resample_kwargs)
    425     except pytz.AmbiguousTimeError:
    426         # Work-around for

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/utils.py in _resample_chain(data, all_resample_kwargs)
    418             warnings.warn("Not all resample_kwargs were consumed: {}".format(repr(resample_kwargs)))
    419 
--> 420         return how(fill_method(data.resample(rule, **resample_kwargs)))
    421 
    422 

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/utils.py in <lambda>(df)
    405         fill_method_str = all_resample_kwargs.pop('fill_method', None)
    406         if fill_method_str:
--> 407             fill_method = lambda df: getattr(df, fill_method_str)()
    408         else:
    409             fill_method = lambda df: df

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/resample.py in pad(self, limit)
    392         DataFrame.fillna
    393         """
--> 394         return self._upsample('pad', limit=limit)
    395     ffill = pad
    396 

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/resample.py in _upsample(self, method, limit, fill_value)
    966         else:
    967             result = obj.reindex(res_index, method=method,
--> 968                                  limit=limit, fill_value=fill_value)
    969 
    970         result = self._apply_loffset(result)

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    184         @wraps(func)
    185         def wrapper(*args, **kwargs):
--> 186             return func(*args, **kwargs)
    187 
    188         if not PY2:

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/frame.py in reindex(self, *args, **kwargs)
   3561         kwargs.pop('axis', None)
   3562         kwargs.pop('labels', None)
-> 3563         return super(DataFrame, self).reindex(**kwargs)
   3564 
   3565     @Appender(_shared_docs['reindex_axis'] % _shared_doc_kwargs)

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/generic.py in reindex(self, *args, **kwargs)
   3683         # perform the reindex on the axes
   3684         return self._reindex_axes(axes, level, limit, tolerance, method,
-> 3685                                   fill_value, copy).__finalize__(self)
   3686 
   3687     def _reindex_axes(self, axes, level, limit, tolerance, method, fill_value,

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/frame.py in _reindex_axes(self, axes, level, limit, tolerance, method, fill_value, copy)
   3496         if index is not None:
   3497             frame = frame._reindex_index(index, method, copy, level,
-> 3498                                          fill_value, limit, tolerance)
   3499 
   3500         return frame

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/frame.py in _reindex_index(self, new_index, method, copy, level, fill_value, limit, tolerance)
   3504         new_index, indexer = self.index.reindex(new_index, method=method,
   3505                                                 level=level, limit=limit,
-> 3506                                                 tolerance=tolerance)
   3507         return self._reindex_with_indexers({0: [new_index, indexer]},
   3508                                            copy=copy, fill_value=fill_value,

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/pandas/core/indexes/base.py in reindex(self, target, method, level, limit, tolerance)
   3606                 else:
   3607                     if method is not None or limit is not None:
-> 3608                         raise ValueError("cannot reindex a non-unique index "
   3609                                          "with a method or limit")
   3610                     indexer, missing = self.get_indexer_non_unique(target)

ValueError: cannot reindex a non-unique index with a method or limit
```

EDIT (by @PMeira): Formatting

**Comment by EliseBcm** [comment]
Hi,
I got a very similar error both with CO and FHMM disaggregation  (but with the UK-DALE dataset). In my case it seems to be linked to the time re-indexing.  Did you find any solution ?

**Comment by nipunbatra** [comment]
I'd urge to follow the examples from the documentation only and not from prior issues.

**Comment by EliseBcm** [comment]
I should have precised that I am following this documentation : nilmtk/docs/manual/user_guide/comparing_nilm_algorithms.ipynb
I have been using the exact same code as in the documentation, except from the training and testing sets : 
`train = DataSet(path+'/UK_DALE.h5')
test = DataSet(path+'/UK_DALE.h5')
building = 1
train.set_window(end="9-11-2013")
test.set_window(start="9-11-2013", end="3-1-2014")`

The training works, but when trying to disaggregate the testing set, I got the error :
`Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.1.4\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2018.1.4\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2018.1.4\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2018.1.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/BCM5/Dropbox (BCM ENERGY)/Documents_Elise/2 - Analyse des conso/NILM Toolkit/nilmtk_work/disaggregationTestsUKDALE.py", line 82, in <module>
    gt, predictions[clf_name] = predict(clf, test_elec, 120, train.metadata['timezone'])
  File "C:/Users/BCM5/Dropbox (BCM ENERGY)/Documents_Elise/2 - Analyse des conso/NILM Toolkit/nilmtk_work/disaggregationTestsUKDALE.py", line 39, in predict
    for i, chunk in enumerate(test_elec.mains().load(sample_period=sample_period)):
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\preprocessing\apply.py", line 15, in process
    new_chunk = self.func(chunk)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\electric.py", line 145, in resample_func
    return safe_resample(df, **resample_kwargs)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\utils.py", line 424, in safe_resample
    data = _resample_chain(data, resample_kwargs)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\utils.py", line 420, in _resample_chain
    return how(fill_method(data.resample(rule, **resample_kwargs)))
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\utils.py", line 407, in <lambda>
    fill_method = lambda df: getattr(df, fill_method_str)()
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\resample.py", line 471, in pad
    return self._upsample('pad', limit=limit)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\resample.py", line 820, in _upsample
    limit=limit, fill_value=fill_value)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\util\_decorators.py", line 127, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\frame.py", line 2935, in reindex
    return super(DataFrame, self).reindex(**kwargs)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\generic.py", line 3023, in reindex
    fill_value, copy).__finalize__(self)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\frame.py", line 2870, in _reindex_axes
    fill_value, limit, tolerance)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\frame.py", line 2878, in _reindex_index
    tolerance=tolerance)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\indexes\base.py", line 2995, in reindex
    raise ValueError("cannot reindex a non-unique index "
ValueError: cannot reindex a non-unique index with a method or limit
Closing remaining open files:E:/2 - Analyse des conso DONNEES/H5_format/UK_DALE.h5...doneE:/2 - Analyse des conso DONNEES/H5_format/UK_DALE.h5...done
sys:1: ResourceWarning: unclosed <socket.socket fd=1140, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 61174), raddr=('127.0.0.1', 61171)>`

When checking what is reindexed at this step, I saw that the index is : 
DatetimeIndex(['2013-09-11 00:00:00.300000+01:00',
               '2013-09-11 00:00:01.300000+01:00',
               '2013-09-11 00:00:02.300000+01:00',
               '2013-09-11 00:00:03.300000+01:00',
               '2013-09-11 00:00:04.300000+01:00',
               '2013-09-11 00:00:05.200000+01:00',
               '2013-09-11 00:00:06.300000+01:00',
               '2013-09-11 00:00:07.300000+01:00',
               '2013-09-11 00:00:08.300000+01:00',
               '2013-09-11 00:00:09.300000+01:00',
               ...
               '2014-02-28 23:59:50.100000+00:00',
               '2014-02-28 23:59:51.200000+00:00',
               '2014-02-28 23:59:52.200000+00:00',
               '2014-02-28 23:59:53.200000+00:00',
               '2014-02-28 23:59:54.200000+00:00',
               '2014-02-28 23:59:55.200000+00:00',
               '2014-02-28 23:59:56.200000+00:00',
               '2014-02-28 23:59:57.100000+00:00',
               '2014-02-28 23:59:58.200000+00:00',
               '2014-02-28 23:59:59.100000+00:00'],
              dtype='datetime64[ns, Europe/London]', length=14787808, freq=None)
And the target is : 
DatetimeIndex(['2013-09-11 00:00:00+01:00', '2013-09-11 00:01:00+01:00',
               '2013-09-11 00:02:00+01:00', '2013-09-11 00:03:00+01:00',
               '2013-09-11 00:04:00+01:00', '2013-09-11 00:05:00+01:00',
               '2013-09-11 00:06:00+01:00', '2013-09-11 00:07:00+01:00',
               '2013-09-11 00:08:00+01:00', '2013-09-11 00:09:00+01:00',
               ...
               '2014-02-28 23:50:00+00:00', '2014-02-28 23:51:00+00:00',
               '2014-02-28 23:52:00+00:00', '2014-02-28 23:53:00+00:00',
               '2014-02-28 23:54:00+00:00', '2014-02-28 23:55:00+00:00',
               '2014-02-28 23:56:00+00:00', '2014-02-28 23:57:00+00:00',
               '2014-02-28 23:58:00+00:00', '2014-02-28 23:59:00+00:00'],
              dtype='datetime64[ns, Europe/London]', length=246300, freq='60S')
This reindexing is consistent with the 2 minutes time sample that is defined in the documentation code, but I don't see why there is an error.

NB : I also got the same error when trying to use the ECO data set, and with the REFIT dataset I get this error at the first training step.

**Comment by walidsliti** [comment]
@EliseBcm hi, 
try to make the dates like this 
train.set_window(end="2013-11-09")
test.set_window(start="2013-11-09", end="2014-01-03"

**Comment by EliseBcm** [comment]
@walidsliti  
Thank you for your answer ! Unfortunately, I had already tried that and got another error "ValueError: Wrong number of items passed 158398, placement implies 79199" :

Traceback (most recent call last):
  File "C:/Users/BCM5/Dropbox (BCM ENERGY)/Documents_Elise/2 - Analyse des conso/NILM Toolkit/nilmtk_work/disaggregationTestsUKDALE.py", line 79, in <module>
    gt, predictions[clf_name] = predict(clf, test_elec, sample_period, train.metadata['timezone'])
  File "C:/Users/BCM5/Dropbox (BCM ENERGY)/Documents_Elise/2 - Analyse des conso/NILM Toolkit/nilmtk_work/disaggregationTestsUKDALE.py", line 38, in predict
    pred[i] = clf.disaggregate_chunk(chunk_drop_na)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\disaggregate\combinatorial_optimisation.py", line 251, in disaggregate_chunk
    column = pd.Series(predicted_power, index=mains.index, name=i)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\series.py", line 266, in __init__
    data = SingleBlockManager(data, index, fastpath=True)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\internals.py", line 4402, in __init__
    fastpath=True)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\internals.py", line 2957, in make_block
    return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
  File "C:\Users\BCM5\Anaconda3\envs\nilmtk-env\lib\site-packages\pandas\core\internals.py", line 120, in __init__
    len(self.mgr_locs)))
ValueError: Wrong number of items passed 158398, placement implies 79199
Closing remaining open files:E:/2 - Analyse des conso DONNEES/H5_format/UK_DALE.h5...doneE:/2 - Analyse des conso DONNEES/H5_format/UK_DALE.h5...done

The problem comes from this line of combinatorial_optimisation.py : 
`column = pd.Series(predicted_power, index=mains.index, name=i)`

predicted_power has 158398 elements while the index is a DateTimeIndex with half the number of elements (which is logical since there are 79199 minutes between '2013-11-09 00:03:00+00:00' and 2014-01-02 23:59:00+00:00)  : 
DatetimeIndex(['2013-11-09 00:01:00+00:00', '2013-11-09 00:02:00+00:00',
               '2013-11-09 00:03:00+00:00', '2013-11-09 00:04:00+00:00',
               ...
            '2014-01-02 23:56:00+00:00', '2014-01-02 23:57:00+00:00',
               '2014-01-02 23:58:00+00:00', '2014-01-02 23:59:00+00:00'],
              dtype='datetime64[ns, Europe/London]', length=79199, freq='60S')

So apparently the results stored in predicted_power are not correctly computed by minute but by 30 seconds (?). It seems to come from the meter group load function, in the function "predict" defined in nilmtk/docs/manual/user_guide/comparing_nilm_algorithms.ipynb : 
'def predict(clf, test_elec, sample_period, timezone):
    pred = {}
    gt = {}

    for i, chunk in enumerate(test_elec.mains().load(sample_period=sample_period)):
        chunk_drop_na = chunk.dropna()
        pred[i] = clf.disaggregate_chunk(chunk_drop_na)
        gt[i] = {}

        for meter in test_elec.submeters().meters:
            # Only use the meters that we trained on (this saves time!)
            gt[i][meter] = next(meter.load(sample_period=sample_period))
        gt[i] = pd.DataFrame({k: v.squeeze() for k, v in iteritems(gt[i])},
                             index=next(iter(gt[i].values())).index).dropna()

    # If everything can fit in memory
    gt_overall = pd.concat(gt)
    gt_overall.index = gt_overall.index.droplevel()
    pred_overall = pd.concat(pred)
    pred_overall.index = pred_overall.index.droplevel()

    # Having the same order of columns
    gt_overall = gt_overall[pred_overall.columns]

    # Intersection of index
    gt_index_utc = gt_overall.index.tz_convert("UTC")
    pred_index_utc = pred_overall.index.tz_convert("UTC")
    common_index_utc = gt_index_utc.intersection(pred_index_utc)

    common_index_local = common_index_utc.tz_convert(timezone)
    gt_overall = gt_overall.ix[common_index_local]
    pred_overall = pred_overall.ix[common_index_local]
    appliance_labels = [m.label() for m in gt_overall.columns.values]
    gt_overall.columns = appliance_labels
    pred_overall.columns = appliance_labels
    return gt_overall, pred_overall'

**Comment by PMeira** [comment]
(I've been reformatting the comments because, for me, they're just unreadable without formatting.)

I'm closing this since I noticed the original issue was already being tracked in #678 (and seems to be fixed). 

The other issue pointed by @EliseBcm is valid. Notice that the examples provided are made for specific datasets, which is something most people don't seem to realize. If anyone thinks it's worthy to track that, please open a new issue so that doesn't get lost.
