### ISSUE TITLE
 No module named 'nilm_metadata'

### ISSUE THREAD

**Issue by MacciM** [nilmtk/nilmtk#677]
Hi, I am struggling to import the dataset converters. I took a screenshot of the error I got. If any one can help me, I would so appreciate it!
![issue](https://user-images.githubusercontent.com/40349632/41521663-584900e2-72d3-11e8-8411-1262b3d1e5f8.PNG)
Thanks in advance :)

**Comment by nipunbatra** [comment]
Nilm_metadata didn’t get installed based on the error. I think you’d need
to provide greater details into what steps you carried out.

**Comment by MacciM** [comment]
Alright, I just followed the instructions from the user guide. So I created the environment using conda env create, then I activated the environment (activate nilmtk-env), then I just copied and past this line -> 
python -m ipykernel install --user --name nilmtk-env --display-name "Python (nilmtk)". After that I went into jupyter notebook, and pasted 
```
from nilmtk.dataset_converters import convert_redd
```

Am I missing a step?? So I have the nilm_metadata, and I tried looking for the 
```
recursively_update_dict,
```
but I couldnt find it, I not sure... am I suppose to have a recursively_update_dict file under nilm_metedata?

Thank you so much for coming back to me so quickly!!!

**Comment by nipunbatra** [comment]
It's hard to ascertain what's going wrong! Instead of Jupiter notebook, can
you run the same code in an activated Conda environment in IPython shell?

**Comment by walidsliti** [comment]
i got this error before try this line of codes 
conda env create
source activate nilmtk-env
cd ~
git clone https://github.com/nilmtk/nilm_metadata/
cd nilm_metadata; python setup.py develop; cd ..
cd ~/nilmtk
python setup.py develop

**Comment by MacciM** [comment]
@walidsliti thank you, it helped! Though I got stuck again, any thoughts on this one??
![issue2](https://user-images.githubusercontent.com/40349632/41595223-512755cc-73c6-11e8-941a-9c858ecc7f68.PNG) And thank you guys so much for your help!!!!

**Comment by MacciM** [comment]
Hallelujah! I managed! Thank you so much guys! Yes, the nilm-metadata wasn't install so I follow your method, thanks @walidsliti . I appreciate your help!
