### ISSUE TITLE
Time stamp Issue

### ISSUE THREAD

**Issue by sanketvijaydesai** [nilmtk/nilmtk#684]
Hello
I have divided the REDD dataset House 2 building in 2 different chunks i.e. Train and Test
So my Test window starts from 2011-04-25 00:00:03
I want to find this interval in the red dataset file
However when I convert the above reading to a time stamp and find it the the main.dat file the readings are completely different. I think it’s the problem with time stamp. Please suggest me some solution

**Comment by nipunbatra** [comment]
@sanketvijaydesai I am afraid your description is not enough for us to help you.

1. Are you using NILMTK?
2. How do you convert 2011-04-25 00:00:03 to timestamp? Do you account for timezones?
3. Why do you think the problem is with the timestamp? How do you propose we help here?

**Comment by sanketvijaydesai** [comment]
THanks Nipun
I did not minus the timezone difference of -4. Thanks
