### ISSUE TITLE
Timestamp Help

### ISSUE THREAD

**Issue by sanketvijaydesai** [nilmtk/nilmtk#694]
Hello everyone,
Instead of Date and Time, I want the output of a CSV file to be in Timestamp Format. Is it possible to get that using the Nilmtk methods? For e.g.  
My chunk_drop_na gives me entries such as 
2011-04-18 09:30:00-04:00                       336.950012207

I want the date to be displayed as timestamp i.e.
1303133400                                              336.950012207

Thanks

**Comment by PMeira** [comment]
Could you try to provide some sample code? That'd help a lot.

**Comment by nipunbatra** [comment]
This is out of scope of NILMTK. You just need a simple python function to
convert from date time to epoch.

**Comment by sanketvijaydesai** [comment]
I was able to output the entries in excel and convert it to Timestamp. Thanks
