### ISSUE TITLE
Installing NILMTK on Ubuntu 18.04

### ISSUE THREAD

**Issue by klemenjak** [nilmtk/nilmtk#699]
Hello,

I experienced difficulties while installing NILMTK in developer mode on Ubuntu 18.04.
However, installing the package  python-pyqt5 resolves the problem.

best regards

**Comment by PMeira** [comment]
Could you provide more details? The installation itself should not depend on PyQt at all. 
If we depend on PyQt, it would be through Matplotlib, NetworkX or some other dependency.

**Comment by klemenjak** [comment]
We installed NILMTK on an Ubuntu 18.04 server (minimal image) and experienced some issues related to qt5. We fixed it but didn't document how. I will try to reproduce the error and provide more details this week.

**Comment by klemenjak** [comment]
@PMeira We repeated the installation process today on the latest Ubuntu server 18.04 image. The commands  _python setup.py_ ... did not end up in an error message. However, when trying to run nosetets or importing nilmtk, we have experienced the following ImportError:

> File "/home/user/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 158, in <module>
   raise ImportError ("Failed to import any qt binding")
Import Error: Failed to import any qt binding

Installing pyqt5 solved the issue:

> sudo apt-get install  python-pyqt5

So the dependency is through Matplotlib, as you suspected. Maybe this information will be useful for one or two potential NILMTK users.

**Comment by PMeira** [comment]
@klemenjak Thank you! It certainly will help, I opened another issue so I don't forget about it.

The root cause seems to be that the matplotlib from Anaconda uses Qt5Agg as the default backend but doesn't list PyQt5 as a dependency.



I'll setup a similar environment to test
