### ISSUE TITLE
Investigate matplotlib dependency in tests

### ISSUE THREAD

**Issue by PMeira** [nilmtk/nilmtk#701]
As described in https://github.com/nilmtk/nilmtk/issues/699#issuecomment-419984323, importing matplotlib can raise errors during testing. Since testing is non-interactive, we could use a non-interactive backend to avoid this altogether.

We should still document that this could happen to help unsuspecting users.

**Comment by PMeira** [comment]
It seems conda actually lists PyQt as a dependency of matplotlib and should install it automatically, both on Windows and Linux.

@klemenjak Re-reading your comments on #699, I noticed you used apt-get to install PyQt and use it with an Anaconda installation. That's not usual or recommended -- since the package from the system distribution is built against the system Python, it might present other issues later. 

Installing via conda, either manually or using the provided environment.yml, should work as usual though.

**Comment by klemenjak** [comment]
@PMeira I agree with you that this is not a general solution. Let's say I went for the quick&dirty solution.
