### ISSUE TITLE
Possibly found a bug in Metergroup - train_test_split 

### ISSUE THREAD

**Issue by klemenjak** [nilmtk/nilmtk#702]
Hello again!

Today I was confronted with a problem while using function train_test_split of metergroup.py:
```
train_test_split(train_fraction=0.5)
```
My intention was using this built-in function to determine the perfect date to split my dataset into training and testing sections for a given fraction. I executed the following code:
```
EDS = 'redd.h5'
train = DataSet(join(data_directory, EDS))
elec = train.buildings[1].elec
split_point =  train_elec.train_test_split(train_fraction=0.6).date()
print(split_point)
```
Which gave me:
```
Traceback (most recent call last):
  File "script_dataset_evaluations.py", line 64, in evaluate_fhmm
    split_point = train_elec.train_test_split(train_fraction=0.6).date()
  File "/home/users/chklemen/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/metergroup.py", line 1233, in train_test_split
    sample_period = mains.device['sample_period']
AttributeError: 'MeterGroup' object has no attribute 'device'
```
To fix it, I changed line 1223 of metergroup.py from
```
sample_period = mains.device['sample_period']
```
to
```
 sample_period = mains.sample_period()
```
Please have a look on occassion.

**Comment by PMeira** [comment]
Your fix seems to be right. When mains is a `Meter` instead of a `MeterGroup`, the current code works. A `MeterGroup` won't, as you noticed. Both classes expose the `sample_period()`, so using it should work in both cases.

I tested with REDD and COMBED and it works as expected.
