### ISSUE TITLE
Password authentication failed when trying to download Dataport dataset

### ISSUE THREAD

**Issue by aszamzam91** [nilmtk/nilmtk#703]
Hi,

I'm trying to download the dataport dataset using the module 'download_dataport'. I get an authentication error:
FATAL: password authentication failed for user "xxxxxx"

I'm sure that the username and password I use when calling the module are correct. When I use these credentials to log it to (https://dataport.cloud/) I have no problem whatsoever. Should I use different username and password?

Your help is appreciated.
Thanks,
Ahmed

**Comment by PMeira** [comment]
Hi, Ahmed,
The login/password pair for the database (PostgreSQL) is different from the website login. Go to the Advanced Access page on the website and it will list the info you need.

Here's a screenshot of the Advanced Access page in case it helps -- I marked in red the region where the database information is listed.

![image](https://user-images.githubusercontent.com/10246101/45840741-37404f80-bcee-11e8-83cb-2ee0050c2605.png)
