### ISSUE TITLE
Issue with PyTables 3.4.4

### ISSUE THREAD

**Issue by diou** [nilmtk/nilmtk#707]
Hi everyone, new NILMTK user here. Thanks for to all contributors for this amazing resource!

I just wanted to let you know that I had an issue converting GREEND with pytables 3.4.4. When I uninstalled pytables 3.4.4 and installed pytables 3.3.0 everything worked fine. 

Here's the error:

```
Putting into store...
meter 9: 000D6F0003BD8C8E
Putting into store...
Traceback (most recent call last):
  File "test3.py", line 7, in <module>
    convert_greend(source, dest)
  File "/home/diou/miniconda3/envs/nilm/lib/python3.6/site-packages/nilmtk/dataset_converters/greend/convert_greend.py", line 176, in convert_greend
    convert_yaml_to_hdf5(metadata_dir, hdf_filename)
  File "/home/diou/miniconda3/envs/nilm/lib/python3.6/site-packages/nilm_metadata/convert_yaml_to_hdf5.py", line 32, in convert_yaml_to_hdf5
    store = pd.HDFStore(hdf_filename, 'a')
  File "/home/diou/miniconda3/envs/nilm/lib/python3.6/site-packages/pandas/io/pytables.py", line 491, in __init__
    self.open(mode=mode, **kwargs)
  File "/home/diou/miniconda3/envs/nilm/lib/python3.6/site-packages/pandas/io/pytables.py", line 604, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/home/diou/miniconda3/envs/nilm/lib/python3.6/site-packages/tables/file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/diou/miniconda3/envs/nilm/lib/python3.6/site-packages/tables/file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 489, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace
  File "H5F.c", line 511, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1519, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1650, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 941, in H5FD_sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

Unable to open/create file '/home/diou/datasets/NILM/GREEND/GREEND.h5'
```

**Comment by salmanshahid8** [comment]
I tried the same thing. First I installed pytables 3.3.0, then I cleared cache like `clear cache = train.buildings[20].elec.clear_cache()`. Later I rerun `loads_top5 = training_data.submeters().select_top_k(k=5)`, nut it is giving the same error.

`1/9 ElecMeter(instance=2, building=20, dataset='REFIT', appliances=[Appliance(type='fridge freezer', instance=1)])

---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)
<ipython-input-8-9497118370d4> in <module>
----> 1 loads_top5 = training_data.submeters().select_top_k(k=5)

C:\AnacondaForPython36\envs\nilmtk-env\lib\site-packages\nilmtk\metergroup.py in select_top_k(self, k, by, asc, group_remainder, **kwargs)
   1317         """
   1318         function_map = {'energy': self.fraction_per_meter, 'entropy': self.entropy_per_meter}
-> 1319         top_k_series = function_map[by](**kwargs)
   1320         top_k_series.sort_values(inplace=True, ascending=asc)
   1321         top_k_elec_meter_ids = list(top_k_series[:k].index)

C:\AnacondaForPython36\envs\nilmtk-env\lib\site-packages\nilmtk\metergroup.py in fraction_per_meter(self, **load_kwargs)
   1196         Each value is a float in the range [0,1].
   1197         """
-> 1198         energy_per_meter = self.energy_per_meter(**load_kwargs).max()
   1199         total_energy = energy_per_meter.sum()
   1200         return energy_per_meter / total_energy

C:\AnacondaForPython36\envs\nilmtk-env\lib\site-packages\nilmtk\metergroup.py in energy_per_meter(self, per_period, mains, use_meter_labels, **load_kwargs)
   1144             stdout.flush()
   1145             if per_period is None:
-> 1146                 meter_energy = meter.total_energy(**load_kwargs)
   1147             else:
   1148                 load_kwargs.setdefault('use_uptime', False)

C:\AnacondaForPython36\envs\nilmtk-env\lib\site-packages\nilmtk\elecmeter.py in total_energy(self, **loader_kwargs)
    585         nodes = [Clip, TotalEnergy]
    586         return self._get_stat_from_cache_or_compute(
--> 587             nodes, TotalEnergy.results_class(), loader_kwargs)
    588 
    589     def dropout_rate(self, ignore_gaps=True, **loader_kwargs):

C:\AnacondaForPython36\envs\nilmtk-env\lib\site-packages\nilmtk\elecmeter.py in _get_stat_from_cache_or_compute(self, nodes, results_obj, loader_kwargs)
    677         key_for_cached_stat = self.key_for_cached_stat(results_obj.name)
    678         if loader_kwargs.get('preprocessing') is None:
--> 679             cached_stat = self.get_cached_stat(key_for_cached_stat)
    680             results_obj.import_from_cache(cached_stat, sections)
    681 

C:\AnacondaForPython36\envs\nilmtk-env\lib\site-packages\nilmtk\elecmeter.py in get_cached_stat(self, key_for_stat)
    824             return pd.DataFrame()
    825         try:
--> 826             stat_from_cache = self.store[key_for_stat]
    827         except KeyError:
    828             return pd.DataFrame()

C:\AnacondaForPython36\envs\nilmtk-env\lib\site-packages\nilmtk\docinherit.py in f(*args, **kwargs)
     44         @wraps(self.mthd, assigned=('__name__', '__module__'))
     45         def f(*args, **kwargs):
---> 46             return self.mthd(obj, *args, **kwargs)
     47 
     48         return self.use_parent_doc(f, overridden)

C:\AnacondaForPython36\envs\nilmtk-env\lib\site-packages\nilmtk\datastore\hdfdatastore.py in __getitem__(self, key)
     25     @doc_inherit
     26     def __getitem__(self, key):
---> 27         return self.store[key]
     28 
     29     @doc_inherit

C:\AnacondaForPython36\envs\nilmtk-env\lib\site-packages\pandas\io\pytables.py in __getitem__(self, key)
    481 
    482     def __getitem__(self, key):
--> 483         return self.get(key)
    484 
    485     def __setitem__(self, key, value):

C:\AnacondaForPython36\envs\nilmtk-env\lib\site-packages\pandas\io\pytables.py in get(self, key)
    669         if group is None:
    670             raise KeyError('No object named %s in the file' % key)
--> 671         return self._read_group(group)
    672 
    673     def select(self, key, where=None, start=None, stop=None, columns=None,

C:\AnacondaForPython36\envs\nilmtk-env\lib\site-packages\pandas\io\pytables.py in _read_group(self, group, **kwargs)
   1347         s = self._create_storer(group)
   1348         s.infer_axes()
-> 1349         return s.read(**kwargs)
   1350 
   1351 

C:\AnacondaForPython36\envs\nilmtk-env\lib\site-packages\pandas\io\pytables.py in read(self, where, columns, **kwargs)
   4139     def read(self, where=None, columns=None, **kwargs):
   4140 
-> 4141         if not self.read_axes(where=where, **kwargs):
   4142             return None
   4143 

C:\AnacondaForPython36\envs\nilmtk-env\lib\site-packages\pandas\io\pytables.py in read_axes(self, where, **kwargs)
   3339         # create the selection
   3340         self.selection = Selection(self, where=where, **kwargs)
-> 3341         values = self.selection.select()
   3342 
   3343         # convert the data

C:\AnacondaForPython36\envs\nilmtk-env\lib\site-packages\pandas\io\pytables.py in select(self)
   4738         elif self.coordinates is not None:
   4739             return self.table.table.read_coordinates(self.coordinates)
-> 4740         return self.table.table.read(start=self.start, stop=self.stop)
   4741 
   4742     def select_coords(self):

C:\AnacondaForPython36\envs\nilmtk-env\lib\site-packages\tables\table.py in read(self, start, stop, step, field, out)
   1924                                                 warn_negstep=False)
   1925 
-> 1926         arr = self._read(start, stop, step, field, out)
   1927         return internal_to_flavor(arr, self.flavor)
   1928 

C:\AnacondaForPython36\envs\nilmtk-env\lib\site-packages\tables\table.py in _read(self, start, stop, step, field, out)
   1838             # This optimization works three times faster than
   1839             # the row._fill_col method (up to 170 MB/s on a pentium IV @ 2GHz)
-> 1840             self._read_records(start, stop - start, result)
   1841         # Warning!: _read_field_name should not be used until
   1842         # H5TBread_fields_name in tableextension will be finished

tables\tableextension.pyx in tables.tableextension.Table._read_records (tables\tableextension.c:8045)()

HDF5ExtError: HDF5 error back trace

  File "C:\Minonda\conda-bld\work\hdf5-1.8.17\src\H5Dio.c", line 173, in H5Dread
    can't read data
  File "C:\Minonda\conda-bld\work\hdf5-1.8.17\src\H5Dio.c", line 554, in H5D__read
    can't read data
  File "C:\Minonda\conda-bld\work\hdf5-1.8.17\src\H5Dchunk.c", line 1875, in H5D__chunk_read
    unable to read raw data chunk
  File "C:\Minonda\conda-bld\work\hdf5-1.8.17\src\H5Dchunk.c", line 2905, in H5D__chunk_lock
    data pipeline read failed
  File "C:\Minonda\conda-bld\work\hdf5-1.8.17\src\H5Z.c", line 1372, in H5Z_pipeline
    filter returned failure during read
  File "hdf5-blosc/src/blosc_filter.c", line 254, in blosc_filter
    Blosc decompression error

End of HDF5 error back trace

Problems reading records.
`
Actually I am trying to disaggregate using FHMM on building 21 in REFIT data. The first time it worked and I went through the results. But next time I re-run it, it did not work.

Any idea why is it like that?
