### ISSUE TITLE
Diagnose function 

### ISSUE THREAD

**Issue by nicolascassia** [nilmtk/nilmtk#710]
Hi,I'm looking for the diagnose function described in NILMTK v0.1 but I didn't find it. Is diagnose function still part of  #nilmtk? 

In case that it isn't,Why it was eliminated? Is there any other statistics function to analyse an entire Dataset? If not, how I should analyse a Dataset using nilmtk?

Thanks in advance.

**Comment by PMeira** [comment]
@nicolascassia Do you have a link with more info? I couldn't find a `diagnose` in the repository history or released packages.

**Comment by nicolascassia** [comment]
@PMeira thanks for reply! I read about this function in the paper "NILMTK: An Open Source Toolkit for Non-intrusive Load Monitoring".A link to this paper can be found in http://nilmtk.github.io/#publications .

**Comment by PMeira** [comment]
@nicolascassia @nipunbatra 
It seems most of the previous methods were refactored into the `nilmtk.stats`  package or in the elecmeters themselves (e.g. `goodsections`, `dropout_rate`), but there are a couple of methods commented/not implemented in the meters.

This (outdated) notebook can be useful:
https://github.com/nilmtk/nilmtk/blob/f601f65bf205aa0c009ed2e7df546285dc86fc3d/docs/outdated/NILM_Workshop_2014_demo.ipynb

I guess porting some of the old notebooks to v0.3 will give us an idea of what's missing. I'll open another issue to track that.

(Thanks @nicolascassia)
