### ISSUE TITLE
AMPDS database loading issue

### ISSUE THREAD

**Issue by ilia200** [nilmtk/nilmtk#712]
Hello,

I have Anaconda 3.7 installed with the newest NILMTK.
I was able to convert and load the redd low frequency database.
On the other hand while trying to convert the AMPDS database to HDF format (*.h5) I have encountered an error. The code and the error listed below.
Just worth mentioning that I have downloaded the old R2013 version and *csv files of the AMPDS database (I have seen here on previous posts people were able to convert an load the database, and that it is supported by the current version of NILMTK).

**Thanks for your Help**
 
**Code I have used in the python console:**
from nilmtk.dataset_converters import convert_ampds
convert_ampds('C:/Users/HP/PycharmProjects/nilmtk_proj/nilmtk master/data/AMPDS','C:/Users/HP/PycharmProjects/nilmtk_proj/nilmtk master/data/AMPDS/ampds.h5')

**I get the folowing error:**
Loading file # 1  :  WHE.csv . Please wait...
Traceback (most recent call last):
  File "C:\Users\HP\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-5958777c1d12>", line 1, in <module>
    convert_ampds('C:/Users/HP/PycharmProjects/nilmtk_proj/nilmtk master/data/AMPDS','C:/Users/HP/PycharmProjects/nilmtk_proj/nilmtk master/data/AMPDS/amp.h5')
  File "c:\users\hp\pycharmprojects\nilmtk_proj\nilmtk master\nilmtk\dataset_converters\ampds\convert_ampds.py", line 75, in convert_ampds
    df.columns.set_names(LEVEL_NAMES, inplace=True)
  File "C:\Users\HP\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 1421, in set_names
    idx._set_names(names, level=level)
  File "C:\Users\HP\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 1352, in _set_names
    len(values))
ValueError: Length of new names must be 1, got 2

**Comment by ilia200** [comment]
The newer version of pandas made the error (0.23).
The solution is similar to the described below:
[link](https://github.com/nilmtk/nilmtk/commit/3e6810fabecf13e815b9d93284ca4ee16819d03d)
You can make a similar fix to the AMPDS converter,
Please close the issue.
Thanks

**Comment by PMeira** [comment]
Sorry about that. There's a recommended `environment.yml` for Anaconda to avoid that, but I'll add a couple of restrictions on `setup.py` to avoid the installation on incompatible environments.

**Comment by sk1306** [comment]
I'm getting the same error for iawe dataset. I changed the code as mentioned by @ilia200 above. Same error, still!
Following is the error:

ValueError                                Traceback (most recent call last)
<ipython-input-33-79834eb75ae4> in <module>()
----> 1 convert_iawe('/home/siddhart/Uniedge/programs/dissaggregation/datasets/dataset', '/home/siddhart/Uniedge/programs/dissaggregation/datasets/dataset/watch.h5')

~/nilmtk/nilmtk/dataset_converters/iawe/convert_iawe.py in convert_iawe(iawe_path, output_filename, format)
     79         df = df.drop(TIMESTAMP_COLUMN_NAME, 1)
     80         df.rename(columns=lambda x: column_mapping[x], inplace=True)
---> 81         df.columns.set_names(LEVEL_NAMES, inplace=True)
     82         df = df.apply(pd.to_numeric, errors='ignore')
     83         df = df.dropna()

~/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py in set_names(self, names, level, inplace)
   1404         else:
   1405             idx = self._shallow_copy()
-> 1406         idx._set_names(names, level=level)
   1407         if not inplace:
   1408             return idx

~/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py in _set_names(self, values, level)
   1336         if len(values) != 1:
   1337             raise ValueError('Length of new names must be 1, got %d' %
-> 1338                              len(values))
   1339 
   1340         # GH 20527

ValueError: Length of new names must be 1, got 2

**Comment by PMeira** [comment]
@sk1306 Can you check which version of Pandas you have installed?

**Comment by sk1306** [comment]
Sorry for replying late. My version of pandas is 0.24.2. This type of error is occuring from last few days. Earlier, though, it used to run fine. @ilia200 @PMeira

**Comment by PMeira** [comment]
@sk1306 It should be fixed now on the master branch, along with most of the other converters.
