### ISSUE TITLE
Anyone would explain to me the concept of 'chunk' ?

### ISSUE THREAD

**Issue by 2ndMessiah** [nilmtk/nilmtk#713]
Seeing this term everywhere in the code, I haven't found an official definition of it.

Is it a workaround to load huge datasets to a space limited memory when computing ?

And I have some confusions:
When is that api called?
How is the size of a single chunk defined?
Will it affect the completeness  of a elec's power data?

Many thanks.

**Comment by PMeira** [comment]
There are a couple sparse mentions in the docstrings, e.g.

https://github.com/nilmtk/nilmtk/blob/0607e7a73bb8df0ec1ba7553077dc93e843fc5bf/nilmtk/metergroup.py#L645

> Is it a workaround to load huge datasets to a space limited memory when computing ?

Yes, that's it. Originally there were few Python packages to support NILMTK on that, hence it has a custom chunk implementation. It loads a smallish chunk of data and yields the data as a generator.

> When is that api called?
> How is the size of a single chunk defined?

The `load` method from the datastore and meter(group) objects support a `chunksize` kwarg (in number of rows). Some methods, including disaggregators, can also restrict the chunk size but it's not uniform across the code base.

> Will it affect the completeness of a elec's power data?

It shouldn't.

The plan is to keep the current API as-is for a v0.3 release soon (by the end of the year), and then move everything to a move robust and generic system, something like Dask.

**Comment by 2ndMessiah** [comment]
> There are a couple sparse mentions in the docstrings, e.g.
> 
> [nilmtk/nilmtk/metergroup.py](https://github.com/nilmtk/nilmtk/blob/0607e7a73bb8df0ec1ba7553077dc93e843fc5bf/nilmtk/metergroup.py#L645)
> 
> Line 645 in [0607e7a](/nilmtk/nilmtk/commit/0607e7a73bb8df0ec1ba7553077dc93e843fc5bf)
> 
>          chunksize : int, optional 
> > Is it a workaround to load huge datasets to a space limited memory when computing ?
> 
> Yes, that's it. Originally there were few Python packages to support NILMTK on that, hence it has a custom chunk implementation. It loads a smallish chunk of data and yields the data as a generator.
> 
> > When is that api called?
> > How is the size of a single chunk defined?
> 
> The `load` method from the datastore and meter(group) objects support a `chunksize` kwarg (in number of rows). Some methods, including disaggregators, can also restrict the chunk size but it's not uniform across the code base.
> 
> > Will it affect the completeness of a elec's power data?
> 
> It shouldn't.
> 
> The plan is to keep the current API as-is for a v0.3 release soon (by the end of the year), and then move everything to a move robust and generic system, something like Dask.

Thanks for your quick response.Hence the default chunk size is the total length of the data?

**Comment by PMeira** [comment]
> Hence the default chunk size is the total length of the data?

@2ndMessiah Basically. There was a partial work to restrict the default chunk size to 256MiB (`2**28`), but the HDFDataStore still interprets that as the number of rows, so the default chunk size should be `2**28` (268435456) rows.
