### ISSUE TITLE
Model loading and saving

### ISSUE THREAD

**Issue by walidsliti** [nilmtk/nilmtk#715]
hi @PMeira @nipunbatra  : 
I want to know how to save my model after the training and load it without repeating the training 
![image](https://user-images.githubusercontent.com/26322476/49236150-cad38200-f3fb-11e8-8552-7826ed4b1982.png)
Thank you

**Comment by PMeira** [comment]
@walidsliti Just implemented this ([here](https://github.com/nilmtk/nilmtk/blob/5edda2eeccc0c79d2665f1829f8761a090ee4594/nilmtk/disaggregate/fhmm_exact.py#L517)). 

You should be able to use something like this to save the model:

```python
fhmm = fhmm_exact.FHMM()
fhmm.train(...)
fhmm.export_model('fhmm_model')
```

And then load it later:
```python
fhmm = fhmm_exact.FHMM()
fhmm.import_model('fhmm_model')
```

Please reopen the ticket if you find any issues.

**Comment by walidsliti** [comment]
@PMeira Yes I already replace the fhmm_exact.py

**Comment by PMeira** [comment]
@walidsliti There must be another copy somewhere else, maybe a running process needs to be restarted, etc. It's not likely it'd be related to the code itself.

**Comment by walidsliti** [comment]
@PMeira I update the whole NILMTK and the error persist, is the problem from the disaggregator.py file ?
fhmm.export_model('fhmm_model')  : is fhmm_model need to be created before, if yes must I give the whole path ?

**Comment by PMeira** [comment]
@walidsliti Try running this:
```python
from nilmtk.disaggregate import fhmm_exact
import inspect
print(inspect.get_source(fhmm_exact.FHMM))
```

If your file is right, it should print the part of the content of the new file, including the last lines that added the new methods:

```python
    def import_model(self, filename):
        with open(filename, 'rb') as in_file:
            imported_model = pickle.load(in_file)

        self.model = imported_model.model
        self.individual = imported_model.individual

        # Recreate datastores from filenames
        for meter in self.individual.keys():
            store_filename = meter.store
            meter.store = HDFDataStore(store_filename)

        self.meters = list(self.individual.keys())


    def export_model(self, filename):
        # Can't pickle datastore, so convert to filenames
        original_stores = []

        meters = self.meters
        self.meters = None

        for meter in self.individual.keys():
            original_store = meter.store
            original_stores.append(original_store)
            meter.store = original_store.store.filename

        try:
            with open(filename, 'wb') as out_file:
                pickle.dump(self, out_file)
        finally:
            # Restore the meters and stores even if the pickling fails
            for original_store, meter in zip(original_stores, self.individual.keys()):
                meter.store = original_store

            self.meters = meters
```

If the output doesn't contain those methods, you can check where the file is with:
```python
print(inspect.getfile(fhmm_exact.FHMM))
```

I hope that helps, I can't imagine any other possible issues.

**Comment by walidsliti** [comment]
thank you @PMeira so much when I execute
print(inspect.getfile(fhmm_exact.FHMM))
I got this path 
 /home/ubuntu/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/disaggregate/fhmm_exact.py 
which is not the path I work with so I delete this one or change it ?

Thank you

**Comment by PMeira** [comment]
@walidsliti You can uninstall that one (running `pip uninstall nilmtk` should be enough), then if install the one you actually by running `pip install -e .` in the root folder (where there is a `setup.py`) of the NILMTK instance you use. Remember that you need to run all commands with nilmtk-env activated.

**Comment by nipunbatra** [comment]
Maybe just need to remove the .pyc?

**Comment by walidsliti** [comment]
Thank you guys I did what @PMeira said and it works now
