### ISSUE TITLE
No bin in nilmtk-env directory

### ISSUE THREAD

**Issue by salmanshahid8** [nilmtk/nilmtk#717]
Hi Nipun,

Great work and indeed very helping. I am trying to use the nilmtk environment as venv for pycharm project, yet there is no bin directory for accessing python.exe. Rather I used the python.exe in the nilmtk-env directory, which only import packages of setuptools and pip.

Please tell me how to fix this.
![sans titre](https://user-images.githubusercontent.com/19222248/49379158-c4504d80-f70e-11e8-89c9-2bf8fff72e64.jpg)

**Comment by PMeira** [comment]
@salmanshahid8 Some comments on a similar issue about using with Spyder:
https://github.com/nilmtk/nilmtk/issues/667#issuecomment-385085229

> Rather I used the python.exe in the nilmtk-env directory,

That's fine.

> which only import packages of setuptools and pip.

If that's the case, you probably didn't specify our `environment.yml` when you created the environment. See also https://github.com/nilmtk/nilmtk/issues/462#issuecomment-383320508

If you still find any issues, take a look at the conda docs too: https://conda.io/docs/user-guide/tasks/manage-environments.html

**Comment by salmanshahid8** [comment]
Hi,
Thanks @PMeira 
I followed your instructions and it stuck at this point. I waited for more than half an hour but it did not continue. On the contrary it started a number of python file processes in the system that keep on growing.

My Anaconda is for Python 3.6 ver 4.4.0. What could be the problem. Meanwhile I will try to do the same at another laptop.

![image](https://user-images.githubusercontent.com/19222248/49640535-23170f00-fa0e-11e8-8214-92a492a931eb.png)

**Comment by salmanshahid8** [comment]
Is there any issue of OS architecture. i.e I am using win 10 x64 on both laptops..

**Comment by PMeira** [comment]
It seems to be an issue with your conda installation, there are some reports in their issue tracker: https://github.com/conda/conda/issues/5219

Might be worth to try to update it and remove custom channels if you have them.

> Is there any issue of OS architecture. i.e I am using win 10 x64 on both laptops..

No, I just tested again to be sure. 

You can also try to install using my conda channel (I just uploaded an up-to-date package):

    conda install nilmtk -c pmeira

But you might get stuck in the same place...

**Comment by salmanshahid8** [comment]
Indeed that is strange. Rather then using environment.yml, I created an environment in anaconda prompt and added all the required packages one by one. They are showing in anaconda navigator but not configuring as an interpreter in pycharm.

![image](https://user-images.githubusercontent.com/19222248/49769667-60ff8600-fce1-11e8-8093-2000ca907535.png)

**Comment by salmanshahid8** [comment]
I upgraded/downgraded the packages in anaconda and added the other packages. Now the default anaconda environment is being used as interpreter in pycharm and it is working.
