### ISSUE TITLE
How to convert 1Hz data of dataport into H5 format？

### ISSUE THREAD

**Issue by xunyiljg** [nilmtk/nilmtk#724]
By default, nilmtk downloads data ports for 1 minute. Now that dataport already have 1hz data, I want to know how to convert 1Hz data into H5 format. Thank you. Will it be a problem to directly replace electricity_egauge_minutes in the source code with electricity_egauge_seconds?

**Comment by PMeira** [comment]
> Will it be a problem to directly replace electricity_egauge_minutes in the source code with electricity_egauge_seconds?

@xunyiljg If the rest of the columns are exactly the same, it should work with little changes. Try just replacing all instances of `minute`  with `second` in the converter.

Do you know if they (Dataport) provide any document describing the schema? If they do, I could implement the minute/second selection in the converter.

**Comment by xunyiljg** [comment]
Last year, the introduction of dataport said that 1 Hz data was added（https://youtu.be/5Q1Zbw2tkRU）, and then I did see this data in database of dataport, but I'm not very good at using pgadmin, so it's not clear whether there is any explanation for 1 Hz data.
