### ISSUE TITLE
REDD.h5 dataset

### ISSUE THREAD

**Issue by hendraahalimm** [nilmtk/nilmtk#727]
Hello, I'm interested in NILMTK as my final project. I tried to follow the instruction how to install and beginner guide for NILMTK but somehow i couldn't find REDD.h5 file. Where can I get the REDD.h5? Thanks

**Comment by MarianaOliveira94** [comment]
Have you already downloaded REDD dataset?

**Comment by hendraahalimm** [comment]
I have downloaded REDD dataset (low freq) from http://redd.csail.mit.edu
And i used WinZip to UnZip it. But i still can not find REDD.h5 like in tutorial on youtube

**Comment by drekisen** [comment]
Hi how are things

After having downloaded the data, what procedure is required to be performed?

I am having the same problem that I could not find the file low_frequency and now I realize that it is actually a folder with a set of subfolders, but then what is next?


Greetings

**Comment by PMeira** [comment]
@drekisen See one of the examples at https://github.com/nilmtk/nilmtk/blob/303d45bf6c39b44d76c35e8aaa690cef6af8ae38/docs/manual/user_guide/data.ipynb

Please do not comment in closed issues from years ago.
