### ISSUE TITLE
Installing NILMTK on Windows: VS C++ compiler link

### ISSUE THREAD

**Issue by Nakata007** [nilmtk/nilmtk#728]
Following the Install NILMTK guide [here ](https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install_user.md), even after installing the Build Tools from the link on line 2 (for Python 3.6), I still got an error when creating the environment: "Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools"

So, to make it run I had to install the build tools for VS from this link https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017

I guess updating the install NILMTK guide with this link will be nice.

**Comment by PMeira** [comment]
There are further issues, it's better to just:
```
conda install -c pmeira nilmtk
```

**Comment by rajatgupta1234** [comment]
**Please follow the steps:**
Uninstall any previous version of python from Control Panel.
Install Anaconda from here-> This version: Anaconda3-5.3.1-Windows-x86_64.exe from the archive : https://repo.continuum.io/archive/ and install Visual Studio as prompted in the last of installation.
**Or if you install through developer mode:**
Follow the steps given in the pdf
link: https://drive.google.com/file/d/1yGuCuDlaRwDpMLXWBamOJXTGlWZ4VXq7/view?usp=sharing

**Comment by ayushp20** [comment]
Try using:
`conda install -c nilmtk nilmtk`
