### ISSUE TITLE
Error while running Disaggregation algorithm on iawe Dataset

### ISSUE THREAD

**Issue by anosharshad** [nilmtk/nilmtk#729]
I am running the disaggregation algorithm on iawe dataset after the execution of the following code i get error.
pred = {}
gt= {}

for i, chunk in enumerate(test_elec.mains().load(sample_period=60)):
    chunk_drop_na = chunk.dropna()
    pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)
    gt[i]={}
    
    for meter in test_elec.submeters().meters:
        # Only use the meters that we trained on (this saves time!)    
        gt[i][meter] = next(meter.load(sample_period=60))
    gt[i] = pd.DataFrame({k:v.squeeze() for k,v in iteritems(gt[i])}, index=next(iter(gt[i].values())).index).dropna()

ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required.

**Comment by nipunbatra** [comment]
Please provide full code

**Comment by anosharshad** [comment]
from __future__ import print_function, division
import time
from matplotlib import rcParams
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from six import iteritems
import warnings

warnings.filterwarnings('ignore')
%matplotlib inline

rcParams['figure.figsize'] = (13, 6)

from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
from nilmtk.disaggregate import CombinatorialOptimisation

train = DataSet('C:\\Users\\anosh\\Anaconda2\\envs\\iawe.h5')
test = DataSet('C:\\Users\\anosh\\Anaconda2\\envs\\iawe.h5')

train.set_window(start="15-06-2013", end="29-06-2013")
test.set_window(start="29-06-2013", end="29-07-2013")

train_elec = train.buildings[1].elec
test_elec = test.buildings[1].elec

top_5_train_elec = train_elec.submeters().select_top_k(k=5)

start = time.time()
from nilmtk.disaggregate import fhmm_exact
fhmm = fhmm_exact.FHMM()
# Note that we have given the sample period to downsample the data to 1 minute. 
# If instead of top_5 we wanted to train on all appliance, we would write 
# fhmm.train(train_elec, sample_period=60)
fhmm.train(top_5_train_elec, sample_period=60)
end = time.time()
print("Runtime =", end-start, "seconds.")

pred = {}
gt= {}

for i, chunk in enumerate(test_elec.mains().load(sample_period=60)):
    chunk_drop_na = chunk.dropna()
    pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)
    gt[i]={}
    
    for meter in test_elec.submeters().meters:
        # Only use the meters that we trained on (this saves time!)    
        gt[i][meter] = next(meter.load(sample_period=60))
    gt[i] = pd.DataFrame({k:v.squeeze() for k,v in iteritems(gt[i])}, index=next(iter(gt[i].values())).index).dropna()

**Comment by nipunbatra** [comment]
Assigned to @raktim2015

**Comment by raktim2015** [comment]
Use `next(test_elec.mains().load(sample_period=60))` to see the dataframe. You will notice that 'voltage apparent', 'power factor' and few other columns are NaN for the all records. So, chunk.dropna() will remove all rows from the record making the dataframe empty.

To solve this use

```
pred = {}
gt= {}
for i, chunk in enumerate(train_elec.mains().load(physical_quantity='power',ac_type='active',sample_period=60)):
    chunk_drop_na = chunk.dropna()
    pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)
    gt[i]={}
    
    for meter in train_elec.submeters().meters:
        # Only use the meters that we trained on (this saves time!)    
        
        #print(df.head())
        gt[i][meter] = next(meter.load(physical_quantity='power',ac_type='active',sample_period=60))
    gt[i] = pd.DataFrame({k:v.squeeze() for k,v in iteritems(gt[i])}, index=next(iter(gt[i].values())).index).dropna()
```
This will consider only the active power column and dropna() will be operated on it.
Hope it helps!!

**Comment by nipunbatra** [comment]
Closing the issue as the above fix works for us. Please reopen if needed.
