### ISSUE TITLE
Issues in installing toolkit NILMTK

### ISSUE THREAD

**Issue by Dhruvin1412** [nilmtk/nilmtk#731]
I installed a  NILMTK in anaconda using a command prompt from MinGW64. It shows in anaconda that application can works on nimtk-env but, I am getting an error "No module named Nilmtk". 

I am using windows 10 and paython 3.6.
![Screenshot (3)](https://user-images.githubusercontent.com/48323399/54137525-1eebfa80-441e-11e9-8af6-1608515c84b7.png)

**Comment by salmanshahid8** [comment]
https://github.com/nilmtk/nilmtk/issues/728#issuecomment-469759684

**Comment by Dhruvin1412** [comment]
Thank you, It is working with jupyter notebook but not with Spyder. In spyder, I do not have any Problem with importing a NILMTK but I can not able to import disaggregation methods.  Could you please help me.

**Comment by rajatgupta1234** [comment]
**Please follow the steps:** 
1. Uninstall any previous version of python from Control Panel.
2. Install Anaconda from here-> This version:  Anaconda3-5.3.1-Windows-x86_64.exe  from the archive : https://repo.continuum.io/archive/ and install Visual Studio as prompted in the last of installation.  

**Or if you install through developer mode: 
Follow the steps given in the pdf** 
link: https://drive.google.com/file/d/1yGuCuDlaRwDpMLXWBamOJXTGlWZ4VXq7/view?usp=sharing

**Comment by ayushp20** [comment]
Try using
`conda install -c nilmtk nilmtk`
