### ISSUE TITLE
can't install nilmtk with python 3.6 it's automatically downgrading to python 2.7.

### ISSUE THREAD

**Issue by sanjay-raghu** [nilmtk/nilmtk#733]
I am trying to install nilmtk in windows 10 I am following developers guide. I start with creating
a virtual environment with python 3.6. as i run this
`conda install --yes pip numpy scipy six scikit-learn pandas numexpr pytables==3.2.2 dateutil matplotlib networkx future`

the python version downgrades to 2.7
is this normal ?

**Comment by rajatgupta1234** [comment]
Please follow the steps given in the pdf : 
Link: 
[NILMTK Installation Steps on windows_.pdf](https://github.com/nilmtk/nilmtk/files/3171221/NILMTK.Installation.Steps.on.windows_.pdf)

**Comment by nipunbatra** [comment]
We've reproduced this behaviour and figured the conflicting package. Please use: 
`conda install -c nilmtk nilmtk` to install nilmtk. We would suggest creating a new environment.
