### ISSUE TITLE
Attribute error : 'str' object has no attribute 'set_window' 

### ISSUE THREAD

**Issue by hendraahalimm** [nilmtk/nilmtk#734]
Hello, I' trying to follow this guide : https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/disaggregation_and_metrics.ipynb

Everything was alright until input [4] where the problem started.

Operating system : Windows 10
Python version : 3.6
I'm installing nilmtk using miniconda : conda-4.6.8

And here the error i got
![ERROR](https://user-images.githubusercontent.com/48208140/54588532-de136780-4a55-11e9-93a9-8b8643e1b38b.png)

Can anyone help me?

**Comment by raktim2015** [comment]
Try to define :-
train = DataSet('<.h5 converted file path>')
test = DataSet('<.h5 converted file path>')
and then run the following commands. This error occurred because 'train' and 'test' have been declared as string and not as DataSet objects.

Hope it helps!
