### ISSUE TITLE
How to plot both two site-meters using dataframe.plot()?

### ISSUE THREAD

**Issue by ExecCyc** [nilmtk/nilmtk#735]
I noticed that you said `nilm.plot` this function samples the data, so the graph we plot is not reflect the true result, is it right? So I want to use `dataframe.plot` to draw **the both site-meters**, like what you have done in [Dissaggregation Tutorial](https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/disaggregation_and_metrics.ipynb), but it only shows one curve, the legend is 'power, apparent'. So why? And how to draw both curves?

![image](https://user-images.githubusercontent.com/48451473/54607614-0f3c6980-4a4f-11e9-942c-fb5cf7a7e234.png)

And I don't know where these values came from, they are not the values which site-meter files (low_freq->house_1->building1->channel_1.dat & channel_2.dat) record.
I'm a NILM biginner, looking forward to your reply... Thank you very much.

**Comment by nipunbatra** [comment]
Assigned to: @raktim2015

**Comment by raktim2015** [comment]
As elec contains two site-meters, `next(mains.load())` will give the added apparent power value. 
Use the following code to select each meter separately.
 
```
dict={}
dict[1]=next(train_elec[1].load(sample_period=60))
dict[2]=next(train_elec[2].load(sample_period=60))
```
Plot the downsampled readings :-
```
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
dict[1].plot(ax=ax, legend=True)
dict[2].plot(ax=ax, legend=True)
```

Check whether the values are summed up or not :-
```
dict[1].head() 
dict[2].head()
mains_df.head()

```
Hope it helps!!
