### ISSUE TITLE
How metadata contributes to NILM?

### ISSUE THREAD

**Issue by ExecCyc** [nilmtk/nilmtk#736]
I have read your paper 'NILMTK: An Open Source Toolkit for Non-intrusive Load
Monitoring', 'Metadata for Energy Disaggregation', also 'REDD: A Public Data Set for
Energy Disaggregation Research' and so on. They all mentioned metadata but I can't see how metadata works in training or dissaggregation process. Could you recommend me some papers that can show more detail about this? Or which code in this toolkit should I study to learn its working mechanism?

I'm a NILM beginner, I have some consumption data (only power), but without any matadata, so I want to know how metadata works in your toolkit then to decide whether I need to write a new converter or just add metadata to my original data. 

Thank you very much!

**Comment by PMeira** [comment]
The metadata is used to identify the actual data in a standard way, allowing the methods to refer to the data generically. 

For example, some datasets are comprised of a bunch of unlabeled CSV files. A dataset converter needs to identify each of the electric quantities in those CSV files, and associate each time series to a meter, meters to appliances, and so on.

Take a look at https://github.com/nilmtk/nilmtk/blob/master/docs/manual/development_guide/writing_a_dataset_converter.md and some of the various dataset converters and the original/input data and their documentation/papers.

**Comment by PMeira** [comment]
Converters can be found at https://github.com/nilmtk/nilmtk/tree/master/nilmtk/dataset_converters

**Comment by jpnmatoso** [comment]
Hi Paulo, how are you?

I'm having a primary question regarding converting dataset csv to HDF5. The metadata files should be placed next to the environment (nilmtk/nilmtk/dataset_converters_jp/metadata/*.yaml) or next to the data collected from the smartmeter (data/metadata/*.yaml)?

If possible, could you give me an email to speak in Portuguese so as not to compromise the issues here in github? My email is jpnmatoso@gmail.com.

Thank you

João Paulo
