### ISSUE TITLE
Trainning an appearant power data using Hart 85

### ISSUE THREAD

**Issue by Dhruvin1412** [nilmtk/nilmtk#737]
I am using a DRED dataset and try to do disaggregation but I am getting an error in Hart 85. 
"'[('power', 'active')]' is not a subset of the available columns: '[('power', 'apparent')]'"
I attached my code, Could you please help me. 
##############################

```python
# - [ 1] 
#%matplotlib inline
import numpy as np
import pandas as pd
from os.path import join
from pylab import rcParams
import matplotlib.pyplot as plt
rcParams['figure.figsize'] = (13, 6)
plt.style.use('ggplot')
import nilmtk
from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
from nilmtk.disaggregate.hart_85 import Hart85
from nilmtk.utils import print_dict, show_versions
from nilmtk.metrics import f1_score
import seaborn as sns
sns.set_palette("Set3", n_colors=12)
import warnings
warnings.filterwarnings("ignore") #suppress warnings, comment out if warnings required

# - [2 ] 
##Load dataset##
data_dir = '/Users/Dhruvin suthar/Desktop/Thesis work/test_of_database/DRED/DRED/' 
DNV = DataSet(join(data_dir, 'DRED.h5'))

# - [3 ] 
DNV.set_window   = TimeFrame(start=None, end='2015-07-10 00:00:00')
elec = DNV.buildings[1].elec
mains = elec.mains()

# - [4 ] 
house = elec['fridge']
df = next(house.load())

# - [5 ] 
df.ix['2015-07-05 12:00:00+02:00':'2015-10-05 12:00:00+02:00'].plot()

# - [6 ] 
h = Hart85()
h.train(mains)

```
#####################################################################

```pytb
MeasurementError                          Traceback (most recent call last)
<ipython-input-9-1d760eba3cc4> in <module>
----> 1 h.train(mains)

~\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\disaggregate\hart_85.py in train(self, metergroup, columns, buffer_size, noise_level, state_threshold, min_tolerance, percent_tolerance, large_transition, **kwargs)
    242         self.noise_level = noise_level
    243         [self.steady_states, self.transients] = find_steady_states_transients(
--> 244             metergroup, columns, noise_level, state_threshold, **kwargs)
    245         self.pair_df = self.pair(
    246             buffer_size, min_tolerance, percent_tolerance, large_transition)

~\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\feature_detectors\steady_states.py in find_steady_states_transients(metergroup, columns, noise_level, state_threshold, **load_kwargs)
     20     transients_list = []
     21 
---> 22     for power_df in metergroup.load(columns=columns, **load_kwargs):
     23         """
     24         if len(power_df.columns) <= 2:

~\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\elecmeter.py in load(self, **kwargs)
    441         # Get source node
    442         preprocessing = kwargs.pop('preprocessing', [])
--> 443         last_node = self.get_source_node(**kwargs)
    444         generator = last_node.generator
    445 

~\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\elecmeter.py in get_source_node(self, **loader_kwargs)
    566                 "Cannot get source node if meter.store is None!")
    567 
--> 568         loader_kwargs = self._convert_physical_quantity_and_ac_type_to_cols(**loader_kwargs)
    569         generator = self.store.load(key=self.key, **loader_kwargs)
    570         self.metadata['device'] = self.device

~\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\elecmeter.py in _convert_physical_quantity_and_ac_type_to_cols(self, physical_quantity, ac_type, columns, **kwargs)
    520                     msg = ("'{}' is not a subset of the available columns: '{}'"
    521                            .format(columns, self.available_columns()))
--> 522                     raise MeasurementError(msg)
    523 
    524         msg = ""

MeasurementError: '[('power', 'active')]' is not a subset of the available columns: '[('power', 'apparent')]'
```
####################################################################

**EDIT by @pmeira**: formatting

**Comment by raktim2015** [comment]
Hello @Dhruvin1412 
Try to store `mains` in DataFrame and check that it only contains apparent power data. Try to use `h.train(mains,columns=[('power','apparent')])`

Hope it helps!!

**Comment by Dhruvin1412** [comment]
Hello @raktim2015 
I tried same but I am facing still an error.
"Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required."

**Comment by rajatgupta1234** [comment]
@Dhruvin1412 
Please share the screenshot whole error. Are you getting it in `h.train(mains)` ?

**Comment by PMeira** [comment]
@Dhruvin1412 Your sample code, modified as suggested (`h.train(mains,columns=[('power','apparent')])`), runs without error in the current master branch.

**Comment by Dhruvin1412** [comment]
Hello, I attached the screen-shot, and I am getting the same error. I am using the hdf5 file from dutch residential energy database from TU-DELFT, Netherland. 

![Screenshot (54)](https://user-images.githubusercontent.com/48323399/59982536-13f75780-9614-11e9-85c1-414d6d52e6b8.png)

**Comment by Dhruvin1412** [comment]
https://github.com/Dhruvin1412/Git/blob/master/tk_nilm/DRED_HART.ipynb
I attached the file too.

**Comment by PMeira** [comment]
@Dhruvin1412 If you're using the H5 file on their site, it's probably outdated and/or broken (it's from 2015). 

To create a new copy:

1. Download `All_data.csv` from http://www.st.ewi.tudelft.nl/akshay/dred/data/All_data.csv
2. Use the updated converter:

```python
from nilmtk.dataset_converters.dred.convert_dred import convert_dred
convert_dred("path_to_file/All_data.csv", "path_to_output/dred.h5")
```

> https://github.com/Dhruvin1412/Git/blob/master/tk_nilm/DRED_HART.ipynb


That repo seems to be private. Please try converting the CSV and rerunning.  I ran the following sample code with a local converted copy of DRED without issues:

```python
import numpy as np
import pandas as pd
from os.path import join
from pylab import rcParams
import matplotlib.pyplot as plt
rcParams['figure.figsize'] = (13, 6)
plt.style.use('ggplot')
import nilmtk
from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
from nilmtk.disaggregate.hart_85 import Hart85
from nilmtk.utils import print_dict, show_versions
from nilmtk.metrics import f1_score
import warnings
warnings.filterwarnings("ignore") #suppress warnings, comment out if warnings required

# - [2 ] 
##Load dataset##
data_dir = '/data' 
DNV = DataSet(join(data_dir, 'DRED.h5'))

# - [3 ] 
DNV.set_window   = TimeFrame(start=None, end='2015-07-10 00:00:00')
elec = DNV.buildings[1].elec
mains = elec.mains()

# - [4 ] 
house = elec['fridge']
df = next(house.load())

# - [5 ] 
df.ix['2015-07-05 12:00:00+02:00':'2015-10-05 12:00:00+02:00'].plot()

# - [6 ] 
h = Hart85()
h.train(mains,columns=[('power','apparent')])
```

**Comment by Dhruvin1412** [comment]
@PMeira, I do not have convert_dred function file, How should I install it? 

![Screenshot (55)](https://user-images.githubusercontent.com/48323399/59983591-d0a3e580-9621-11e9-9d61-33b8c0208acd.png)

**Comment by PMeira** [comment]
@Dhruvin1412 How did you install NILMTK? You need to update from the master branch, and how to do it depends on how it was installed. Since it couldn't find the module (it's not new), you should reinstall anyway.

If you installed using the `environment.yml` file, I'd suggest removing the current environment and recreating from new version of the file (updated today but you need the MSVC build tools installed). 

If you used the conda package from the NILMTK channel or manually, activate the environment you installed it into, uninstall nilmtk, clone or download this repository, then either run `python setup.py develop` from its folder or `pip install -e .`.

**Comment by Dhruvin1412** [comment]
@PMeira Hi, I reinstall the NILMTK, and I did convert file from the All data.csv to dred.h5 format but, I am getting an error with Hmmlearn while running the python setup.py develop and I am using "conda install -c nilmtk nilmtk". 

What are the possible solutions?

**Comment by Dhruvin1412** [comment]
I attached the script. 

(nilmtk-env) C:\Users\GitHub\nilmtk>conda install -c nilmtk nilmtk
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - nilmtk -> hmmlearn

Current channels:

  - https://conda.anaconda.org/nilmtk/win-64
  - https://conda.anaconda.org/nilmtk/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by PMeira** [comment]
@Dhruvin1412 Somehow I got an issue from the issue but I don't see your message here. 

Here's a more detailed version using the official NILMTK channel:

- create an environment:

    conda create -n nilmtk -c nilmtk -c conda-forge nilmtk

- remove the old `nilmtk`  package from this environment

    activate nilmtk 
    conda remove nilmtk

- clone the git repository (assuming you have git installed)

    git clone https://github.com/nilmtk/nilmtk.git

- install without checking the dependencies

    cd nilmtk
    python setup.py develop --no-deps

**Comment by Dhruvin1412** [comment]
@PMeira 
Hi, I followed the steps that you suggested to me, but I am having a problem to convert Dred datasets so, I attached procedure which I followed and with results.

1.) Select the path with loaction name : nilmtk
2.) conda create -n nilmtk -c nilmtk -c conda-forge nilmtk
[Issues: 
	1.)ClobberError"This transaction has incompatible packages due to a shared path" 
	2.)SafetyError: "The package for widgetsnbextension located at C:\Users\Dhruvin suthar\Anaconda3\p	\widgetsnbextension-3.4.2-py36_1000" 
	3.) reported size: 398 bytes; actual size: 207 bytes  ]
3.) conda activate nilmtk
4.) git clone https://github.com/nilmtk/nilmtk.git [results:"Resolving deltas: 100% (8313/8313), done."]
5.) cd nilmtk
6.) python setup.py develop --no-deps [result: "Adding nilmtk 0.3.0.dev0+git.2f15ab7 to easy-install.pth file & am able to work with nilmtk"; issues while converting the dataset using'convert_dred':"# Load Dataset and MeterDevice metadata; AssertionError: "("attached screenshort")"]
7.) git clone https://github.com/nilmtk/nilm_metadata/ [result:"Resolving deltas: 100% (1366/1366), done."]
8.) cd nilm_metadata
9.) python setup.py develop["All file installed properly"]
10.) Installed jupyter notebook: ("python -m ipykernel install --user --name nilmtk-env --display-name "Python (nilmtk)")
11.) having the same issue as step no. 6 ["Attached the scrren shorts"]

Could you please suggest me, what exectly am I missing?


![Screenshot (57)](https://user-images.githubusercontent.com/48323399/60335582-8e223600-999e-11e9-980e-01420da66247.png)

**Comment by raktim2015** [comment]
Hi, @Dhruvin1412 
Please use [link](https://drive.google.com/open?id=1eMIoaiyQsVR-UznRaL9ejar9mYh19hs9) version of DRED for now

**Comment by PMeira** [comment]
@Dhruvin1412 First, please run the following in Python to check if you

```python
import nilmtk.utils
nilmtk.utils.show_versions()
```

If the nilmtk version doesn't match the one you just installed (0.3.0.dev0+git.2f15ab7), then you have multiple installed versions still. Did you forget to run `conda remove nilmtk`? From your screenshot, it's running nilmtk from site-packages, not from the git clone folder.

If you did follow exactly what I listed and it did not work, try updating your conda basic packages first:

```
conda update -n base -c defaults conda
```

Then remove the environment 

```
conda env remove -n nilmtk
```

And try the process again.


> 1.) Select the path with loaction name : nilmtk

Not sure what this means. When you run `conda create -n nilmtk ...` it will create an environment with the name `nilmtk` in the default conda path, there's no need to create one previously. If you want to create the environment on a specific path, check conda docs.

> 1.)ClobberError"This transaction has incompatible packages due to a shared path"
> 2.)SafetyError: "The package for widgetsnbextension located at C:\Users\Dhruvin suthar\Anaconda3\p \widgetsnbextension-3.4.2-py36_1000"
> 3.) reported size: 398 bytes; actual size: 207 bytes ]

I don't get any of those, which suggest you may need update you conda base as I mentioned above.

> 3.) conda activate nilmtk
> 4.) git clone https://github.com/nilmtk/nilmtk.git [results:"Resolving deltas: 100% (8313/8313), done."]
> 5.) cd nilmtk
> 6.) python setup.py develop --no-deps [result: "Adding nilmtk 0.3.0.dev0+git.2f15ab7 to easy-install.pth file

I don't see you mention `conda remove nilmtk` -- that may be the issue.

It seems at least the nilmtk installation from git worked -- 2f15ab7 is the current master hash.


> 7.) git clone https://github.com/nilmtk/nilm_metadata/ [result:"Resolving deltas: 100% (1366/1366), done."]
> 8.) cd nilm_metadata
> 9.) python setup.py develop["All file installed properly"]

You don't need this, it's already installed. You can do it but first you should uninstall nilm_metadata with conda (`conda remove nilm_metadata`) and also use `python setup.py develop --no-deps` to be sure it doesn't try to reinstall any of the conda-installed packages.

> 10.) Installed jupyter notebook: ("python -m ipykernel install --user --name nilmtk-env --display-name "Python (nilmtk)")

OK, but you could just run `jupyter notebook` with environment activated too.

Here's my full output running from a fresh environment with the instructions I listed -- since it's only two lines of code, try running from the command line first (it takes a couple of minutes to run):
```
Python 3.6.7 (default, Feb 28 2019, 07:28:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from nilmtk.dataset_converters.dred.convert_dred import convert_dred
>>> convert_dred("c:/temp/All_data.csv", "c:/temp/dred.h5")
Loading house 1... 1 2 3 4 5 6 7 8 9 10 11 12 13
z:\nilm\nilm_metadata\nilm_metadata\convert_yaml_to_hdf5.py:106: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(fh)
Loaded metadata
z:\nilm\nilm_metadata\nilm_metadata\file_management.py:16: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  objs = yaml.load(fh)
Done converting YAML metadata to HDF5!
Done converting DRED to HDF5!
>>>
```

(If you install nilm_metadata from git, the `YAMLLoadWarning` should be gone, but they're harmless here.)

If this doesn't work, I'm afraid I have no idea what's wrong with your installation.
