### ISSUE TITLE
How to downsample the whole metergroup ?

### ISSUE THREAD

**Issue by anosharshad** [nilmtk/nilmtk#738]
Code :
data = DataSet('C:\\Users\\anosh\\Anaconda2\\envs\\REDD\\redd.h5')
elec = data.buildings[building].elec

I want to downsample the elec (the whole metergroup).

**Comment by nipunbatra** [comment]
Assigned to @raktim2015

**Comment by raktim2015** [comment]
I didn't understand what do you mean by downsampling the whole metergroup. I think you want to downsample each mains separately. 
As elec contains two site-meters, elec.load(sample_period=60) will give the summed up apparent power value. 
Use the following code to select each meter separately.
 
dict={}
dict[1]=next(elec[1].load(sample_period=60))
dict[2]=next(elec[2].load(sample_period=60))

Plot the downsampled readings :-
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
dict[1].plot(ax=ax, legend=True)
dict[2].plot(ax=ax, legend=True)

Check whether the values are summed up or not :-
dict[1].head() 
dict[2].head()
next(elec.load(sample_period=60))

Hope it helps!!
