### ISSUE TITLE
Unable to generate a data extraction from REDD

### ISSUE THREAD

**Issue by aleonnet** [nilmtk/nilmtk#740]
Hi @nipunbatra!
I'm really trying hard to generate a dict per house according to the following picture from REDD database. But I'm unable to accomplish correctly :(
Please help me. Thank you!

![image](https://user-images.githubusercontent.com/20618327/56450600-a2dab180-62fd-11e9-9155-e842ed7608cb.png)

------------------------
import pickle
from nilmtk import DataSet, TimeFrame
import pandas as pd
datafolder = '/Users/alessandro/Documents/data/'
redd = DataSet(datafolder + 'redd.h5')
metadata = dict(redd.metadata)

deviceName = set()
appName = set()
mains={}
appliances={}
for i in range(1,7):
      mains[i] = {} 

for house in range(1,7):
      print('house_',house)
      elec = redd.buildings[house].elec
      appliancelist = elec.appliances
      mainsvalues = elec.mains().power_series_all_data()
      mains[house]=mainsvalues
      for app in appliancelist:
            label = app.label('unknown')
            print(' '*3,label)
            appName.add(label)
            appliances[house][label] = elec[label].power_series(ac_type='active') 
      deviceName = list(appName)
      with open('house_{}.pickle'.format(house), 'wb') as file:
          pickle.dump([deviceName], file)
print('End')

**Comment by nipunbatra** [comment]
Could you please format the code and tell thr error?

**Comment by rajatgupta1234** [comment]
@aleonnet 
Please see the updated code for the same. 
It's in the attachment.
[# Code for Data Extractor.pdf](https://github.com/nilmtk/nilmtk/files/3220181/Code.for.Data.Extractor.pdf)

**Comment by rajatgupta1234** [comment]
@aleonnet , the updated code is as follows:
# Code for Data Extractor

import pickle
from nilmtk import DataSet, TimeFrame
import pandas as pd

# define data path
datafolder = '/Users/Rajat/Documents/data/'
redd = DataSet(datafolder + 'redd.h5')

# define dictionaries and sets to save data
metadata = dict(redd.metadata)
deviceName = set()
appName = set()
mains = {}
appliances = {}

for i in range(1, 7):
   mains[i] = {}


for house in range(1, 7):
   # Extract data housewise
   print('house_', house)
   elec = redd.buildings[house].elec
   appliancelist = elec.appliances
   mainsvalues = elec.mains().power_series_all_data()
   mains[house] = mainsvalues
   for app in appliancelist:
       label = app.type['type']
       print(' ' * 3, label)
       appName.add(label)
       temp = elec[label]
       appliances[label] = next(temp.load())
       deviceName = list(appName)
       deviceName = list(appName)
       with open('house_{}.pickle'.format(house), 'wb') as file:
           # save data per house using pickle
           pickle.dump([deviceName], file)
       print('End')

**Comment by rajatgupta1234** [comment]
@aleonnet 
Please find the attached pdf containing updated code and it's working.
[ Code for Data Extractor .pdf](https://github.com/nilmtk/nilmtk/files/3220189/Code.for.Data.Extractor.pdf)

**Comment by rajatgupta1234** [comment]
@aleonnet  Please see the updated code. 

<pre>
# Code for Data Extractor

import pickle
from nilmtk import DataSet, TimeFrame
import pandas as pd

# define data path
datafolder = '/Users/Rajat/Documents/data/'
redd = DataSet(datafolder + 'redd.h5')

# define dictionaries and sets to save data
metadata = dict(redd.metadata)
deviceName = set()
appName = set()
mains = {}
appliances = {}

for i in range(1, 7):
    mains[i] = {}


for house in range(1, 7):
    # Extract data housewise
    print('house_', house)
    elec = redd.buildings[house].elec
    appliancelist = elec.appliances
    mainsvalues = elec.mains().power_series_all_data()
    mains[house] = mainsvalues
    for app in appliancelist:
        label = app.type['type']
        print(' ' * 3, label)
        appName.add(label)
        temp = elec[label]
        appliances[label] = next(temp.load())
        deviceName = list(appName)
        deviceName = list(appName)
        with open('house_{}.pickle'.format(house), 'wb') as file:
            # save data per house using pickle
            pickle.dump([deviceName], file)
        print('End')

</pre>
