### ISSUE TITLE
Exploring Dataport downloaded data

### ISSUE THREAD

**Issue by Virtsionis** [nilmtk/nilmtk#742]
Hello,

I downloaded Dataport dataset as h5df file format using "periods_to_load" and I am trying to explore the dataset as described in the example here: https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/data.ipynb
https://github.com/nilmtk/nilmtk/blob/master/nilmtk/dataset_converters/dataport/download_dataport.py
The problem is that in that way I downloaded only one building and I cannot use the commands properly. For example when I try to use _print_dict(dataport.buildings[1].metadata)_
I get the following error:
_**KeyError                                  Traceback (most recent call last)
<ipython-input-24-0c89eb0e7380> in <module>
----> 1 print_dict(dataport.buildings[1].metadata)
KeyError: 1**_

The command _print_dict(dataport.buildings)_ does not print anything..

My questions are : 
1) how to download more than one building for the same time period
2) in the case I want to examine only one building which commands should I use?

Thanks in advance

EDIT: I managed to answer the first question myself.  Lets say we want the first 4 houses at the same time period:
periods_to_load={   1: ('2014-04-01', '2014-05-01'),
                                2: ('2014-04-01', '2014-05-01'),
                                3: ('2014-04-01', '2014-05-01'),
                                4: ('2014-04-01', '2014-05-01')})
BUT I still cant use the commands to explore the dataset..

**Comment by nipunbatra** [comment]
Assigned to: @rajatgupta1234

**Comment by raktim2015** [comment]
Hi,
You cannot use the commands because the `periods_to_load` are within the interval when no data are collected. Try using `len(dataport.buildings)` and it will return 0. I would suggest you to use `periods_to_load={9737: ('2013-01-01', '2013-01-31')}` for now and use the dataset. I think you can use the commands now.
Hope it helps !!

**Comment by Virtsionis** [comment]
Thank you very much for your answer. I will try your solution and come back
with feedback.



Στις Δευ, 27 Μαΐ 2019, 18:54 ο χρήστης raktim2015 <notifications@github.com>
έγραψε:
