### ISSUE TITLE
Adding a algorithm to nilmtk

### ISSUE THREAD

**Issue by sanketvijaydesai** [nilmtk/nilmtk#743]
Hello
      Can anyone help me guide on how to add an algorithm to the nilmtk
I have a file name say rnndisagg.py which I copy paste in disaggregate directory. What need to be done after that?

I have no idea about python compiling code etc. Would appreciate the help

**Comment by Virtsionis** [comment]
Hi,

just write the following command:

from rnndisagg  import "class name"

Nick

**Comment by ayushp20** [comment]
https://github.com/nilmtk/nilmtk/blob/master/docs/manual/development_guide/writing_a_disaggregation_algorithm.md

This documents the process of adding an algorithm to NILMTK.
