### ISSUE TITLE
Three phase disaggregation

### ISSUE THREAD

**Issue by unidev10** [nilmtk/nilmtk#744]
Hi. I tried the disaggregation on my single phase energy data. It worked perfectly fine. I'm not understanding how do I disaggregate the three-phase energy data. I have individual phase wise active powers, reactive powers, voltages, currents and power factor. Thanks.

**Comment by nipunbatra** [comment]
Could you give more details?

**Comment by unidev10** [comment]
Yes, sure. 
I've got a mains dataset which contains the following parameters.
Also, there's a dataset containing air conditioning energy consumption which has the same parameters. 

TS | srl | VA | W | VAR | PF | A | F | V1 | V2 | V3 | A1 | A2 | A3 | W1 | W2 | W3 | VA1 | VA2 | VA3 | VAR1 | VAR2 | VAR3 | PF1 | PF2 | PF3 | FwdVAh | FwdWh | FwdVARhR | FwdVARhC
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

And now, here I'm confused, whether the disaggregation has to be done separately for three individual phases, or to use the total power consumption by the three phases.

**Comment by nipunbatra** [comment]
@unidev10 That's up to you the way you wish to do the disaggregation.

If you know which phase the AC is installed in, it's an easier problem to disaggregate on that phase. 
Else, disaggregate on the total power consumption.

Most research papers do the latter as the phase-wise consumption is mostly not known and varies across countries.
