### ISSUE TITLE
COMBED problem with FHMM

### ISSUE THREAD

**Issue by chicooom** [nilmtk/nilmtk#750]
Hi there everyone,

Hope you are all having a great week!

I'm facing a problem while running the FHMM algorithm on the combed dataset.
First I tried with the h5 file from the http://combed.github.io/ and then I tried myself to "clean" the CSVs, put everything with the same number of entries and convert it to h5.

Both approaches are giving me the same error :(

`train1 = DataSet('/Users/chicooom/Desktop/combed_test1.h5')
test1 = DataSet('/Users/chicooom/Desktop/combed_test1.h5')

train1.set_window(end = "15-06-2014")
test1.set_window(start = "15-06-2014")

train1_elec = train1.buildings[1].elec
test1_elec = test1.buildings[1].elec

AHU1_train = train1_elec.select_using_appliances(type = 'AHU', instance = 3)`

`
start = time.time()
from nilmtk.disaggregate import fhmm_exact
fhmm = fhmm_exact.FHMM()

fhmm.train(AHU1_train, sample_period = 30)
end = time.time()
print("Runtime =", end-start, "seconds.")`

`
pred = {}
gt   = {}

for i, chunk in enumerate(test1_elec.mains().load(sample_period=30)):
    chunk_drop_na = chunk.dropna()
    pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)
    gt[i]={}
    
    for meter in test1_elec.submeters().meters:
        # Only use the meters that we trained on (this saves time!)    
        gt[i][meter] = next(meter.load(sample_period=30))
    gt[i] = pd.DataFrame({k:v.squeeze() for k,v in iteritems(gt[i])}, index=next(iter(gt[i].values())).index).dropna()
`

ERROR:
`ValueError                                Traceback (most recent call last)
<ipython-input-23-aff187b49429> in <module>
      4 for i, chunk in enumerate(test1_elec.mains().load(sample_period=30)):
      5     chunk_drop_na = chunk.dropna()
----> 6     pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)
      7     gt[i]={}
      8 

/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/disaggregate/fhmm_exact.py in disaggregate_chunk(self, test_mains)
    340         test_mains = test_mains.dropna()
    341         length = len(test_mains.index)
--> 342         temp = test_mains.values.reshape(length, 1)
    343         learnt_states_array.append(self.model.predict(temp))
    344 

ValueError: cannot reshape array of size 141660 into shape (47220,1)`

Thanks a lot in advance!

**Comment by raktim2015** [comment]
Lets discuss the problem in details.
AHU1_train will consist of current, energy and power readings for that appliance. Convert this MeterGroup into pandas dataframe to see all the attributes. 
Code :- 
```
df=next(AHU1_train.load(sample_period=30))
df.head()
```
Now, while testing the data, target column should be one dimensional, that is, the algorithm should disaggregate either on current, energy or active power.

Use the following code :- 

```
pred = {}
gt= {}

for i, chunk in enumerate(test1_elec.mains().load(physical_quantity='power',ac_type='active',sample_period=30)):
    chunk_drop_na = chunk.dropna()
    pred[i] = fhmm.disaggregate_chunk(chunk_drop_na)
    gt[i]={}
    
    for meter in test1_elec.submeters().meters:
        # Only use the meters that we trained on (this saves time!)    
        gt[i][meter] = next(meter.load(physical_quantity='power',ac_type='active',sample_period=30))
    gt[i] = pd.DataFrame({k:v.squeeze() for k,v in iteritems(gt[i])}, index=next(iter(gt[i].values())).index).dropna() 
```
This should work like charm.
In your code, the chunk contains 3 columns instead of 1. To verify this, check the ValueError part. 141660/47220 = 3

Hope it helps!!

**Comment by nipunbatra** [comment]
I will close the issue as it is resolved for us. Please reopen if necessary.

**Comment by chicooom** [comment]
Sorry for the late reply!

Thanks a lot for the help @raktim2015 
Apparently, I'm not facing the error anymore
