### ISSUE TITLE
Dataset issue (IAWE)

### ISSUE THREAD

**Issue by snmuduli** [nilmtk/nilmtk#757]
Hello Sir,
I am a data scientist currently working in the field of energy disaggregation. I aim to explore the application of various deep learning methods (GRU, Seq2Point and LSTM) in this field. I was working on IAWE dataset but I found that the models are not working well on unseen data, maybe due to lack of sufficient amount of data and variations. I have tried for REDD dataset and also simulated new data for a period of 2 months but still it fails for unseen data. Please suggest a suitable solution or dataset for the same.

Thank you.

**Comment by nipunbatra** [comment]
> I aim to explore the application of various deep learning methods (GRU, Seq2Point and LSTM) in this field
 We plan to implement some of these in the coming months

>I was working on IAWE dataset but I found that the models are not working well on unseen data, maybe due to lack of sufficient amount of data and variations. 
Unseen data from what dataset? How do you quantify not working well? NILM is a hard problem and the accuracy/errors need to be put into perspective and looked at wrt state-of-the-art.

>Please suggest a suitable solution or dataset for the same.
If you think data set size is an issue, then, I would highly recommend looking into Dataport dataset.
