### ISSUE TITLE
The current version performs training ONLY on the first chunk.

### ISSUE THREAD

**Issue by walidsliti** [nilmtk/nilmtk#767]
Hi,

I'am working with FHMM and in fhmm-exact there is a comment in the train function says " The current version performs training ONLY on the first chunk." I didn't get it well
can you please explain it to me 

Thanks

**Comment by nipunbatra** [comment]
@walidsliti 
FHMM or many other algorithms might be capable of being trained in an online fashion, i.e. to say as and when more data is made available for training, the model can be refined. However, implementing the same can be non-trivial. 

Thus, in the current implementation only a single batch of data is used for training.
