### ISSUE TITLE
FHMM training

### ISSUE THREAD

**Issue by walidsliti** [nilmtk/nilmtk#768]
Hi @nipunbatra 
I'am confusing Why in the train function we don't take the mains as an argument 
def train(self, metergroup, num_states_dict={}, **load_kwargs)
or fhmm needs only the appliance to get the parameters : means, cov, states, startprob..
I want also to know how to choose the number of states "num_states_dict={}" and the default number ?

THank you

**Comment by nipunbatra** [comment]
number of states is how many states you'd expect for the appliance - like ON, OFF, INTERMEDIATE. If you don't know, then default would work well for you.

We do not require the mains as we're only looking to learn an HMM for each appliance, which is later combined to create the exact FHMM model.

**Comment by walidsliti** [comment]
So in the dissagrgation part, when we give it the main, FHMM look to the average of the combined states and predict ?
