### ISSUE TITLE
set_window - strange behaviour using ECO dataset

### ISSUE THREAD

**Issue by nekovolta** [nilmtk/nilmtk#774]
I used the REDD dataset to check the disaggregation features, using this notebook:
[https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/disaggregation_and_metrics.ipynb](url)

I tried to do the same with the ECO dataset, but when I set the 'start' and 'end' of the windows for train and test it does not work correctly. I dug in this problem, and I realised these problems:

**### 1**. In REDD the format for time is dd-mm-yyyy, and it seems that when I use the ECO dataset, it appears that the format is mm-dd-yyyy. I realised this because when I used this example, it plotted for 8th October to 12th October.

```python
train.set_window(start="10-8-2012",end="10-12-2012")
train_elec = train.buildings[1].elec
train_elec.plot()
```
![image](https://user-images.githubusercontent.com/29656053/58632560-29fc4b80-82e6-11e9-88e7-590f32595410.png)

Why in REDD the format is in one way and for ECO in another different?

**### 2**. Taking into account that the format would be mm-dd-yyyy, I run the next example:

```python
train.set_window(start="8-10-2012",end="12-10-2012")
train_elec = train.buildings[1].elec
train_elec.plot()
```
In this case, it also plotted the interval from 10th August to 10th December but I get the next error, which I do not understand.

![image](https://user-images.githubusercontent.com/29656053/58633971-55813500-82ea-11e9-93e3-f111b6b86b63.png)

**### 3**. Lastly, when I use this structure:

```
train.set_window(end="8-31-2012")
train_elec = train.buildings[1].elec
train_elec.plot()
```

It does not plot anything and also reported the same error than in point 2.

```
train.set_window(end="8-31-2012")
train_elec = train.buildings[1].elec
train_elec.plot()
Traceback (most recent call last):

  File "<ipython-input-194-03c1fbf52c64>", line 3, in <module>
    train_elec.plot()

  File "C:\Users\AbrahamA-Idener\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\metergroup.py", line 1398, in plot
    ax = function_map[kind](**kwargs)

  File "C:\Users\AbrahamA-Idener\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\metergroup.py", line 1409, in _plot_separate_lines
    ax = meter.plot(ax=ax, plot_legend=False, **kwargs)

  File "C:\Users\AbrahamA-Idener\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\electric.py", line 180, in plot
    kwargs = self._set_sample_period(timeframe, **kwargs)

  File "C:\Users\AbrahamA-Idener\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\electric.py", line 204, in _set_sample_period
    duration = timeframe.timedelta.total_seconds()

  File "C:\Users\AbrahamA-Idener\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\timeframe.py", line 132, in timedelta
    return self.end - self.start

  File "pandas/_libs/tslib.pyx", line 1324, in pandas._libs.tslib._Timestamp.__sub__

TypeError: Timestamp subtraction must have the same timezones or no timezones
```

**Comment by rajatgupta1234** [comment]
@nekovolta 
### 2 and ### 3 are getting plotted without no error. 
What version of pandas are you using? 
![issue](https://user-images.githubusercontent.com/46721220/58782962-7359dd00-85fd-11e9-9689-e0c2316c1841.PNG)

**Comment by ayushp20** [comment]
@nekovolta 
###1. I can confirm that the format is 'mm-'. Still looking into this behaviour.
###2. Can't replicate this error, code runs perfectly fine. Would help to know if which building data your *eco.h5*, some particular building or the entire dataset.
My code for reference:
```python
from __future__ import print_function, division
import time
from matplotlib import rcParams
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from six import iteritems
import warnings

warnings.filterwarnings('ignore')
%matplotlib inline

rcParams['figure.figsize'] = (20, 10)

from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
from nilmtk.disaggregate import CombinatorialOptimisation,FHMM
    
train = DataSet('/home/ayush/data/eco.h5')
test = DataSet('/home/ayush/data/eco.h5')

train.set_window(start="10-8-2012",end="10-12-2012")
train_elec = train.buildings[1].elec
train_elec.plot()
```
![Screenshot from 2019-06-03 12-44-24](https://user-images.githubusercontent.com/36565028/58782966-5c03fb00-85cf-11e9-93cc-6d7115fa79ea.png)

###3.  Same. Can't replicate this error.
```python
from __future__ import print_function, division
import time
from matplotlib import rcParams
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from six import iteritems
import warnings

warnings.filterwarnings('ignore')
%matplotlib inline

rcParams['figure.figsize'] = (20, 10)

from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
from nilmtk.disaggregate import CombinatorialOptimisation,FHMM
    
train = DataSet('/home/ayush/data/eco.h5')
test = DataSet('/home/ayush/data/eco.h5')
train.set_window(end="8-31-2012")
train_elec = train.buildings[1].elec
train_elec.plot()
```
![Screenshot from 2019-06-03 12-42-39](https://user-images.githubusercontent.com/36565028/58782881-2eb74d00-85cf-11e9-8f5f-d744de3d37cc.png)

**Comment by ayushp20** [comment]
@nekovolta 
The correct format to pass the date window is actually 'yyyy-mm-dd'. 
```python
elec = redd.buildings[1].elec
elec.get_timeframe()
TimeFrame(start='2011-04-18 09:22:09-04:00', end='2011-05-24 15:57:02-04:00', empty=False)
```
Next it defaults to 'mm-dd-yyyy'.
If 'mm' >12 then it defaults to 'dd-mm-yyyy'.
The window for REDD dataset is actually the 3rd scenario, 'mm' >12 and thus 'dd-mm-yyyy' works correctly.
But if the day first parameter is < 12, we can replicate this behaviour in REDD dataset as well. Here is an example:
![Screenshot from 2019-06-03 13-19-08](https://user-images.githubusercontent.com/36565028/58785510-2104c600-85d5-11e9-8bca-7247d0212519.png)

I'll push an update to the documentation to reflect the same.

**Comment by nekovolta** [comment]
@rajatgupta1234 @ayushp20 

I tried again with the same examples I posted and **it works perfectly fine now**. I do not know what the problem is, but as you can see in the first two examples, I got that mentioned:

`TypeError: Timestamp subtraction must have the same timezones or no timezones`

@ayushp20 

Thank you for the information about the date format. I think it could be useful to set a format as a reference, to avoid these complex cases depending on whether the 'mm'>12 or not.

**Comment by ayushp20** [comment]
Yes, I'll update the documentation to use the format that is universal for all datasets. It is surprising this behavior went unnoticed all this time.
