### ISSUE TITLE
what is the 'sample period' ?

### ISSUE THREAD

**Issue by nekovolta** [nilmtk/nilmtk#793]
I am struggling to understand what is the 'sampling period'. I thought that this parameter would allow adjusting the sampling rate of the data acquisition. For instance, ECO and REDD dataset are at each second. If I put the **sample_period = 1**, then it takes the data for training and prediction at each second. If I put **sample_period = 60** it would make the data at every minute.

But I am afraid I can be wrong. I tested three cases, with **sample_period = 600, sample_period = 60 and sample_period = 6** and the data is very similar, as you can see in these pictures:

**ECO dataset / sample_period = 600**
![image](https://user-images.githubusercontent.com/29656053/59371468-6186e100-8d45-11e9-9aac-c42b998a5f7c.png)

**ECO dataset / sample_period = 60**
![image](https://user-images.githubusercontent.com/29656053/59371502-795e6500-8d45-11e9-8efe-aa0b5a6747b6.png)

**ECO dataset / sample_period = 6**
![image](https://user-images.githubusercontent.com/29656053/59371510-7f544600-8d45-11e9-8c48-43dc0454404a.png)

For instance, the cycles of the ground truth data are very similar in the three cases, and if the sample_period downsampled the data, they would be very different. Moreover, the disaggregation feature does not change considerably. 

On the other hand, doing a similar test with REDD dataset, I found out the same behaviour, and even with less resolution (**REDD dataset / sample_period = 120**), the results are better than with higher resolution (**REDD dataset / sample_period = 1**), when the response would be just the other way around.

**REDD dataset / sample_period = 120**
![image](https://user-images.githubusercontent.com/29656053/59372281-6fd5fc80-8d47-11e9-830f-ba9c561e2c3b.png)

**REDD dataset / sample_period = 1**
![image](https://user-images.githubusercontent.com/29656053/59373415-ebd14400-8d49-11e9-97cf-5da9df3f3e21.png)

**Comment by nipunbatra** [comment]
Please run something like on your dataset with varying sample_period to understand what goes on:

```python

from nilmtk import DataSet
ds = DataSet("/home/nipunbatra-pc/Downloads/iawe.h5")
elec = ds.buildings[1].elec
df = next(elec.meters[0].load(chunksize=1000, sample_period=3600))
```

**Comment by rajatgupta1234** [comment]
@nekovolta 
1. The sample_period works fine. 
![isue](https://user-images.githubusercontent.com/46721220/59560516-e23d2a00-9030-11e9-9db0-d811391f07e7.PNG)

2. The prediction depends on how much dataset you use for training and which algorithm you are feeding it into. One more thing is that the resolution(which is inversely proportional to sample period) may vary the mean squared error after prediction too. But generally it is seen that default sample_period which is 60 gives good prediction.

**Comment by nekovolta** [comment]
@nipunbatra I think that what I tried in the first post is different experiments with several sample periods. However, I did something similar again just trying with the dataset, without training and prediction, and I think it works as I supposed: 

![Sample_Period_ECO](https://user-images.githubusercontent.com/29656053/59609456-b6e13a80-9117-11e9-9416-f9a72014dc63.png)

But based on the results I plotted previously, it is not in accordance with the results (at high sample period, the results are worse). @rajatgupta1234 commented about this issue, considering the original data granularity. I agree that if the original dataset has a resolution lower than the sample_period, the results can be worse. But ECO dataset has a granularity of 1 Hz, and the sample period in the last example is 1. Why should the results be worse then?

**Comment by nekovolta** [comment]
@nipunbatra 
I understand what you mean, but still, I do not manage to identify clearly. In the first post, I compared in REDD dataset two cases: with sample period=120 and sample_period=1. I understand that there is much more noise, but FHMM is not considered a not sophisticated method, don't you think?
 On the other hand, with ECO dataset the results show some improvement between the cases of sample period=600 and sample_period=6, and both datasets have the same minimal resolution (1Hz), and the disaggregation was performed under the same method (FHMM).

So I guess it should be something more. Maybe something related to the dataset?

**Comment by nekovolta** [comment]
Checking the data of REDD dataset, I realised that the granularity is not 1Hz, and it is recorded each 3-4 seconds:

```python
df = next(fridge.load())
df.head()
```

```
physical_quantity          power
type                      active
2011-04-18 09:22:13-04:00    6.0
2011-04-18 09:22:16-04:00    6.0
2011-04-18 09:22:20-04:00    6.0
2011-04-18 09:22:23-04:00    6.0
2011-04-18 09:22:26-04:00    6.0
```

I set the sample_period=1, and it may be the root of poor performance when disaggregating. On the other hand, when I load the data a **sample_period=1**, it generates intermediate values. 


```python
df = next(fridge.load(sample_period=1))
df.head()
```

```
physical_quantity          power
type                      active
2011-04-18 09:22:13-04:00    6.0
2011-04-18 09:22:14-04:00    6.0
2011-04-18 09:22:15-04:00    6.0
2011-04-18 09:22:16-04:00    6.0
2011-04-18 09:22:17-04:00    6.0
```

Shouldn't it have generated maximal resolution available (data each 3-4) instead of data each second even though I am setting the sample_period=1?

**Comment by PMeira** [comment]
> Shouldn't it have generated maximal resolution available (data each 3-4) instead of data each second even though I am setting the sample_period=1?

I don't think so. At some point, it's up to the user to know the dataset. You can check `fridge.sample_period()` or the meter's metadata property directly.

I just added (a1dfdeb) a warning though, it should now say something like if you have warnings enabled:

> UserWarning: The provided sample_period (1) is shorter than the meter's sample_period (3)
