### ISSUE TITLE
Training with different few appliances in REDD

### ISSUE THREAD

**Issue by nekovolta** [nilmtk/nilmtk#797]
The issue #792 reveals that there is a limitation with the number of appliances used during the training phase. After some test, I tried with 8 appliances and sample_period = 120, and the computer cannot solve this problem. With less number of appliances, it takes time, but it solved the problem. I found that when I train with less number of appliances, the disaggregation results are much worse. For instance, here, you can see an example:

**Training = 1 appliance / Sample_period = 120**

![image](https://user-images.githubusercontent.com/29656053/59777902-c26a6800-92b5-11e9-9362-22f7b1043a57.png)

**Training = 6 appliances / Sample_period = 120**

![image](https://user-images.githubusercontent.com/29656053/59777911-c9917600-92b5-11e9-8678-5a605d240526.png)

As can be observed, the results with a higher number of appliances are much better than when the training is carried out with just 1 appliance. I don't understand very well this, because if I am training only with the fridge (1 appliance), it should be better disaggregation the results on the aggregate power consumption (main meters). Don't you think? What am I misunderstanding here?

**Comment by nipunbatra** [comment]
Too few appliances and the aggregate doesn’t show them well enough, too
many and the model becomes very complicated and doesn’t generalise. This is
akin to underfitting/overfitting behaviour in machine learning. In General
having 5-6 appliances cosnsituting 70 percent or so of load will likely
give reasonable numbers.
