### ISSUE TITLE
load(cols=['list of tuples']) does not work

### ISSUE THREAD

**Issue by nekovolta** [nilmtk/nilmtk#800]
Reading the API documentation, you can load the data selecting the specific cols. For instance, I am using the IAWE dataset to load this data:

```python
df = next(fridge.load(cols=[('power', 'active'), ('voltage', '')]))
df.head()
```
but I get this error: 

```python
df = next(fridge.load(cols=[('power', 'active'), ('voltage', '')]))
df.head()
Traceback (most recent call last):

  File "<ipython-input-236-fffc1e7d092d>", line 1, in <module>
    df = next(fridge.load(cols=[('power', 'active'), ('voltage', '')]))

  File "C:\Users\nekovolta\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\elecmeter.py", line 443, in load
    last_node = self.get_source_node(**kwargs)

  File "C:\Users\nekovolta\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\elecmeter.py", line 569, in get_source_node
    generator = self.store.load(key=self.key, **loader_kwargs)

  File "C:\Users\nekovolta\Anaconda3\envs\nilmtk-env\lib\site-packages\nilmtk\docinherit.py", line 46, in f
    return self.mthd(obj, *args, **kwargs)

TypeError: load() got an unexpected keyword argument 'cols'
```

**Comment by PMeira** [comment]
@nekovolta Check `help(fridge.load)` or, in Jupyter or IPython, `? fridge.load`. Nowadays the parameter is `columns` for compatibility with Pandas. Renamed in https://github.com/nilmtk/nilmtk/commit/fed7009b174853ffadb8ad63f9786868a5c692b3 on September/2018.

> columns : list of tuples, using NILMTK's vocabulary for measurements.
>     e.g. [('power', 'active'), ('voltage', ''), ('energy', 'reactive')]
>     `columns` can't be used if `ac_type` and/or `physical_quantity` are set.

@nipunbatra  Do you think it is time to update the API docs at http://nilmtk.github.io/nilmtk/master/index.html ?
