### ISSUE TITLE
Drop Python 2.7

### ISSUE THREAD

**Issue by PMeira** [nilmtk/nilmtk#802]
We should probably drop Python 2.7 completely soon. I'm opening the issue now to see it there's any objections.

That would allow us to remove a bunch of lines related to `__futures__`, `past`, `six`.

**Comment by nipunbatra** [comment]
I'd agree. We should drop Python 2 support now.

**Comment by jpchavat** [comment]
I'm starting to use nilmtk for my msc thesis. I can't find a better option to get in the framework than participating in work of dropping py2.

It may also be beneficial to make progress in the use of a style standard as PEP8 [1], at the time of dropping py2. I tried to start in that way on the PR https://github.com/nilmtk/nilmtk/pull/811.

[1]. https://www.python.org/dev/peps/pep-0008/

**Comment by jpchavat** [comment]
Is someone working on it?
How can I participate?

**Comment by PMeira** [comment]
> Is someone working on it?

@jpchavat Yep, I'll handle it (I assigned it to myself here on GitHub). As soon as v0.3.x is full out, I'll merge the changes. Still need to update the docs to reflect the state of the v0.3 release and so on. We're also waiting on a some pending changes for starting the work on v0.4 on the master branch. 

Pandas v0.25.0 is also out now and it already dropped Python 2.7, but there are several bugs fixed already for the future v0.25.1, so it's probably better to wait for it before migrating.

**Comment by PMeira** [comment]
@jpchavat The changeset for dropping Python 2.7 doesn't change that much, it's mostly removal of the wrapper for iterables and dict iterators for six.

**Comment by jpchavat** [comment]
> Yep, I'll handle it (I assigned it to myself here on GitHub).

Sorry, I didn't figure it out. 

> The changeset for dropping Python 2.7 doesn't change that much, it's mostly removal of the wrapper for iterables and dict iterators for six.

Ok. Where can I see the preview of the version? Are you working over master branch? or do you follow a particular workflow on git?

Do you think that I can help in something before the launch of v0.3.x?

**Comment by PMeira** [comment]
> or do you follow a particular workflow on git?

@jpchavat I have a local copy that I'll merge after retesting most things.

> Do you think that I can help in something before the launch of v0.3.x?

If you're familiar enough, either updating the docs or just pointing docs that need updates would help. 

I'll probably work on both of these on a weekend -- even if v0.3 is not fully released by them, its development will be moved into a v0.3.x branch to allow us to work on more severe changes on master.
