### ISSUE TITLE
Hart85 algorithm notebook/blog post/python file example?

### ISSUE THREAD

**Issue by beautifwhale** [nilmtk/nilmtk#803]
Is there a simple example notebook/blog post/python file I can read that uses the Hart85 algorithm on the REDD dataset?

**Comment by PMeira** [comment]
Please check the docs at https://github.com/nilmtk/nilmtk/tree/master/docs/manual
Especially https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/hart_disaggregation_demo.ipynb

Note that NILMTK is aimed at researchers, you might not get what you expect from it.

**Comment by beautifwhale** [comment]
@PMeira Thanks for the link, really appreciated

> Note that NILMTK is aimed at researchers, you might not get what you expect from it.

Wondering what you mean here?
