### ISSUE TITLE
REDD: Using model for building 1 to predict appliances in building 2

### ISSUE THREAD

**Issue by beautifwhale** [nilmtk/nilmtk#805]
Can we use a model trained on one building to disaggregate another buildings mains? I've tried to select only appliances that exist in both to train on building 1 and use on building 2 but this does not work.

**Comment by beautifwhale** [comment]
Answering this myself, building a model with FHMM and trying to apply it to different buildings just dosent work...

**Comment by nipunbatra** [comment]
This setting works. We plan to release a newer version of NILMTK by early next week which allows to do the things you've been asking. So, keep a tab on NILMTK :)
