### ISSUE TITLE
Value Error Hart algorithm

### ISSUE THREAD

**Issue by anosharshad** [nilmtk/nilmtk#812]

**Comment by anosharshad** [comment]
I am using "hart_disaggregation_demo.ipynb" file and while training the hart model i get value error. Kindly help me to fix it 

h.train(mains, columns=[('power','apparent')])
Loading data for meter ElecMeterID(instance=2, building=2, dataset='REDD')     
Done loading data all meters for this chunk.
Finding Edges, please wait ...
Edge detection complete.
Creating transition frame ...
Transition frame created.
Creating states frame ...
States frame created.
Finished.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-27-05b421f0c594> in <module>
----> 1 h.train(mains,sample_period=60, columns=[('power','apparent')])

~\Anaconda2\envs\nilmtk-env\lib\site-packages\nilmtk\disaggregate\hart_85.py in train(self, metergroup, columns, buffer_size, noise_level, state_threshold, min_tolerance, percent_tolerance, large_transition, **kwargs)
    245         self.pair_df = self.pair(
    246             buffer_size, min_tolerance, percent_tolerance, large_transition)
--> 247         self.centroids = hart85_means_shift_cluster(self.pair_df, columns)
    248 
    249         self.model = dict(

~\Anaconda2\envs\nilmtk-env\lib\site-packages\nilmtk\feature_detectors\cluster.py in hart85_means_shift_cluster(pair_buffer_df, columns)
    156     X = cluster_df.values.reshape((len(cluster_df.index), len(columns)))
    157     ms = MeanShift(bin_seeding=True)
--> 158     ms.fit(X)
    159     labels = ms.labels_
    160     cluster_centers = ms.cluster_centers_

~\Anaconda2\envs\nilmtk-env\lib\site-packages\sklearn\cluster\mean_shift_.py in fit(self, X, y)
    394 
    395         """
--> 396         X = check_array(X)
    397         self.cluster_centers_, self.labels_ = \
    398             mean_shift(X, bandwidth=self.bandwidth, seeds=self.seeds,

~\Anaconda2\envs\nilmtk-env\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
    460                              " minimum of %d is required%s."
    461                              % (n_samples, shape_repr, ensure_min_samples,
--> 462                                 context))
    463 
    464     if ensure_min_features > 0 and array.ndim == 2:

ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required.

**Comment by PMeira** [comment]
Pretty sure you need to update NILMTK, please run the following and paste the result here. 

```
import nilmtk.utils
nilmtk.utils.show_versions()
```

**Comment by anosharshad** [comment]
Results 

INSTALLED VERSIONS
------------------
commit: None
python: 3.6.8.final.0
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: None.None

pandas: 0.22.0
pytest: None
pip: 18.1
setuptools: 40.6.3
Cython: 0.29.2
numpy: 1.15.4
scipy: 1.1.0
pyarrow: None
xarray: None
IPython: 7.2.0
sphinx: None
patsy: 0.5.1
dateutil: 2.7.5
pytz: 2018.7
blosc: None
bottleneck: 1.2.1
tables: 3.4.4
numexpr: 2.6.8
feather: None
matplotlib: 3.0.2
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
sqlalchemy: None
pymysql: None
psycopg2: 2.7.6.1 (dt dec pq3 ext lo64)
jinja2: 2.10
s3fs: None
fastparquet: None
pandas_gbq: None
pandas_datareader: None
None

Date: 2019-07-13 11:55:28.963481
Platform: Windows-10-10.0.17763-SP0
System version: 3.6
nilmtk version: 0.3.0.dev
nilm_metadata version: 0.2.2
numpy version: 1.15.4
matplotlib version: 3.0.2
pandas version: 0.22.0
sklearn version: 0.19.2
hmmlearn version: 0.2.1

**Comment by PMeira** [comment]
Yep, that's it, you're a few months behind.

I'd recommend removing the current nilmtk-env and either recreate the environment using the new `environment.yml`, or the (slightly outdated) conda package with `conda create -n nilmtk-env -c nilmtk -c conda-forge nilmtk`
