### ISSUE TITLE
Creating an Elecmeter object manually

### ISSUE THREAD

**Issue by cathreya** [nilmtk/nilmtk#815]
We were using a model that takes an Elecmeter object as an input to the disaggregation function. We were interested in running the model on a single monthly aggregate(given by the user). For this, we need to create an Elecmeter object with a single entry (the monthly aggregate). We could not find anything in the documentation to this end. We tried to circumvent this by using something similar to the dataset converter code, by writing and reading from an hdf5 store, but we didn't manage to get anywhere with it. Is there any other way to achieve this?

**Comment by nipunbatra** [comment]
You could resample to a month while loading the data.

**Comment by cathreya** [comment]
We were interested in taking the value from a user instead of taking data from the test set. Would this be possible?

**Comment by PMeira** [comment]
@cathreya AFAICT, that's not the original intended usage of NILMTK, hence there's no nothing to do that.

Still, I'd recommend two alternatives:

1) Consider subclassing the base `DataStore` class. I wouldn't guarantee it works, as a some functionality is currently tied to the HDFStore, but you might be able to adapt it more easily. If I were to add remote loading, that's what I'd choose. 
I haven't tested the [CSV datastore](https://github.com/nilmtk/nilmtk/blob/906ad988e58d3738917a8b838d853aecaf69d150/nilmtk/datastore/csvdatastore.py) for a while, but if that is still in shape, you could use it as base. You probably need to replace [utils.get_datastore](https://github.com/nilmtk/nilmtk/blob/906ad988e58d3738917a8b838d853aecaf69d150/nilmtk/utils.py#L308) too.

2) Alternatively, you could try to write you own [`ElecMeter.Load`](https://github.com/nilmtk/nilmtk/blob/906ad988e58d3738917a8b838d853aecaf69d150/nilmtk/elecmeter.py#L348), either by subclassing and replacing every instance you need, or monkey-patching.

**Comment by PMeira** [comment]
@cathreya Oh, and if you think this is worth integrating into NILMTK, feel free to open a PR later.
