### ISSUE TITLE
Trying one one metre reading, disaggregate lights

### ISSUE THREAD

**Issue by meljsingh** [nilmtk/nilmtk#816]
Hello! I know this is a very vague question, but I would like to try this algorithm to separate the energy use of an energy metre dataset of mine, for a hydroponic farm.

I am a bit confused about how to create the metadata file (nilmk-df) for a simple energy metre reading with three appliances (lights, ventilation and other). I would appreciate being directed towards the appropriate resource or to find out if only possible on small example?

Dataset: csv file with hourly energy use, clear on/off light pattern, slightly variable ventilation pattern.

Data format
Timestamp                         Energy Use
YYYY-MM-DD HH:MM     X kWh

.. available for 9 months

Any help immensely appreciated, a little lost!

Thank you,
Melanie

**Comment by PMeira** [comment]
Have you checked the guide already?
https://github.com/nilmtk/nilmtk/blob/master/docs/manual/development_guide/writing_a_dataset_converter.md

**Comment by meljsingh** [comment]
Ah thank you I was on this: https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/data.ipynb <https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/data.ipynb>

And did not find the development guide subsection. 

I am simply a little confused about metadata, as all the examples seem to be quite big, and contain more information (such as power, voltage) etc, while I only have power and time, and my priors are simply that I know the expected time appliances are on/off, and the likely ventilation setting (only two appliances really: ventilation, light, other).

Is this doable in NILMK?

Thanks for quick response, very appreciated!




Melanie Jans-Singh
PhD student - Energy Efficient Cities initiative
CDT in Future Infrastructure and the Built Environment
Department of Engineering
mkj32@cam.ac.uk

**Comment by PMeira** [comment]
> I am simply a little confused about metadata, as all the examples seem to be quite big

You can use a simpler dataset that doesn't have too many different quantities. Looks like you only need a single building.


> my priors are simply that I know the expected time appliances are on/off, and the likely ventilation setting (only two appliances really: ventilation, light, other).

Currently you'd need to generate timeseries for those.

Power and time should be enough. Usually the mains is more detailed, while the meters on the individual devices more limited. The REFIT dataset seems more close to what you're looking for, take a look at the [converter](https://github.com/nilmtk/nilmtk/blob/master/nilmtk/dataset_converters/refit/convert_refit.py) and the [metadata folder](https://github.com/nilmtk/nilmtk/tree/master/nilmtk/dataset_converters/refit/metadata) that it uses.

I'd copy the converter folder, delete all but one of the `buildingX.yaml`, rename everything to match your data, and adjust the code and the remaining metadata.
