### ISSUE TITLE
Why this code can decode the power?

### ISSUE THREAD

**Issue by Wusir2018** [nilmtk/nilmtk#825]
Hello!
In this link,
[https://github.com/nilmtk/nilmtk/blob/master/nilmtk/legacy/disaggregate/fhmm_exact.py](url)

I know the purpose of `def decode_hmm` is to get the power, but I can't understand how the follow code realize the function. Why did you calculate power in this way?
`factor = total_num_combinations
for appliance in appliance_list:
    factor = factor // len(centroids[appliance])
    temp =int(states[i]) / factor
    hmm_states[appliacne][i] = temp % len(centroids[appliance])
    hmm_power[appliance][i] = centroids[appliance][hmm_states[appliance][i]]`

Thank you!

**Comment by PMeira** [comment]
```python
factor = total_num_combinations
for appliance in appliance_list:
    factor = factor // len(centroids[appliance])
    temp =int(states[i]) / factor
    hmm_states[appliacne][i] = temp % len(centroids[appliance])
    hmm_power[appliance][i] = centroids[appliance][hmm_states[appliance][i]]
```

For HMM, we model discrete states and the transitions across them. Here, the states are estimated through the centroids. So we map from/to power to/from state.
