### ISSUE TITLE
SciPy >= 0.19 and HMM

### ISSUE THREAD

**Issue by klemenjak** [nilmtk/nilmtk#826]
Hello,

I don't know if that's still a problem but I had to deal with it today. After updating SciPy to a version >=0.19 I had to update some import statements in files related to the FHMM implementation.

Instead of:

```
from scipy.misc import comb, logsumexp
```

you need to use:

```
from scipy.special import comb, logsumexp
```

Possible fix:

```
try:  # SciPy >= 0.19
    from scipy.special import comb, logsumexp
except ImportError:
    from scipy.misc import comb, logsumexp  # noqa 
```

Felt like sharing that fix. If it's not a thing anymore, never mind.

Best,
Christoph

**Comment by PMeira** [comment]
@klemenjak The hmmlearn module itself handled that, just need to update it. The package versions we use for the conda package and the ones listed in the environment.yml files should work fine (were tested).
