### ISSUE TITLE
Combine Initialise and Init in init

### ISSUE THREAD

**Issue by nipunbatra** [nilmtk/nilmtk#828]
https://github.com/nilmtk/nilmtk/blob/52230bed15dae3186dc550d8c8812b221fc7e320/nilmtk/api.py#L27

Assigned to @Rithwikksvr

**Comment by PMeira** [comment]
Done in https://github.com/nilmtk/nilmtk/commit/bb0541e520f09f5ab6469bb4ea552ca8c598c28c
