### ISSUE TITLE
Dataset link not working

### ISSUE THREAD

**Issue by Laxchan** [nilmtk/nilmtk#829]
Dear Sirs,

I am trying to use the dataset link on the github depository but it doesnt seem to work. It just led me to a blank page.

best wishes,
Lax

**Comment by UPstartDeveloper** [comment]
@Laxchan could you please clarify which link are you referring to? I am not a collaborator on this repository, but I think I may be able to help you. I used to be a novice to GitHub as well, and I can relate if you are having trouble navigating the files.

**Comment by Laxchan** [comment]
Hello @UPstartDeveloper thank you very much for your reply. I am looking at this link here https://iawe.github.io/ and I went to the download section where it led me to the data files. But when I clicked on them, it just led me to blank pages.

Best wishes,
Lax

**Comment by Mars0207** [comment]
I had the same problem with you.

**Comment by PMeira** [comment]
@Laxchan  @Mars0207 Try the archived pages, e.g. http://web.archive.org/web/20160913194509/https://www.iiitd.edu.in/~nipunb/iawe/electricity.tar.gz -- it's a 418 MB file, so it should take some time to download it from archive.org.

@nipunbatra Looks like the files from the dataset hosted under https://www.iiitd.edu.in/~nipunb/iawe/ were removed -- any chance you rehosted them somewhere else?

**Comment by PMeira** [comment]
Closing for now since it's not related to NILMTK itself. The archive.org link continues to work too.
