### ISSUE TITLE
How exactly does this function calculates?

### ISSUE THREAD

**Issue by Laxchan** [nilmtk/nilmtk#831]
Can anyone enlighten me with how the output value is being calculated 
elec.mains().total_energy() ?

It seems like it keeps giving me negative number on my dataset.

Best,
Lax

**Comment by PMeira** [comment]
I recommend stepping through the code with a debugger to see how.

**Comment by Laxchan** [comment]
Hello PMeira, 

Many thanks for your reply. I  just want to know if there is a reference or a formulae you can point me to?

**Comment by PMeira** [comment]
No, it's nothing that complex. Take a look at https://github.com/nilmtk/nilmtk/blob/dd97f01ec43fcbbdaa5b680b700f91b15a56770f/nilmtk/stats/totalenergy.py

**Comment by Laxchan** [comment]
Hello PMeira,

Many thanks and sorry to ask you another question. I have been trying to use the plot function here. 
elec.plot_when_on()

but the date of the resulting plot does not seem to correspond to my data.

Best
L

**Comment by PMeira** [comment]
> but the date of the resulting plot does not seem to correspond to my data.

@Laxchan Are you sure it's not just date formatting/locale and/or timezone issues?

If that's not the case, I can take a look at the issue tomorrow.

**Comment by Laxchan** [comment]
Dear Paulo,

My last question in relation to my initial question. I know the
max_sample_period and sample_period are specified in the metadata file. May
I ask how are they related to each other?

Best wishes,
L

**Comment by PMeira** [comment]
IIRC, `sample_period` is the usual value for normal operation and `max_sample_period` is used in a couple of places to check if there is any valid sample in a time window. 

Note that some meters/devices use varying sampling rates but I don't recall any of the public datasets providing data like that.

**Comment by Laxchan** [comment]
Hello Paola,

Thank you very much for your detailed reply. I want to trace back to the second question I asked. When I load the h5 file I produced, all the date were correct, but when I do the elec.plot_when_on(). It just scaled to at least 4 months back. Is the date formatting/locale and/or timezone issues addressed in the metadata file?

Best wishes,
L

**Comment by PMeira** [comment]
@Laxchan Not sure if the metadata is used at that point. Try looking for general questions about that with pandas or matplotlib.

**Comment by Laxchan** [comment]
Hello PMeira,

I am wondering if I can share my h5 file with you through private email?

Lax

**Comment by Laxchan** [comment]
Is the power in kw for most of the dataset or w?

Best wishes,
Lax
