### ISSUE TITLE
Refit converter expects csv with different names than they appear in dataset?

### ISSUE THREAD

**Issue by mpodlasin** [nilmtk/nilmtk#833]
Hi.

I am using refit converter. In general it works, but I had to rename my csv files downloaded from refit website: 

https://pureportal.strath.ac.uk/en/datasets/refit-electrical-load-measurements-cleaned

In actual dataset csv files have names like `CLEAN_House1.csv`, while converter expects files like `House_1.csv`.

Am I loading a wrong dataset, or is it a problem with the code? Obviously it's not a big deal, but it would be nice if converter worked "out of the box"?

If it's the problem with code, I can submit a PR fixing it. Just let me know. :)

Thanks in advance!

**Comment by PMeira** [comment]
I'll add an option to handle/try the different names later.

**Comment by PMeira** [comment]
Updated (and tested) it to handle both versions. @mpodlasin, thank you for reporting this.
