### ISSUE TITLE
no module found for this 

### ISSUE THREAD

**Issue by Laxchan** [nilmtk/nilmtk#835]
Hello, 

I have followed the install instruction and tried to import this using this line of code 
from nilmtk.legacy.disaggregate import CombinatorialOptimisation, FHMM
but it keeps saying no module found. 

Anyone has a solution for this?
L

**Comment by PMeira** [comment]
There is warning on the README

> The last steps in the development of the next NILMTK version (0.4) are being done in the master git branch. If you are a new user, please refer to the version 0.3.x branch at https://github.com/nilmtk/nilmtk/tree/0.3.x.

**Comment by Laxchan** [comment]
what does this mean?

Best wishes,
Lax

**Comment by PMeira** [comment]
@Laxchan You probably installed v0.3.x and is using the (in development) version v0.4.x docs. Browse at https://github.com/nilmtk/nilmtk/tree/0.3.x

**Comment by Laxchan** [comment]
@PMeira Thank you so much for all the recent replies. I am rather new to this area and also to github. Your patience is appreciated.
