### ISSUE TITLE
Importing convert_hes 

### ISSUE THREAD

**Issue by jdesouza-ai** [nilmtk/nilmtk#836]
Hi,

I am trying to import the convert_hes function using the below code:

`from nilmtk.dataset_converters.hes import convert_hes`

but it is generating an error message which says:

> ImportError: cannot import name 'MatplotlibDeprecationWarning'

Does anyone know the root cause of this error and how we can remediate it?

**Comment by PMeira** [comment]
Update your matplotlib, you're expected to have at least version 3.1.0. 

If you got that error, your Python environment as a whole might not be compatible -- check https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install_user.md
