### ISSUE TITLE
elec.mains()[1].plot() not working/plotting

### ISSUE THREAD

**Issue by jst0319** [nilmtk/nilmtk#837]
Hi. I am getting this weird error. I have imported matplotlib library. But when I do `elec.mains()[1].plot()`, the program just runs without any error and does not plot any graph. I am attaching the code which I wrote. The start and end date and time included the `ue.set_window` are perfect.

`from nilmtk import DataSet`
`ue = DataSet(output_filename)`
`ue.set_window(start="2019-10-02 03:00:00", end="2019-10-02 06:00:00")`
`elec = ue.buildings[1].elec`
`elec`
`mains = elec.mains()[1]`
`import matplotlib.pyplot as plt`
`elec.mains()[1].plot()`

**Comment by PMeira** [comment]
That doesn't look like an error. Have you used matplotlib before? If not, you need to either call the show function as in:

```python
from matplotlib import pyplot as plt
plt.show()
```

Or, on a notebook, switch to the correct backend, for example :
```
%matplotlib inline
```
