### ISSUE TITLE
Good disaggregation results?

### ISSUE THREAD

**Issue by Hessen525** [nilmtk/nilmtk#847]
Hi, 
Do you think that it is a good result?
`
'sample_interval': 60,
'appliances': ['washing machine'],
'methods': {

     'WindowGRU': WindowGRU({'n_epochs':30}),
     'RNN': RNN({'n_epochs':50}),
     'DAE': DAE({'n_epochs':50}),
     'Seq2Point': Seq2Point({'n_epochs':50}),
     'Seq2Seq': Seq2Seq({'n_epochs':50}),
     'Convlstm': Convlstm({'n_epochs':30,}),
},
'train': {
    'datasets': {
        '1': {
            'path': 'C:/Users/Jia/Desktop/NILM/ukdale.h5',
            #'path':'/public/home/jd_jzy/anaconda3/ukdale.h5',
            'buildings': {
                1: {
                    'start_time': '2014-01-05',
                    'end_time': '2014-02-05'
                },
            }

        }
    }
},
'test': {
    'datasets': {
        'Datport': {
            #'path': 'C:/Users/Jia/Desktop/NILM/redd.h5',
            'path': 'C:/Users/Jia/Desktop/NILM/ukdale.h5',
            #'path':'/public/home/jd_jzy/anaconda3/redd.h5',
            'buildings': {
                1: {
                    'start_time': '2014-04-1',
                    'end_time': '2014-04-7'
                },
            }
        }
    },
    'metrics': ['mae','rmse' ]
}
`
![JJF1VZ{B4C~_466F2F)_$ 0](https://user-images.githubusercontent.com/25447481/71766593-74a90a80-2f3c-11ea-8904-fe60ad24d7e7.png)

![(`D_3 2(5MG~WAQQ0(1~)PR](https://user-images.githubusercontent.com/25447481/71766600-84c0ea00-2f3c-11ea-8745-05eeec80ee40.png)

It looks like there is a big difference with true.

**Comment by PMeira** [comment]
I recommend checking the papers to understand the current state of art and better interpret the results.
