### ISSUE TITLE
Converting Greend Error

### ISSUE THREAD

**Issue by mittermario** [nilmtk/nilmtk#848]
Hi,
when converting the greend dataset (GREEND_0-1_311014.zip from https://sourceforge.net/projects/greend/) I get the following error:

input:
from nilmtk.dataset_converters import convert_greend
greend_folder = "/home/jovyan/data/solarihs/GREEND_0-1_311014"
greend_dataset = "/home/jovyan/data/solarihs/hdf_stores/greend.h5"
convert_greend(greend_folder, greend_dataset)

output:

...
/home/jovyan/data/solarihs/GREEND_0-1_311014/building7/dataset_2014-08-05.csv
/home/jovyan/data/solarihs/GREEND_0-1_311014/building7/dataset_2014-09-13.csv
meter 1: 000D6F00029C2542
Putting into store...
meter 2: 000D6F00036BC42A
Putting into store...
meter 3: 000D6F0003BD8082
Putting into store...
meter 4: 000D6F0003BD8C8E
Putting into store...
meter 5: 000D6F0003BD76C4
Putting into store...
meter 6: 000D6F0003BD8103
Putting into store...
meter 7: 000D6F0003BD8293
Putting into store...
meter 8: 000D6F0003BD6E92
Putting into store...
meter 9: 000D6F0003B9C636
Putting into store...

---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)
<ipython-input-2-901a228cafca> in <module>
      3 greend_dataset = greend_folder
      4 greend_dataset += '/greend.h5'
----> 5 convert_greend(greend_folder, greend_dataset)

/opt/conda/lib/python3.7/site-packages/nilmtk/dataset_converters/greend/convert_greend.py in convert_greend(greend_path, hdf_filename, use_mp)
    175         # retrieve the dataset metadata in the metadata subfolder
    176     metadata_dir = join(get_module_directory(), 'dataset_converters', 'greend', 'metadata')
--> 177     convert_yaml_to_hdf5(metadata_dir, hdf_filename)
    178 
    179 #is only called when this file is the main file... only test purpose

/opt/conda/lib/python3.7/site-packages/nilm_metadata/convert_yaml_to_hdf5.py in convert_yaml_to_hdf5(yaml_dir, hdf_filename)
     30 
     31     assert isdir(yaml_dir)
---> 32     store = pd.HDFStore(hdf_filename, 'a')
     33 
     34     # Load Dataset and MeterDevice metadata

/opt/conda/lib/python3.7/site-packages/pandas/io/pytables.py in __init__(self, path, mode, complevel, complib, fletcher32, **kwargs)
    503         self._fletcher32 = fletcher32
    504         self._filters = None
--> 505         self.open(mode=mode, **kwargs)
    506 
    507     def __fspath__(self):

/opt/conda/lib/python3.7/site-packages/pandas/io/pytables.py in open(self, mode, **kwargs)
    625 
    626         try:
--> 627             self._handle = tables.open_file(self._path, self._mode, **kwargs)
    628         except (IOError) as e:  # pragma: no cover
    629             if "can not be written" in str(e):

/opt/conda/lib/python3.7/site-packages/tables/file.py in open_file(filename, mode, title, root_uep, filters, **kwargs)
    313 
    314     # Finally, create the File instance, and return it
--> 315     return File(filename, mode, title, root_uep, filters, **kwargs)
    316 
    317 

/opt/conda/lib/python3.7/site-packages/tables/file.py in __init__(self, filename, mode, title, root_uep, filters, **kwargs)
    776 
    777         # Now, it is time to initialize the File extension
--> 778         self._g_new(filename, mode, **params)
    779 
    780         # Check filters and set PyTables format version for new files.

tables/hdf5extension.pyx in tables.hdf5extension.File._g_new()

HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 509, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1567, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1640, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 959, in H5FD_sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

Unable to open/create file '/home/jovyan/data/solarihs/GREEND_0-1_311014/greend.h5'

**Comment by Rithwikksvr** [comment]
@rajatgupta1234 Can you look into this?

**Comment by PMeira** [comment]
Weird that the file listed here in the error message:

> Unable to open/create file '/home/jovyan/data/solarihs/GREEND_0-1_311014/greend.h5'

doesn't match the input:

> greend_dataset = "/home/jovyan/data/solarihs/hdf_stores/greend.h5"


I couldn't reproduce the issue though. I suggest trying the updated package, just uploaded nilmtk 0.4.1 to anaconda to restrict pandas to the 0.25.x versions.

It might be worth trying the sequential conversion too, without using multiprocessing:

```python
convert_greend(greend_folder, greend_dataset, use_mp=False)
```
