### ISSUE TITLE
CondaHTTPError

### ISSUE THREAD

**Issue by Hessen525** [nilmtk/nilmtk#851]
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/nilmtk/noarch/nilmtk-0.4.0-py_0.tar.bz2>

**Comment by Hessen525** [comment]
no idea why so hard to download his nilmtk-0.4 pkgs, but if anyone encounter same situation, repeat until success or download by this url and then install local.

**Comment by PMeira** [comment]
Happens sometimes with anaconda.org, nothing to do with nilmtk itself
