### ISSUE TITLE
cannot import name 'DataSet' from 'nilmtk' 

### ISSUE THREAD

**Issue by carloscruzdelatorre** [nilmtk/nilmtk#853]
I am trying to run nilmtk, I installed correctly nilmk as no error appears running this library. Nevertheless from nilmtk import DataSet I got the following error:    

from nilmtk import DataSet
ImportError: cannot import name 'DataSet' from 'nilmtk' (unknown location)

Any suggestion is welcome 
thanks in advance

**Comment by PMeira** [comment]
Probably missed some steps in the installation. Double check https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install_user.md

If you properly installed it, maybe you forgot to activate the environment.
