### ISSUE TITLE
unse of channels in UK DALE dataset

### ISSUE THREAD

**Issue by StefanoLeonori** [nilmtk/nilmtk#860]
I want to couple power time-series of any device with its corresponding channel since devices like "vacuum cleaner" are corrupted.
Indeed, "Some individual appliance meters are switched off from the socket for significant portions of time" and the power seems to be constant in that period.
How to detect them in order to put equal to 0?
In my opinion, the only way to fix it is to couple the power time series with their channels.
How should I proceed?

Thank you

**Comment by PMeira** [comment]
Yeah, that's completely up to the user. Unfortunately all datasets so far have some issues...
