### ISSUE TITLE
Unable to insert new value in an empty dataFrame within FOR loop

### ISSUE THREAD

**Issue by mukulmunjal** [nilmtk/nilmtk#864]
I'm trying to insert a row in EMPTY DataFrame in FOR loop if the condition meets. I'm getting IndexError: index 1 is out of bounds for axis 0 with size 0

Below is my code:

**women = pd.DataFrame(columns= ["Survival_Rate"])
for i in range(len(titanic_train_data.Sex)):
    if (titanic_train_data.Sex[i] == 'female'):
        women['Survival_Rate'][i] = ([titanic_train_data.Survived[i]])**

In order to accomplish above, I've also tried to use APPEND method but that is also not working & I'm getting TypeError: cannot concatenate object of type ''; only Series and DataFrame objs are valid

**women = pd.DataFrame(columns= ["Survival_Rate"])
for i in range(len(titanic_train_data.Sex)):
    if (titanic_train_data.Sex[i] == 'female'):
        women['Survival_Rate'].append([titanic_train_data.Survived[i]])**
Can any one please share insights on above issue and what mistake I'm doing. Awaiting for reply.

Regards, Mukul

**Comment by mukulmunjal** [comment]
Can anyone help here?

**Comment by nipunbatra** [comment]
This is not related to NILMTK.
