### ISSUE TITLE
REDD dataset conversion issue

### ISSUE THREAD

**Issue by alfa1902** [nilmtk/nilmtk#867]
Hi i'm trying to convert redd dataset using convert_redd but it's not working with several errors

![image](https://user-images.githubusercontent.com/62867235/77910525-770bce00-72b9-11ea-9bd7-226d82a72afa.png)

Can anybody help me? Thank you.

**Comment by supergreditur** [comment]
i also encoutered this problem.
I seem to get the same error for my linux machine and my windows machine.
I followed the install instructions directly (using anaconda)

**Comment by supergreditur** [comment]
I looked at the file producing the error.
it is inside the put() function of hdfdatastory.py.
self.store.put(key, value, expectedrows = ....) where store is of type panda. only panda.put does not have such an argument. Thus the type error.
Removing expectedrows removed the error and produced a valid file

**Comment by alfa1902** [comment]
> I looked at the file producing the error.
> it is inside the put() function of hdfdatastory.py.
> self.store.put(key, value, expectedrows = ....) where store is of type panda. only panda.put does not have such an argument. Thus the type error.
> Removing expectedrows removed the error and produced a valid file

**Comment by alfa1902** [comment]
@supergreditur hi thank u for the response. I'm sorry I'm new to github that i anccidentaly closed the issue. I removed expectedrows but when i tried to import the package it gave me this error.

![image](https://user-images.githubusercontent.com/62867235/78321940-8891f600-7597-11ea-9d37-29cd1d515ccc.png)

**Comment by alfa1902** [comment]
@supergreditur hi thank u for the response. I'm sorry I'm new to github that i accidentally closed the issue. I removed expectedrows but when i tried to import the package it gave me this error.

![image](https://user-images.githubusercontent.com/62867235/78322924-5b931280-759a-11ea-8b22-f351357d973d.png)

**Comment by PMeira** [comment]
@alfa1902 @supergreditur 
I uploaded a new conda package (version 0.4.1) with constrained dependencies. Try updating or reinstalling.

Probably downgrading Pandas to 0.25.3 is enough though. Beware that using Pandas 1.0+ without fixing several other issues might end in unexpected/wrong results.

There might be some other package conflict besides Pandas, so feel free to open issues this kind of errors. I hope we upgrade everything by the end of month.

**Comment by alfa1902** [comment]
@PMeira it works perfectly now, thank you so much.
