### ISSUE TITLE
error: test_combinatorial_optimisation()  

### ISSUE THREAD

**Issue by carloscruzdelatorre** [nilmtk/nilmtk#869]
Hi, I cannot test the CO NILMTK model: I have tried test_combinatorial_optimisation()  and combinatorial_optimisation() . 
When train and test REDD or UKDALE dataset, this error appears when calling the co function

co = test_combinatorial_optimisation ()

TypeError: 'module' object is not callable

**Comment by PMeira** [comment]
Those tests are for checking if NILMTK is working, they're not general tests for anything.

You can check sample notebooks here, some use CO:
https://github.com/nilmtk/nilmtk/tree/master/docs/manual
