### ISSUE TITLE
download_dataport() got multiple values for argument 'periods_to_load'

### ISSUE THREAD

**Issue by Shibumi497** [nilmtk/nilmtk#872]
Dear all,

I am trying to convert the the dataport data in HDF5.
The easiest way seems to download it with the tool, that converts it automatically.
However, when I enter that : 

-->download_dataport('my username', 'my password', 'the code received by email', 'my path for the new file', 'electricity','eg_realpower_1min', periods_to_load= { 1: ('2018-11-17', '2019-12-17')})

The answer is always the same : 
![Screenshot 2020-05-21 at 09 27 46](https://user-images.githubusercontent.com/60926736/82534392-56d3ef00-9b45-11ea-8db1-ba53481c1733.png)

I changed various of time the period to loads, tried with "none", nothing works...

In nay case, I already dowloaded manually the dataport data I need, but I want to convert it, how can I do ? I don't really understqqnd what the arguments are about. to write in the function "_dataport_dataframe_to_hdf"

Thanks in advance,

@nipunbatra @JackKelly @PMeira @raktim2015 @eshapec @ahersey

**Comment by JackKelly** [comment]
I could be wrong but I think you're not calling `download_dataport` correctly.  Please see the function signature: https://github.com/nilmtk/nilmtk/blob/master/nilmtk/dataset_converters/dataport/download_dataport.py#L325

**Comment by Shibumi497** [comment]
Dear Jack kelly


Dataport changed its procedure to connect.
Now they ask you an additional code they send you by email to be able to
connect.

I don't know if you made reference to that point, but this is the only
additional change I did :/
(without this email code I can't connect to Dataport)

Thanks in advance,

Best regards

**Comment by JackKelly** [comment]
Aha!  Thanks loads for flagging this up!  Sounds like the `download_dataport` code needs to be modified to conform to the new dataport access procedure!  

Please could you submit a NILMTK feature request (just submit another github issue, asking for the dataport code to be modified to handle the new requirements!)  Thanks!

**Comment by Shibumi497** [comment]
Done! :)

**Comment by JackKelly** [comment]
Conversation continued in #873 :)
