### ISSUE TITLE
Error in disaggregation (Hart's unsupervised NILM)

### ISSUE THREAD

**Issue by sid548** [nilmtk/nilmtk#875]
I followed Hart's unsupervised NILM from [https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/hart_disaggregation_demo.ipynb](url) , and got "TypeError: Cannot compare tz-naive and tz-aware timestamps." Could you please help me solve the error? I really appreciate your kind help. Thanks so much.
# In [1]:
from __future__ import print_function
import numpy as np
import pandas as pd
from pylab import rcParams
import matplotlib.pyplot as plt
rcParams['figure.figsize'] = (13, 6)
# Out [1]:

# In [2]:
import nilmtk
from nilmtk import DataSet, TimeFrame, MeterGroup, HDFDataStore
from nilmtk.legacy.disaggregate import CombinatorialOptimisation
from nilmtk.utils import print_dict
from nilmtk.metrics import f1_score
# Out [2]:

# In [3]:
from nilmtk import DataSet
from nilmtk.utils import print_dict
data = DataSet('/home/sidharth/Desktop/IoT/REDD/output',format='CSV')
print('Loaded', len(data.buildings), 'buildings')
# Out [3]:
Loaded 6 buildings

# In [4]:
elec = data.buildings[1].elec
# Out [4]:

# In [5]:
elec.get_timeframe()
#Out [5]:
TimeFrame(start='2011-04-18 13:22:09', end='2011-05-24 19:57:02', empty=False)

# In [6]:
data.set_window(start='2011-04-20',end='2011-04-24')
elec_1 = data.buildings[1].elec
# Out [6]:

# In [7]:
mains=elec_1.mains()
submeters=elec_1.submeters()
# Out [7]:

# In [8]:
mains.available_ac_types('power')
# Out [8]:
['apparent']

# In [9]:
submeters.available_ac_types('power')
# Out [10]:
['active']

# In [10]:
from nilmtk.legacy.disaggregate.hart_85 import Hart85
h = Hart85()
# Out [10]:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-126-9ab602284e1d> in <module>
----> 1 h.train(mains,columns=[('power','apparent')])
      2 

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/legacy/disaggregate/hart_85.py in train(self, metergroup, columns, buffer_size, noise_level, state_threshold, min_tolerance, percent_tolerance, large_transition, **kwargs)
    242         self.noise_level = noise_level
    243         [self.steady_states, self.transients] = find_steady_states_transients(
--> 244             metergroup, columns, noise_level, state_threshold, **kwargs)
    245         self.pair_df = self.pair(
    246             buffer_size, min_tolerance, percent_tolerance, large_transition)

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/feature_detectors/steady_states.py in find_steady_states_transients(metergroup, columns, noise_level, state_threshold, **load_kwargs)
     13     transients_list = []
     14 
---> 15     for power_df in metergroup.load(columns=columns, **load_kwargs):
     16         """
     17         if len(power_df.columns) <= 2:

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/metergroup.py in load(self, **kwargs)
    697         # Handle kwargs
    698         sample_period = kwargs.setdefault('sample_period', self.sample_period())
--> 699         sections = kwargs.pop('sections', [self.get_timeframe()])
    700         chunksize = kwargs.pop('chunksize', MAX_MEM_ALLOWANCE_IN_BYTES)
    701         duration_threshold = sample_period * chunksize

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/metergroup.py in get_timeframe(self)
   1385         nilmtk.TimeFrame representing the timeframe which is the union
   1386             of all meters in self.meters.
-> 1387         """
   1388         timeframe = None
   1389         for meter in self.meters:

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/elecmeter.py in get_timeframe(self)
     89     def get_timeframe(self):
     90         self._check_store()
---> 91         return self.store.get_timeframe(key=self.key)
     92 
     93     def _check_store(self):

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/docinherit.py in f(*args, **kwargs)
     44         @wraps(self.mthd, assigned=('__name__', '__module__'))
     45         def f(*args, **kwargs):
---> 46             return self.mthd(obj, *args, **kwargs)
     47 
     48         return self.use_parent_doc(f, overridden)

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/datastore/csvdatastore.py in get_timeframe(self, key)
    229             end = df.index[-1]
    230         timeframe = TimeFrame(start, end)
--> 231         return self.window.intersection(timeframe)
    232 
    233     def _get_metadata_path(self):

~/anaconda3/envs/nilmtk-env/lib/python3.6/site-packages/nilmtk/timeframe.py in intersection(self, other)
    153                 start = other.start
    154             else:
--> 155                 start = max(self.start, other.start)
    156 
    157             if other.end is None:

pandas/_libs/tslib.pyx in pandas._libs.tslib._Timestamp.__richcmp__()

pandas/_libs/tslib.pyx in pandas._libs.tslib._Timestamp._assert_tzawareness_compat()

TypeError: Cannot compare tz-naive and tz-aware timestamps

**Comment by PMeira** [comment]
> data = DataSet('/home/sidharth/Desktop/IoT/REDD/output',format='CSV')

Don't use the CSV datastore. Convert first to HDF (see `data.ipynb` in the same folder).

I guess it's a good idea to remove the old CSV datastore from NILMTK to avoid this kind of issue.
