### ISSUE TITLE
Multiple events are detecting at the same place

### ISSUE THREAD

**Issue by csetanmayjain** [nilmtk/nilmtk#878]
Hello,
Multiple events are detecting at the same place by [steady_states.py](https://github.com/nilmtk/nilmtk/blob/master/nilmtk/feature_detectors/steady_states.py)

![image](https://user-images.githubusercontent.com/37631570/86369022-87a65880-bc9b-11ea-8581-6382cb735d81.png)

Can anyone faces the similar issue or any suggestions on how to fix it?
Thanks

**Comment by PMeira** [comment]
Yeah, that might happen. That method is very simple, you probably have to post process the detections or even downsample the input data to reduce the number of detections.
