### ISSUE TITLE
HDF5ExtError 

### ISSUE THREAD

**Issue by kuo1993** [nilmtk/nilmtk#880]
I imported my own model based on the https://github.com/odysseaskr/neural-disaggregator , which worked well before, but in the last few days I've been able to create a decomposable H5 file during the decomposer phase, but I didn't write anything and got an error, so I tried to reinstall the environment, but it didn't work out. Please help me!

HDF5ExtError                              Traceback (most recent call last)
<ipython-input-5-c779a59141aa> in <module>()
      2 from nilmtk.datastore import HDFDataStore
      3 output = HDFDataStore(disag_filename, 'w')
----> 4 gru.disaggregate(test_mains, output, train_meter,step_length=10, sample_period=3)

D:\Jupter\nilmproject\根据原文代码制作\microwave\多通道卷积cnn2\滑动窗口法\mydisaggregator.py in disaggregate(self, mains, output_datastore, meter_metadata, step_length, **load_kwargs)
    102 
    103         load_kwargs.setdefault('sample_period', 3)
--> 104         load_kwargs.setdefault('sections', mains.good_sections())
    105 
    106         timeframes = []

D:\anaconda3\envs\nilmtk-env2\lib\site-packages\nilmtk\metergroup.py in good_sections(self, **kwargs)
    941                      " return the intersection of the good sections for all"
    942                      " meters.  This will be fixed...")
--> 943             return self.meters[0].good_sections(**kwargs)
    944         else:
    945             return []

D:\anaconda3\envs\nilmtk-env2\lib\site-packages\nilmtk\elecmeter.py in good_sections(self, **loader_kwargs)
    629         results_obj = GoodSections.results_class(self.device['max_sample_period'])
    630         return self._get_stat_from_cache_or_compute(
--> 631             nodes, results_obj, loader_kwargs)
    632 
    633     def _get_stat_from_cache_or_compute(self, nodes, results_obj, loader_kwargs):

D:\anaconda3\envs\nilmtk-env2\lib\site-packages\nilmtk\elecmeter.py in _get_stat_from_cache_or_compute(self, nodes, results_obj, loader_kwargs)
    682         key_for_cached_stat = self.key_for_cached_stat(results_obj.name)
    683         if loader_kwargs.get('preprocessing') is None:
--> 684             cached_stat = self.get_cached_stat(key_for_cached_stat)
    685             results_obj.import_from_cache(cached_stat, sections)
    686 

D:\anaconda3\envs\nilmtk-env2\lib\site-packages\nilmtk\elecmeter.py in get_cached_stat(self, key_for_stat)
    829             return pd.DataFrame()
    830         try:
--> 831             stat_from_cache = self.store[key_for_stat]
    832         except KeyError:
    833             return pd.DataFrame()

D:\anaconda3\envs\nilmtk-env2\lib\site-packages\nilmtk\docinherit.py in f(*args, **kwargs)
     44         @wraps(self.mthd, assigned=('__name__', '__module__'))
     45         def f(*args, **kwargs):
---> 46             return self.mthd(obj, *args, **kwargs)
     47 
     48         return self.use_parent_doc(f, overridden)

D:\anaconda3\envs\nilmtk-env2\lib\site-packages\nilmtk\datastore\hdfdatastore.py in __getitem__(self, key)
     27     @doc_inherit
     28     def __getitem__(self, key):
---> 29         return self.store[key]
     30 
     31     @doc_inherit

D:\anaconda3\envs\nilmtk-env2\lib\site-packages\pandas\io\pytables.py in __getitem__(self, key)
    519 
    520     def __getitem__(self, key):
--> 521         return self.get(key)
    522 
    523     def __setitem__(self, key, value):

D:\anaconda3\envs\nilmtk-env2\lib\site-packages\pandas\io\pytables.py in get(self, key)
    718         if group is None:
    719             raise KeyError("No object named {key} in the file".format(key=key))
--> 720         return self._read_group(group)
    721 
    722     def select(

D:\anaconda3\envs\nilmtk-env2\lib\site-packages\pandas\io\pytables.py in _read_group(self, group, **kwargs)
   1531         s = self._create_storer(group)
   1532         s.infer_axes()
-> 1533         return s.read(**kwargs)
   1534 
   1535 

D:\anaconda3\envs\nilmtk-env2\lib\site-packages\pandas\io\pytables.py in read(self, where, columns, **kwargs)
   4431     def read(self, where=None, columns=None, **kwargs):
   4432 
-> 4433         if not self.read_axes(where=where, **kwargs):
   4434             return None
   4435 

D:\anaconda3\envs\nilmtk-env2\lib\site-packages\pandas\io\pytables.py in read_axes(self, where, **kwargs)
   3664         # create the selection
   3665         self.selection = Selection(self, where=where, **kwargs)
-> 3666         values = self.selection.select()
   3667 
   3668         # convert the data

D:\anaconda3\envs\nilmtk-env2\lib\site-packages\pandas\io\pytables.py in select(self)
   5040         elif self.coordinates is not None:
   5041             return self.table.table.read_coordinates(self.coordinates)
-> 5042         return self.table.table.read(start=self.start, stop=self.stop)
   5043 
   5044     def select_coords(self):

D:\anaconda3\envs\nilmtk-env2\lib\site-packages\tables\table.py in read(self, start, stop, step, field, out)
   1927                                                 warn_negstep=False)
   1928 
-> 1929         arr = self._read(start, stop, step, field, out)
   1930         return internal_to_flavor(arr, self.flavor)
   1931 

D:\anaconda3\envs\nilmtk-env2\lib\site-packages\tables\table.py in _read(self, start, stop, step, field, out)
   1841             # This optimization works three times faster than
   1842             # the row._fill_col method (up to 170 MB/s on a pentium IV @ 2GHz)
-> 1843             self._read_records(start, stop - start, result)
   1844         # Warning!: _read_field_name should not be used until
   1845         # H5TBread_fields_name in tableextension will be finished

tables/tableextension.pyx in tables.tableextension.Table._read_records()

HDF5ExtError: HDF5 error back trace

  File "..\src\H5Dio.c", line 199, in H5Dread
    can't read data
  File "..\src\H5Dio.c", line 603, in H5D__read
    can't read data
  File "..\src\H5Dchunk.c", line 2293, in H5D__chunk_read
    unable to read raw data chunk
  File "..\src\H5Dchunk.c", line 3644, in H5D__chunk_lock
    unable to read raw data chunk
  File "..\src\H5Fio.c", line 118, in H5F_block_read
    read through page buffer failed
  File "..\src\H5PB.c", line 732, in H5PB_read
    read through metadata accumulator failed
  File "..\src\H5Faccum.c", line 260, in H5F__accum_read
    driver read request failed
  File "..\src\H5FDint.c", line 200, in H5FD_read
    addr overflow, addr = 401371027, size = 1301, eoa = 401371027

End of HDF5 error back trace

Problems reading records.

**Comment by kuo1993** [comment]
Further analysis, found that the good_sections() function error, how to solve?

**Comment by PMeira** [comment]
> Further analysis, found that the good_sections() function error, how to solve?

Sorry, but that's kinda obvious from the traceback. But just because something is called there, doesn't mean there is an error there (until we have an easily reproducible example).

```pytb
D:\anaconda3\envs\nilmtk-env2\lib\site-packages\nilmtk\metergroup.py in good_sections(self, **kwargs)
    941                      " return the intersection of the good sections for all"
    942                      " meters.  This will be fixed...")
--> 943             return self.meters[0].good_sections(**kwargs)
    944         else:
    945             return []
```

You can also see down in the traceback that the error is Pytables, which Pandas uses to handle HDF5 files. 

Without a lot more information, we have no idea if the error is caused by something in NILMTK or neural-disaggregator. Notice that neither project has been updated recently, so it's probably an issue related to your environment or scripts.  Related docs:

http://www.pytables.org/usersguide/index.html
https://pandas.pydata.org/docs/user_guide/io.html
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html

I recommend checking the HDF manually to check it that is working correctly. If you updated or installed any other package besides the ones listed in our environment, it's quite possible that action updated something

From experience, I can tell is that the HDF modules can fragile and don't always handle updates well.  You could try to downgrade pytables, for example. HDF files have some restrictions like concurrent access and such. Many weird errors pop up due to the users forgetting to close the HDF(DataStore) and rerunning a process with the same file as output, invalid paths or permissions, etc.

**Comment by kuo1993** [comment]
thanks you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Paulo Meira"<notifications@github.com&gt;; 
发送时间: 2020年8月20日(星期四) 上午9:32
收件人: "nilmtk/nilmtk"<nilmtk@noreply.github.com&gt;; 
抄送: "654834865"<654834865@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [nilmtk/nilmtk] HDF5ExtError  (#880)





  
Further analysis, found that the good_sections() function error, how to solve?
  
Sorry, but that's kinda obvious from the traceback. But just because something is called there, doesn't mean there is an error there (until we have an easily reproducible example).
 D:\anaconda3\envs\nilmtk-env2\lib\site-packages\nilmtk\metergroup.py in good_sections(self, **kwargs)     941                      " return the intersection of the good sections for all"     942                      " meters.  This will be fixed...") --&gt; 943             return self.meters[0].good_sections(**kwargs)     944         else:     945             return []
 
You can also see down in the traceback that the error is Pytables, which Pandas uses to handle HDF5 files.
 
Without a lot more information, we have no idea if the error is caused by something in NILMTK or neural-disaggregator. Notice that neither project has been updated recently, so it's probably an issue related to your environment or scripts.  Related docs:
 
http://www.pytables.org/usersguide/index.html
 https://pandas.pydata.org/docs/user_guide/io.html
 https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html
 
I recommend checking the HDF manually to check it that is working correctly. If you updated or installed any other package besides the ones listed in our environment, it's quite possible that action updated something
 
From experience, I can tell is that the HDF modules can fragile and don't always handle updates well.  You could try to downgrade pytables, for example. HDF files have some restrictions like concurrent access and such. Many weird errors pop up due to the users forgetting to close the HDF(DataStore) and rerunning a process with the same file as output, invalid paths or permissions, etc.

**Comment by PMeira** [comment]
@kuo1993 If your HDF files are working OK, you can try checking the versions running the `conda list` command or through:

```python
from nilmtk.utils import show_versions
show_versions()
```
Then check if that matches the expected: https://github.com/nilmtk/nilmtk/blob/master/environment.yml

If it does, you could post the output of `show_versions()` here in hopes someone can point a package that might be causing the issue, if it's indeed an incompatible update.

**Comment by kuo1993** [comment]
ok，i will check the environment，thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Paulo Meira"<notifications@github.com&gt;; 
发送时间: 2020年8月20日(星期四) 上午9:43
收件人: "nilmtk/nilmtk"<nilmtk@noreply.github.com&gt;; 
抄送: "654834865"<654834865@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [nilmtk/nilmtk] HDF5ExtError  (#880)





 
@kuo1993 If your HDF files are working OK, you can try checking the versions running the conda list command or through:
 from nilmtk.utils import show_versions show_versions()
 
Then check if that matches the expected: https://github.com/nilmtk/nilmtk/blob/master/environment.yml
 
If it does, you could post the output of show_versions() here in hopes someone can point a package that might be causing the issue, if it's indeed an incompatible update.

**Comment by PMeira** [comment]
I reran some tests now, couldn't find any explicit issue with NILMTK. It's probably an interaction with something else.
