### ISSUE TITLE
Approaching NILMTK for the first time

### ISSUE THREAD

**Issue by saimonseas** [nilmtk/nilmtk#882]
Hi everyone;

In the last year I have been interested in NILM algorithms, personally developing some algorithms mainly based on machine learning.
I do not consider myself an expert in the sector, but I am very fascinated by the subject and willing to work on it.
In the various papers I have read over the last year I have often come across the NILMTK.

I would be interested to know which disaggregation algorithms are directly implementable through this toolkit, and if maybe there are instructions that allow me to understand the logic.

Regards

**Comment by PMeira** [comment]
NILMTK itself implements some methods and there are many more in NILMTK-Contrib using the current API.  Read more in
https://github.com/nilmtk/nilmtk-contrib (there's a link to a paper there too).
