### ISSUE TITLE
NILMTK Rapid Experimentation API - Parameter DROP_ALL_NANS is hardcoded

### ISSUE THREAD

**Issue by levaphenyl** [nilmtk/nilmtk#890]
NILMTK Rapid Experimentation API offers to choose whether to drop NaNs in training and testing data.
This behaviour is controlled by the `DROP_ALL_NANS` parameter.

However, the chosen value in the experiment configuration is never assigned to the `API` class attribute. The parameter is just hardcoded in [api.py, line 40](https://github.com/nilmtk/nilmtk/blob/master/nilmtk/api.py#L40).

Thus, changing the value of `DROP_ALL_NANS` in the experiment configuration does nothing!

I see 2 solutions:
    a) I change the line with `params.get(...)`.
    b) The parameter is removed from the API and the docs as NaNs are always intented to be dropped.

I intend to open the PR myself, this issue is for referencing. I will go for solution a). If you want solution b), please shout :).

**Comment by PMeira** [comment]
By the amount of small issues, it's probably worth investigating a more automated approach in the future to facilitate validation and extension of the declarative API model.

Closed via #891, thanks to @levaphenyl
