### ISSUE TITLE
Installation encountered some problem

### ISSUE THREAD

**Issue by KKK-AAA** [nilmtk/nilmtk#894]
1.
Installed d:\anaconda3\envs\nilmtk\lib\site-packages\psycopg2_binary-2.8.6-py3.7-win-amd64.egg
Searching for future
Reading https://pypi.org/simple/future/
Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz#sha256=b1bead90b70cf6ec3f0710ae53a525360fa360d306a86583adc6bf83a4db537d
Best match: future 0.18.2
Processing future-0.18.2.tar.gz
Writing C:\Users\孤帆叠影\AppData\Local\Temp\easy_install-f3yprqjl\future-0.18.2\setup.cfg
Running future-0.18.2\setup.py -q bdist_egg --dist-dir C:\Users\孤帆叠影\AppData\Local\Temp\easy_install-f3yprqjl\future-0.18.2\egg-dist-tmp-t3g0ql56
warning: no files found matching '*.au' under directory 'tests'
warning: no files found matching '*.gif' under directory 'tests'
warning: no files found matching '*.txt' under directory 'tests'
2.
Writing C:\Users\孤帆叠影\AppData\Local\Temp\easy_install-yaevsk35\networkx-2.1\setup.cfg
Running networkx-2.1\setup.py -q bdist_egg --dist-dir C:\Users\孤帆叠影\AppData\Local\Temp\easy_install-yaevsk35\networkx-2.1\egg-dist-tmp-c_ki2fi9
warning: no files found matching '*.html' under directory 'doc'
warning: no files found matching '*.css' under directory 'doc'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.svn' found anywhere in distribution
no previously-included directories found matching 'doc\build'
no previously-included directories found matching 'doc\auto_examples'
no previously-included directories found matching 'doc\modules'
no previously-included directories found matching 'doc\reference\generated'
no previously-included directories found matching 'doc\reference\algorithms\generated'
no previously-included directories found matching 'doc\reference\classes\generated'
no previously-included directories found matching 'doc\reference\readwrite\generated'
creating d:\anaconda3\envs\nilmtk\lib\site-packages\networkx-2.1-py3.7.egg
Extracting networkx-2.1-py3.7.egg to d:\anaconda3\envs\nilmtk\lib\site-packages
Adding networkx 2.1 to easy-install.pth file
3.
when I run 
nosetests

(nilmtk) PS C:\Users\孤帆叠影> nosetests

----------------------------------------------------------------------
Ran 0 tests in 0.008s

OK

**Comment by PMeira** [comment]
See https://github.com/nilmtk/nilmtk/blob/master/docs/manual/user_guide/install_user.md
