### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by KKK-AAA** [nilmtk/nilmtk#902]
This is the relevant source code：

train = DataSet('redd.h5')
train.set_window(end="30-4-2011")
test = DataSet('redd.h5')
test.set_window(start="10-5-2011", end="13-5-2011")

when I want to print the result....

AttributeError: Attribute 'metadata' does not exist in node: '/'

**Comment by levaphenyl** [comment]
I see several issues with your issue description:
1. When sharing code, please use triple backquotes to enclose it (```).
2. When calling `set_window`, you can avoid ambiguity by using the ISO date format "YYYY-MM-DD". What is `13-5-21` supposed to be?
3. You want to "print the result" but you do not share any relevant detail on where the result comes from or how you want to print it.

This issue requires more info, IMO.

**Comment by KKK-AAA** [comment]
Thank you for your guide! For issue 2, it's not `13-5-21`, it's should be `13-5-2011`.  I think this is algorithm error (* ￣︿￣)
