### ISSUE TITLE
an error met when convert and load data.

### ISSUE THREAD

**Issue by wbn520** [nilmtk/nilmtk#916]
when i completed ths installment according to the NILMTK Documentation, Then run the convert and load code, an error happened. the code is:
`from nilmtk.dataset_converters import convert_redd
convert_redd('low_freq', 'low_freq/redd.h5')`
the data path is changed to my data path.
the error is :

> HDF5ExtError: HDF5 error back trace
> File "C:\ci\hdf5_1545244154871\work\src\H5F.c", line 444, in H5Fcreate
>     unable to create file
>   File "C:\ci\hdf5_1545244154871\work\src\H5Fint.c", line 1364, in H5F__create
>     unable to open file
>   File "C:\ci\hdf5_1545244154871\work\src\H5Fint.c", line 1557, in H5F_open
>     unable to open file: time = Sat Feb 27 16:54:49 2021
> , name = 'F:\jupyter\非侵入式负荷监测\nimltk\low_freq\pytables-e0s2gdcm.tmp', tent_flags = 13
>   File "C:\ci\hdf5_1545244154871\work\src\H5FD.c", line 734, in H5FD_open
>     open failed
>   File "C:\ci\hdf5_1545244154871\work\src\H5FDsec2.c", line 346, in H5FD_sec2_open
>     unable to open file: name = 'F:\jupyter\非侵入式负荷监测\nimltk\low_freq\pytables-e0s2gdcm.tmp', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 302
> 
> End of HDF5 error back trace
> Unable` to open/create file 'F:\jupyter\非侵入式负荷监测\nimltk\low_freq\pytables-e0s2gdcm.tmp'

**Comment by PMeira** [comment]
Do you have the raw REDD files in `F:\jupyter\非侵入式负荷监测\nimltk\low_freq`?

You could try
```
import os
print(os.listdir(r'F:\jupyter\非侵入式负荷监测\nimltk\low_freq'))
```
to ensure Python is handling the path correctly. If the doesn't list the folder contents correctly, there's probably some encoding issue somewhere.

**Comment by wbn520** [comment]
the result of the code is:

> ['house_1', 'house_2', 'house_3', 'house_4', 'house_5', 'house_6', 'pytables-byr1gepy.tmp', 'redd.h5']

the last two files is generated by the convert_redd function,

**Comment by PMeira** [comment]
What's weird is that it did create any file at all, given that exception. 

I thought maybe it was related to an old HDF5 issue (https://github.com/conda-forge/hdf5-feedstock/issues/47) but with a fresh installed environment with HDF5 1.10.6, I couldn't reproduce it.

Can you check if the real-time scan from your antivirus could be interfering? You could try pausing that.

If that's not the case, maybe try moving the data folder somewhere else, containing only ASCII chars (e.g. `F:\jupyter\nimltk\low_freq`).

**Comment by wbn520** [comment]
Thanks a lot. I changed the data path to that only containing ASCII chars. It can work!
