### ISSUE TITLE
Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

### ISSUE THREAD

**Issue by yokomaz** [nilmtk/nilmtk#919]
I meet an error when I try to train my model:

Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

I heared somebody said it may be the version conflict of numpy and pandas.
I checked my version of numpy=1.20.1 and pandas=0.25.3,then i try to update them,but it shows me many other conflicts.So i wander that if anybody meet the same question as me ,and is there anyone can help me to fix it.

**Comment by PMeira** [comment]
We can't help much without more information. If you could provide a sample script that gives that error, that'd probably help us investigate it.

**Comment by yokomaz** [comment]
Thx for ur responsing,
I'm studying the package 'NILMTK' for energy disaggregate.
I used the code offered by my teacher,and when i try to train the model,here is the code for training i used:
`train = DataSet('/home/chen/Dataset/low_freq_h5.h5')
test = DataSet('/home/chen/Dataset/low_freq_h5.h5')

print(type(train))

building = 1

train.set_window(end = "30-4-2011")
test.set_window(start="30-4-2011")

train_elec = train.buildings[building].elec
test_elec = test.buildings[building].elec`

`classifiers = {'FHMM':FHMM()}
predictions = {}
sample_period = 60
for clf_name, clf in classifiers.items():
    print("*"*20)
    print(clf_name)
    print("*"*20)
    clf.train(top_5_train_elec, sample_period=sample_period)
    gt, predictions[clf_name] = predict(clf, test_elec, sample_period, train.metadata['timezone'])`
It noticed me the error:`Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type`
I later find the solution to the problem in #

**Comment by PMeira** [comment]
@yokomaz Thanks for the update. Yes, it seems indeed the problem is a compatibility issue with that version of Pandas and newer NumPy (released last month). In this case, the recipe/restrictions in the Pandas package is incorrect, it should not allow NumPy 1.20.x to be used. We can add a restriction on our side though so it doesn't affect other users.

On a side-note, avoid using dates in the "DD-MM-YYYY" format since they're ambiguous, prefer "YYYY-MM-DD".

**Comment by PMeira** [comment]
A new package (version 0.4.3) was released that should address this. I also tweaked the other dependencies.

**Comment by yokomaz** [comment]
Thx a lot for ur update,i think it can work better now!
