### ISSUE TITLE
cannot copy sequence with size 1048576 to array axis with dimension 8

### ISSUE THREAD

**Issue by marwaaKamel** [nilmtk/nilmtk#923]
Hi!
I'm trying to build a multiple linear regression model. 
I got this error when I want to normalize the values:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-31-6abd1dbb4f37> in <module>
----> 1 normalized_data = preprocessing.normalize([dataset])
      2 print(normalized_data)

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     71                           FutureWarning)
     72         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 73         return f(**kwargs)
     74     return inner_f
     75 

~\Anaconda3\lib\site-packages\sklearn\preprocessing\_data.py in normalize(X, norm, axis, copy, return_norm)
   1708         raise ValueError("'%d' is not a supported axis" % axis)
   1709 
-> 1710     X = check_array(X, accept_sparse=sparse_format, copy=copy,
   1711                     estimator='the normalize function', dtype=FLOAT_DTYPES)
   1712     if axis == 0:

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     71                           FutureWarning)
     72         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 73         return f(**kwargs)
     74     return inner_f
     75 

~\Anaconda3\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    597                     array = array.astype(dtype, casting="unsafe", copy=False)
    598                 else:
--> 599                     array = np.asarray(array, order=order, dtype=dtype)
    600             except ComplexWarning:
    601                 raise ValueError("Complex data not supported\n"

~\Anaconda3\lib\site-packages\numpy\core\_asarray.py in asarray(a, dtype, order)
     83 
     84     """
---> 85     return array(a, dtype, copy=False, order=order)
     86 
     87 

ValueError: cannot copy sequence with size 1048576 to array axis with dimension 8

This is my code:
import numpy as np
import pandas as pd
from matplotlib import pyplot
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
# load all data
dataset = read_csv('household_power_consumption1.csv', header=None, names =['Global_active_power','Global_reactive_power', 'Voltage','Global_intensity','Sub_metering_1','Sub_metering_2','Sub_metering_3','Sub_metering_4'])
normalized_data = preprocessing.normalize([dataset])
print(normalized_data)

**Comment by PMeira** [comment]
Maybe try asking in the [sklearn repo](https://github.com/scikit-learn/scikit-learn) instead, or stackoverflow? This is not exactly a general support forum.
