### ISSUE TITLE
In FT2Font: Can not load face.

### ISSUE THREAD

**Issue by oneway3124** [nilmtk/nilmtk#924]
C:\ProgramData\Anaconda3\envs\t2\lib\site-packages\matplotlib\backends\backend_agg.py in _get_agg_font(self, prop)
    244         """
    245         fname = findfont(prop)
--> 246         font = get_font(fname)
    247 
    248         font.clear()

C:\ProgramData\Anaconda3\envs\t2\lib\site-packages\matplotlib\font_manager.py in get_font(filename, hinting_factor)
   1339     if hinting_factor is None:
   1340         hinting_factor = rcParams['text.hinting_factor']
-> 1341     return _get_font(filename, hinting_factor)
   1342 
   1343 

RuntimeError: In FT2Font: Can not load face.

**Comment by oneway3124** [comment]
I have tried new environment creation.
conda config --add channels conda-forge
conda config --add channels nilmtk


conda create -n t2
conda activate t2
conda install nilmtk

**Comment by oneway3124** [comment]
But why generated some error like this "in FT2Font: Can not load face"

**Comment by PMeira** [comment]
matplotlib issue, out of our control. It might have been fixed by now.
