### ISSUE TITLE
PackagesNotFoundError: The following packages are not available from current channels: - nilmtk=0.4.2

### ISSUE THREAD

**Issue by riahtu** [nilmtk/nilmtk#928]
Stoper error has show when I use command `conda install -c nilmtk nilmtk=0.4.2`
PackagesNotFoundError: The following packages are not available from current channels: 

- nilmtk=0.4.2

Current channels:
- https://conda.anaconda.org/nilmtk/linux-64
- https://conda.anaconda.org/nilmtk/noarch
- https://conda.anaconda.org/conda-forge/linux-64
- https://conda.anaconda.org/conda-forge/noarch
- https://repo.anaconda.com/pkgs/main/linux-64
- https://repo.anaconda.com/pkgs/main/noarch
- https://repo.anaconda.com/pkgs/r/linux-64
- https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

https://anaconda.org

and use the search bar at the top of the page.

**Comment by PMeira** [comment]
Use 0.4.3.
