### ISSUE TITLE
co_fhmm is not working for ukdale data set

### ISSUE THREAD

**Issue by sastry3009** [nilmtk/nilmtk#934]
![Screenshot from 2021-07-01 14-47-59](https://user-images.githubusercontent.com/50710697/124100336-059e6a80-da7c-11eb-9cdb-20985257a275.png)

**Comment by sastry3009** [comment]
this was solved by re verifying the code once again

**Comment by Rohitkr1997** [comment]
WHat changes did you have to make? I am getting a similar error.

**Comment by Rohitkr1997** [comment]
How did you avoid getting error here
gt[i][meter] = next(meter.load(physical_quantity = 'power' ,ac_type='active', sample_period=sample_period))
