### ISSUE TITLE
How to run nilmtk  in the cloud?

### ISSUE THREAD

**Issue by crn565** [nilmtk/nilmtk#964]
I have had memory problems running NILMTK with the FHMM algorithm with 10 applications.  You would certainly think that the lack of physical memory could be made up for by swapping memory, but I'm afraid that doesn't make any headway.
Now my idea is to try to run NILMK on some public infrastructure so I think Google Collab could be an option, but the problem is that there is no direct coverage between the conda and python version of google Cloud and the Nilmtk installation.

**Comment by crn565** [comment]
### This my code in Google Collab for the moment:

!pip install -q condacolab

import condacolab

condacolab.install()



!conda update -n base -c conda-forge conda


!conda create  --name nilmtk-env


!conda config --add channels conda-forge

  $ conda activate nilmtk-env
---->>>> Not works 

pip install git+https://github.com/nilmtk/nilmtk

pip install git+https://github.com/nilmtk/nilm_metadata

**Comment by crn565** [comment]
**Other option to run nilmtk in the cloud is bender. For now  it's posible to activate nilmtk-env  but unfortunatelly falls instalalling nilmtk . This is the result of the  runing installig commands in the console:**

(base) jovyan@jupyter-crn565-2dozm10-5fappliances-2d85v923dl:~$ sudo apt-get update
bash: sudo: command not found
(base) jovyan@jupyter-crn565-2dozm10-5fappliances-2d85v923dl:~$ conda create --name nilmtk-env 
WARNING: A conda environment already exists at '/srv/conda/envs/nilmtk-env'
Remove existing environment (y/[n])? y

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /srv/conda/envs/nilmtk-env



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate nilmtk-env
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) jovyan@jupyter-crn565-2dozm10-5fappliances-2d85v923dl:~$ conda config --add channels conda-forge
Warning: 'conda-forge' already in 'channels' list, moving to the top
(base) jovyan@jupyter-crn565-2dozm10-5fappliances-2d85v923dl:~$ conda activate nilmtk-env
(nilmtk-env) jovyan@jupyter-crn565-2dozm10-5fappliances-2d85v923dl:~$ conda install -c nilmtk nilmtk=0.4.3
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): Killed
(nilmtk-env) jovyan@jupyter-crn565-2dozm10-5fappliances-2d85v923dl:~$

**Comment by crn565** [comment]
Thanks for the help. Unfornnatelly the code throw an `error:`

> [1]
7 s
1
!git clone https://github.com/nilmtk/nilmtk.git
Cloning into 'nilmtk'...
remote: Enumerating objects: 12355, done.
remote: Counting objects: 100% (145/145), done.
remote: Compressing objects: 100% (70/70), done.
remote: Total 12355 (delta 79), reused 124 (delta 74), pack-reused 12210
Receiving objects: 100% (12355/12355), 51.88 MiB | 14.74 MiB/s, done.
Resolving deltas: 100% (8785/8785), done.
[6]
0 s
1
!python nilmtk/setup.py install
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/content/nilmtk/setup.py", line 115, in <module>
    long_description=open("README.md", encoding="utf-8").read(),
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

**Comment by RajatPatodi** [comment]
> Thanks for the help. Unfornnatelly the code throw an `error:`
> 
> > [1]
> > 7 s
> > 1
> > !git clone https://github.com/nilmtk/nilmtk.git
> > Cloning into 'nilmtk'...
> > remote: Enumerating objects: 12355, done.
> > remote: Counting objects: 100% (145/145), done.
> > remote: Compressing objects: 100% (70/70), done.
> > remote: Total 12355 (delta 79), reused 124 (delta 74), pack-reused 12210
> > Receiving objects: 100% (12355/12355), 51.88 MiB | 14.74 MiB/s, done.
> > Resolving deltas: 100% (8785/8785), done.
> > [6]
> > 0 s
> > 1
> > !python nilmtk/setup.py install
> > fatal: not a git repository (or any of the parent directories): .git
> > Traceback (most recent call last):
> > File "/content/nilmtk/setup.py", line 115, in 
> > long_description=open("README.md", encoding="utf-8").read(),
> > FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

is this issue resolved, if yes how?

**Comment by crn565** [comment]
I think that there's a bug in the implementation of fhmm in Nilmtk. I probed with powerfull machine with the same results

**Comment by crn565** [comment]
Given the complexity of installing all the necessary environment I think it is much better to try to solve this by minimising the sampling time or the method of backfilling.
